const utils = require('../utils/utils');
const InvoiceAdjustmentCreateDto = require('../models/InvoiceAdjustmentCreateDto');
const InvoiceLineCreateDto = require('../models/InvoiceLineCreateDto');
const InvoiceReferenceCreateDto = require('../models/InvoiceReferenceCreateDto');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}closed`,
                label: `[${labelPrefix}closed]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}userId`,
                label: `[${labelPrefix}userId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}priceListId`,
                label: `[${labelPrefix}priceListId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}individualId`,
                label: `[${labelPrefix}individualId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}paymentTermId`,
                label: `[${labelPrefix}paymentTermId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}organizationId`,
                label: `[${labelPrefix}organizationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}receiverTenantId`,
                label: `[${labelPrefix}receiverTenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}firstName`,
                label: `[${labelPrefix}firstName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lastName`,
                label: `[${labelPrefix}lastName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}companyName`,
                label: `[${labelPrefix}companyName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingEmail`,
                label: `[${labelPrefix}billingEmail]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine1`,
                label: `[${labelPrefix}addressLine1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine2`,
                label: `[${labelPrefix}addressLine2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}postalCode`,
                label: `[${labelPrefix}postalCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryId`,
                label: `[${labelPrefix}countryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}stateId`,
                label: `[${labelPrefix}stateId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cityId`,
                label: `[${labelPrefix}cityId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingLocationId`,
                label: `[${labelPrefix}billingLocationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingLocationId`,
                label: `[${labelPrefix}shippingLocationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingMethodId`,
                label: `[${labelPrefix}shippingMethodId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}forexRate`,
                label: `[${labelPrefix}forexRate]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}currencyId`,
                label: `[${labelPrefix}currencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDetail`,
                label: `[${labelPrefix}totalDetail]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDetailCurrencyId`,
                label: `[${labelPrefix}totalDetailCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalProfit`,
                label: `[${labelPrefix}totalProfit]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalProfitCurrencyId`,
                label: `[${labelPrefix}totalProfitCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDiscounts`,
                label: `[${labelPrefix}totalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalSurcharges`,
                label: `[${labelPrefix}totalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingTax`,
                label: `[${labelPrefix}totalShippingTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingTaxCurrencyId`,
                label: `[${labelPrefix}totalShippingTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingCost`,
                label: `[${labelPrefix}totalShippingCost]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingCostCurrencyId`,
                label: `[${labelPrefix}totalShippingCostCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalDiscounts`,
                label: `[${labelPrefix}totalGlobalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalGlobalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalSurcharges`,
                label: `[${labelPrefix}totalGlobalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalGlobalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalWithheldTax`,
                label: `[${labelPrefix}totalWithheldTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalWithheldTaxCurrencyId`,
                label: `[${labelPrefix}totalWithheldTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxBase`,
                label: `[${labelPrefix}totalTaxBase]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxBaseCurrencyId`,
                label: `[${labelPrefix}totalTaxBaseCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxes`,
                label: `[${labelPrefix}totalTaxes]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxesCurrencyId`,
                label: `[${labelPrefix}totalTaxesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}total`,
                label: `[${labelPrefix}total]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalCurrencyId`,
                label: `[${labelPrefix}totalCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}costCalculationMethod`,
                label: `[${labelPrefix}costCalculationMethod]`,
                type: 'string',
                choices: [
                    'Automatic',
                    'Custom',
                ],
            },
            {
                key: `${keyPrefix}taxCalculationMethod`,
                label: `[${labelPrefix}taxCalculationMethod]`,
                type: 'string',
                choices: [
                    'Included',
                    'Excluded',
                ],
            },
            {
                key: `${keyPrefix}paid`,
                label: `[${labelPrefix}paid]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}number`,
                label: `[${labelPrefix}number]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}notes`,
                label: `[${labelPrefix}notes]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}orderId`,
                label: `[${labelPrefix}orderId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enumeration`,
                label: `[${labelPrefix}enumeration]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}paymentModeId`,
                label: `[${labelPrefix}paymentModeId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enumerationRangeId`,
                label: `[${labelPrefix}enumerationRangeId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}emisorBillingProfileId`,
                label: `[${labelPrefix}emisorBillingProfileId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}receiverBillingProfileId`,
                label: `[${labelPrefix}receiverBillingProfileId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}emisorWalletAccountId`,
                label: `[${labelPrefix}emisorWalletAccountId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}receiverWalletAccountId`,
                label: `[${labelPrefix}receiverWalletAccountId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}customerNotes`,
                label: `[${labelPrefix}customerNotes]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}invoiceType`,
                label: `[${labelPrefix}invoiceType]`,
                type: 'string',
                choices: [
                    'PurchaseInvoice',
                    'SalesInvoice',
                    'CreditNote',
                    'DebitNote',
                ],
            },
            {
                key: `${keyPrefix}documentType`,
                label: `[${labelPrefix}documentType]`,
                type: 'string',
                choices: [
                    'Standard',
                    'DebitNote',
                    'CreditNote',
                ],
            },
            {
                key: `${keyPrefix}invoiceStatus`,
                label: `[${labelPrefix}invoiceStatus]`,
                type: 'string',
                choices: [
                    'Draft',
                    'Closed',
                    'Signed',
                    'Expired',
                    'Paid',
                ],
            },
            {
                key: `${keyPrefix}paymentDue`,
                label: `[${labelPrefix}paymentDue]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}validFrom`,
                label: `[${labelPrefix}validFrom]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}validTo`,
                label: `[${labelPrefix}validTo]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}invoiceLines`,
                label: `[${labelPrefix}invoiceLines]`,
                children: InvoiceLineCreateDto.fields(`${keyPrefix}invoiceLines${!isInput ? '[]' : ''}`, isInput, true), 
            },
            {
                key: `${keyPrefix}invoiceReferences`,
                label: `[${labelPrefix}invoiceReferences]`,
                children: InvoiceReferenceCreateDto.fields(`${keyPrefix}invoiceReferences${!isInput ? '[]' : ''}`, isInput, true), 
            },
            {
                key: `${keyPrefix}invoiceAdjustments`,
                label: `[${labelPrefix}invoiceAdjustments]`,
                children: InvoiceAdjustmentCreateDto.fields(`${keyPrefix}invoiceAdjustments${!isInput ? '[]' : ''}`, isInput, true), 
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'closed': bundle.inputData?.[`${keyPrefix}closed`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'userId': bundle.inputData?.[`${keyPrefix}userId`],
            'priceListId': bundle.inputData?.[`${keyPrefix}priceListId`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'individualId': bundle.inputData?.[`${keyPrefix}individualId`],
            'paymentTermId': bundle.inputData?.[`${keyPrefix}paymentTermId`],
            'organizationId': bundle.inputData?.[`${keyPrefix}organizationId`],
            'receiverTenantId': bundle.inputData?.[`${keyPrefix}receiverTenantId`],
            'firstName': bundle.inputData?.[`${keyPrefix}firstName`],
            'lastName': bundle.inputData?.[`${keyPrefix}lastName`],
            'companyName': bundle.inputData?.[`${keyPrefix}companyName`],
            'billingEmail': bundle.inputData?.[`${keyPrefix}billingEmail`],
            'addressLine1': bundle.inputData?.[`${keyPrefix}addressLine1`],
            'addressLine2': bundle.inputData?.[`${keyPrefix}addressLine2`],
            'postalCode': bundle.inputData?.[`${keyPrefix}postalCode`],
            'countryId': bundle.inputData?.[`${keyPrefix}countryId`],
            'stateId': bundle.inputData?.[`${keyPrefix}stateId`],
            'cityId': bundle.inputData?.[`${keyPrefix}cityId`],
            'billingLocationId': bundle.inputData?.[`${keyPrefix}billingLocationId`],
            'shippingLocationId': bundle.inputData?.[`${keyPrefix}shippingLocationId`],
            'shippingMethodId': bundle.inputData?.[`${keyPrefix}shippingMethodId`],
            'forexRate': bundle.inputData?.[`${keyPrefix}forexRate`],
            'currencyId': bundle.inputData?.[`${keyPrefix}currencyId`],
            'totalDetail': bundle.inputData?.[`${keyPrefix}totalDetail`],
            'totalDetailCurrencyId': bundle.inputData?.[`${keyPrefix}totalDetailCurrencyId`],
            'totalProfit': bundle.inputData?.[`${keyPrefix}totalProfit`],
            'totalProfitCurrencyId': bundle.inputData?.[`${keyPrefix}totalProfitCurrencyId`],
            'totalDiscounts': bundle.inputData?.[`${keyPrefix}totalDiscounts`],
            'totalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalDiscountsCurrencyId`],
            'totalSurcharges': bundle.inputData?.[`${keyPrefix}totalSurcharges`],
            'totalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalSurchargesCurrencyId`],
            'totalShippingTax': bundle.inputData?.[`${keyPrefix}totalShippingTax`],
            'totalShippingTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingTaxCurrencyId`],
            'totalShippingCost': bundle.inputData?.[`${keyPrefix}totalShippingCost`],
            'totalShippingCostCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingCostCurrencyId`],
            'totalGlobalDiscounts': bundle.inputData?.[`${keyPrefix}totalGlobalDiscounts`],
            'totalGlobalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalDiscountsCurrencyId`],
            'totalGlobalSurcharges': bundle.inputData?.[`${keyPrefix}totalGlobalSurcharges`],
            'totalGlobalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalSurchargesCurrencyId`],
            'totalWithheldTax': bundle.inputData?.[`${keyPrefix}totalWithheldTax`],
            'totalWithheldTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalWithheldTaxCurrencyId`],
            'totalTaxBase': bundle.inputData?.[`${keyPrefix}totalTaxBase`],
            'totalTaxBaseCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxBaseCurrencyId`],
            'totalTaxes': bundle.inputData?.[`${keyPrefix}totalTaxes`],
            'totalTaxesCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxesCurrencyId`],
            'total': bundle.inputData?.[`${keyPrefix}total`],
            'totalCurrencyId': bundle.inputData?.[`${keyPrefix}totalCurrencyId`],
            'costCalculationMethod': bundle.inputData?.[`${keyPrefix}costCalculationMethod`],
            'taxCalculationMethod': bundle.inputData?.[`${keyPrefix}taxCalculationMethod`],
            'paid': bundle.inputData?.[`${keyPrefix}paid`],
            'number': bundle.inputData?.[`${keyPrefix}number`],
            'notes': bundle.inputData?.[`${keyPrefix}notes`],
            'orderId': bundle.inputData?.[`${keyPrefix}orderId`],
            'enumeration': bundle.inputData?.[`${keyPrefix}enumeration`],
            'paymentModeId': bundle.inputData?.[`${keyPrefix}paymentModeId`],
            'enumerationRangeId': bundle.inputData?.[`${keyPrefix}enumerationRangeId`],
            'emisorBillingProfileId': bundle.inputData?.[`${keyPrefix}emisorBillingProfileId`],
            'receiverBillingProfileId': bundle.inputData?.[`${keyPrefix}receiverBillingProfileId`],
            'emisorWalletAccountId': bundle.inputData?.[`${keyPrefix}emisorWalletAccountId`],
            'receiverWalletAccountId': bundle.inputData?.[`${keyPrefix}receiverWalletAccountId`],
            'customerNotes': bundle.inputData?.[`${keyPrefix}customerNotes`],
            'invoiceType': bundle.inputData?.[`${keyPrefix}invoiceType`],
            'documentType': bundle.inputData?.[`${keyPrefix}documentType`],
            'invoiceStatus': bundle.inputData?.[`${keyPrefix}invoiceStatus`],
            'paymentDue': bundle.inputData?.[`${keyPrefix}paymentDue`],
            'validFrom': bundle.inputData?.[`${keyPrefix}validFrom`],
            'validTo': bundle.inputData?.[`${keyPrefix}validTo`],
            'invoiceLines': utils.childMapping(bundle.inputData?.[`${keyPrefix}invoiceLines`], `${keyPrefix}invoiceLines`, InvoiceLineCreateDto),
            'invoiceReferences': utils.childMapping(bundle.inputData?.[`${keyPrefix}invoiceReferences`], `${keyPrefix}invoiceReferences`, InvoiceReferenceCreateDto),
            'invoiceAdjustments': utils.childMapping(bundle.inputData?.[`${keyPrefix}invoiceAdjustments`], `${keyPrefix}invoiceAdjustments`, InvoiceAdjustmentCreateDto),
        }
    },
}
