const AccountGroupsApi = require('../apis/AccountGroupsApi');
const AccountingPeriodsApi = require('../apis/AccountingPeriodsApi');
const AccountsApi = require('../apis/AccountsApi');
const BankingApi = require('../apis/BankingApi');
const BillingProfilesApi = require('../apis/BillingProfilesApi');
const BudgetsApi = require('../apis/BudgetsApi');
const CommissionsApi = require('../apis/CommissionsApi');
const CostCentresApi = require('../apis/CostCentresApi');
const FenixAllianceABPWebApi = require('../apis/FenixAllianceABPWebApi');
const FinancialBooksApi = require('../apis/FinancialBooksApi');
const FiscalAuthoritiesApi = require('../apis/FiscalAuthoritiesApi');
const FiscalAuthorityYearsApi = require('../apis/FiscalAuthorityYearsApi');
const FiscalEnumerationRangesApi = require('../apis/FiscalEnumerationRangesApi');
const FiscalIdentificationTypesApi = require('../apis/FiscalIdentificationTypesApi');
const FiscalPeriodsApi = require('../apis/FiscalPeriodsApi');
const FiscalRegimesApi = require('../apis/FiscalRegimesApi');
const FiscalResponsibilitiesApi = require('../apis/FiscalResponsibilitiesApi');
const FiscalResponsibilityRecordsApi = require('../apis/FiscalResponsibilityRecordsApi');
const FiscalYearsApi = require('../apis/FiscalYearsApi');
const GrantsApi = require('../apis/GrantsApi');
const InvoiceEnumerationRangesApi = require('../apis/InvoiceEnumerationRangesApi');
const JournalTypesApi = require('../apis/JournalTypesApi');
const JournalsApi = require('../apis/JournalsApi');
const LedgerTypesApi = require('../apis/LedgerTypesApi');
const LedgersApi = require('../apis/LedgersApi');
const LoansApi = require('../apis/LoansApi');
const ReceiptsApi = require('../apis/ReceiptsApi');
const SharesApi = require('../apis/SharesApi');
const TaxPoliciesApi = require('../apis/TaxPoliciesApi');
const TaxRatesApi = require('../apis/TaxRatesApi');
const TransactionsApi = require('../apis/TransactionsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [AccountGroupsApi.createAccountGroup.key]: AccountGroupsApi.createAccountGroup,
    [AccountGroupsApi.deleteAccountGroup.key]: AccountGroupsApi.deleteAccountGroup,
    [AccountGroupsApi.getAccountGroup.key]: AccountGroupsApi.getAccountGroup,
    [AccountGroupsApi.getAccountGroups.key]: AccountGroupsApi.getAccountGroups,
    [AccountGroupsApi.getAccountGroupsCountAsync.key]: AccountGroupsApi.getAccountGroupsCountAsync,
    [AccountGroupsApi.updateAccountGroup.key]: AccountGroupsApi.updateAccountGroup,
    [AccountingPeriodsApi.createAccountingPeriod.key]: AccountingPeriodsApi.createAccountingPeriod,
    [AccountingPeriodsApi.deleteAccountingPeriod.key]: AccountingPeriodsApi.deleteAccountingPeriod,
    [AccountingPeriodsApi.getAccountingPeriod.key]: AccountingPeriodsApi.getAccountingPeriod,
    [AccountingPeriodsApi.getAccountingPeriods.key]: AccountingPeriodsApi.getAccountingPeriods,
    [AccountingPeriodsApi.getAccountingPeriodsCountAsync.key]: AccountingPeriodsApi.getAccountingPeriodsCountAsync,
    [AccountingPeriodsApi.updateAccountingPeriod.key]: AccountingPeriodsApi.updateAccountingPeriod,
    [AccountsApi.balanceAccountAsync.key]: AccountsApi.balanceAccountAsync,
    [AccountsApi.balanceRootAccountAsync.key]: AccountsApi.balanceRootAccountAsync,
    [AccountsApi.createAccountAsync.key]: AccountsApi.createAccountAsync,
    [AccountsApi.createAccountCreditAsync.key]: AccountsApi.createAccountCreditAsync,
    [AccountsApi.createAccountDebitAsync.key]: AccountsApi.createAccountDebitAsync,
    [AccountsApi.createAccountEntryAsync.key]: AccountsApi.createAccountEntryAsync,
    [AccountsApi.createAccountRelationAsync.key]: AccountsApi.createAccountRelationAsync,
    [AccountsApi.createAccountTypeAsync.key]: AccountsApi.createAccountTypeAsync,
    [AccountsApi.deleteAccountAsync.key]: AccountsApi.deleteAccountAsync,
    [AccountsApi.deleteAccountEntryAsync.key]: AccountsApi.deleteAccountEntryAsync,
    [AccountsApi.deleteAccountRelationAsync.key]: AccountsApi.deleteAccountRelationAsync,
    [AccountsApi.deleteAccountTypeAsync.key]: AccountsApi.deleteAccountTypeAsync,
    [AccountsApi.getAccountAggregateAsync.key]: AccountsApi.getAccountAggregateAsync,
    [AccountsApi.getAccountCreditsAsync.key]: AccountsApi.getAccountCreditsAsync,
    [AccountsApi.getAccountCreditsCountAsync.key]: AccountsApi.getAccountCreditsCountAsync,
    [AccountsApi.getAccountDebitsAsync.key]: AccountsApi.getAccountDebitsAsync,
    [AccountsApi.getAccountDebitsCountAsync.key]: AccountsApi.getAccountDebitsCountAsync,
    [AccountsApi.getAccountDetailsAsync.key]: AccountsApi.getAccountDetailsAsync,
    [AccountsApi.getAccountEntriesAsync.key]: AccountsApi.getAccountEntriesAsync,
    [AccountsApi.getAccountEntryAsync.key]: AccountsApi.getAccountEntryAsync,
    [AccountsApi.getAccountRelationsAsync.key]: AccountsApi.getAccountRelationsAsync,
    [AccountsApi.getAccountRelationsCountAsync.key]: AccountsApi.getAccountRelationsCountAsync,
    [AccountsApi.getAccountTypesAsync.key]: AccountsApi.getAccountTypesAsync,
    [AccountsApi.getAccountTypesCountAsync.key]: AccountsApi.getAccountTypesCountAsync,
    [AccountsApi.getAccountsAsync.key]: AccountsApi.getAccountsAsync,
    [AccountsApi.getAccountsCountAsync.key]: AccountsApi.getAccountsCountAsync,
    [AccountsApi.getChildAccountsAsync.key]: AccountsApi.getChildAccountsAsync,
    [AccountsApi.getCreditAccountEntriesAsync.key]: AccountsApi.getCreditAccountEntriesAsync,
    [AccountsApi.getDebitAccountEntriesAsync.key]: AccountsApi.getDebitAccountEntriesAsync,
    [AccountsApi.getRootAccountsAsync.key]: AccountsApi.getRootAccountsAsync,
    [AccountsApi.patchAccountAsync.key]: AccountsApi.patchAccountAsync,
    [AccountsApi.updateAccountAsync.key]: AccountsApi.updateAccountAsync,
    [AccountsApi.updateAccountEntryAsync.key]: AccountsApi.updateAccountEntryAsync,
    [AccountsApi.updateAccountRelationAsync.key]: AccountsApi.updateAccountRelationAsync,
    [AccountsApi.updateAccountTypeAsync.key]: AccountsApi.updateAccountTypeAsync,
    [BankingApi.createBank.key]: BankingApi.createBank,
    [BankingApi.createBankAccount.key]: BankingApi.createBankAccount,
    [BankingApi.createBankGuarantee.key]: BankingApi.createBankGuarantee,
    [BankingApi.createBankTransaction.key]: BankingApi.createBankTransaction,
    [BankingApi.deleteBank.key]: BankingApi.deleteBank,
    [BankingApi.deleteBankAccount.key]: BankingApi.deleteBankAccount,
    [BankingApi.deleteBankGuarantee.key]: BankingApi.deleteBankGuarantee,
    [BankingApi.deleteBankTransaction.key]: BankingApi.deleteBankTransaction,
    [BankingApi.getBank.key]: BankingApi.getBank,
    [BankingApi.getBankAccount.key]: BankingApi.getBankAccount,
    [BankingApi.getBankAccounts.key]: BankingApi.getBankAccounts,
    [BankingApi.getBankAccountsCount.key]: BankingApi.getBankAccountsCount,
    [BankingApi.getBankGuarantee.key]: BankingApi.getBankGuarantee,
    [BankingApi.getBankGuarantees.key]: BankingApi.getBankGuarantees,
    [BankingApi.getBankGuaranteesCount.key]: BankingApi.getBankGuaranteesCount,
    [BankingApi.getBankTransaction.key]: BankingApi.getBankTransaction,
    [BankingApi.getBankTransactions.key]: BankingApi.getBankTransactions,
    [BankingApi.getBankTransactionsCount.key]: BankingApi.getBankTransactionsCount,
    [BankingApi.getBanks.key]: BankingApi.getBanks,
    [BankingApi.getBanksCount.key]: BankingApi.getBanksCount,
    [BankingApi.updateBank.key]: BankingApi.updateBank,
    [BankingApi.updateBankAccount.key]: BankingApi.updateBankAccount,
    [BankingApi.updateBankGuarantee.key]: BankingApi.updateBankGuarantee,
    [BankingApi.updateBankTransaction.key]: BankingApi.updateBankTransaction,
    [BillingProfilesApi.createBillingProfileAsync.key]: BillingProfilesApi.createBillingProfileAsync,
    [BillingProfilesApi.deleteBillingProfileAsync.key]: BillingProfilesApi.deleteBillingProfileAsync,
    [BillingProfilesApi.getBillingProfileByIdAsync.key]: BillingProfilesApi.getBillingProfileByIdAsync,
    [BillingProfilesApi.getBillingProfilesAsync.key]: BillingProfilesApi.getBillingProfilesAsync,
    [BillingProfilesApi.getBillingProfilesCountAsync.key]: BillingProfilesApi.getBillingProfilesCountAsync,
    [BillingProfilesApi.updateBillingProfileAsync.key]: BillingProfilesApi.updateBillingProfileAsync,
    [BudgetsApi.createBudgetAccountEntryAsync.key]: BudgetsApi.createBudgetAccountEntryAsync,
    [BudgetsApi.createBudgetAsync.key]: BudgetsApi.createBudgetAsync,
    [BudgetsApi.deleteBudgetAccountEntryAsync.key]: BudgetsApi.deleteBudgetAccountEntryAsync,
    [BudgetsApi.deleteBudgetAsync.key]: BudgetsApi.deleteBudgetAsync,
    [BudgetsApi.getBudgetAccountEntriesCollectionAsync.key]: BudgetsApi.getBudgetAccountEntriesCollectionAsync,
    [BudgetsApi.getBudgetAccountEntryAsync.key]: BudgetsApi.getBudgetAccountEntryAsync,
    [BudgetsApi.getBudgetDetailsAsync.key]: BudgetsApi.getBudgetDetailsAsync,
    [BudgetsApi.getBudgetsAsync.key]: BudgetsApi.getBudgetsAsync,
    [BudgetsApi.updateBudgetAccountEntryAsync.key]: BudgetsApi.updateBudgetAccountEntryAsync,
    [BudgetsApi.updateBudgetAsync.key]: BudgetsApi.updateBudgetAsync,
    [CommissionsApi.createCommissionAsync.key]: CommissionsApi.createCommissionAsync,
    [CommissionsApi.createPaymentCommissionAsync.key]: CommissionsApi.createPaymentCommissionAsync,
    [CommissionsApi.deleteCommissionAsync.key]: CommissionsApi.deleteCommissionAsync,
    [CommissionsApi.deletePaymentCommissionAsync.key]: CommissionsApi.deletePaymentCommissionAsync,
    [CommissionsApi.getCommissionAsync.key]: CommissionsApi.getCommissionAsync,
    [CommissionsApi.getCommissionsAsync.key]: CommissionsApi.getCommissionsAsync,
    [CommissionsApi.getCommissionsCountAsync.key]: CommissionsApi.getCommissionsCountAsync,
    [CommissionsApi.getPaymentCommissionAsync.key]: CommissionsApi.getPaymentCommissionAsync,
    [CommissionsApi.getPaymentCommissionsAsync.key]: CommissionsApi.getPaymentCommissionsAsync,
    [CommissionsApi.getPaymentCommissionsCountAsync.key]: CommissionsApi.getPaymentCommissionsCountAsync,
    [CommissionsApi.updateCommissionAsync.key]: CommissionsApi.updateCommissionAsync,
    [CommissionsApi.updatePaymentCommissionAsync.key]: CommissionsApi.updatePaymentCommissionAsync,
    [CostCentresApi.createCostCentre.key]: CostCentresApi.createCostCentre,
    [CostCentresApi.createCostCentreBudget.key]: CostCentresApi.createCostCentreBudget,
    [CostCentresApi.createCostCentreGroup.key]: CostCentresApi.createCostCentreGroup,
    [CostCentresApi.deleteCostCentre.key]: CostCentresApi.deleteCostCentre,
    [CostCentresApi.deleteCostCentreBudget.key]: CostCentresApi.deleteCostCentreBudget,
    [CostCentresApi.deleteCostCentreGroup.key]: CostCentresApi.deleteCostCentreGroup,
    [CostCentresApi.getCostCentre.key]: CostCentresApi.getCostCentre,
    [CostCentresApi.getCostCentreBudget.key]: CostCentresApi.getCostCentreBudget,
    [CostCentresApi.getCostCentreBudgets.key]: CostCentresApi.getCostCentreBudgets,
    [CostCentresApi.getCostCentreGroup.key]: CostCentresApi.getCostCentreGroup,
    [CostCentresApi.getCostCentreGroups.key]: CostCentresApi.getCostCentreGroups,
    [CostCentresApi.getCostCentreGroupsCount.key]: CostCentresApi.getCostCentreGroupsCount,
    [CostCentresApi.getCostCentres.key]: CostCentresApi.getCostCentres,
    [CostCentresApi.getCostCentresCount.key]: CostCentresApi.getCostCentresCount,
    [CostCentresApi.updateCostCentre.key]: CostCentresApi.updateCostCentre,
    [CostCentresApi.updateCostCentreBudget.key]: CostCentresApi.updateCostCentreBudget,
    [CostCentresApi.updateCostCentreGroup.key]: CostCentresApi.updateCostCentreGroup,
    [FenixAllianceABPWebApi.forgotPasswordPost.key]: FenixAllianceABPWebApi.forgotPasswordPost,
    [FenixAllianceABPWebApi.healthGet.key]: FenixAllianceABPWebApi.healthGet,
    [FenixAllianceABPWebApi.helloGet.key]: FenixAllianceABPWebApi.helloGet,
    [FenixAllianceABPWebApi.loginPost.key]: FenixAllianceABPWebApi.loginPost,
    [FenixAllianceABPWebApi.manage2faPost.key]: FenixAllianceABPWebApi.manage2faPost,
    [FenixAllianceABPWebApi.manageInfoGet.key]: FenixAllianceABPWebApi.manageInfoGet,
    [FenixAllianceABPWebApi.manageInfoPost.key]: FenixAllianceABPWebApi.manageInfoPost,
    [FenixAllianceABPWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABPWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABPWebApi.refreshPost.key]: FenixAllianceABPWebApi.refreshPost,
    [FenixAllianceABPWebApi.registerPost.key]: FenixAllianceABPWebApi.registerPost,
    [FenixAllianceABPWebApi.resendConfirmationEmailPost.key]: FenixAllianceABPWebApi.resendConfirmationEmailPost,
    [FenixAllianceABPWebApi.resetPasswordPost.key]: FenixAllianceABPWebApi.resetPasswordPost,
    [FenixAllianceABPWebApi.versionGet.key]: FenixAllianceABPWebApi.versionGet,
    [FinancialBooksApi.createFinancialBookAsync.key]: FinancialBooksApi.createFinancialBookAsync,
    [FinancialBooksApi.deleteFinancialBookAsync.key]: FinancialBooksApi.deleteFinancialBookAsync,
    [FinancialBooksApi.getFinancialBookDetailsAsync.key]: FinancialBooksApi.getFinancialBookDetailsAsync,
    [FinancialBooksApi.getFinancialBooksAsync.key]: FinancialBooksApi.getFinancialBooksAsync,
    [FinancialBooksApi.getFinancialBooksCountAsync.key]: FinancialBooksApi.getFinancialBooksCountAsync,
    [FinancialBooksApi.updateFinancialBookAsync.key]: FinancialBooksApi.updateFinancialBookAsync,
    [FiscalAuthoritiesApi.createFiscalAuthority.key]: FiscalAuthoritiesApi.createFiscalAuthority,
    [FiscalAuthoritiesApi.deleteFiscalAuthority.key]: FiscalAuthoritiesApi.deleteFiscalAuthority,
    [FiscalAuthoritiesApi.getFiscalAuthorities.key]: FiscalAuthoritiesApi.getFiscalAuthorities,
    [FiscalAuthoritiesApi.getFiscalAuthoritiesCount.key]: FiscalAuthoritiesApi.getFiscalAuthoritiesCount,
    [FiscalAuthoritiesApi.getFiscalAuthority.key]: FiscalAuthoritiesApi.getFiscalAuthority,
    [FiscalAuthoritiesApi.updateFiscalAuthority.key]: FiscalAuthoritiesApi.updateFiscalAuthority,
    [FiscalAuthorityYearsApi.createFiscalYear.key]: FiscalAuthorityYearsApi.createFiscalYear,
    [FiscalAuthorityYearsApi.deleteFiscalYear.key]: FiscalAuthorityYearsApi.deleteFiscalYear,
    [FiscalAuthorityYearsApi.getFiscalYear.key]: FiscalAuthorityYearsApi.getFiscalYear,
    [FiscalAuthorityYearsApi.getFiscalYears.key]: FiscalAuthorityYearsApi.getFiscalYears,
    [FiscalAuthorityYearsApi.getFiscalYearsCount.key]: FiscalAuthorityYearsApi.getFiscalYearsCount,
    [FiscalAuthorityYearsApi.updateFiscalYear.key]: FiscalAuthorityYearsApi.updateFiscalYear,
    [FiscalEnumerationRangesApi.createInvoiceEnumerationRange.key]: FiscalEnumerationRangesApi.createInvoiceEnumerationRange,
    [FiscalEnumerationRangesApi.deleteInvoiceEnumerationRange.key]: FiscalEnumerationRangesApi.deleteInvoiceEnumerationRange,
    [FiscalEnumerationRangesApi.getInvoiceEnumerationRange.key]: FiscalEnumerationRangesApi.getInvoiceEnumerationRange,
    [FiscalEnumerationRangesApi.getInvoiceEnumerationRanges.key]: FiscalEnumerationRangesApi.getInvoiceEnumerationRanges,
    [FiscalEnumerationRangesApi.getInvoiceEnumerationRangesCount.key]: FiscalEnumerationRangesApi.getInvoiceEnumerationRangesCount,
    [FiscalEnumerationRangesApi.updateInvoiceEnumerationRange.key]: FiscalEnumerationRangesApi.updateInvoiceEnumerationRange,
    [FiscalIdentificationTypesApi.createFiscalIdentificationType.key]: FiscalIdentificationTypesApi.createFiscalIdentificationType,
    [FiscalIdentificationTypesApi.deleteFiscalIdentificationType.key]: FiscalIdentificationTypesApi.deleteFiscalIdentificationType,
    [FiscalIdentificationTypesApi.getFiscalIdentificationType.key]: FiscalIdentificationTypesApi.getFiscalIdentificationType,
    [FiscalIdentificationTypesApi.getFiscalIdentificationTypes.key]: FiscalIdentificationTypesApi.getFiscalIdentificationTypes,
    [FiscalIdentificationTypesApi.getFiscalIdentificationTypesCount.key]: FiscalIdentificationTypesApi.getFiscalIdentificationTypesCount,
    [FiscalIdentificationTypesApi.updateFiscalIdentificationType.key]: FiscalIdentificationTypesApi.updateFiscalIdentificationType,
    [FiscalPeriodsApi.createFiscalPeriod.key]: FiscalPeriodsApi.createFiscalPeriod,
    [FiscalPeriodsApi.deleteFiscalPeriod.key]: FiscalPeriodsApi.deleteFiscalPeriod,
    [FiscalPeriodsApi.getFiscalPeriod.key]: FiscalPeriodsApi.getFiscalPeriod,
    [FiscalPeriodsApi.getFiscalPeriods.key]: FiscalPeriodsApi.getFiscalPeriods,
    [FiscalPeriodsApi.getFiscalPeriodsCount.key]: FiscalPeriodsApi.getFiscalPeriodsCount,
    [FiscalPeriodsApi.updateFiscalPeriod.key]: FiscalPeriodsApi.updateFiscalPeriod,
    [FiscalRegimesApi.createFiscalRegime.key]: FiscalRegimesApi.createFiscalRegime,
    [FiscalRegimesApi.deleteFiscalRegime.key]: FiscalRegimesApi.deleteFiscalRegime,
    [FiscalRegimesApi.getFiscalRegime.key]: FiscalRegimesApi.getFiscalRegime,
    [FiscalRegimesApi.getFiscalRegimes.key]: FiscalRegimesApi.getFiscalRegimes,
    [FiscalRegimesApi.getFiscalRegimesCount.key]: FiscalRegimesApi.getFiscalRegimesCount,
    [FiscalRegimesApi.updateFiscalRegime.key]: FiscalRegimesApi.updateFiscalRegime,
    [FiscalResponsibilitiesApi.createFiscalResponsibility.key]: FiscalResponsibilitiesApi.createFiscalResponsibility,
    [FiscalResponsibilitiesApi.deleteFiscalResponsibility.key]: FiscalResponsibilitiesApi.deleteFiscalResponsibility,
    [FiscalResponsibilitiesApi.getFiscalResponsibilities.key]: FiscalResponsibilitiesApi.getFiscalResponsibilities,
    [FiscalResponsibilitiesApi.getFiscalResponsibilitiesCount.key]: FiscalResponsibilitiesApi.getFiscalResponsibilitiesCount,
    [FiscalResponsibilitiesApi.getFiscalResponsibility.key]: FiscalResponsibilitiesApi.getFiscalResponsibility,
    [FiscalResponsibilitiesApi.updateFiscalResponsibility.key]: FiscalResponsibilitiesApi.updateFiscalResponsibility,
    [FiscalResponsibilityRecordsApi.createFiscalResponsibilityRecord.key]: FiscalResponsibilityRecordsApi.createFiscalResponsibilityRecord,
    [FiscalResponsibilityRecordsApi.deleteFiscalResponsibilityRecord.key]: FiscalResponsibilityRecordsApi.deleteFiscalResponsibilityRecord,
    [FiscalResponsibilityRecordsApi.getFiscalResponsibilityRecord.key]: FiscalResponsibilityRecordsApi.getFiscalResponsibilityRecord,
    [FiscalResponsibilityRecordsApi.getFiscalResponsibilityRecords.key]: FiscalResponsibilityRecordsApi.getFiscalResponsibilityRecords,
    [FiscalResponsibilityRecordsApi.getFiscalResponsibilityRecordsCount.key]: FiscalResponsibilityRecordsApi.getFiscalResponsibilityRecordsCount,
    [FiscalResponsibilityRecordsApi.updateFiscalResponsibilityRecord.key]: FiscalResponsibilityRecordsApi.updateFiscalResponsibilityRecord,
    [FiscalYearsApi.createFiscalYearAsync.key]: FiscalYearsApi.createFiscalYearAsync,
    [FiscalYearsApi.deleteFiscalYearAsync.key]: FiscalYearsApi.deleteFiscalYearAsync,
    [FiscalYearsApi.getFiscalYearDetailsAsync.key]: FiscalYearsApi.getFiscalYearDetailsAsync,
    [FiscalYearsApi.getFiscalYearsAsync.key]: FiscalYearsApi.getFiscalYearsAsync,
    [FiscalYearsApi.getFiscalYearsCountAsync.key]: FiscalYearsApi.getFiscalYearsCountAsync,
    [FiscalYearsApi.updateFiscalYearAsync.key]: FiscalYearsApi.updateFiscalYearAsync,
    [GrantsApi.createGrantAsync.key]: GrantsApi.createGrantAsync,
    [GrantsApi.deleteGrantAsync.key]: GrantsApi.deleteGrantAsync,
    [GrantsApi.getGrantDetailsAsync.key]: GrantsApi.getGrantDetailsAsync,
    [GrantsApi.getGrantsAsync.key]: GrantsApi.getGrantsAsync,
    [GrantsApi.getGrantsCountAsync.key]: GrantsApi.getGrantsCountAsync,
    [GrantsApi.updateGrantAsync.key]: GrantsApi.updateGrantAsync,
    [InvoiceEnumerationRangesApi.createInvoiceEnumerationRangeAsync.key]: InvoiceEnumerationRangesApi.createInvoiceEnumerationRangeAsync,
    [InvoiceEnumerationRangesApi.deleteInvoiceEnumerationRangeAsync.key]: InvoiceEnumerationRangesApi.deleteInvoiceEnumerationRangeAsync,
    [InvoiceEnumerationRangesApi.getInvoiceEnumerationRangeDetailsAsync.key]: InvoiceEnumerationRangesApi.getInvoiceEnumerationRangeDetailsAsync,
    [InvoiceEnumerationRangesApi.getInvoiceEnumerationRangesAsync.key]: InvoiceEnumerationRangesApi.getInvoiceEnumerationRangesAsync,
    [InvoiceEnumerationRangesApi.updateInvoiceEnumerationRangeAsync.key]: InvoiceEnumerationRangesApi.updateInvoiceEnumerationRangeAsync,
    [JournalTypesApi.createJournalTypeAsync.key]: JournalTypesApi.createJournalTypeAsync,
    [JournalTypesApi.deleteJournalTypeAsync.key]: JournalTypesApi.deleteJournalTypeAsync,
    [JournalTypesApi.getJournalTypeDetailsAsync.key]: JournalTypesApi.getJournalTypeDetailsAsync,
    [JournalTypesApi.getJournalTypesAsync.key]: JournalTypesApi.getJournalTypesAsync,
    [JournalTypesApi.getJournalTypesCountAsync.key]: JournalTypesApi.getJournalTypesCountAsync,
    [JournalTypesApi.updateJournalTypeAsync.key]: JournalTypesApi.updateJournalTypeAsync,
    [JournalsApi.countJournalsAsync.key]: JournalsApi.countJournalsAsync,
    [JournalsApi.createJournalAsync.key]: JournalsApi.createJournalAsync,
    [JournalsApi.createJournalEntryAsync.key]: JournalsApi.createJournalEntryAsync,
    [JournalsApi.deleteJournalAsync.key]: JournalsApi.deleteJournalAsync,
    [JournalsApi.deleteJournalEntryAsync.key]: JournalsApi.deleteJournalEntryAsync,
    [JournalsApi.getJournalDetailsAsync.key]: JournalsApi.getJournalDetailsAsync,
    [JournalsApi.getJournalEntriesAsync.key]: JournalsApi.getJournalEntriesAsync,
    [JournalsApi.getJournalEntriesCountAsync.key]: JournalsApi.getJournalEntriesCountAsync,
    [JournalsApi.getJournalsAsync.key]: JournalsApi.getJournalsAsync,
    [JournalsApi.updateJournalAsync.key]: JournalsApi.updateJournalAsync,
    [JournalsApi.updateJournalEntryAsync.key]: JournalsApi.updateJournalEntryAsync,
    [LedgerTypesApi.createLedgerTypeAsync.key]: LedgerTypesApi.createLedgerTypeAsync,
    [LedgerTypesApi.deleteLedgerTypeAsync.key]: LedgerTypesApi.deleteLedgerTypeAsync,
    [LedgerTypesApi.getLedgerTypeDetailsAsync.key]: LedgerTypesApi.getLedgerTypeDetailsAsync,
    [LedgerTypesApi.getLedgerTypesAsync.key]: LedgerTypesApi.getLedgerTypesAsync,
    [LedgerTypesApi.getLedgerTypesCountAsync.key]: LedgerTypesApi.getLedgerTypesCountAsync,
    [LedgerTypesApi.updateLedgerTypeAsync.key]: LedgerTypesApi.updateLedgerTypeAsync,
    [LedgersApi.createLedgerAsync.key]: LedgersApi.createLedgerAsync,
    [LedgersApi.deleteLedgerAsync.key]: LedgersApi.deleteLedgerAsync,
    [LedgersApi.getLedgerDetailsAsync.key]: LedgersApi.getLedgerDetailsAsync,
    [LedgersApi.getLedgersAsync.key]: LedgersApi.getLedgersAsync,
    [LedgersApi.getLedgersCountAsync.key]: LedgersApi.getLedgersCountAsync,
    [LedgersApi.updateLedgerAsync.key]: LedgersApi.updateLedgerAsync,
    [LoansApi.createLoanApplicationAsync.key]: LoansApi.createLoanApplicationAsync,
    [LoansApi.createLoanAsync.key]: LoansApi.createLoanAsync,
    [LoansApi.deleteLoanApplicationAsync.key]: LoansApi.deleteLoanApplicationAsync,
    [LoansApi.deleteLoanAsync.key]: LoansApi.deleteLoanAsync,
    [LoansApi.getLoanApplicationDetailsAsync.key]: LoansApi.getLoanApplicationDetailsAsync,
    [LoansApi.getLoanApplicationsAsync.key]: LoansApi.getLoanApplicationsAsync,
    [LoansApi.getLoanApplicationsCountAsync.key]: LoansApi.getLoanApplicationsCountAsync,
    [LoansApi.getLoanDetailsAsync.key]: LoansApi.getLoanDetailsAsync,
    [LoansApi.getLoansAsync.key]: LoansApi.getLoansAsync,
    [LoansApi.getLoansCountAsync.key]: LoansApi.getLoansCountAsync,
    [LoansApi.updateLoanApplicationAsync.key]: LoansApi.updateLoanApplicationAsync,
    [LoansApi.updateLoanAsync.key]: LoansApi.updateLoanAsync,
    [ReceiptsApi.createReceiptAsync.key]: ReceiptsApi.createReceiptAsync,
    [ReceiptsApi.deleteReceiptAsync.key]: ReceiptsApi.deleteReceiptAsync,
    [ReceiptsApi.getReceiptDetailsAsync.key]: ReceiptsApi.getReceiptDetailsAsync,
    [ReceiptsApi.getReceiptsAsync.key]: ReceiptsApi.getReceiptsAsync,
    [ReceiptsApi.getReceiptsCountAsync.key]: ReceiptsApi.getReceiptsCountAsync,
    [ReceiptsApi.updateReceiptAsync.key]: ReceiptsApi.updateReceiptAsync,
    [SharesApi.createShareClass.key]: SharesApi.createShareClass,
    [SharesApi.createShareIssuance.key]: SharesApi.createShareIssuance,
    [SharesApi.createShareTransfer.key]: SharesApi.createShareTransfer,
    [SharesApi.createShareTransferReason.key]: SharesApi.createShareTransferReason,
    [SharesApi.deleteShareClass.key]: SharesApi.deleteShareClass,
    [SharesApi.deleteShareIssuance.key]: SharesApi.deleteShareIssuance,
    [SharesApi.deleteShareTransfer.key]: SharesApi.deleteShareTransfer,
    [SharesApi.deleteShareTransferReason.key]: SharesApi.deleteShareTransferReason,
    [SharesApi.getShareClass.key]: SharesApi.getShareClass,
    [SharesApi.getShareClasses.key]: SharesApi.getShareClasses,
    [SharesApi.getShareClassesCount.key]: SharesApi.getShareClassesCount,
    [SharesApi.getShareIssuance.key]: SharesApi.getShareIssuance,
    [SharesApi.getShareIssuances.key]: SharesApi.getShareIssuances,
    [SharesApi.getShareIssuancesCount.key]: SharesApi.getShareIssuancesCount,
    [SharesApi.getShareTransfer.key]: SharesApi.getShareTransfer,
    [SharesApi.getShareTransferReason.key]: SharesApi.getShareTransferReason,
    [SharesApi.getShareTransferReasons.key]: SharesApi.getShareTransferReasons,
    [SharesApi.getShareTransferReasonsCount.key]: SharesApi.getShareTransferReasonsCount,
    [SharesApi.getShareTransfers.key]: SharesApi.getShareTransfers,
    [SharesApi.getShareTransfersCount.key]: SharesApi.getShareTransfersCount,
    [SharesApi.updateShareClass.key]: SharesApi.updateShareClass,
    [SharesApi.updateShareIssuance.key]: SharesApi.updateShareIssuance,
    [SharesApi.updateShareTransfer.key]: SharesApi.updateShareTransfer,
    [SharesApi.updateShareTransferReason.key]: SharesApi.updateShareTransferReason,
    [TaxPoliciesApi.createAppliedTaxPolicyRecord.key]: TaxPoliciesApi.createAppliedTaxPolicyRecord,
    [TaxPoliciesApi.createItemTaxPolicyRecord.key]: TaxPoliciesApi.createItemTaxPolicyRecord,
    [TaxPoliciesApi.createTaxPolicy.key]: TaxPoliciesApi.createTaxPolicy,
    [TaxPoliciesApi.deleteAppliedTaxPolicyRecord.key]: TaxPoliciesApi.deleteAppliedTaxPolicyRecord,
    [TaxPoliciesApi.deleteItemTaxPolicyRecord.key]: TaxPoliciesApi.deleteItemTaxPolicyRecord,
    [TaxPoliciesApi.deleteTaxPolicy.key]: TaxPoliciesApi.deleteTaxPolicy,
    [TaxPoliciesApi.getAppliedTaxPolicyRecord.key]: TaxPoliciesApi.getAppliedTaxPolicyRecord,
    [TaxPoliciesApi.getAppliedTaxPolicyRecords.key]: TaxPoliciesApi.getAppliedTaxPolicyRecords,
    [TaxPoliciesApi.getAppliedTaxPolicyRecordsCount.key]: TaxPoliciesApi.getAppliedTaxPolicyRecordsCount,
    [TaxPoliciesApi.getItemTaxPolicyRecord.key]: TaxPoliciesApi.getItemTaxPolicyRecord,
    [TaxPoliciesApi.getItemTaxPolicyRecords.key]: TaxPoliciesApi.getItemTaxPolicyRecords,
    [TaxPoliciesApi.getTaxPolicies.key]: TaxPoliciesApi.getTaxPolicies,
    [TaxPoliciesApi.getTaxPoliciesByAuthority.key]: TaxPoliciesApi.getTaxPoliciesByAuthority,
    [TaxPoliciesApi.getTaxPoliciesCount.key]: TaxPoliciesApi.getTaxPoliciesCount,
    [TaxPoliciesApi.getTaxPolicy.key]: TaxPoliciesApi.getTaxPolicy,
    [TaxPoliciesApi.updateAppliedTaxPolicyRecord.key]: TaxPoliciesApi.updateAppliedTaxPolicyRecord,
    [TaxPoliciesApi.updateItemTaxPolicyRecord.key]: TaxPoliciesApi.updateItemTaxPolicyRecord,
    [TaxPoliciesApi.updateTaxPolicy.key]: TaxPoliciesApi.updateTaxPolicy,
    [TaxRatesApi.createTaxRate.key]: TaxRatesApi.createTaxRate,
    [TaxRatesApi.deleteTaxRate.key]: TaxRatesApi.deleteTaxRate,
    [TaxRatesApi.getTaxRate.key]: TaxRatesApi.getTaxRate,
    [TaxRatesApi.getTaxRates.key]: TaxRatesApi.getTaxRates,
    [TaxRatesApi.getTaxRatesCount.key]: TaxRatesApi.getTaxRatesCount,
    [TaxRatesApi.updateTaxRate.key]: TaxRatesApi.updateTaxRate,
    [TransactionsApi.createTransaction.key]: TransactionsApi.createTransaction,
    [TransactionsApi.createTransactionCategory.key]: TransactionsApi.createTransactionCategory,
    [TransactionsApi.deleteTransaction.key]: TransactionsApi.deleteTransaction,
    [TransactionsApi.deleteTransactionCategory.key]: TransactionsApi.deleteTransactionCategory,
    [TransactionsApi.getTransaction.key]: TransactionsApi.getTransaction,
    [TransactionsApi.getTransactionCategories.key]: TransactionsApi.getTransactionCategories,
    [TransactionsApi.getTransactionCategoriesCount.key]: TransactionsApi.getTransactionCategoriesCount,
    [TransactionsApi.getTransactionCategory.key]: TransactionsApi.getTransactionCategory,
    [TransactionsApi.getTransactions.key]: TransactionsApi.getTransactions,
    [TransactionsApi.getTransactionsCount.key]: TransactionsApi.getTransactionsCount,
    [TransactionsApi.updateTransaction.key]: TransactionsApi.updateTransaction,
    [TransactionsApi.updateTransactionCategory.key]: TransactionsApi.updateTransactionCategory,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
