const ContactGroupsApi = require('../apis/ContactGroupsApi');
const ContactProfilesApi = require('../apis/ContactProfilesApi');
const ContactRelationTypesApi = require('../apis/ContactRelationTypesApi');
const ContactRelationsApi = require('../apis/ContactRelationsApi');
const ContactSourcesApi = require('../apis/ContactSourcesApi');
const ContactsApi = require('../apis/ContactsApi');
const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const OptionsApi = require('../apis/OptionsApi');
const SyncApi = require('../apis/SyncApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [ContactGroupsApi.createContactGroupAsync.key]: ContactGroupsApi.createContactGroupAsync,
    [ContactGroupsApi.deleteContactGroupAsync.key]: ContactGroupsApi.deleteContactGroupAsync,
    [ContactGroupsApi.getContactGroupByIdAsync.key]: ContactGroupsApi.getContactGroupByIdAsync,
    [ContactGroupsApi.getContactGroupsAsync.key]: ContactGroupsApi.getContactGroupsAsync,
    [ContactGroupsApi.getContactGroupsCountAsync.key]: ContactGroupsApi.getContactGroupsCountAsync,
    [ContactGroupsApi.patchContactGroupAsync.key]: ContactGroupsApi.patchContactGroupAsync,
    [ContactGroupsApi.updateContactGroupAsync.key]: ContactGroupsApi.updateContactGroupAsync,
    [ContactProfilesApi.createContactProfileAsync.key]: ContactProfilesApi.createContactProfileAsync,
    [ContactProfilesApi.deleteContactProfileAsync.key]: ContactProfilesApi.deleteContactProfileAsync,
    [ContactProfilesApi.getContactProfileByIdAsync.key]: ContactProfilesApi.getContactProfileByIdAsync,
    [ContactProfilesApi.getContactProfilesAsync.key]: ContactProfilesApi.getContactProfilesAsync,
    [ContactProfilesApi.getContactProfilesCountAsync.key]: ContactProfilesApi.getContactProfilesCountAsync,
    [ContactProfilesApi.getPartnerProfilesCountAsync.key]: ContactProfilesApi.getPartnerProfilesCountAsync,
    [ContactProfilesApi.getPatientProfilesCountAsync.key]: ContactProfilesApi.getPatientProfilesCountAsync,
    [ContactProfilesApi.patchContactProfileAsync.key]: ContactProfilesApi.patchContactProfileAsync,
    [ContactProfilesApi.updateContactProfileAsync.key]: ContactProfilesApi.updateContactProfileAsync,
    [ContactRelationTypesApi.createContactRelationTypeAsync.key]: ContactRelationTypesApi.createContactRelationTypeAsync,
    [ContactRelationTypesApi.deleteContactRelationTypeAsync.key]: ContactRelationTypesApi.deleteContactRelationTypeAsync,
    [ContactRelationTypesApi.getContactRelationTypeByIdAsync.key]: ContactRelationTypesApi.getContactRelationTypeByIdAsync,
    [ContactRelationTypesApi.getContactRelationTypesAsync.key]: ContactRelationTypesApi.getContactRelationTypesAsync,
    [ContactRelationTypesApi.getContactRelationTypesCountAsync.key]: ContactRelationTypesApi.getContactRelationTypesCountAsync,
    [ContactRelationTypesApi.patchContactRelationTypeAsync.key]: ContactRelationTypesApi.patchContactRelationTypeAsync,
    [ContactRelationTypesApi.updateContactRelationTypeAsync.key]: ContactRelationTypesApi.updateContactRelationTypeAsync,
    [ContactRelationsApi.createContactRelationAsync.key]: ContactRelationsApi.createContactRelationAsync,
    [ContactRelationsApi.deleteContactRelationAsync.key]: ContactRelationsApi.deleteContactRelationAsync,
    [ContactRelationsApi.getContactRelationByIdAsync.key]: ContactRelationsApi.getContactRelationByIdAsync,
    [ContactRelationsApi.getContactRelationsAsync.key]: ContactRelationsApi.getContactRelationsAsync,
    [ContactRelationsApi.getContactRelationsCountAsync.key]: ContactRelationsApi.getContactRelationsCountAsync,
    [ContactRelationsApi.patchContactRelationAsync.key]: ContactRelationsApi.patchContactRelationAsync,
    [ContactRelationsApi.updateContactRelationAsync.key]: ContactRelationsApi.updateContactRelationAsync,
    [ContactSourcesApi.createContactSourceAsync.key]: ContactSourcesApi.createContactSourceAsync,
    [ContactSourcesApi.deleteContactSourceAsync.key]: ContactSourcesApi.deleteContactSourceAsync,
    [ContactSourcesApi.getContactSourceByIdAsync.key]: ContactSourcesApi.getContactSourceByIdAsync,
    [ContactSourcesApi.getContactSourcesAsync.key]: ContactSourcesApi.getContactSourcesAsync,
    [ContactSourcesApi.getContactSourcesCountAsync.key]: ContactSourcesApi.getContactSourcesCountAsync,
    [ContactSourcesApi.patchContactSourceAsync.key]: ContactSourcesApi.patchContactSourceAsync,
    [ContactSourcesApi.updateContactSourceAsync.key]: ContactSourcesApi.updateContactSourceAsync,
    [ContactsApi.createContactAsync.key]: ContactsApi.createContactAsync,
    [ContactsApi.createContactEmailAsync.key]: ContactsApi.createContactEmailAsync,
    [ContactsApi.createProfileForContactAsync.key]: ContactsApi.createProfileForContactAsync,
    [ContactsApi.deleteContactAsync.key]: ContactsApi.deleteContactAsync,
    [ContactsApi.deleteContactEmailAsync.key]: ContactsApi.deleteContactEmailAsync,
    [ContactsApi.deleteProfileForContactAsync.key]: ContactsApi.deleteProfileForContactAsync,
    [ContactsApi.getBusinessOwnedIndividualAsync.key]: ContactsApi.getBusinessOwnedIndividualAsync,
    [ContactsApi.getBusinessOwnedIndividualsAsync.key]: ContactsApi.getBusinessOwnedIndividualsAsync,
    [ContactsApi.getBusinessOwnedIndividualsCountAsync.key]: ContactsApi.getBusinessOwnedIndividualsCountAsync,
    [ContactsApi.getBusinessOwnedOrganizationAsync.key]: ContactsApi.getBusinessOwnedOrganizationAsync,
    [ContactsApi.getBusinessOwnedOrganizationsAsync.key]: ContactsApi.getBusinessOwnedOrganizationsAsync,
    [ContactsApi.getBusinessOwnedOrganizationsCountAsync.key]: ContactsApi.getBusinessOwnedOrganizationsCountAsync,
    [ContactsApi.getContactAsync.key]: ContactsApi.getContactAsync,
    [ContactsApi.getContactAvatarAsync.key]: ContactsApi.getContactAvatarAsync,
    [ContactsApi.getContactCartAsync.key]: ContactsApi.getContactCartAsync,
    [ContactsApi.getContactEmailsAsync.key]: ContactsApi.getContactEmailsAsync,
    [ContactsApi.getContactEmailsCountAsync.key]: ContactsApi.getContactEmailsCountAsync,
    [ContactsApi.getContactSocialProfileAsync.key]: ContactsApi.getContactSocialProfileAsync,
    [ContactsApi.getContactWalletAsync.key]: ContactsApi.getContactWalletAsync,
    [ContactsApi.getContactsAsync.key]: ContactsApi.getContactsAsync,
    [ContactsApi.getContactsCountAsync.key]: ContactsApi.getContactsCountAsync,
    [ContactsApi.getExtendedBusinessOwnedIndividualsAsync.key]: ContactsApi.getExtendedBusinessOwnedIndividualsAsync,
    [ContactsApi.getExtendedBusinessOwnedOrganizationsAsync.key]: ContactsApi.getExtendedBusinessOwnedOrganizationsAsync,
    [ContactsApi.getExtendedContactAsync.key]: ContactsApi.getExtendedContactAsync,
    [ContactsApi.getExtendedContactsAsync.key]: ContactsApi.getExtendedContactsAsync,
    [ContactsApi.getIndividualRelatedIndividualsAsync.key]: ContactsApi.getIndividualRelatedIndividualsAsync,
    [ContactsApi.getIndividualRelatedOrganizationsAsync.key]: ContactsApi.getIndividualRelatedOrganizationsAsync,
    [ContactsApi.getOrganizationRelatedIndividualsAsync.key]: ContactsApi.getOrganizationRelatedIndividualsAsync,
    [ContactsApi.getOrganizationRelatedOrganizationsAsync.key]: ContactsApi.getOrganizationRelatedOrganizationsAsync,
    [ContactsApi.getProfilesForContactAsync.key]: ContactsApi.getProfilesForContactAsync,
    [ContactsApi.getProfilesForContactCountAsync.key]: ContactsApi.getProfilesForContactCountAsync,
    [ContactsApi.patchContactAsync.key]: ContactsApi.patchContactAsync,
    [ContactsApi.patchContactEmailAsync.key]: ContactsApi.patchContactEmailAsync,
    [ContactsApi.previewContactEmailTemplate.key]: ContactsApi.previewContactEmailTemplate,
    [ContactsApi.sendContactEmail.key]: ContactsApi.sendContactEmail,
    [ContactsApi.updateContactAsync.key]: ContactsApi.updateContactAsync,
    [ContactsApi.updateContactAvatarAsync.key]: ContactsApi.updateContactAvatarAsync,
    [ContactsApi.updateContactEmailAsync.key]: ContactsApi.updateContactEmailAsync,
    [ContactsApi.updateProfileForContactAsync.key]: ContactsApi.updateProfileForContactAsync,
    [ContactsApi.upsertTenantOntoAnotherTenantContactListAsync.key]: ContactsApi.upsertTenantOntoAnotherTenantContactListAsync,
    [ContactsApi.upsertUserOntoAnotherTenantContactListAsync.key]: ContactsApi.upsertUserOntoAnotherTenantContactListAsync,
    [ContactsApi.verifyContactEmailAsync.key]: ContactsApi.verifyContactEmailAsync,
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [OptionsApi.createContactOption.key]: OptionsApi.createContactOption,
    [OptionsApi.deleteContactOption.key]: OptionsApi.deleteContactOption,
    [OptionsApi.getContactOptionById.key]: OptionsApi.getContactOptionById,
    [OptionsApi.getContactOptionByKey.key]: OptionsApi.getContactOptionByKey,
    [OptionsApi.getContactOptions.key]: OptionsApi.getContactOptions,
    [OptionsApi.getContactOptionsCount.key]: OptionsApi.getContactOptionsCount,
    [OptionsApi.patchContactOptionAsync.key]: OptionsApi.patchContactOptionAsync,
    [OptionsApi.patchContactOptionByKeyAsync.key]: OptionsApi.patchContactOptionByKeyAsync,
    [OptionsApi.updateContactOption.key]: OptionsApi.updateContactOption,
    [OptionsApi.upsertContactOption.key]: OptionsApi.upsertContactOption,
    [SyncApi.syncCurrentHolderToCurrentTenantCrm.key]: SyncApi.syncCurrentHolderToCurrentTenantCrm,
    [SyncApi.syncCurrentHolderToTenantCrm.key]: SyncApi.syncCurrentHolderToTenantCrm,
    [SyncApi.syncHolderToTenantCrmAsync.key]: SyncApi.syncHolderToTenantCrmAsync,
    [SyncApi.syncTenantToTenantCrm.key]: SyncApi.syncTenantToTenantCrm,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
