const ContactsApi = require('../apis/ContactsApi');
const FenixAllianceABPWebApi = require('../apis/FenixAllianceABPWebApi');
const OptionsApi = require('../apis/OptionsApi');
const SyncApi = require('../apis/SyncApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [ContactsApi.createContactAsync.key]: ContactsApi.createContactAsync,
    [ContactsApi.deleteContactAsync.key]: ContactsApi.deleteContactAsync,
    [ContactsApi.getBusinessOwnedIndividualAsync.key]: ContactsApi.getBusinessOwnedIndividualAsync,
    [ContactsApi.getBusinessOwnedIndividualsAsync.key]: ContactsApi.getBusinessOwnedIndividualsAsync,
    [ContactsApi.getBusinessOwnedIndividualsCountAsync.key]: ContactsApi.getBusinessOwnedIndividualsCountAsync,
    [ContactsApi.getBusinessOwnedOrganizationAsync.key]: ContactsApi.getBusinessOwnedOrganizationAsync,
    [ContactsApi.getBusinessOwnedOrganizationsAsync.key]: ContactsApi.getBusinessOwnedOrganizationsAsync,
    [ContactsApi.getBusinessOwnedOrganizationsCountAsync.key]: ContactsApi.getBusinessOwnedOrganizationsCountAsync,
    [ContactsApi.getContactAsync.key]: ContactsApi.getContactAsync,
    [ContactsApi.getContactAvatarAsync.key]: ContactsApi.getContactAvatarAsync,
    [ContactsApi.getContactCartAsync.key]: ContactsApi.getContactCartAsync,
    [ContactsApi.getContactProfilesAsync.key]: ContactsApi.getContactProfilesAsync,
    [ContactsApi.getContactSocialProfileAsync.key]: ContactsApi.getContactSocialProfileAsync,
    [ContactsApi.getContactWalletAsync.key]: ContactsApi.getContactWalletAsync,
    [ContactsApi.getContactsAsync.key]: ContactsApi.getContactsAsync,
    [ContactsApi.getContactsCountAsync.key]: ContactsApi.getContactsCountAsync,
    [ContactsApi.getExtendedBusinessOwnedIndividualsAsync.key]: ContactsApi.getExtendedBusinessOwnedIndividualsAsync,
    [ContactsApi.getExtendedBusinessOwnedOrganizationsAsync.key]: ContactsApi.getExtendedBusinessOwnedOrganizationsAsync,
    [ContactsApi.getExtendedContactAsync.key]: ContactsApi.getExtendedContactAsync,
    [ContactsApi.getExtendedContactsAsync.key]: ContactsApi.getExtendedContactsAsync,
    [ContactsApi.getIndividualRelatedIndividualsAsync.key]: ContactsApi.getIndividualRelatedIndividualsAsync,
    [ContactsApi.getIndividualRelatedOrganizationsAsync.key]: ContactsApi.getIndividualRelatedOrganizationsAsync,
    [ContactsApi.getOrganizationRelatedIndividualsAsync.key]: ContactsApi.getOrganizationRelatedIndividualsAsync,
    [ContactsApi.getOrganizationRelatedOrganizationsAsync.key]: ContactsApi.getOrganizationRelatedOrganizationsAsync,
    [ContactsApi.patchContactAsync.key]: ContactsApi.patchContactAsync,
    [ContactsApi.previewContactEmailTemplate.key]: ContactsApi.previewContactEmailTemplate,
    [ContactsApi.sendContactEmail.key]: ContactsApi.sendContactEmail,
    [ContactsApi.updateContactAsync.key]: ContactsApi.updateContactAsync,
    [ContactsApi.updateContactAvatarAsync.key]: ContactsApi.updateContactAvatarAsync,
    [ContactsApi.upsertTenantOntoAnotherTenantContactListAsync.key]: ContactsApi.upsertTenantOntoAnotherTenantContactListAsync,
    [ContactsApi.upsertUserOntoAnotherTenantContactListAsync.key]: ContactsApi.upsertUserOntoAnotherTenantContactListAsync,
    [FenixAllianceABPWebApi.forgotPasswordPost.key]: FenixAllianceABPWebApi.forgotPasswordPost,
    [FenixAllianceABPWebApi.healthGet.key]: FenixAllianceABPWebApi.healthGet,
    [FenixAllianceABPWebApi.helloGet.key]: FenixAllianceABPWebApi.helloGet,
    [FenixAllianceABPWebApi.loginPost.key]: FenixAllianceABPWebApi.loginPost,
    [FenixAllianceABPWebApi.manage2faPost.key]: FenixAllianceABPWebApi.manage2faPost,
    [FenixAllianceABPWebApi.manageInfoGet.key]: FenixAllianceABPWebApi.manageInfoGet,
    [FenixAllianceABPWebApi.manageInfoPost.key]: FenixAllianceABPWebApi.manageInfoPost,
    [FenixAllianceABPWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABPWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABPWebApi.refreshPost.key]: FenixAllianceABPWebApi.refreshPost,
    [FenixAllianceABPWebApi.registerPost.key]: FenixAllianceABPWebApi.registerPost,
    [FenixAllianceABPWebApi.resendConfirmationEmailPost.key]: FenixAllianceABPWebApi.resendConfirmationEmailPost,
    [FenixAllianceABPWebApi.resetPasswordPost.key]: FenixAllianceABPWebApi.resetPasswordPost,
    [FenixAllianceABPWebApi.versionGet.key]: FenixAllianceABPWebApi.versionGet,
    [OptionsApi.createContactOption.key]: OptionsApi.createContactOption,
    [OptionsApi.deleteContactOption.key]: OptionsApi.deleteContactOption,
    [OptionsApi.getContactOptionById.key]: OptionsApi.getContactOptionById,
    [OptionsApi.getContactOptionByKey.key]: OptionsApi.getContactOptionByKey,
    [OptionsApi.getContactOptions.key]: OptionsApi.getContactOptions,
    [OptionsApi.getContactOptionsCount.key]: OptionsApi.getContactOptionsCount,
    [OptionsApi.updateContactOption.key]: OptionsApi.updateContactOption,
    [OptionsApi.upsertContactOption.key]: OptionsApi.upsertContactOption,
    [SyncApi.syncCurrentHolderToCurrentTenantCrm.key]: SyncApi.syncCurrentHolderToCurrentTenantCrm,
    [SyncApi.syncCurrentHolderToTenantCrm.key]: SyncApi.syncCurrentHolderToTenantCrm,
    [SyncApi.syncHolderToTenantCrmAsync.key]: SyncApi.syncHolderToTenantCrmAsync,
    [SyncApi.syncTenantToTenantCrm.key]: SyncApi.syncTenantToTenantCrm,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
