const AssetCategoriesApi = require('../apis/AssetCategoriesApi');
const AssetTransfersApi = require('../apis/AssetTransfersApi');
const AssetTypesApi = require('../apis/AssetTypesApi');
const AssetsApi = require('../apis/AssetsApi');
const CompletionsApi = require('../apis/CompletionsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [AssetCategoriesApi.createAssetCategory.key]: AssetCategoriesApi.createAssetCategory,
    [AssetCategoriesApi.deleteAssetCategory.key]: AssetCategoriesApi.deleteAssetCategory,
    [AssetCategoriesApi.getAssetCategories.key]: AssetCategoriesApi.getAssetCategories,
    [AssetCategoriesApi.getAssetCategoriesCount.key]: AssetCategoriesApi.getAssetCategoriesCount,
    [AssetCategoriesApi.getAssetCategory.key]: AssetCategoriesApi.getAssetCategory,
    [AssetCategoriesApi.patchAssetCategory.key]: AssetCategoriesApi.patchAssetCategory,
    [AssetCategoriesApi.updateAssetCategory.key]: AssetCategoriesApi.updateAssetCategory,
    [AssetTransfersApi.createAssetTransferAsync.key]: AssetTransfersApi.createAssetTransferAsync,
    [AssetTransfersApi.deleteAssetTransferAsync.key]: AssetTransfersApi.deleteAssetTransferAsync,
    [AssetTransfersApi.getAssetTransferAsync.key]: AssetTransfersApi.getAssetTransferAsync,
    [AssetTransfersApi.getAssetTransfersAsync.key]: AssetTransfersApi.getAssetTransfersAsync,
    [AssetTransfersApi.getAssetTransfersCountAsync.key]: AssetTransfersApi.getAssetTransfersCountAsync,
    [AssetTransfersApi.patchAssetTransferAsync.key]: AssetTransfersApi.patchAssetTransferAsync,
    [AssetTransfersApi.updateAssetTransferAsync.key]: AssetTransfersApi.updateAssetTransferAsync,
    [AssetTypesApi.createAssetType.key]: AssetTypesApi.createAssetType,
    [AssetTypesApi.deleteAssetType.key]: AssetTypesApi.deleteAssetType,
    [AssetTypesApi.getAssetType.key]: AssetTypesApi.getAssetType,
    [AssetTypesApi.getAssetTypes.key]: AssetTypesApi.getAssetTypes,
    [AssetTypesApi.getAssetTypesCount.key]: AssetTypesApi.getAssetTypesCount,
    [AssetTypesApi.patchAssetType.key]: AssetTypesApi.patchAssetType,
    [AssetTypesApi.updateAssetType.key]: AssetTypesApi.updateAssetType,
    [AssetsApi.createAsset.key]: AssetsApi.createAsset,
    [AssetsApi.createAssetAssetCategory.key]: AssetsApi.createAssetAssetCategory,
    [AssetsApi.createAssetDepreciationRecord.key]: AssetsApi.createAssetDepreciationRecord,
    [AssetsApi.createAssetRepair.key]: AssetsApi.createAssetRepair,
    [AssetsApi.createAssetTransfer.key]: AssetsApi.createAssetTransfer,
    [AssetsApi.createAssetValueAmend.key]: AssetsApi.createAssetValueAmend,
    [AssetsApi.deleteAsset.key]: AssetsApi.deleteAsset,
    [AssetsApi.deleteAssetAssetCategory.key]: AssetsApi.deleteAssetAssetCategory,
    [AssetsApi.deleteAssetDepreciationRecord.key]: AssetsApi.deleteAssetDepreciationRecord,
    [AssetsApi.deleteAssetRepair.key]: AssetsApi.deleteAssetRepair,
    [AssetsApi.deleteAssetTransfer.key]: AssetsApi.deleteAssetTransfer,
    [AssetsApi.deleteAssetValueAmend.key]: AssetsApi.deleteAssetValueAmend,
    [AssetsApi.getAsset.key]: AssetsApi.getAsset,
    [AssetsApi.getAssetAssetCategories.key]: AssetsApi.getAssetAssetCategories,
    [AssetsApi.getAssetAssetCategoriesCount.key]: AssetsApi.getAssetAssetCategoriesCount,
    [AssetsApi.getAssetAssetCategory.key]: AssetsApi.getAssetAssetCategory,
    [AssetsApi.getAssetDepreciationRecord.key]: AssetsApi.getAssetDepreciationRecord,
    [AssetsApi.getAssetDepreciationRecords.key]: AssetsApi.getAssetDepreciationRecords,
    [AssetsApi.getAssetDepreciationRecordsCount.key]: AssetsApi.getAssetDepreciationRecordsCount,
    [AssetsApi.getAssetRepair.key]: AssetsApi.getAssetRepair,
    [AssetsApi.getAssetRepairs.key]: AssetsApi.getAssetRepairs,
    [AssetsApi.getAssetRepairsCount.key]: AssetsApi.getAssetRepairsCount,
    [AssetsApi.getAssetTransfer.key]: AssetsApi.getAssetTransfer,
    [AssetsApi.getAssetTransfers.key]: AssetsApi.getAssetTransfers,
    [AssetsApi.getAssetTransfersCount.key]: AssetsApi.getAssetTransfersCount,
    [AssetsApi.getAssetValueAmend.key]: AssetsApi.getAssetValueAmend,
    [AssetsApi.getAssetValueAmends.key]: AssetsApi.getAssetValueAmends,
    [AssetsApi.getAssetValueAmendsCount.key]: AssetsApi.getAssetValueAmendsCount,
    [AssetsApi.getAssets.key]: AssetsApi.getAssets,
    [AssetsApi.getAssetsCount.key]: AssetsApi.getAssetsCount,
    [AssetsApi.patchAsset.key]: AssetsApi.patchAsset,
    [AssetsApi.patchAssetAssetCategory.key]: AssetsApi.patchAssetAssetCategory,
    [AssetsApi.patchAssetDepreciationRecord.key]: AssetsApi.patchAssetDepreciationRecord,
    [AssetsApi.patchAssetRepair.key]: AssetsApi.patchAssetRepair,
    [AssetsApi.patchAssetTransfer.key]: AssetsApi.patchAssetTransfer,
    [AssetsApi.patchAssetValueAmend.key]: AssetsApi.patchAssetValueAmend,
    [AssetsApi.updateAsset.key]: AssetsApi.updateAsset,
    [AssetsApi.updateAssetAssetCategory.key]: AssetsApi.updateAssetAssetCategory,
    [AssetsApi.updateAssetDepreciationRecord.key]: AssetsApi.updateAssetDepreciationRecord,
    [AssetsApi.updateAssetRepair.key]: AssetsApi.updateAssetRepair,
    [AssetsApi.updateAssetTransfer.key]: AssetsApi.updateAssetTransfer,
    [AssetsApi.updateAssetValueAmend.key]: AssetsApi.updateAssetValueAmend,
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
