const AssetCategoriesApi = require('../apis/AssetCategoriesApi');
const AssetTransfersApi = require('../apis/AssetTransfersApi');
const AssetTypesApi = require('../apis/AssetTypesApi');
const AssetsApi = require('../apis/AssetsApi');
const FenixAllianceABPWebApi = require('../apis/FenixAllianceABPWebApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [AssetCategoriesApi.createAssetCategory.key]: AssetCategoriesApi.createAssetCategory,
    [AssetCategoriesApi.deleteAssetCategory.key]: AssetCategoriesApi.deleteAssetCategory,
    [AssetCategoriesApi.getAssetCategories.key]: AssetCategoriesApi.getAssetCategories,
    [AssetCategoriesApi.getAssetCategoriesCount.key]: AssetCategoriesApi.getAssetCategoriesCount,
    [AssetCategoriesApi.getAssetCategory.key]: AssetCategoriesApi.getAssetCategory,
    [AssetCategoriesApi.updateAssetCategory.key]: AssetCategoriesApi.updateAssetCategory,
    [AssetTransfersApi.createAssetTransferAsync.key]: AssetTransfersApi.createAssetTransferAsync,
    [AssetTransfersApi.deleteAssetTransferAsync.key]: AssetTransfersApi.deleteAssetTransferAsync,
    [AssetTransfersApi.getAssetTransferAsync.key]: AssetTransfersApi.getAssetTransferAsync,
    [AssetTransfersApi.getAssetTransfersAsync.key]: AssetTransfersApi.getAssetTransfersAsync,
    [AssetTransfersApi.getAssetTransfersCountAsync.key]: AssetTransfersApi.getAssetTransfersCountAsync,
    [AssetTransfersApi.updateAssetTransferAsync.key]: AssetTransfersApi.updateAssetTransferAsync,
    [AssetTypesApi.createAssetType.key]: AssetTypesApi.createAssetType,
    [AssetTypesApi.deleteAssetType.key]: AssetTypesApi.deleteAssetType,
    [AssetTypesApi.getAssetType.key]: AssetTypesApi.getAssetType,
    [AssetTypesApi.getAssetTypes.key]: AssetTypesApi.getAssetTypes,
    [AssetTypesApi.getAssetTypesCount.key]: AssetTypesApi.getAssetTypesCount,
    [AssetTypesApi.updateAssetType.key]: AssetTypesApi.updateAssetType,
    [AssetsApi.createAsset.key]: AssetsApi.createAsset,
    [AssetsApi.createAssetAssetCategory.key]: AssetsApi.createAssetAssetCategory,
    [AssetsApi.createAssetDepreciationRecord.key]: AssetsApi.createAssetDepreciationRecord,
    [AssetsApi.createAssetRepair.key]: AssetsApi.createAssetRepair,
    [AssetsApi.createAssetTransfer.key]: AssetsApi.createAssetTransfer,
    [AssetsApi.createAssetValueAmend.key]: AssetsApi.createAssetValueAmend,
    [AssetsApi.deleteAsset.key]: AssetsApi.deleteAsset,
    [AssetsApi.deleteAssetAssetCategory.key]: AssetsApi.deleteAssetAssetCategory,
    [AssetsApi.deleteAssetDepreciationRecord.key]: AssetsApi.deleteAssetDepreciationRecord,
    [AssetsApi.deleteAssetRepair.key]: AssetsApi.deleteAssetRepair,
    [AssetsApi.deleteAssetTransfer.key]: AssetsApi.deleteAssetTransfer,
    [AssetsApi.deleteAssetValueAmend.key]: AssetsApi.deleteAssetValueAmend,
    [AssetsApi.getAsset.key]: AssetsApi.getAsset,
    [AssetsApi.getAssetAssetCategories.key]: AssetsApi.getAssetAssetCategories,
    [AssetsApi.getAssetAssetCategoriesCount.key]: AssetsApi.getAssetAssetCategoriesCount,
    [AssetsApi.getAssetAssetCategory.key]: AssetsApi.getAssetAssetCategory,
    [AssetsApi.getAssetDepreciationRecord.key]: AssetsApi.getAssetDepreciationRecord,
    [AssetsApi.getAssetDepreciationRecords.key]: AssetsApi.getAssetDepreciationRecords,
    [AssetsApi.getAssetDepreciationRecordsCount.key]: AssetsApi.getAssetDepreciationRecordsCount,
    [AssetsApi.getAssetRepair.key]: AssetsApi.getAssetRepair,
    [AssetsApi.getAssetRepairs.key]: AssetsApi.getAssetRepairs,
    [AssetsApi.getAssetRepairsCount.key]: AssetsApi.getAssetRepairsCount,
    [AssetsApi.getAssetTransfer.key]: AssetsApi.getAssetTransfer,
    [AssetsApi.getAssetTransfers.key]: AssetsApi.getAssetTransfers,
    [AssetsApi.getAssetTransfersCount.key]: AssetsApi.getAssetTransfersCount,
    [AssetsApi.getAssetValueAmend.key]: AssetsApi.getAssetValueAmend,
    [AssetsApi.getAssetValueAmends.key]: AssetsApi.getAssetValueAmends,
    [AssetsApi.getAssetValueAmendsCount.key]: AssetsApi.getAssetValueAmendsCount,
    [AssetsApi.getAssets.key]: AssetsApi.getAssets,
    [AssetsApi.getAssetsCount.key]: AssetsApi.getAssetsCount,
    [AssetsApi.updateAsset.key]: AssetsApi.updateAsset,
    [AssetsApi.updateAssetAssetCategory.key]: AssetsApi.updateAssetAssetCategory,
    [AssetsApi.updateAssetDepreciationRecord.key]: AssetsApi.updateAssetDepreciationRecord,
    [AssetsApi.updateAssetRepair.key]: AssetsApi.updateAssetRepair,
    [AssetsApi.updateAssetTransfer.key]: AssetsApi.updateAssetTransfer,
    [AssetsApi.updateAssetValueAmend.key]: AssetsApi.updateAssetValueAmend,
    [FenixAllianceABPWebApi.forgotPasswordPost.key]: FenixAllianceABPWebApi.forgotPasswordPost,
    [FenixAllianceABPWebApi.healthGet.key]: FenixAllianceABPWebApi.healthGet,
    [FenixAllianceABPWebApi.helloGet.key]: FenixAllianceABPWebApi.helloGet,
    [FenixAllianceABPWebApi.loginPost.key]: FenixAllianceABPWebApi.loginPost,
    [FenixAllianceABPWebApi.manage2faPost.key]: FenixAllianceABPWebApi.manage2faPost,
    [FenixAllianceABPWebApi.manageInfoGet.key]: FenixAllianceABPWebApi.manageInfoGet,
    [FenixAllianceABPWebApi.manageInfoPost.key]: FenixAllianceABPWebApi.manageInfoPost,
    [FenixAllianceABPWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABPWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABPWebApi.refreshPost.key]: FenixAllianceABPWebApi.refreshPost,
    [FenixAllianceABPWebApi.registerPost.key]: FenixAllianceABPWebApi.registerPost,
    [FenixAllianceABPWebApi.resendConfirmationEmailPost.key]: FenixAllianceABPWebApi.resendConfirmationEmailPost,
    [FenixAllianceABPWebApi.resetPasswordPost.key]: FenixAllianceABPWebApi.resetPasswordPost,
    [FenixAllianceABPWebApi.versionGet.key]: FenixAllianceABPWebApi.versionGet,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
