const BlogPostAuthorsApi = require('../apis/BlogPostAuthorsApi');
const BlogPostCategoriesApi = require('../apis/BlogPostCategoriesApi');
const BlogPostTagsApi = require('../apis/BlogPostTagsApi');
const BlogPostsApi = require('../apis/BlogPostsApi');
const BusinessDomainsApi = require('../apis/BusinessDomainsApi');
const CompletionsApi = require('../apis/CompletionsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const LocalizationStringsApi = require('../apis/LocalizationStringsApi');
const MenuContextsApi = require('../apis/MenuContextsApi');
const PortalsApi = require('../apis/PortalsApi');
const ThemesApi = require('../apis/ThemesApi');
const WebComponentsApi = require('../apis/WebComponentsApi');
const WebContentsApi = require('../apis/WebContentsApi');
const WebPageCategoriesApi = require('../apis/WebPageCategoriesApi');
const WebPageTagsApi = require('../apis/WebPageTagsApi');
const WebPagesApi = require('../apis/WebPagesApi');
const WebTemplatesApi = require('../apis/WebTemplatesApi');
const WebsiteThemesApi = require('../apis/WebsiteThemesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [BlogPostAuthorsApi.countBlogPostsByAuthorAsync.key]: BlogPostAuthorsApi.countBlogPostsByAuthorAsync,
    [BlogPostAuthorsApi.getBlogAuthorByIdAsync.key]: BlogPostAuthorsApi.getBlogAuthorByIdAsync,
    [BlogPostAuthorsApi.getBlogAuthorsAsync.key]: BlogPostAuthorsApi.getBlogAuthorsAsync,
    [BlogPostAuthorsApi.getBlogPostsByAuthorAsync.key]: BlogPostAuthorsApi.getBlogPostsByAuthorAsync,
    [BlogPostCategoriesApi.countBlogPostCategoriesAsync.key]: BlogPostCategoriesApi.countBlogPostCategoriesAsync,
    [BlogPostCategoriesApi.createBlogPostCategoryAsync.key]: BlogPostCategoriesApi.createBlogPostCategoryAsync,
    [BlogPostCategoriesApi.deleteBlogPostCategoryAsync.key]: BlogPostCategoriesApi.deleteBlogPostCategoryAsync,
    [BlogPostCategoriesApi.getBlogPostCategoriesAsync.key]: BlogPostCategoriesApi.getBlogPostCategoriesAsync,
    [BlogPostCategoriesApi.getBlogPostCategoryByIdAsync.key]: BlogPostCategoriesApi.getBlogPostCategoryByIdAsync,
    [BlogPostCategoriesApi.patchBlogPostCategoryAsync.key]: BlogPostCategoriesApi.patchBlogPostCategoryAsync,
    [BlogPostCategoriesApi.updateBlogPostCategoryAsync.key]: BlogPostCategoriesApi.updateBlogPostCategoryAsync,
    [BlogPostTagsApi.countBlogPostTagsAsync.key]: BlogPostTagsApi.countBlogPostTagsAsync,
    [BlogPostTagsApi.createBlogPostTagAsync.key]: BlogPostTagsApi.createBlogPostTagAsync,
    [BlogPostTagsApi.deleteBlogPostTagAsync.key]: BlogPostTagsApi.deleteBlogPostTagAsync,
    [BlogPostTagsApi.getBlogPostTagByIdAsync.key]: BlogPostTagsApi.getBlogPostTagByIdAsync,
    [BlogPostTagsApi.getBlogPostTagsAsync.key]: BlogPostTagsApi.getBlogPostTagsAsync,
    [BlogPostTagsApi.patchBlogPostTagAsync.key]: BlogPostTagsApi.patchBlogPostTagAsync,
    [BlogPostTagsApi.updateBlogPostTagAsync.key]: BlogPostTagsApi.updateBlogPostTagAsync,
    [BlogPostsApi.createBlogPostAsync.key]: BlogPostsApi.createBlogPostAsync,
    [BlogPostsApi.createCategoryForBlogPostAsync.key]: BlogPostsApi.createCategoryForBlogPostAsync,
    [BlogPostsApi.createCommentForBlogPostAsync.key]: BlogPostsApi.createCommentForBlogPostAsync,
    [BlogPostsApi.createTagForBlogPostAsync.key]: BlogPostsApi.createTagForBlogPostAsync,
    [BlogPostsApi.deleteBlogPostAsync.key]: BlogPostsApi.deleteBlogPostAsync,
    [BlogPostsApi.deleteCommentFromBlogPostAsync.key]: BlogPostsApi.deleteCommentFromBlogPostAsync,
    [BlogPostsApi.getBlogPostByIdAsync.key]: BlogPostsApi.getBlogPostByIdAsync,
    [BlogPostsApi.getBlogPostsAsync.key]: BlogPostsApi.getBlogPostsAsync,
    [BlogPostsApi.getBlogPostsCountAsync.key]: BlogPostsApi.getBlogPostsCountAsync,
    [BlogPostsApi.getCategoriesForBlogPostAsync.key]: BlogPostsApi.getCategoriesForBlogPostAsync,
    [BlogPostsApi.getCommentsForBlogPostAsync.key]: BlogPostsApi.getCommentsForBlogPostAsync,
    [BlogPostsApi.getRepliesForCommentAsync.key]: BlogPostsApi.getRepliesForCommentAsync,
    [BlogPostsApi.getTagsForBlogPostAsync.key]: BlogPostsApi.getTagsForBlogPostAsync,
    [BlogPostsApi.patchBlogPostAsync.key]: BlogPostsApi.patchBlogPostAsync,
    [BlogPostsApi.relateCategoryToBlogPostAsync.key]: BlogPostsApi.relateCategoryToBlogPostAsync,
    [BlogPostsApi.relateTagToBlogPostAsync.key]: BlogPostsApi.relateTagToBlogPostAsync,
    [BlogPostsApi.replyToCommentAsync.key]: BlogPostsApi.replyToCommentAsync,
    [BlogPostsApi.unrelateCategoryFromBlogPostAsync.key]: BlogPostsApi.unrelateCategoryFromBlogPostAsync,
    [BlogPostsApi.unrelateTagFromBlogPostAsync.key]: BlogPostsApi.unrelateTagFromBlogPostAsync,
    [BlogPostsApi.updateBlogPostAsync.key]: BlogPostsApi.updateBlogPostAsync,
    [BusinessDomainsApi.createBusinessDomainAsync.key]: BusinessDomainsApi.createBusinessDomainAsync,
    [BusinessDomainsApi.deleteBusinessDomainAsync.key]: BusinessDomainsApi.deleteBusinessDomainAsync,
    [BusinessDomainsApi.getBusinessDomainByIdAsync.key]: BusinessDomainsApi.getBusinessDomainByIdAsync,
    [BusinessDomainsApi.getBusinessDomainsAsync.key]: BusinessDomainsApi.getBusinessDomainsAsync,
    [BusinessDomainsApi.getBusinessDomainsCountAsync.key]: BusinessDomainsApi.getBusinessDomainsCountAsync,
    [BusinessDomainsApi.updateBusinessDomainAsync.key]: BusinessDomainsApi.updateBusinessDomainAsync,
    [BusinessDomainsApi.verifyBusinessDomainAsync.key]: BusinessDomainsApi.verifyBusinessDomainAsync,
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [LocalizationStringsApi.countLocalizationStringsAsync.key]: LocalizationStringsApi.countLocalizationStringsAsync,
    [LocalizationStringsApi.createLocalizationStringAsync.key]: LocalizationStringsApi.createLocalizationStringAsync,
    [LocalizationStringsApi.deleteLocalizationStringAsync.key]: LocalizationStringsApi.deleteLocalizationStringAsync,
    [LocalizationStringsApi.getLocalizationStringByIdAsync.key]: LocalizationStringsApi.getLocalizationStringByIdAsync,
    [LocalizationStringsApi.getLocalizationStringsAsync.key]: LocalizationStringsApi.getLocalizationStringsAsync,
    [LocalizationStringsApi.updateLocalizationStringAsync.key]: LocalizationStringsApi.updateLocalizationStringAsync,
    [MenuContextsApi.countMenuContextsAsync.key]: MenuContextsApi.countMenuContextsAsync,
    [MenuContextsApi.createMenuContextAsync.key]: MenuContextsApi.createMenuContextAsync,
    [MenuContextsApi.deleteMenuContextAsync.key]: MenuContextsApi.deleteMenuContextAsync,
    [MenuContextsApi.getMenuContextByIdAsync.key]: MenuContextsApi.getMenuContextByIdAsync,
    [MenuContextsApi.getMenuContextsAsync.key]: MenuContextsApi.getMenuContextsAsync,
    [MenuContextsApi.updateMenuContextAsync.key]: MenuContextsApi.updateMenuContextAsync,
    [PortalsApi.bindWebPortalDomainAsync.key]: PortalsApi.bindWebPortalDomainAsync,
    [PortalsApi.countPortalsAsync.key]: PortalsApi.countPortalsAsync,
    [PortalsApi.createWebPortalAsync.key]: PortalsApi.createWebPortalAsync,
    [PortalsApi.deleteWebPortalAsync.key]: PortalsApi.deleteWebPortalAsync,
    [PortalsApi.getCurrentWebPortalAsync.key]: PortalsApi.getCurrentWebPortalAsync,
    [PortalsApi.getCurrentWebPortalOptionsAsync.key]: PortalsApi.getCurrentWebPortalOptionsAsync,
    [PortalsApi.getPortalsAsync.key]: PortalsApi.getPortalsAsync,
    [PortalsApi.getRootWebPortalAsync.key]: PortalsApi.getRootWebPortalAsync,
    [PortalsApi.getWebPortalByIdAsync.key]: PortalsApi.getWebPortalByIdAsync,
    [PortalsApi.getWebPortalDomainBindingsAsync.key]: PortalsApi.getWebPortalDomainBindingsAsync,
    [PortalsApi.getWebPortalOptionsAsync.key]: PortalsApi.getWebPortalOptionsAsync,
    [PortalsApi.getWebPortalSettingsAsync.key]: PortalsApi.getWebPortalSettingsAsync,
    [PortalsApi.initializeCurrentWebPortalAsync.key]: PortalsApi.initializeCurrentWebPortalAsync,
    [PortalsApi.patchWebPortalAsync.key]: PortalsApi.patchWebPortalAsync,
    [PortalsApi.searchWebPortalAsync.key]: PortalsApi.searchWebPortalAsync,
    [PortalsApi.unbindWebPortalDomainAsync.key]: PortalsApi.unbindWebPortalDomainAsync,
    [PortalsApi.updateWebPortalAsync.key]: PortalsApi.updateWebPortalAsync,
    [PortalsApi.updateWebPortalSettingsAsync.key]: PortalsApi.updateWebPortalSettingsAsync,
    [ThemesApi.getLatestCurrencyRatesModelAsync.key]: ThemesApi.getLatestCurrencyRatesModelAsync,
    [WebComponentsApi.countWebComponentsAsync.key]: WebComponentsApi.countWebComponentsAsync,
    [WebComponentsApi.createWebComponentAsync.key]: WebComponentsApi.createWebComponentAsync,
    [WebComponentsApi.deleteWebComponentAsync.key]: WebComponentsApi.deleteWebComponentAsync,
    [WebComponentsApi.getWebComponentByIdAsync.key]: WebComponentsApi.getWebComponentByIdAsync,
    [WebComponentsApi.getWebComponentsAsync.key]: WebComponentsApi.getWebComponentsAsync,
    [WebComponentsApi.updateWebComponentAsync.key]: WebComponentsApi.updateWebComponentAsync,
    [WebContentsApi.countWebContentsAsync.key]: WebContentsApi.countWebContentsAsync,
    [WebContentsApi.createWebContentAsync.key]: WebContentsApi.createWebContentAsync,
    [WebContentsApi.deleteWebContentAsync.key]: WebContentsApi.deleteWebContentAsync,
    [WebContentsApi.getWebContentByIdAsync.key]: WebContentsApi.getWebContentByIdAsync,
    [WebContentsApi.getWebContentsAsync.key]: WebContentsApi.getWebContentsAsync,
    [WebContentsApi.patchWebContentAsync.key]: WebContentsApi.patchWebContentAsync,
    [WebContentsApi.updateWebContentAsync.key]: WebContentsApi.updateWebContentAsync,
    [WebPageCategoriesApi.countWebPageCategoriesAsync.key]: WebPageCategoriesApi.countWebPageCategoriesAsync,
    [WebPageCategoriesApi.createWebPageCategoryAsync.key]: WebPageCategoriesApi.createWebPageCategoryAsync,
    [WebPageCategoriesApi.deleteWebPageCategoryAsync.key]: WebPageCategoriesApi.deleteWebPageCategoryAsync,
    [WebPageCategoriesApi.getWebPageCategoriesAsync.key]: WebPageCategoriesApi.getWebPageCategoriesAsync,
    [WebPageCategoriesApi.getWebPageCategoryByIdAsync.key]: WebPageCategoriesApi.getWebPageCategoryByIdAsync,
    [WebPageCategoriesApi.patchWebPageCategoryAsync.key]: WebPageCategoriesApi.patchWebPageCategoryAsync,
    [WebPageCategoriesApi.updateWebPageCategoryAsync.key]: WebPageCategoriesApi.updateWebPageCategoryAsync,
    [WebPageTagsApi.countWebPageTagsAsync.key]: WebPageTagsApi.countWebPageTagsAsync,
    [WebPageTagsApi.createWebPageTagAsync.key]: WebPageTagsApi.createWebPageTagAsync,
    [WebPageTagsApi.deleteWebPageTagAsync.key]: WebPageTagsApi.deleteWebPageTagAsync,
    [WebPageTagsApi.getWebPageTagByIdAsync.key]: WebPageTagsApi.getWebPageTagByIdAsync,
    [WebPageTagsApi.getWebPageTagsAsync.key]: WebPageTagsApi.getWebPageTagsAsync,
    [WebPageTagsApi.patchWebPageTagAsync.key]: WebPageTagsApi.patchWebPageTagAsync,
    [WebPageTagsApi.updateWebPageTagAsync.key]: WebPageTagsApi.updateWebPageTagAsync,
    [WebPagesApi.countWebPagesAsync.key]: WebPagesApi.countWebPagesAsync,
    [WebPagesApi.createWebPageAsync.key]: WebPagesApi.createWebPageAsync,
    [WebPagesApi.createWebPageCategoryRelationAsync.key]: WebPagesApi.createWebPageCategoryRelationAsync,
    [WebPagesApi.createWebPageTagRelationAsync.key]: WebPagesApi.createWebPageTagRelationAsync,
    [WebPagesApi.deleteWebPageAsync.key]: WebPagesApi.deleteWebPageAsync,
    [WebPagesApi.getCategoriesByWebPageAsync.key]: WebPagesApi.getCategoriesByWebPageAsync,
    [WebPagesApi.getTagsByWebPageAsync.key]: WebPagesApi.getTagsByWebPageAsync,
    [WebPagesApi.getWebPageByIdAsync.key]: WebPagesApi.getWebPageByIdAsync,
    [WebPagesApi.getWebPagesAsync.key]: WebPagesApi.getWebPagesAsync,
    [WebPagesApi.patchWebPageAsync.key]: WebPagesApi.patchWebPageAsync,
    [WebPagesApi.relateWebPageToCategoryAsync.key]: WebPagesApi.relateWebPageToCategoryAsync,
    [WebPagesApi.relateWebPageToTagAsync.key]: WebPagesApi.relateWebPageToTagAsync,
    [WebPagesApi.unrelateWebPageCategoryAsync.key]: WebPagesApi.unrelateWebPageCategoryAsync,
    [WebPagesApi.unrelateWebPageTagAsync.key]: WebPagesApi.unrelateWebPageTagAsync,
    [WebPagesApi.updateWebPageAsync.key]: WebPagesApi.updateWebPageAsync,
    [WebTemplatesApi.countWebTemplatesAsync.key]: WebTemplatesApi.countWebTemplatesAsync,
    [WebTemplatesApi.createWebTemplateAsync.key]: WebTemplatesApi.createWebTemplateAsync,
    [WebTemplatesApi.deleteWebTemplateAsync.key]: WebTemplatesApi.deleteWebTemplateAsync,
    [WebTemplatesApi.getWebTemplateByIdAsync.key]: WebTemplatesApi.getWebTemplateByIdAsync,
    [WebTemplatesApi.getWebTemplatesAsync.key]: WebTemplatesApi.getWebTemplatesAsync,
    [WebTemplatesApi.patchWebTemplateAsync.key]: WebTemplatesApi.patchWebTemplateAsync,
    [WebTemplatesApi.updateWebTemplateAsync.key]: WebTemplatesApi.updateWebTemplateAsync,
    [WebsiteThemesApi.createWebsiteThemeAsync.key]: WebsiteThemesApi.createWebsiteThemeAsync,
    [WebsiteThemesApi.deleteWebsiteThemeAsync.key]: WebsiteThemesApi.deleteWebsiteThemeAsync,
    [WebsiteThemesApi.getWebsiteThemeByIdAsync.key]: WebsiteThemesApi.getWebsiteThemeByIdAsync,
    [WebsiteThemesApi.getWebsiteThemesAsync.key]: WebsiteThemesApi.getWebsiteThemesAsync,
    [WebsiteThemesApi.getWebsiteThemesCountAsync.key]: WebsiteThemesApi.getWebsiteThemesCountAsync,
    [WebsiteThemesApi.patchWebsiteThemeAsync.key]: WebsiteThemesApi.patchWebsiteThemeAsync,
    [WebsiteThemesApi.updateWebsiteThemeAsync.key]: WebsiteThemesApi.updateWebsiteThemeAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
