const BlogPostAuthorsApi = require('../apis/BlogPostAuthorsApi');
const BlogPostCategoriesApi = require('../apis/BlogPostCategoriesApi');
const BlogPostTagsApi = require('../apis/BlogPostTagsApi');
const BlogPostsApi = require('../apis/BlogPostsApi');
const BusinessDomainsApi = require('../apis/BusinessDomainsApi');
const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const PortalsApi = require('../apis/PortalsApi');
const ThemesApi = require('../apis/ThemesApi');
const WebContentsApi = require('../apis/WebContentsApi');
const WebPageCategoriesApi = require('../apis/WebPageCategoriesApi');
const WebPageTagsApi = require('../apis/WebPageTagsApi');
const WebPagesApi = require('../apis/WebPagesApi');
const WebTemplatesApi = require('../apis/WebTemplatesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [BlogPostAuthorsApi.countBlogPostsByAuthorAsync.key]: BlogPostAuthorsApi.countBlogPostsByAuthorAsync,
    [BlogPostAuthorsApi.getBlogAuthorByIdAsync.key]: BlogPostAuthorsApi.getBlogAuthorByIdAsync,
    [BlogPostAuthorsApi.getBlogAuthorsAsync.key]: BlogPostAuthorsApi.getBlogAuthorsAsync,
    [BlogPostAuthorsApi.getBlogPostsByAuthorAsync.key]: BlogPostAuthorsApi.getBlogPostsByAuthorAsync,
    [BlogPostCategoriesApi.countBlogPostCategoriesAsync.key]: BlogPostCategoriesApi.countBlogPostCategoriesAsync,
    [BlogPostCategoriesApi.createBlogPostCategoryAsync.key]: BlogPostCategoriesApi.createBlogPostCategoryAsync,
    [BlogPostCategoriesApi.deleteBlogPostCategoryAsync.key]: BlogPostCategoriesApi.deleteBlogPostCategoryAsync,
    [BlogPostCategoriesApi.getBlogPostCategoriesAsync.key]: BlogPostCategoriesApi.getBlogPostCategoriesAsync,
    [BlogPostCategoriesApi.getBlogPostCategoryByIdAsync.key]: BlogPostCategoriesApi.getBlogPostCategoryByIdAsync,
    [BlogPostCategoriesApi.updateBlogPostCategoryAsync.key]: BlogPostCategoriesApi.updateBlogPostCategoryAsync,
    [BlogPostTagsApi.countBlogPostTagsAsync.key]: BlogPostTagsApi.countBlogPostTagsAsync,
    [BlogPostTagsApi.createBlogPostTagAsync.key]: BlogPostTagsApi.createBlogPostTagAsync,
    [BlogPostTagsApi.deleteBlogPostTagAsync.key]: BlogPostTagsApi.deleteBlogPostTagAsync,
    [BlogPostTagsApi.getBlogPostTagByIdAsync.key]: BlogPostTagsApi.getBlogPostTagByIdAsync,
    [BlogPostTagsApi.getBlogPostTagsAsync.key]: BlogPostTagsApi.getBlogPostTagsAsync,
    [BlogPostTagsApi.updateBlogPostTagAsync.key]: BlogPostTagsApi.updateBlogPostTagAsync,
    [BlogPostsApi.createBlogPostAsync.key]: BlogPostsApi.createBlogPostAsync,
    [BlogPostsApi.createCategoryForBlogPostAsync.key]: BlogPostsApi.createCategoryForBlogPostAsync,
    [BlogPostsApi.createCommentForBlogPostAsync.key]: BlogPostsApi.createCommentForBlogPostAsync,
    [BlogPostsApi.createTagForBlogPostAsync.key]: BlogPostsApi.createTagForBlogPostAsync,
    [BlogPostsApi.deleteBlogPostAsync.key]: BlogPostsApi.deleteBlogPostAsync,
    [BlogPostsApi.deleteCommentFromBlogPostAsync.key]: BlogPostsApi.deleteCommentFromBlogPostAsync,
    [BlogPostsApi.getBlogPostByIdAsync.key]: BlogPostsApi.getBlogPostByIdAsync,
    [BlogPostsApi.getBlogPostsAsync.key]: BlogPostsApi.getBlogPostsAsync,
    [BlogPostsApi.getBlogPostsCountAsync.key]: BlogPostsApi.getBlogPostsCountAsync,
    [BlogPostsApi.getCategoriesForBlogPostAsync.key]: BlogPostsApi.getCategoriesForBlogPostAsync,
    [BlogPostsApi.getCommentsForBlogPostAsync.key]: BlogPostsApi.getCommentsForBlogPostAsync,
    [BlogPostsApi.getRepliesForCommentAsync.key]: BlogPostsApi.getRepliesForCommentAsync,
    [BlogPostsApi.getTagsForBlogPostAsync.key]: BlogPostsApi.getTagsForBlogPostAsync,
    [BlogPostsApi.relateCategoryToBlogPostAsync.key]: BlogPostsApi.relateCategoryToBlogPostAsync,
    [BlogPostsApi.relateTagToBlogPostAsync.key]: BlogPostsApi.relateTagToBlogPostAsync,
    [BlogPostsApi.replyToCommentAsync.key]: BlogPostsApi.replyToCommentAsync,
    [BlogPostsApi.unrelateCategoryFromBlogPostAsync.key]: BlogPostsApi.unrelateCategoryFromBlogPostAsync,
    [BlogPostsApi.unrelateTagFromBlogPostAsync.key]: BlogPostsApi.unrelateTagFromBlogPostAsync,
    [BlogPostsApi.updateBlogPostAsync.key]: BlogPostsApi.updateBlogPostAsync,
    [BusinessDomainsApi.getBusinessDomainByIdAsync.key]: BusinessDomainsApi.getBusinessDomainByIdAsync,
    [BusinessDomainsApi.getBusinessDomainsAsync.key]: BusinessDomainsApi.getBusinessDomainsAsync,
    [BusinessDomainsApi.getBusinessDomainsCountAsync.key]: BusinessDomainsApi.getBusinessDomainsCountAsync,
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [PortalsApi.countPortalsAsync.key]: PortalsApi.countPortalsAsync,
    [PortalsApi.createWebPortalAsync.key]: PortalsApi.createWebPortalAsync,
    [PortalsApi.deleteWebPortalAsync.key]: PortalsApi.deleteWebPortalAsync,
    [PortalsApi.getCurrentWebPortalAsync.key]: PortalsApi.getCurrentWebPortalAsync,
    [PortalsApi.getCurrentWebPortalOptionsAsync.key]: PortalsApi.getCurrentWebPortalOptionsAsync,
    [PortalsApi.getPortalsAsync.key]: PortalsApi.getPortalsAsync,
    [PortalsApi.getRootWebPortalAsync.key]: PortalsApi.getRootWebPortalAsync,
    [PortalsApi.getWebPortalByIdAsync.key]: PortalsApi.getWebPortalByIdAsync,
    [PortalsApi.getWebPortalOptionsAsync.key]: PortalsApi.getWebPortalOptionsAsync,
    [PortalsApi.getWebPortalSettingsAsync.key]: PortalsApi.getWebPortalSettingsAsync,
    [PortalsApi.initializeCurrentWebPortalAsync.key]: PortalsApi.initializeCurrentWebPortalAsync,
    [PortalsApi.patchWebPortalAsync.key]: PortalsApi.patchWebPortalAsync,
    [PortalsApi.searchWebPortalAsync.key]: PortalsApi.searchWebPortalAsync,
    [PortalsApi.updateWebPortalAsync.key]: PortalsApi.updateWebPortalAsync,
    [ThemesApi.getLatestCurrencyRatesModelAsync.key]: ThemesApi.getLatestCurrencyRatesModelAsync,
    [WebContentsApi.countWebContentsAsync.key]: WebContentsApi.countWebContentsAsync,
    [WebContentsApi.createWebContentAsync.key]: WebContentsApi.createWebContentAsync,
    [WebContentsApi.deleteWebContentAsync.key]: WebContentsApi.deleteWebContentAsync,
    [WebContentsApi.getWebContentByIdAsync.key]: WebContentsApi.getWebContentByIdAsync,
    [WebContentsApi.getWebContentsAsync.key]: WebContentsApi.getWebContentsAsync,
    [WebContentsApi.updateWebContentAsync.key]: WebContentsApi.updateWebContentAsync,
    [WebPageCategoriesApi.countWebPageCategoriesAsync.key]: WebPageCategoriesApi.countWebPageCategoriesAsync,
    [WebPageCategoriesApi.createWebPageCategoryAsync.key]: WebPageCategoriesApi.createWebPageCategoryAsync,
    [WebPageCategoriesApi.deleteWebPageCategoryAsync.key]: WebPageCategoriesApi.deleteWebPageCategoryAsync,
    [WebPageCategoriesApi.getWebPageCategoriesAsync.key]: WebPageCategoriesApi.getWebPageCategoriesAsync,
    [WebPageCategoriesApi.getWebPageCategoryByIdAsync.key]: WebPageCategoriesApi.getWebPageCategoryByIdAsync,
    [WebPageCategoriesApi.updateWebPageCategoryAsync.key]: WebPageCategoriesApi.updateWebPageCategoryAsync,
    [WebPageTagsApi.countWebPageTagsAsync.key]: WebPageTagsApi.countWebPageTagsAsync,
    [WebPageTagsApi.createWebPageTagAsync.key]: WebPageTagsApi.createWebPageTagAsync,
    [WebPageTagsApi.deleteWebPageTagAsync.key]: WebPageTagsApi.deleteWebPageTagAsync,
    [WebPageTagsApi.getWebPageTagByIdAsync.key]: WebPageTagsApi.getWebPageTagByIdAsync,
    [WebPageTagsApi.getWebPageTagsAsync.key]: WebPageTagsApi.getWebPageTagsAsync,
    [WebPageTagsApi.updateWebPageTagAsync.key]: WebPageTagsApi.updateWebPageTagAsync,
    [WebPagesApi.countWebPagesAsync.key]: WebPagesApi.countWebPagesAsync,
    [WebPagesApi.createWebPageAsync.key]: WebPagesApi.createWebPageAsync,
    [WebPagesApi.createWebPageCategoryRelationAsync.key]: WebPagesApi.createWebPageCategoryRelationAsync,
    [WebPagesApi.createWebPageTagRelationAsync.key]: WebPagesApi.createWebPageTagRelationAsync,
    [WebPagesApi.deleteWebPageAsync.key]: WebPagesApi.deleteWebPageAsync,
    [WebPagesApi.getCategoriesByWebPageAsync.key]: WebPagesApi.getCategoriesByWebPageAsync,
    [WebPagesApi.getTagsByWebPageAsync.key]: WebPagesApi.getTagsByWebPageAsync,
    [WebPagesApi.getWebPageByIdAsync.key]: WebPagesApi.getWebPageByIdAsync,
    [WebPagesApi.getWebPagesAsync.key]: WebPagesApi.getWebPagesAsync,
    [WebPagesApi.relateWebPageToCategoryAsync.key]: WebPagesApi.relateWebPageToCategoryAsync,
    [WebPagesApi.relateWebPageToTagAsync.key]: WebPagesApi.relateWebPageToTagAsync,
    [WebPagesApi.unrelateWebPageCategoryAsync.key]: WebPagesApi.unrelateWebPageCategoryAsync,
    [WebPagesApi.unrelateWebPageTagAsync.key]: WebPagesApi.unrelateWebPageTagAsync,
    [WebPagesApi.updateWebPageAsync.key]: WebPagesApi.updateWebPageAsync,
    [WebTemplatesApi.countWebTemplatesAsync.key]: WebTemplatesApi.countWebTemplatesAsync,
    [WebTemplatesApi.createWebTemplateAsync.key]: WebTemplatesApi.createWebTemplateAsync,
    [WebTemplatesApi.deleteWebTemplateAsync.key]: WebTemplatesApi.deleteWebTemplateAsync,
    [WebTemplatesApi.getWebTemplateByIdAsync.key]: WebTemplatesApi.getWebTemplateByIdAsync,
    [WebTemplatesApi.getWebTemplatesAsync.key]: WebTemplatesApi.getWebTemplatesAsync,
    [WebTemplatesApi.updateWebTemplateAsync.key]: WebTemplatesApi.updateWebTemplateAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
