const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}closed`,
                label: `[${labelPrefix}closed]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}userId`,
                label: `[${labelPrefix}userId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tenantId`,
                label: `[${labelPrefix}tenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}priceListId`,
                label: `[${labelPrefix}priceListId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enrollmentId`,
                label: `[${labelPrefix}enrollmentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}individualId`,
                label: `[${labelPrefix}individualId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}paymentTermId`,
                label: `[${labelPrefix}paymentTermId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}organizationId`,
                label: `[${labelPrefix}organizationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}receiverTenantId`,
                label: `[${labelPrefix}receiverTenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}firstName`,
                label: `[${labelPrefix}firstName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lastName`,
                label: `[${labelPrefix}lastName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}companyName`,
                label: `[${labelPrefix}companyName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingEmail`,
                label: `[${labelPrefix}billingEmail]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine1`,
                label: `[${labelPrefix}addressLine1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine2`,
                label: `[${labelPrefix}addressLine2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}postalCode`,
                label: `[${labelPrefix}postalCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryId`,
                label: `[${labelPrefix}countryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}stateId`,
                label: `[${labelPrefix}stateId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cityId`,
                label: `[${labelPrefix}cityId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingLocationId`,
                label: `[${labelPrefix}billingLocationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingLocationId`,
                label: `[${labelPrefix}shippingLocationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingMethodId`,
                label: `[${labelPrefix}shippingMethodId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}forexRate`,
                label: `[${labelPrefix}forexRate]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}currencyId`,
                label: `[${labelPrefix}currencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDetail`,
                label: `[${labelPrefix}totalDetail]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDetailCurrencyId`,
                label: `[${labelPrefix}totalDetailCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalProfit`,
                label: `[${labelPrefix}totalProfit]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalProfitCurrencyId`,
                label: `[${labelPrefix}totalProfitCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDiscounts`,
                label: `[${labelPrefix}totalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalSurcharges`,
                label: `[${labelPrefix}totalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingTax`,
                label: `[${labelPrefix}totalShippingTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingTaxCurrencyId`,
                label: `[${labelPrefix}totalShippingTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingCost`,
                label: `[${labelPrefix}totalShippingCost]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingCostCurrencyId`,
                label: `[${labelPrefix}totalShippingCostCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalDiscounts`,
                label: `[${labelPrefix}totalGlobalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalGlobalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalSurcharges`,
                label: `[${labelPrefix}totalGlobalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalGlobalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalWithheldTax`,
                label: `[${labelPrefix}totalWithheldTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalWithheldTaxCurrencyId`,
                label: `[${labelPrefix}totalWithheldTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxBase`,
                label: `[${labelPrefix}totalTaxBase]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxBaseCurrencyId`,
                label: `[${labelPrefix}totalTaxBaseCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxes`,
                label: `[${labelPrefix}totalTaxes]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxesCurrencyId`,
                label: `[${labelPrefix}totalTaxesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}total`,
                label: `[${labelPrefix}total]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalCurrencyId`,
                label: `[${labelPrefix}totalCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}costCalculationMethod`,
                label: `[${labelPrefix}costCalculationMethod]`,
                type: 'string',
                choices: [
                    'Automatic',
                    'Custom',
                ],
            },
            {
                key: `${keyPrefix}taxCalculationMethod`,
                label: `[${labelPrefix}taxCalculationMethod]`,
                type: 'string',
                choices: [
                    'Included',
                    'Excluded',
                ],
            },
            {
                key: `${keyPrefix}ordered`,
                label: `[${labelPrefix}ordered]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}cartId`,
                label: `[${labelPrefix}cartId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dealUnitFeedId`,
                label: `[${labelPrefix}dealUnitFeedId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dealUnitFlowId`,
                label: `[${labelPrefix}dealUnitFlowId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dealUnitFlowStageId`,
                label: `[${labelPrefix}dealUnitFlowStageId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}partnerCreated`,
                label: `[${labelPrefix}partnerCreated]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}partnerCollaboration`,
                label: `[${labelPrefix}partnerCollaboration]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}proposedSolution`,
                label: `[${labelPrefix}proposedSolution]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}currentSituation`,
                label: `[${labelPrefix}currentSituation]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}customerNeed`,
                label: `[${labelPrefix}customerNeed]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}wonDate`,
                label: `[${labelPrefix}wonDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lostDate`,
                label: `[${labelPrefix}lostDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}expiryDate`,
                label: `[${labelPrefix}expiryDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}deliveredDate`,
                label: `[${labelPrefix}deliveredDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}closedTimestamp`,
                label: `[${labelPrefix}closedTimestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}expectedCloseDate`,
                label: `[${labelPrefix}expectedCloseDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dealUnitStatus`,
                label: `[${labelPrefix}dealUnitStatus]`,
                type: 'string',
                choices: [
                    'Open',
                    'Won',
                    'Lost',
                    'Frozen',
                ],
            },
            {
                key: `${keyPrefix}dealUnitPurchaseProcess`,
                label: `[${labelPrefix}dealUnitPurchaseProcess]`,
                type: 'string',
                choices: [
                    'None',
                    'Individual',
                    'Commitee',
                    'Unknown',
                ],
            },
            {
                key: `${keyPrefix}dealUnitForecastCategory`,
                label: `[${labelPrefix}dealUnitForecastCategory]`,
                type: 'string',
                choices: [
                    'None',
                    'Pipeline',
                    'BestCase',
                    'Commited',
                    'Ommited',
                    'Won',
                    'Lost',
                ],
            },
            {
                key: `${keyPrefix}dealUnitAmountsCalculation`,
                label: `[${labelPrefix}dealUnitAmountsCalculation]`,
                type: 'string',
                choices: [
                    'UserProvided',
                    'SystemCalculated',
                ],
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'closed': bundle.inputData?.[`${keyPrefix}closed`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'userId': bundle.inputData?.[`${keyPrefix}userId`],
            'tenantId': bundle.inputData?.[`${keyPrefix}tenantId`],
            'priceListId': bundle.inputData?.[`${keyPrefix}priceListId`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'enrollmentId': bundle.inputData?.[`${keyPrefix}enrollmentId`],
            'individualId': bundle.inputData?.[`${keyPrefix}individualId`],
            'paymentTermId': bundle.inputData?.[`${keyPrefix}paymentTermId`],
            'organizationId': bundle.inputData?.[`${keyPrefix}organizationId`],
            'receiverTenantId': bundle.inputData?.[`${keyPrefix}receiverTenantId`],
            'firstName': bundle.inputData?.[`${keyPrefix}firstName`],
            'lastName': bundle.inputData?.[`${keyPrefix}lastName`],
            'companyName': bundle.inputData?.[`${keyPrefix}companyName`],
            'billingEmail': bundle.inputData?.[`${keyPrefix}billingEmail`],
            'addressLine1': bundle.inputData?.[`${keyPrefix}addressLine1`],
            'addressLine2': bundle.inputData?.[`${keyPrefix}addressLine2`],
            'postalCode': bundle.inputData?.[`${keyPrefix}postalCode`],
            'countryId': bundle.inputData?.[`${keyPrefix}countryId`],
            'stateId': bundle.inputData?.[`${keyPrefix}stateId`],
            'cityId': bundle.inputData?.[`${keyPrefix}cityId`],
            'billingLocationId': bundle.inputData?.[`${keyPrefix}billingLocationId`],
            'shippingLocationId': bundle.inputData?.[`${keyPrefix}shippingLocationId`],
            'shippingMethodId': bundle.inputData?.[`${keyPrefix}shippingMethodId`],
            'forexRate': bundle.inputData?.[`${keyPrefix}forexRate`],
            'currencyId': bundle.inputData?.[`${keyPrefix}currencyId`],
            'totalDetail': bundle.inputData?.[`${keyPrefix}totalDetail`],
            'totalDetailCurrencyId': bundle.inputData?.[`${keyPrefix}totalDetailCurrencyId`],
            'totalProfit': bundle.inputData?.[`${keyPrefix}totalProfit`],
            'totalProfitCurrencyId': bundle.inputData?.[`${keyPrefix}totalProfitCurrencyId`],
            'totalDiscounts': bundle.inputData?.[`${keyPrefix}totalDiscounts`],
            'totalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalDiscountsCurrencyId`],
            'totalSurcharges': bundle.inputData?.[`${keyPrefix}totalSurcharges`],
            'totalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalSurchargesCurrencyId`],
            'totalShippingTax': bundle.inputData?.[`${keyPrefix}totalShippingTax`],
            'totalShippingTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingTaxCurrencyId`],
            'totalShippingCost': bundle.inputData?.[`${keyPrefix}totalShippingCost`],
            'totalShippingCostCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingCostCurrencyId`],
            'totalGlobalDiscounts': bundle.inputData?.[`${keyPrefix}totalGlobalDiscounts`],
            'totalGlobalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalDiscountsCurrencyId`],
            'totalGlobalSurcharges': bundle.inputData?.[`${keyPrefix}totalGlobalSurcharges`],
            'totalGlobalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalSurchargesCurrencyId`],
            'totalWithheldTax': bundle.inputData?.[`${keyPrefix}totalWithheldTax`],
            'totalWithheldTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalWithheldTaxCurrencyId`],
            'totalTaxBase': bundle.inputData?.[`${keyPrefix}totalTaxBase`],
            'totalTaxBaseCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxBaseCurrencyId`],
            'totalTaxes': bundle.inputData?.[`${keyPrefix}totalTaxes`],
            'totalTaxesCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxesCurrencyId`],
            'total': bundle.inputData?.[`${keyPrefix}total`],
            'totalCurrencyId': bundle.inputData?.[`${keyPrefix}totalCurrencyId`],
            'costCalculationMethod': bundle.inputData?.[`${keyPrefix}costCalculationMethod`],
            'taxCalculationMethod': bundle.inputData?.[`${keyPrefix}taxCalculationMethod`],
            'ordered': bundle.inputData?.[`${keyPrefix}ordered`],
            'cartId': bundle.inputData?.[`${keyPrefix}cartId`],
            'dealUnitFeedId': bundle.inputData?.[`${keyPrefix}dealUnitFeedId`],
            'dealUnitFlowId': bundle.inputData?.[`${keyPrefix}dealUnitFlowId`],
            'dealUnitFlowStageId': bundle.inputData?.[`${keyPrefix}dealUnitFlowStageId`],
            'partnerCreated': bundle.inputData?.[`${keyPrefix}partnerCreated`],
            'partnerCollaboration': bundle.inputData?.[`${keyPrefix}partnerCollaboration`],
            'proposedSolution': bundle.inputData?.[`${keyPrefix}proposedSolution`],
            'currentSituation': bundle.inputData?.[`${keyPrefix}currentSituation`],
            'customerNeed': bundle.inputData?.[`${keyPrefix}customerNeed`],
            'wonDate': bundle.inputData?.[`${keyPrefix}wonDate`],
            'lostDate': bundle.inputData?.[`${keyPrefix}lostDate`],
            'expiryDate': bundle.inputData?.[`${keyPrefix}expiryDate`],
            'deliveredDate': bundle.inputData?.[`${keyPrefix}deliveredDate`],
            'closedTimestamp': bundle.inputData?.[`${keyPrefix}closedTimestamp`],
            'expectedCloseDate': bundle.inputData?.[`${keyPrefix}expectedCloseDate`],
            'dealUnitStatus': bundle.inputData?.[`${keyPrefix}dealUnitStatus`],
            'dealUnitPurchaseProcess': bundle.inputData?.[`${keyPrefix}dealUnitPurchaseProcess`],
            'dealUnitForecastCategory': bundle.inputData?.[`${keyPrefix}dealUnitForecastCategory`],
            'dealUnitAmountsCalculation': bundle.inputData?.[`${keyPrefix}dealUnitAmountsCalculation`],
        }
    },
}
