const CartsApi = require('../apis/CartsApi');
const CompareApi = require('../apis/CompareApi');
const CompletionsApi = require('../apis/CompletionsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const RecordsApi = require('../apis/RecordsApi');
const WishListsApi = require('../apis/WishListsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CartsApi.addItemToCartAsync.key]: CartsApi.addItemToCartAsync,
    [CartsApi.addItemToCartCompareTable.key]: CartsApi.addItemToCartCompareTable,
    [CartsApi.addItemToWishList.key]: CartsApi.addItemToWishList,
    [CartsApi.cartWishListExistsHead.key]: CartsApi.cartWishListExistsHead,
    [CartsApi.clearCartRecords.key]: CartsApi.clearCartRecords,
    [CartsApi.createWishListAsync.key]: CartsApi.createWishListAsync,
    [CartsApi.decreaseCartItemQuantity.key]: CartsApi.decreaseCartItemQuantity,
    [CartsApi.decreaseCartLineAsync.key]: CartsApi.decreaseCartLineAsync,
    [CartsApi.deleteCartWishList.key]: CartsApi.deleteCartWishList,
    [CartsApi.deleteCartWishListRecord.key]: CartsApi.deleteCartWishListRecord,
    [CartsApi.getActingCart.key]: CartsApi.getActingCart,
    [CartsApi.getCartByIdAsync.key]: CartsApi.getCartByIdAsync,
    [CartsApi.getCartCompareRecord.key]: CartsApi.getCartCompareRecord,
    [CartsApi.getCartCompareRecords.key]: CartsApi.getCartCompareRecords,
    [CartsApi.getCartCountryAsync.key]: CartsApi.getCartCountryAsync,
    [CartsApi.getCartCurrencyAsync.key]: CartsApi.getCartCurrencyAsync,
    [CartsApi.getCartItems.key]: CartsApi.getCartItems,
    [CartsApi.getCartLineAsync.key]: CartsApi.getCartLineAsync,
    [CartsApi.getCartLinesAsync.key]: CartsApi.getCartLinesAsync,
    [CartsApi.getCartWishList.key]: CartsApi.getCartWishList,
    [CartsApi.getCartWishListDetails.key]: CartsApi.getCartWishListDetails,
    [CartsApi.getCartWishListItemAsync.key]: CartsApi.getCartWishListItemAsync,
    [CartsApi.getCartWishListItems.key]: CartsApi.getCartWishListItems,
    [CartsApi.getGuestCartAsync.key]: CartsApi.getGuestCartAsync,
    [CartsApi.getTenantCartAsync.key]: CartsApi.getTenantCartAsync,
    [CartsApi.getUserCart.key]: CartsApi.getUserCart,
    [CartsApi.increaseCartLineAsync.key]: CartsApi.increaseCartLineAsync,
    [CartsApi.increaseItemCartRecordQuantityAsync.key]: CartsApi.increaseItemCartRecordQuantityAsync,
    [CartsApi.isItemAlreadyInCartAsync.key]: CartsApi.isItemAlreadyInCartAsync,
    [CartsApi.isItemInCompareTableAsync.key]: CartsApi.isItemInCompareTableAsync,
    [CartsApi.isItemInWishLists.key]: CartsApi.isItemInWishLists,
    [CartsApi.removeCartLineAsync.key]: CartsApi.removeCartLineAsync,
    [CartsApi.removeItemFromCartAsync.key]: CartsApi.removeItemFromCartAsync,
    [CartsApi.removeItemFromCompareTableAsync.key]: CartsApi.removeItemFromCompareTableAsync,
    [CartsApi.setCartCountryAsync.key]: CartsApi.setCartCountryAsync,
    [CartsApi.setCartCurrencyAsync.key]: CartsApi.setCartCurrencyAsync,
    [CartsApi.submitCartAsync.key]: CartsApi.submitCartAsync,
    [CartsApi.updateCartAsync.key]: CartsApi.updateCartAsync,
    [CartsApi.updateCartLineAsync.key]: CartsApi.updateCartLineAsync,
    [CartsApi.updateItemCartRecordAsync.key]: CartsApi.updateItemCartRecordAsync,
    [CartsApi.updateItemToWishList.key]: CartsApi.updateItemToWishList,
    [CartsApi.wishListExistsAsync.key]: CartsApi.wishListExistsAsync,
    [CompareApi.addItemToCompareTableAsync.key]: CompareApi.addItemToCompareTableAsync,
    [CompareApi.getItemToCompareRecord.key]: CompareApi.getItemToCompareRecord,
    [CompareApi.getItemToCompareRecords.key]: CompareApi.getItemToCompareRecords,
    [CompareApi.removeItemFromCompareTable.key]: CompareApi.removeItemFromCompareTable,
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [RecordsApi.addItemToCart.key]: RecordsApi.addItemToCart,
    [RecordsApi.addProductToCartAsync.key]: RecordsApi.addProductToCartAsync,
    [RecordsApi.clearCartAsync.key]: RecordsApi.clearCartAsync,
    [RecordsApi.decreaseItemCartRecord.key]: RecordsApi.decreaseItemCartRecord,
    [RecordsApi.getItemCartRecord.key]: RecordsApi.getItemCartRecord,
    [RecordsApi.getItemsInCartAsync.key]: RecordsApi.getItemsInCartAsync,
    [RecordsApi.increaseItemCartRecord.key]: RecordsApi.increaseItemCartRecord,
    [RecordsApi.isItemAlreadyInCart.key]: RecordsApi.isItemAlreadyInCart,
    [RecordsApi.removeProductFromCartByParams.key]: RecordsApi.removeProductFromCartByParams,
    [RecordsApi.removeProductFromCartByRecordId.key]: RecordsApi.removeProductFromCartByRecordId,
    [RecordsApi.updateItemCartRecord.key]: RecordsApi.updateItemCartRecord,
    [WishListsApi.addProductToWishList.key]: WishListsApi.addProductToWishList,
    [WishListsApi.createWishList.key]: WishListsApi.createWishList,
    [WishListsApi.deleteWishList.key]: WishListsApi.deleteWishList,
    [WishListsApi.deleteWishListRecord.key]: WishListsApi.deleteWishListRecord,
    [WishListsApi.getCartWishListDetailsAsync.key]: WishListsApi.getCartWishListDetailsAsync,
    [WishListsApi.getCartWishListItemsAsync.key]: WishListsApi.getCartWishListItemsAsync,
    [WishListsApi.getWishListAsync.key]: WishListsApi.getWishListAsync,
    [WishListsApi.isProductInWishLists.key]: WishListsApi.isProductInWishLists,
    [WishListsApi.updateProductToWishList.key]: WishListsApi.updateProductToWishList,
    [WishListsApi.wishListExists.key]: WishListsApi.wishListExists,
    [WishListsApi.wishListExistsHeadAsync.key]: WishListsApi.wishListExistsHeadAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
