const CartsApi = require('../apis/CartsApi');
const CompareApi = require('../apis/CompareApi');
const FenixAllianceABPWebApi = require('../apis/FenixAllianceABPWebApi');
const RecordsApi = require('../apis/RecordsApi');
const WishListsApi = require('../apis/WishListsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CartsApi.addItemToCartAsync.key]: CartsApi.addItemToCartAsync,
    [CartsApi.addItemToCartCompareTable.key]: CartsApi.addItemToCartCompareTable,
    [CartsApi.addItemToWishList.key]: CartsApi.addItemToWishList,
    [CartsApi.cartWishListExistsHead.key]: CartsApi.cartWishListExistsHead,
    [CartsApi.clearCartRecords.key]: CartsApi.clearCartRecords,
    [CartsApi.createWishListAsync.key]: CartsApi.createWishListAsync,
    [CartsApi.decreaseCartItemQuantity.key]: CartsApi.decreaseCartItemQuantity,
    [CartsApi.decreaseCartLineAsync.key]: CartsApi.decreaseCartLineAsync,
    [CartsApi.deleteCartWishList.key]: CartsApi.deleteCartWishList,
    [CartsApi.deleteCartWishListRecord.key]: CartsApi.deleteCartWishListRecord,
    [CartsApi.getActingCart.key]: CartsApi.getActingCart,
    [CartsApi.getCartByIdAsync.key]: CartsApi.getCartByIdAsync,
    [CartsApi.getCartCompareRecord.key]: CartsApi.getCartCompareRecord,
    [CartsApi.getCartCompareRecords.key]: CartsApi.getCartCompareRecords,
    [CartsApi.getCartCountryAsync.key]: CartsApi.getCartCountryAsync,
    [CartsApi.getCartCurrencyAsync.key]: CartsApi.getCartCurrencyAsync,
    [CartsApi.getCartItems.key]: CartsApi.getCartItems,
    [CartsApi.getCartLineAsync.key]: CartsApi.getCartLineAsync,
    [CartsApi.getCartLinesAsync.key]: CartsApi.getCartLinesAsync,
    [CartsApi.getCartWishList.key]: CartsApi.getCartWishList,
    [CartsApi.getCartWishListDetails.key]: CartsApi.getCartWishListDetails,
    [CartsApi.getCartWishListItemAsync.key]: CartsApi.getCartWishListItemAsync,
    [CartsApi.getCartWishListItems.key]: CartsApi.getCartWishListItems,
    [CartsApi.getGuestCartAsync.key]: CartsApi.getGuestCartAsync,
    [CartsApi.getTenantCartAsync.key]: CartsApi.getTenantCartAsync,
    [CartsApi.getUserCart.key]: CartsApi.getUserCart,
    [CartsApi.increaseCartLineAsync.key]: CartsApi.increaseCartLineAsync,
    [CartsApi.increaseItemCartRecordQuantityAsync.key]: CartsApi.increaseItemCartRecordQuantityAsync,
    [CartsApi.isItemAlreadyInCartAsync.key]: CartsApi.isItemAlreadyInCartAsync,
    [CartsApi.isItemInCompareTableAsync.key]: CartsApi.isItemInCompareTableAsync,
    [CartsApi.isItemInWishLists.key]: CartsApi.isItemInWishLists,
    [CartsApi.removeCartLineAsync.key]: CartsApi.removeCartLineAsync,
    [CartsApi.removeItemFromCartAsync.key]: CartsApi.removeItemFromCartAsync,
    [CartsApi.removeItemFromCompareTableAsync.key]: CartsApi.removeItemFromCompareTableAsync,
    [CartsApi.setCartCountryAsync.key]: CartsApi.setCartCountryAsync,
    [CartsApi.setCartCurrencyAsync.key]: CartsApi.setCartCurrencyAsync,
    [CartsApi.submitCartAsync.key]: CartsApi.submitCartAsync,
    [CartsApi.updateCartAsync.key]: CartsApi.updateCartAsync,
    [CartsApi.updateCartLineAsync.key]: CartsApi.updateCartLineAsync,
    [CartsApi.updateItemCartRecordAsync.key]: CartsApi.updateItemCartRecordAsync,
    [CartsApi.updateItemToWishList.key]: CartsApi.updateItemToWishList,
    [CartsApi.wishListExistsAsync.key]: CartsApi.wishListExistsAsync,
    [CompareApi.addItemToCompareTableAsync.key]: CompareApi.addItemToCompareTableAsync,
    [CompareApi.getItemToCompareRecord.key]: CompareApi.getItemToCompareRecord,
    [CompareApi.getItemToCompareRecords.key]: CompareApi.getItemToCompareRecords,
    [CompareApi.removeItemFromCompareTable.key]: CompareApi.removeItemFromCompareTable,
    [FenixAllianceABPWebApi.forgotPasswordPost.key]: FenixAllianceABPWebApi.forgotPasswordPost,
    [FenixAllianceABPWebApi.healthGet.key]: FenixAllianceABPWebApi.healthGet,
    [FenixAllianceABPWebApi.helloGet.key]: FenixAllianceABPWebApi.helloGet,
    [FenixAllianceABPWebApi.loginPost.key]: FenixAllianceABPWebApi.loginPost,
    [FenixAllianceABPWebApi.manage2faPost.key]: FenixAllianceABPWebApi.manage2faPost,
    [FenixAllianceABPWebApi.manageInfoGet.key]: FenixAllianceABPWebApi.manageInfoGet,
    [FenixAllianceABPWebApi.manageInfoPost.key]: FenixAllianceABPWebApi.manageInfoPost,
    [FenixAllianceABPWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABPWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABPWebApi.refreshPost.key]: FenixAllianceABPWebApi.refreshPost,
    [FenixAllianceABPWebApi.registerPost.key]: FenixAllianceABPWebApi.registerPost,
    [FenixAllianceABPWebApi.resendConfirmationEmailPost.key]: FenixAllianceABPWebApi.resendConfirmationEmailPost,
    [FenixAllianceABPWebApi.resetPasswordPost.key]: FenixAllianceABPWebApi.resetPasswordPost,
    [FenixAllianceABPWebApi.versionGet.key]: FenixAllianceABPWebApi.versionGet,
    [RecordsApi.addItemToCart.key]: RecordsApi.addItemToCart,
    [RecordsApi.addProductToCartAsync.key]: RecordsApi.addProductToCartAsync,
    [RecordsApi.clearCartAsync.key]: RecordsApi.clearCartAsync,
    [RecordsApi.decreaseItemCartRecord.key]: RecordsApi.decreaseItemCartRecord,
    [RecordsApi.getItemCartRecord.key]: RecordsApi.getItemCartRecord,
    [RecordsApi.getItemsInCartAsync.key]: RecordsApi.getItemsInCartAsync,
    [RecordsApi.increaseItemCartRecord.key]: RecordsApi.increaseItemCartRecord,
    [RecordsApi.isItemAlreadyInCart.key]: RecordsApi.isItemAlreadyInCart,
    [RecordsApi.removeProductFromCartByParams.key]: RecordsApi.removeProductFromCartByParams,
    [RecordsApi.removeProductFromCartByRecordId.key]: RecordsApi.removeProductFromCartByRecordId,
    [RecordsApi.updateItemCartRecord.key]: RecordsApi.updateItemCartRecord,
    [WishListsApi.addProductToWishList.key]: WishListsApi.addProductToWishList,
    [WishListsApi.createWishList.key]: WishListsApi.createWishList,
    [WishListsApi.deleteWishList.key]: WishListsApi.deleteWishList,
    [WishListsApi.deleteWishListRecord.key]: WishListsApi.deleteWishListRecord,
    [WishListsApi.getCartWishListDetailsAsync.key]: WishListsApi.getCartWishListDetailsAsync,
    [WishListsApi.getCartWishListItemsAsync.key]: WishListsApi.getCartWishListItemsAsync,
    [WishListsApi.getWishListAsync.key]: WishListsApi.getWishListAsync,
    [WishListsApi.isProductInWishLists.key]: WishListsApi.isProductInWishLists,
    [WishListsApi.updateProductToWishList.key]: WishListsApi.updateProductToWishList,
    [WishListsApi.wishListExists.key]: WishListsApi.wishListExists,
    [WishListsApi.wishListExistsHeadAsync.key]: WishListsApi.wishListExistsHeadAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
