const DepartmentsApi = require('../apis/DepartmentsApi');
const EmployeeEnrollmentsApi = require('../apis/EmployeeEnrollmentsApi');
const EnrollmentsApi = require('../apis/EnrollmentsApi');
const FenixAllianceABPWebApi = require('../apis/FenixAllianceABPWebApi');
const IndustriesApi = require('../apis/IndustriesApi');
const InvitationsApi = require('../apis/InvitationsApi');
const OptionsApi = require('../apis/OptionsApi');
const PositionsApi = require('../apis/PositionsApi');
const SegmentsApi = require('../apis/SegmentsApi');
const SizesApi = require('../apis/SizesApi');
const TeamContactEnrollmentsApi = require('../apis/TeamContactEnrollmentsApi');
const TeamProjectEnrollmentsApi = require('../apis/TeamProjectEnrollmentsApi');
const TeamRecordsApi = require('../apis/TeamRecordsApi');
const TeamsApi = require('../apis/TeamsApi');
const TenantsApi = require('../apis/TenantsApi');
const TerritoriesApi = require('../apis/TerritoriesApi');
const TypesApi = require('../apis/TypesApi');
const UnitGroupsApi = require('../apis/UnitGroupsApi');
const UnitsApi = require('../apis/UnitsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [DepartmentsApi.createTenantDepartment.key]: DepartmentsApi.createTenantDepartment,
    [DepartmentsApi.deleteTenantDepartment.key]: DepartmentsApi.deleteTenantDepartment,
    [DepartmentsApi.getTenantDepartmentById.key]: DepartmentsApi.getTenantDepartmentById,
    [DepartmentsApi.getTenantDepartments.key]: DepartmentsApi.getTenantDepartments,
    [DepartmentsApi.getTenantDepartmentsCount.key]: DepartmentsApi.getTenantDepartmentsCount,
    [DepartmentsApi.updateTenantDepartment.key]: DepartmentsApi.updateTenantDepartment,
    [EmployeeEnrollmentsApi.createTenantEmployeeEnrollment.key]: EmployeeEnrollmentsApi.createTenantEmployeeEnrollment,
    [EmployeeEnrollmentsApi.deleteTenantEmployeeEnrollment.key]: EmployeeEnrollmentsApi.deleteTenantEmployeeEnrollment,
    [EmployeeEnrollmentsApi.getTenantEmployeeEnrollmentById.key]: EmployeeEnrollmentsApi.getTenantEmployeeEnrollmentById,
    [EmployeeEnrollmentsApi.getTenantEmployeeEnrollments.key]: EmployeeEnrollmentsApi.getTenantEmployeeEnrollments,
    [EmployeeEnrollmentsApi.getTenantEmployeeEnrollmentsCount.key]: EmployeeEnrollmentsApi.getTenantEmployeeEnrollmentsCount,
    [EmployeeEnrollmentsApi.updateTenantEmployeeEnrollment.key]: EmployeeEnrollmentsApi.updateTenantEmployeeEnrollment,
    [EnrollmentsApi.createTenantEnrollment.key]: EnrollmentsApi.createTenantEnrollment,
    [EnrollmentsApi.deleteTenantEnrollment.key]: EnrollmentsApi.deleteTenantEnrollment,
    [EnrollmentsApi.getExtendedTenantEnrollments.key]: EnrollmentsApi.getExtendedTenantEnrollments,
    [EnrollmentsApi.getExtendedTenantEnrollmentsCount.key]: EnrollmentsApi.getExtendedTenantEnrollmentsCount,
    [EnrollmentsApi.getTenantEnrollmentById.key]: EnrollmentsApi.getTenantEnrollmentById,
    [EnrollmentsApi.getTenantEnrollments.key]: EnrollmentsApi.getTenantEnrollments,
    [EnrollmentsApi.getTenantEnrollmentsCount.key]: EnrollmentsApi.getTenantEnrollmentsCount,
    [EnrollmentsApi.updateTenantEnrollment.key]: EnrollmentsApi.updateTenantEnrollment,
    [FenixAllianceABPWebApi.forgotPasswordPost.key]: FenixAllianceABPWebApi.forgotPasswordPost,
    [FenixAllianceABPWebApi.healthGet.key]: FenixAllianceABPWebApi.healthGet,
    [FenixAllianceABPWebApi.helloGet.key]: FenixAllianceABPWebApi.helloGet,
    [FenixAllianceABPWebApi.loginPost.key]: FenixAllianceABPWebApi.loginPost,
    [FenixAllianceABPWebApi.manage2faPost.key]: FenixAllianceABPWebApi.manage2faPost,
    [FenixAllianceABPWebApi.manageInfoGet.key]: FenixAllianceABPWebApi.manageInfoGet,
    [FenixAllianceABPWebApi.manageInfoPost.key]: FenixAllianceABPWebApi.manageInfoPost,
    [FenixAllianceABPWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABPWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABPWebApi.refreshPost.key]: FenixAllianceABPWebApi.refreshPost,
    [FenixAllianceABPWebApi.registerPost.key]: FenixAllianceABPWebApi.registerPost,
    [FenixAllianceABPWebApi.resendConfirmationEmailPost.key]: FenixAllianceABPWebApi.resendConfirmationEmailPost,
    [FenixAllianceABPWebApi.resetPasswordPost.key]: FenixAllianceABPWebApi.resetPasswordPost,
    [FenixAllianceABPWebApi.versionGet.key]: FenixAllianceABPWebApi.versionGet,
    [IndustriesApi.createTenantIndustry.key]: IndustriesApi.createTenantIndustry,
    [IndustriesApi.deleteTenantIndustry.key]: IndustriesApi.deleteTenantIndustry,
    [IndustriesApi.getTenantIndustries.key]: IndustriesApi.getTenantIndustries,
    [IndustriesApi.getTenantIndustriesCount.key]: IndustriesApi.getTenantIndustriesCount,
    [IndustriesApi.getTenantIndustryById.key]: IndustriesApi.getTenantIndustryById,
    [IndustriesApi.updateTenantIndustry.key]: IndustriesApi.updateTenantIndustry,
    [InvitationsApi.acceptTenantInvitation.key]: InvitationsApi.acceptTenantInvitation,
    [InvitationsApi.declineTenantInvitation.key]: InvitationsApi.declineTenantInvitation,
    [InvitationsApi.deleteTenantInvitation.key]: InvitationsApi.deleteTenantInvitation,
    [InvitationsApi.getTenantInvitationById.key]: InvitationsApi.getTenantInvitationById,
    [InvitationsApi.getTenantInvitations.key]: InvitationsApi.getTenantInvitations,
    [InvitationsApi.getTenantInvitationsCount.key]: InvitationsApi.getTenantInvitationsCount,
    [InvitationsApi.sendTenantInvitation.key]: InvitationsApi.sendTenantInvitation,
    [OptionsApi.createTenantOption.key]: OptionsApi.createTenantOption,
    [OptionsApi.deleteTenantOption.key]: OptionsApi.deleteTenantOption,
    [OptionsApi.getTenantOptionById.key]: OptionsApi.getTenantOptionById,
    [OptionsApi.getTenantOptionByKey.key]: OptionsApi.getTenantOptionByKey,
    [OptionsApi.getTenantOptions.key]: OptionsApi.getTenantOptions,
    [OptionsApi.getTenantOptionsCount.key]: OptionsApi.getTenantOptionsCount,
    [OptionsApi.updateTenantOption.key]: OptionsApi.updateTenantOption,
    [OptionsApi.upsertTenantOption.key]: OptionsApi.upsertTenantOption,
    [PositionsApi.createTenantPosition.key]: PositionsApi.createTenantPosition,
    [PositionsApi.deleteTenantPosition.key]: PositionsApi.deleteTenantPosition,
    [PositionsApi.getTenantPositionById.key]: PositionsApi.getTenantPositionById,
    [PositionsApi.getTenantPositions.key]: PositionsApi.getTenantPositions,
    [PositionsApi.getTenantPositionsCount.key]: PositionsApi.getTenantPositionsCount,
    [PositionsApi.updateTenantPosition.key]: PositionsApi.updateTenantPosition,
    [SegmentsApi.createTenantSegment.key]: SegmentsApi.createTenantSegment,
    [SegmentsApi.deleteTenantSegment.key]: SegmentsApi.deleteTenantSegment,
    [SegmentsApi.getTenantSegmentById.key]: SegmentsApi.getTenantSegmentById,
    [SegmentsApi.getTenantSegments.key]: SegmentsApi.getTenantSegments,
    [SegmentsApi.getTenantSegmentsCount.key]: SegmentsApi.getTenantSegmentsCount,
    [SegmentsApi.updateTenantSegment.key]: SegmentsApi.updateTenantSegment,
    [SizesApi.createTenantSize.key]: SizesApi.createTenantSize,
    [SizesApi.deleteTenantSize.key]: SizesApi.deleteTenantSize,
    [SizesApi.getTenantSizeById.key]: SizesApi.getTenantSizeById,
    [SizesApi.getTenantSizes.key]: SizesApi.getTenantSizes,
    [SizesApi.getTenantSizesCount.key]: SizesApi.getTenantSizesCount,
    [SizesApi.updateTenantSize.key]: SizesApi.updateTenantSize,
    [TeamContactEnrollmentsApi.createTenantTeamContactEnrollment.key]: TeamContactEnrollmentsApi.createTenantTeamContactEnrollment,
    [TeamContactEnrollmentsApi.deleteTenantTeamContactEnrollment.key]: TeamContactEnrollmentsApi.deleteTenantTeamContactEnrollment,
    [TeamContactEnrollmentsApi.getTenantTeamContactEnrollmentById.key]: TeamContactEnrollmentsApi.getTenantTeamContactEnrollmentById,
    [TeamContactEnrollmentsApi.getTenantTeamContactEnrollments.key]: TeamContactEnrollmentsApi.getTenantTeamContactEnrollments,
    [TeamContactEnrollmentsApi.getTenantTeamContactEnrollmentsCount.key]: TeamContactEnrollmentsApi.getTenantTeamContactEnrollmentsCount,
    [TeamContactEnrollmentsApi.updateTenantTeamContactEnrollment.key]: TeamContactEnrollmentsApi.updateTenantTeamContactEnrollment,
    [TeamProjectEnrollmentsApi.createTenantTeamProjectEnrollment.key]: TeamProjectEnrollmentsApi.createTenantTeamProjectEnrollment,
    [TeamProjectEnrollmentsApi.deleteTenantTeamProjectEnrollment.key]: TeamProjectEnrollmentsApi.deleteTenantTeamProjectEnrollment,
    [TeamProjectEnrollmentsApi.getTenantTeamProjectEnrollmentById.key]: TeamProjectEnrollmentsApi.getTenantTeamProjectEnrollmentById,
    [TeamProjectEnrollmentsApi.getTenantTeamProjectEnrollments.key]: TeamProjectEnrollmentsApi.getTenantTeamProjectEnrollments,
    [TeamProjectEnrollmentsApi.getTenantTeamProjectEnrollmentsCount.key]: TeamProjectEnrollmentsApi.getTenantTeamProjectEnrollmentsCount,
    [TeamProjectEnrollmentsApi.updateTenantTeamProjectEnrollment.key]: TeamProjectEnrollmentsApi.updateTenantTeamProjectEnrollment,
    [TeamRecordsApi.createTenantTeamRecord.key]: TeamRecordsApi.createTenantTeamRecord,
    [TeamRecordsApi.deleteTenantTeamRecord.key]: TeamRecordsApi.deleteTenantTeamRecord,
    [TeamRecordsApi.getTenantTeamRecordById.key]: TeamRecordsApi.getTenantTeamRecordById,
    [TeamRecordsApi.getTenantTeamRecords.key]: TeamRecordsApi.getTenantTeamRecords,
    [TeamRecordsApi.getTenantTeamRecordsCount.key]: TeamRecordsApi.getTenantTeamRecordsCount,
    [TeamRecordsApi.updateTenantTeamRecord.key]: TeamRecordsApi.updateTenantTeamRecord,
    [TeamsApi.createTenantTeam.key]: TeamsApi.createTenantTeam,
    [TeamsApi.deleteTenantTeam.key]: TeamsApi.deleteTenantTeam,
    [TeamsApi.getTenantTeamById.key]: TeamsApi.getTenantTeamById,
    [TeamsApi.getTenantTeams.key]: TeamsApi.getTenantTeams,
    [TeamsApi.getTenantTeamsCount.key]: TeamsApi.getTenantTeamsCount,
    [TeamsApi.updateTenantTeam.key]: TeamsApi.updateTenantTeam,
    [TenantsApi.assignLicenseAsync.key]: TenantsApi.assignLicenseAsync,
    [TenantsApi.createTenantAsync.key]: TenantsApi.createTenantAsync,
    [TenantsApi.deSelectTenantAsync.key]: TenantsApi.deSelectTenantAsync,
    [TenantsApi.deleteTenantAsync.key]: TenantsApi.deleteTenantAsync,
    [TenantsApi.getAccessibleFeaturesAsync.key]: TenantsApi.getAccessibleFeaturesAsync,
    [TenantsApi.getCurrentTenantAsync.key]: TenantsApi.getCurrentTenantAsync,
    [TenantsApi.getEnrollmentLicenseByIdAsync.key]: TenantsApi.getEnrollmentLicenseByIdAsync,
    [TenantsApi.getEnrollmentLicensesAsync.key]: TenantsApi.getEnrollmentLicensesAsync,
    [TenantsApi.getEnrollmentPermissionsAsync.key]: TenantsApi.getEnrollmentPermissionsAsync,
    [TenantsApi.getExtendedTenantAsync.key]: TenantsApi.getExtendedTenantAsync,
    [TenantsApi.getExtendedTenantEnrollmentAsync.key]: TenantsApi.getExtendedTenantEnrollmentAsync,
    [TenantsApi.getRootTenantAsync.key]: TenantsApi.getRootTenantAsync,
    [TenantsApi.getTenantAsync.key]: TenantsApi.getTenantAsync,
    [TenantsApi.getTenantAvatarAsync.key]: TenantsApi.getTenantAvatarAsync,
    [TenantsApi.getTenantCartAsync.key]: TenantsApi.getTenantCartAsync,
    [TenantsApi.getTenantEnrollmentAsync.key]: TenantsApi.getTenantEnrollmentAsync,
    [TenantsApi.getTenantEnrollmentsAsync.key]: TenantsApi.getTenantEnrollmentsAsync,
    [TenantsApi.getTenantInvitationsAsync.key]: TenantsApi.getTenantInvitationsAsync,
    [TenantsApi.getTenantLicensesAsync.key]: TenantsApi.getTenantLicensesAsync,
    [TenantsApi.getTenantNotificationsAsync.key]: TenantsApi.getTenantNotificationsAsync,
    [TenantsApi.getTenantNotificationsCountAsync.key]: TenantsApi.getTenantNotificationsCountAsync,
    [TenantsApi.getTenantPendingInvitationsAsync.key]: TenantsApi.getTenantPendingInvitationsAsync,
    [TenantsApi.getTenantRedeemedInvitationsAsync.key]: TenantsApi.getTenantRedeemedInvitationsAsync,
    [TenantsApi.getTenantRevokedInvitationsAsync.key]: TenantsApi.getTenantRevokedInvitationsAsync,
    [TenantsApi.getTenantSocialProfileAsync.key]: TenantsApi.getTenantSocialProfileAsync,
    [TenantsApi.getTenantUsersAsync.key]: TenantsApi.getTenantUsersAsync,
    [TenantsApi.getTenantWalletAsync.key]: TenantsApi.getTenantWalletAsync,
    [TenantsApi.getTenantWebPortalsAsync.key]: TenantsApi.getTenantWebPortalsAsync,
    [TenantsApi.patchTenantAsync.key]: TenantsApi.patchTenantAsync,
    [TenantsApi.revokeLicenseAsync.key]: TenantsApi.revokeLicenseAsync,
    [TenantsApi.selectTenantAsync.key]: TenantsApi.selectTenantAsync,
    [TenantsApi.updateAvatarAsync.key]: TenantsApi.updateAvatarAsync,
    [TenantsApi.updateTenantAsync.key]: TenantsApi.updateTenantAsync,
    [TenantsApi.validateEnrollmentFeatureAccess.key]: TenantsApi.validateEnrollmentFeatureAccess,
    [TenantsApi.validateEnrollmentPermissionsAsync.key]: TenantsApi.validateEnrollmentPermissionsAsync,
    [TerritoriesApi.createTenantTerritory.key]: TerritoriesApi.createTenantTerritory,
    [TerritoriesApi.deleteTenantTerritory.key]: TerritoriesApi.deleteTenantTerritory,
    [TerritoriesApi.getTenantTerritories.key]: TerritoriesApi.getTenantTerritories,
    [TerritoriesApi.getTenantTerritoriesCount.key]: TerritoriesApi.getTenantTerritoriesCount,
    [TerritoriesApi.getTenantTerritoryById.key]: TerritoriesApi.getTenantTerritoryById,
    [TerritoriesApi.updateTenantTerritory.key]: TerritoriesApi.updateTenantTerritory,
    [TypesApi.createTenantType.key]: TypesApi.createTenantType,
    [TypesApi.deleteTenantType.key]: TypesApi.deleteTenantType,
    [TypesApi.getTenantTypeById.key]: TypesApi.getTenantTypeById,
    [TypesApi.getTenantTypes.key]: TypesApi.getTenantTypes,
    [TypesApi.getTenantTypesCount.key]: TypesApi.getTenantTypesCount,
    [TypesApi.updateTenantType.key]: TypesApi.updateTenantType,
    [UnitGroupsApi.createUnitAsync.key]: UnitGroupsApi.createUnitAsync,
    [UnitGroupsApi.createUnitGroupAsync.key]: UnitGroupsApi.createUnitGroupAsync,
    [UnitGroupsApi.deleteUnitAsync.key]: UnitGroupsApi.deleteUnitAsync,
    [UnitGroupsApi.deleteUnitGroupAsync.key]: UnitGroupsApi.deleteUnitGroupAsync,
    [UnitGroupsApi.getUnitAsync.key]: UnitGroupsApi.getUnitAsync,
    [UnitGroupsApi.getUnitGroupAsync.key]: UnitGroupsApi.getUnitGroupAsync,
    [UnitGroupsApi.getUnitGroupsAsync.key]: UnitGroupsApi.getUnitGroupsAsync,
    [UnitGroupsApi.getUnitGroupsCountAsync.key]: UnitGroupsApi.getUnitGroupsCountAsync,
    [UnitGroupsApi.getUnitsAsync.key]: UnitGroupsApi.getUnitsAsync,
    [UnitGroupsApi.getUnitsCountAsync.key]: UnitGroupsApi.getUnitsCountAsync,
    [UnitGroupsApi.updateUnitAsync.key]: UnitGroupsApi.updateUnitAsync,
    [UnitGroupsApi.updateUnitGroupAsync.key]: UnitGroupsApi.updateUnitGroupAsync,
    [UnitsApi.createTenantUnit.key]: UnitsApi.createTenantUnit,
    [UnitsApi.deleteTenantUnit.key]: UnitsApi.deleteTenantUnit,
    [UnitsApi.getTenantUnitById.key]: UnitsApi.getTenantUnitById,
    [UnitsApi.getTenantUnits.key]: UnitsApi.getTenantUnits,
    [UnitsApi.getTenantUnitsCount.key]: UnitsApi.getTenantUnitsCount,
    [UnitsApi.updateTenantUnit.key]: UnitsApi.updateTenantUnit,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
