const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}type`,
                label: `[${labelPrefix}type]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}message`,
                label: `[${labelPrefix}message]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}logType`,
                label: `[${labelPrefix}logType]`,
                type: 'string',
                choices: [
                    'Continue',
                    'SwitchingProtocols',
                    'Processing',
                    'EarlyHints',
                    'OK',
                    'Created',
                    'Accepted',
                    'NonAuthoritativeInformation',
                    'NoContent',
                    'ResetContent',
                    'PartialContent',
                    'MultiStatus',
                    'AlreadyReported',
                    'IMUsed',
                    'MultipleChoices',
                    'MovedPermanently',
                    'Found',
                    'SeeOther',
                    'NotModified',
                    'UseProxy',
                    'Unused',
                    'TemporaryRedirect',
                    'PermanentRedirect',
                    'BadRequest',
                    'Unauthorized',
                    'PaymentRequired',
                    'Forbidden',
                    'NotFound',
                    'MethodNotAllowed',
                    'NotAcceptable',
                    'ProxyAuthenticationRequired',
                    'RequestTimeout',
                    'Conflict',
                    'Gone',
                    'LengthRequired',
                    'PreconditionFailed',
                    'RequestEntityTooLarge',
                    'RequestUriTooLong',
                    'UnsupportedMediaType',
                    'RequestedRangeNotSatisfiable',
                    'ExpectationFailed',
                    'MisdirectedRequest',
                    'UnprocessableEntity',
                    'Locked',
                    'FailedDependency',
                    'UpgradeRequired',
                    'PreconditionRequired',
                    'TooManyRequests',
                    'RequestHeaderFieldsTooLarge',
                    'UnavailableForLegalReasons',
                    'InternalServerError',
                    'NotImplemented',
                    'BadGateway',
                    'ServiceUnavailable',
                    'GatewayTimeout',
                    'HttpVersionNotSupported',
                    'VariantAlsoNegotiates',
                    'InsufficientStorage',
                    'LoopDetected',
                    'NotExtended',
                    'NetworkAuthenticationRequired',
                ],
            },
            {
                key: `${keyPrefix}businessID`,
                label: `[${labelPrefix}businessID]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'type': bundle.inputData?.[`${keyPrefix}type`],
            'message': bundle.inputData?.[`${keyPrefix}message`],
            'logType': bundle.inputData?.[`${keyPrefix}logType`],
            'businessID': bundle.inputData?.[`${keyPrefix}businessID`],
        }
    },
}
