const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}remote`,
                label: `[${labelPrefix}remote]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}expectedHireDate`,
                label: `[${labelPrefix}expectedHireDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}technicalSkills`,
                label: `[${labelPrefix}technicalSkills]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}nonTechnicalSkills`,
                label: `[${labelPrefix}nonTechnicalSkills]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}certifications`,
                label: `[${labelPrefix}certifications]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}projectExperience`,
                label: `[${labelPrefix}projectExperience]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}technologies`,
                label: `[${labelPrefix}technologies]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}benefits`,
                label: `[${labelPrefix}benefits]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}isOfficialJobOffer`,
                label: `[${labelPrefix}isOfficialJobOffer]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isRemoteJobOffer`,
                label: `[${labelPrefix}isRemoteJobOffer]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isMidTimeJobOffer`,
                label: `[${labelPrefix}isMidTimeJobOffer]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isUndergraduateOption`,
                label: `[${labelPrefix}isUndergraduateOption]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}minOverallExperienceYears`,
                label: `[${labelPrefix}minOverallExperienceYears]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}availiablePositionsCount`,
                label: `[${labelPrefix}availiablePositionsCount]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}viewsCount`,
                label: `[${labelPrefix}viewsCount]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}minSalaryAmount`,
                label: `[${labelPrefix}minSalaryAmount]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}maxSalaryAmount`,
                label: `[${labelPrefix}maxSalaryAmount]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}imageUrl`,
                label: `[${labelPrefix}imageUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}location`,
                label: `[${labelPrefix}location]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data`,
                label: `[${labelPrefix}data]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dataLabel`,
                label: `[${labelPrefix}dataLabel]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data1`,
                label: `[${labelPrefix}data1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data1Label`,
                label: `[${labelPrefix}data1Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data2`,
                label: `[${labelPrefix}data2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data2Label`,
                label: `[${labelPrefix}data2Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data3`,
                label: `[${labelPrefix}data3]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data3Label`,
                label: `[${labelPrefix}data3Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data4`,
                label: `[${labelPrefix}data4]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data4Label`,
                label: `[${labelPrefix}data4Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data5`,
                label: `[${labelPrefix}data5]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data5Label`,
                label: `[${labelPrefix}data5Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data6`,
                label: `[${labelPrefix}data6]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data6Label`,
                label: `[${labelPrefix}data6Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data7`,
                label: `[${labelPrefix}data7]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data7Label`,
                label: `[${labelPrefix}data7Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data8`,
                label: `[${labelPrefix}data8]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data8Label`,
                label: `[${labelPrefix}data8Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data9`,
                label: `[${labelPrefix}data9]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data9Label`,
                label: `[${labelPrefix}data9Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}externalUrl`,
                label: `[${labelPrefix}externalUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tenantId`,
                label: `[${labelPrefix}tenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enrollmentId`,
                label: `[${labelPrefix}enrollmentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}currencyId`,
                label: `[${labelPrefix}currencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}jobFieldId`,
                label: `[${labelPrefix}jobFieldId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}employerProfileId`,
                label: `[${labelPrefix}employerProfileId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryId`,
                label: `[${labelPrefix}countryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryStateId`,
                label: `[${labelPrefix}countryStateId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cityId`,
                label: `[${labelPrefix}cityId]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'remote': bundle.inputData?.[`${keyPrefix}remote`],
            'expectedHireDate': bundle.inputData?.[`${keyPrefix}expectedHireDate`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'technicalSkills': bundle.inputData?.[`${keyPrefix}technicalSkills`],
            'nonTechnicalSkills': bundle.inputData?.[`${keyPrefix}nonTechnicalSkills`],
            'certifications': bundle.inputData?.[`${keyPrefix}certifications`],
            'projectExperience': bundle.inputData?.[`${keyPrefix}projectExperience`],
            'technologies': bundle.inputData?.[`${keyPrefix}technologies`],
            'benefits': bundle.inputData?.[`${keyPrefix}benefits`],
            'isOfficialJobOffer': bundle.inputData?.[`${keyPrefix}isOfficialJobOffer`],
            'isRemoteJobOffer': bundle.inputData?.[`${keyPrefix}isRemoteJobOffer`],
            'isMidTimeJobOffer': bundle.inputData?.[`${keyPrefix}isMidTimeJobOffer`],
            'isUndergraduateOption': bundle.inputData?.[`${keyPrefix}isUndergraduateOption`],
            'minOverallExperienceYears': bundle.inputData?.[`${keyPrefix}minOverallExperienceYears`],
            'availiablePositionsCount': bundle.inputData?.[`${keyPrefix}availiablePositionsCount`],
            'viewsCount': bundle.inputData?.[`${keyPrefix}viewsCount`],
            'minSalaryAmount': bundle.inputData?.[`${keyPrefix}minSalaryAmount`],
            'maxSalaryAmount': bundle.inputData?.[`${keyPrefix}maxSalaryAmount`],
            'imageUrl': bundle.inputData?.[`${keyPrefix}imageUrl`],
            'location': bundle.inputData?.[`${keyPrefix}location`],
            'data': bundle.inputData?.[`${keyPrefix}data`],
            'dataLabel': bundle.inputData?.[`${keyPrefix}dataLabel`],
            'data1': bundle.inputData?.[`${keyPrefix}data1`],
            'data1Label': bundle.inputData?.[`${keyPrefix}data1Label`],
            'data2': bundle.inputData?.[`${keyPrefix}data2`],
            'data2Label': bundle.inputData?.[`${keyPrefix}data2Label`],
            'data3': bundle.inputData?.[`${keyPrefix}data3`],
            'data3Label': bundle.inputData?.[`${keyPrefix}data3Label`],
            'data4': bundle.inputData?.[`${keyPrefix}data4`],
            'data4Label': bundle.inputData?.[`${keyPrefix}data4Label`],
            'data5': bundle.inputData?.[`${keyPrefix}data5`],
            'data5Label': bundle.inputData?.[`${keyPrefix}data5Label`],
            'data6': bundle.inputData?.[`${keyPrefix}data6`],
            'data6Label': bundle.inputData?.[`${keyPrefix}data6Label`],
            'data7': bundle.inputData?.[`${keyPrefix}data7`],
            'data7Label': bundle.inputData?.[`${keyPrefix}data7Label`],
            'data8': bundle.inputData?.[`${keyPrefix}data8`],
            'data8Label': bundle.inputData?.[`${keyPrefix}data8Label`],
            'data9': bundle.inputData?.[`${keyPrefix}data9`],
            'data9Label': bundle.inputData?.[`${keyPrefix}data9Label`],
            'externalUrl': bundle.inputData?.[`${keyPrefix}externalUrl`],
            'tenantId': bundle.inputData?.[`${keyPrefix}tenantId`],
            'enrollmentId': bundle.inputData?.[`${keyPrefix}enrollmentId`],
            'currencyId': bundle.inputData?.[`${keyPrefix}currencyId`],
            'jobFieldId': bundle.inputData?.[`${keyPrefix}jobFieldId`],
            'employerProfileId': bundle.inputData?.[`${keyPrefix}employerProfileId`],
            'countryId': bundle.inputData?.[`${keyPrefix}countryId`],
            'countryStateId': bundle.inputData?.[`${keyPrefix}countryStateId`],
            'cityId': bundle.inputData?.[`${keyPrefix}cityId`],
        }
    },
}
