const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const WalletsApi = require('../apis/WalletsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [WalletsApi.createWalletBankAccountAsync.key]: WalletsApi.createWalletBankAccountAsync,
    [WalletsApi.createWalletLocationAsync.key]: WalletsApi.createWalletLocationAsync,
    [WalletsApi.createWalletPaymentAsync.key]: WalletsApi.createWalletPaymentAsync,
    [WalletsApi.createWalletTokenAsync.key]: WalletsApi.createWalletTokenAsync,
    [WalletsApi.createWalletWithdrawRequestAsync.key]: WalletsApi.createWalletWithdrawRequestAsync,
    [WalletsApi.deleteWalletBankAccountAsync.key]: WalletsApi.deleteWalletBankAccountAsync,
    [WalletsApi.deleteWalletLocationAsync.key]: WalletsApi.deleteWalletLocationAsync,
    [WalletsApi.deleteWalletTokenAsync.key]: WalletsApi.deleteWalletTokenAsync,
    [WalletsApi.getIncomingPaymentsAsync.key]: WalletsApi.getIncomingPaymentsAsync,
    [WalletsApi.getIncomingPaymentsCountAsync.key]: WalletsApi.getIncomingPaymentsCountAsync,
    [WalletsApi.getIncomingWalletInvoicesAsync.key]: WalletsApi.getIncomingWalletInvoicesAsync,
    [WalletsApi.getIncomingWalletInvoicesCountAsync.key]: WalletsApi.getIncomingWalletInvoicesCountAsync,
    [WalletsApi.getOutgoingPaymentsAsync.key]: WalletsApi.getOutgoingPaymentsAsync,
    [WalletsApi.getOutgoingPaymentsCountAsync.key]: WalletsApi.getOutgoingPaymentsCountAsync,
    [WalletsApi.getOutgoingWalletInvoicesAsync.key]: WalletsApi.getOutgoingWalletInvoicesAsync,
    [WalletsApi.getOutgoingWalletInvoicesCountAsync.key]: WalletsApi.getOutgoingWalletInvoicesCountAsync,
    [WalletsApi.getWalletBankAccountAsync.key]: WalletsApi.getWalletBankAccountAsync,
    [WalletsApi.getWalletBankAccountsAsync.key]: WalletsApi.getWalletBankAccountsAsync,
    [WalletsApi.getWalletBankAccountsCountAsync.key]: WalletsApi.getWalletBankAccountsCountAsync,
    [WalletsApi.getWalletChargebacksAsync.key]: WalletsApi.getWalletChargebacksAsync,
    [WalletsApi.getWalletChargebacksCountAsync.key]: WalletsApi.getWalletChargebacksCountAsync,
    [WalletsApi.getWalletDetailsAsync.key]: WalletsApi.getWalletDetailsAsync,
    [WalletsApi.getWalletExtendedOrdersAsync.key]: WalletsApi.getWalletExtendedOrdersAsync,
    [WalletsApi.getWalletInvoicesAsync.key]: WalletsApi.getWalletInvoicesAsync,
    [WalletsApi.getWalletInvoicesCountAsync.key]: WalletsApi.getWalletInvoicesCountAsync,
    [WalletsApi.getWalletLocationAsync.key]: WalletsApi.getWalletLocationAsync,
    [WalletsApi.getWalletLocationsAsync.key]: WalletsApi.getWalletLocationsAsync,
    [WalletsApi.getWalletLocationsCountAsync.key]: WalletsApi.getWalletLocationsCountAsync,
    [WalletsApi.getWalletOrdersAsync.key]: WalletsApi.getWalletOrdersAsync,
    [WalletsApi.getWalletOrdersCountAsync.key]: WalletsApi.getWalletOrdersCountAsync,
    [WalletsApi.getWalletPaymentsAsync.key]: WalletsApi.getWalletPaymentsAsync,
    [WalletsApi.getWalletPaymentsCountAsync.key]: WalletsApi.getWalletPaymentsCountAsync,
    [WalletsApi.getWalletQuotesAsync.key]: WalletsApi.getWalletQuotesAsync,
    [WalletsApi.getWalletQuotesCountAsync.key]: WalletsApi.getWalletQuotesCountAsync,
    [WalletsApi.getWalletRefundsAsync.key]: WalletsApi.getWalletRefundsAsync,
    [WalletsApi.getWalletRefundsCountAsync.key]: WalletsApi.getWalletRefundsCountAsync,
    [WalletsApi.getWalletTokenAsync.key]: WalletsApi.getWalletTokenAsync,
    [WalletsApi.getWalletTokensAsync.key]: WalletsApi.getWalletTokensAsync,
    [WalletsApi.getWalletTokensCountAsync.key]: WalletsApi.getWalletTokensCountAsync,
    [WalletsApi.getWalletWithdrawRequestsAsync.key]: WalletsApi.getWalletWithdrawRequestsAsync,
    [WalletsApi.getWalletWithdrawRequestsCountAsync.key]: WalletsApi.getWalletWithdrawRequestsCountAsync,
    [WalletsApi.getWalletWithdrawsAsync.key]: WalletsApi.getWalletWithdrawsAsync,
    [WalletsApi.getWalletWithdrawsCountAsync.key]: WalletsApi.getWalletWithdrawsCountAsync,
    [WalletsApi.updateWalletBankAccountAsync.key]: WalletsApi.updateWalletBankAccountAsync,
    [WalletsApi.updateWalletLocationAsync.key]: WalletsApi.updateWalletLocationAsync,
    [WalletsApi.updateWalletTokenAsync.key]: WalletsApi.updateWalletTokenAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
