const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const WalletsApi = require('../apis/WalletsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [WalletsApi.createWalletLocationAsync.key]: WalletsApi.createWalletLocationAsync,
    [WalletsApi.deleteWalletLocationAsync.key]: WalletsApi.deleteWalletLocationAsync,
    [WalletsApi.getIncomingPaymentsAsync.key]: WalletsApi.getIncomingPaymentsAsync,
    [WalletsApi.getIncomingPaymentsCountAsync.key]: WalletsApi.getIncomingPaymentsCountAsync,
    [WalletsApi.getIncomingWalletInvoicesAsync.key]: WalletsApi.getIncomingWalletInvoicesAsync,
    [WalletsApi.getIncomingWalletInvoicesCountAsync.key]: WalletsApi.getIncomingWalletInvoicesCountAsync,
    [WalletsApi.getOutgoingPaymentsAsync.key]: WalletsApi.getOutgoingPaymentsAsync,
    [WalletsApi.getOutgoingPaymentsCountAsync.key]: WalletsApi.getOutgoingPaymentsCountAsync,
    [WalletsApi.getOutgoingWalletInvoicesAsync.key]: WalletsApi.getOutgoingWalletInvoicesAsync,
    [WalletsApi.getOutgoingWalletInvoicesCountAsync.key]: WalletsApi.getOutgoingWalletInvoicesCountAsync,
    [WalletsApi.getWalletDetailsAsync.key]: WalletsApi.getWalletDetailsAsync,
    [WalletsApi.getWalletExtendedOrdersAsync.key]: WalletsApi.getWalletExtendedOrdersAsync,
    [WalletsApi.getWalletInvoicesAsync.key]: WalletsApi.getWalletInvoicesAsync,
    [WalletsApi.getWalletInvoicesCountAsync.key]: WalletsApi.getWalletInvoicesCountAsync,
    [WalletsApi.getWalletLocationAsync.key]: WalletsApi.getWalletLocationAsync,
    [WalletsApi.getWalletLocationsAsync.key]: WalletsApi.getWalletLocationsAsync,
    [WalletsApi.getWalletLocationsCountAsync.key]: WalletsApi.getWalletLocationsCountAsync,
    [WalletsApi.getWalletOrdersAsync.key]: WalletsApi.getWalletOrdersAsync,
    [WalletsApi.getWalletOrdersCountAsync.key]: WalletsApi.getWalletOrdersCountAsync,
    [WalletsApi.getWalletPaymentsAsync.key]: WalletsApi.getWalletPaymentsAsync,
    [WalletsApi.getWalletPaymentsCountAsync.key]: WalletsApi.getWalletPaymentsCountAsync,
    [WalletsApi.updateWalletLocationAsync.key]: WalletsApi.updateWalletLocationAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
