const CompletionsApi = require('../apis/CompletionsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const InvoicesApi = require('../apis/InvoicesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [InvoicesApi.aggregateInvoiceDiscounts.key]: InvoicesApi.aggregateInvoiceDiscounts,
    [InvoicesApi.aggregateInvoiceGlobalSurcharges.key]: InvoicesApi.aggregateInvoiceGlobalSurcharges,
    [InvoicesApi.aggregateInvoiceTaxBases.key]: InvoicesApi.aggregateInvoiceTaxBases,
    [InvoicesApi.aggregateInvoiceTaxes.key]: InvoicesApi.aggregateInvoiceTaxes,
    [InvoicesApi.aggregateInvoiceTotals.key]: InvoicesApi.aggregateInvoiceTotals,
    [InvoicesApi.calculateInvoice.key]: InvoicesApi.calculateInvoice,
    [InvoicesApi.calculateInvoiceLine.key]: InvoicesApi.calculateInvoiceLine,
    [InvoicesApi.createInvoice.key]: InvoicesApi.createInvoice,
    [InvoicesApi.createInvoiceAdjustment.key]: InvoicesApi.createInvoiceAdjustment,
    [InvoicesApi.createInvoiceLine.key]: InvoicesApi.createInvoiceLine,
    [InvoicesApi.createInvoiceLineTax.key]: InvoicesApi.createInvoiceLineTax,
    [InvoicesApi.createInvoiceReference.key]: InvoicesApi.createInvoiceReference,
    [InvoicesApi.deleteInvoice.key]: InvoicesApi.deleteInvoice,
    [InvoicesApi.deleteInvoiceAdjustment.key]: InvoicesApi.deleteInvoiceAdjustment,
    [InvoicesApi.deleteInvoiceLine.key]: InvoicesApi.deleteInvoiceLine,
    [InvoicesApi.deleteInvoiceLineTax.key]: InvoicesApi.deleteInvoiceLineTax,
    [InvoicesApi.deleteInvoiceReference.key]: InvoicesApi.deleteInvoiceReference,
    [InvoicesApi.getExtendedInvoice.key]: InvoicesApi.getExtendedInvoice,
    [InvoicesApi.getExtendedInvoices.key]: InvoicesApi.getExtendedInvoices,
    [InvoicesApi.getExtendedInvoicesCount.key]: InvoicesApi.getExtendedInvoicesCount,
    [InvoicesApi.getInvoice.key]: InvoicesApi.getInvoice,
    [InvoicesApi.getInvoiceAdjustment.key]: InvoicesApi.getInvoiceAdjustment,
    [InvoicesApi.getInvoiceAdjustments.key]: InvoicesApi.getInvoiceAdjustments,
    [InvoicesApi.getInvoiceAdjustmentsCount.key]: InvoicesApi.getInvoiceAdjustmentsCount,
    [InvoicesApi.getInvoiceLine.key]: InvoicesApi.getInvoiceLine,
    [InvoicesApi.getInvoiceLineTaxes.key]: InvoicesApi.getInvoiceLineTaxes,
    [InvoicesApi.getInvoiceLineTaxesCount.key]: InvoicesApi.getInvoiceLineTaxesCount,
    [InvoicesApi.getInvoiceLines.key]: InvoicesApi.getInvoiceLines,
    [InvoicesApi.getInvoiceLinesCount.key]: InvoicesApi.getInvoiceLinesCount,
    [InvoicesApi.getInvoicePayments.key]: InvoicesApi.getInvoicePayments,
    [InvoicesApi.getInvoicePaymentsCount.key]: InvoicesApi.getInvoicePaymentsCount,
    [InvoicesApi.getInvoiceReference.key]: InvoicesApi.getInvoiceReference,
    [InvoicesApi.getInvoiceReferences.key]: InvoicesApi.getInvoiceReferences,
    [InvoicesApi.getInvoiceReferencesCount.key]: InvoicesApi.getInvoiceReferencesCount,
    [InvoicesApi.getInvoices.key]: InvoicesApi.getInvoices,
    [InvoicesApi.getInvoicesCount.key]: InvoicesApi.getInvoicesCount,
    [InvoicesApi.previewInvoiceEmail.key]: InvoicesApi.previewInvoiceEmail,
    [InvoicesApi.sendInvoiceEmail.key]: InvoicesApi.sendInvoiceEmail,
    [InvoicesApi.updateInvoice.key]: InvoicesApi.updateInvoice,
    [InvoicesApi.updateInvoiceAdjustment.key]: InvoicesApi.updateInvoiceAdjustment,
    [InvoicesApi.updateInvoiceLine.key]: InvoicesApi.updateInvoiceLine,
    [InvoicesApi.updateInvoiceLineTax.key]: InvoicesApi.updateInvoiceLineTax,
    [InvoicesApi.updateInvoiceReference.key]: InvoicesApi.updateInvoiceReference,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
