const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tenantId`,
                label: `[${labelPrefix}tenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}contactId`,
                label: `[${labelPrefix}contactId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enrollmentId`,
                label: `[${labelPrefix}enrollmentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}about`,
                label: `[${labelPrefix}about]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}verified`,
                label: `[${labelPrefix}verified]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}submitted`,
                label: `[${labelPrefix}submitted]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}avatarUrl`,
                label: `[${labelPrefix}avatarUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}qualifiedName`,
                label: `[${labelPrefix}qualifiedName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}verificationTimestamp`,
                label: `[${labelPrefix}verificationTimestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data`,
                label: `[${labelPrefix}data]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dataLabel`,
                label: `[${labelPrefix}dataLabel]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data1`,
                label: `[${labelPrefix}data1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data1Label`,
                label: `[${labelPrefix}data1Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data2`,
                label: `[${labelPrefix}data2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data2Label`,
                label: `[${labelPrefix}data2Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data3`,
                label: `[${labelPrefix}data3]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data3Label`,
                label: `[${labelPrefix}data3Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data4`,
                label: `[${labelPrefix}data4]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data4Label`,
                label: `[${labelPrefix}data4Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data5`,
                label: `[${labelPrefix}data5]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data5Label`,
                label: `[${labelPrefix}data5Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data6`,
                label: `[${labelPrefix}data6]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data6Label`,
                label: `[${labelPrefix}data6Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data7`,
                label: `[${labelPrefix}data7]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data7Label`,
                label: `[${labelPrefix}data7Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data8`,
                label: `[${labelPrefix}data8]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data8Label`,
                label: `[${labelPrefix}data8Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data9`,
                label: `[${labelPrefix}data9]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data9Label`,
                label: `[${labelPrefix}data9Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}taxId`,
                label: `[${labelPrefix}taxId]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}email`,
                label: `[${labelPrefix}email]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}phone`,
                label: `[${labelPrefix}phone]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}address`,
                label: `[${labelPrefix}address]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}address1`,
                label: `[${labelPrefix}address1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}address2`,
                label: `[${labelPrefix}address2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}postalCode`,
                label: `[${labelPrefix}postalCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}businessName`,
                label: `[${labelPrefix}businessName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}commercialName`,
                label: `[${labelPrefix}commercialName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ticker`,
                label: `[${labelPrefix}ticker]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}duns`,
                label: `[${labelPrefix}duns]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}isPublicCompany`,
                label: `[${labelPrefix}isPublicCompany]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isFactaCustomer`,
                label: `[${labelPrefix}isFactaCustomer]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}taxPayerType`,
                label: `[${labelPrefix}taxPayerType]`,
                type: 'string',
                choices: [
                    'Individual',
                    'Business',
                ],
            },
            {
                key: `${keyPrefix}countryId`,
                label: `[${labelPrefix}countryId]`,
                required: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}stateId`,
                label: `[${labelPrefix}stateId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cityId`,
                label: `[${labelPrefix}cityId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}fiscalIdentificationTypeId`,
                label: `[${labelPrefix}fiscalIdentificationTypeId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}fiscalAuthorityId`,
                label: `[${labelPrefix}fiscalAuthorityId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}fiscalRegimeId`,
                label: `[${labelPrefix}fiscalRegimeId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}contactName`,
                label: `[${labelPrefix}contactName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}fiscalAuthorityName`,
                label: `[${labelPrefix}fiscalAuthorityName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryName`,
                label: `[${labelPrefix}countryName]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'tenantId': bundle.inputData?.[`${keyPrefix}tenantId`],
            'contactId': bundle.inputData?.[`${keyPrefix}contactId`],
            'enrollmentId': bundle.inputData?.[`${keyPrefix}enrollmentId`],
            'about': bundle.inputData?.[`${keyPrefix}about`],
            'verified': bundle.inputData?.[`${keyPrefix}verified`],
            'submitted': bundle.inputData?.[`${keyPrefix}submitted`],
            'avatarUrl': bundle.inputData?.[`${keyPrefix}avatarUrl`],
            'qualifiedName': bundle.inputData?.[`${keyPrefix}qualifiedName`],
            'verificationTimestamp': bundle.inputData?.[`${keyPrefix}verificationTimestamp`],
            'data': bundle.inputData?.[`${keyPrefix}data`],
            'dataLabel': bundle.inputData?.[`${keyPrefix}dataLabel`],
            'data1': bundle.inputData?.[`${keyPrefix}data1`],
            'data1Label': bundle.inputData?.[`${keyPrefix}data1Label`],
            'data2': bundle.inputData?.[`${keyPrefix}data2`],
            'data2Label': bundle.inputData?.[`${keyPrefix}data2Label`],
            'data3': bundle.inputData?.[`${keyPrefix}data3`],
            'data3Label': bundle.inputData?.[`${keyPrefix}data3Label`],
            'data4': bundle.inputData?.[`${keyPrefix}data4`],
            'data4Label': bundle.inputData?.[`${keyPrefix}data4Label`],
            'data5': bundle.inputData?.[`${keyPrefix}data5`],
            'data5Label': bundle.inputData?.[`${keyPrefix}data5Label`],
            'data6': bundle.inputData?.[`${keyPrefix}data6`],
            'data6Label': bundle.inputData?.[`${keyPrefix}data6Label`],
            'data7': bundle.inputData?.[`${keyPrefix}data7`],
            'data7Label': bundle.inputData?.[`${keyPrefix}data7Label`],
            'data8': bundle.inputData?.[`${keyPrefix}data8`],
            'data8Label': bundle.inputData?.[`${keyPrefix}data8Label`],
            'data9': bundle.inputData?.[`${keyPrefix}data9`],
            'data9Label': bundle.inputData?.[`${keyPrefix}data9Label`],
            'taxId': bundle.inputData?.[`${keyPrefix}taxId`],
            'email': bundle.inputData?.[`${keyPrefix}email`],
            'phone': bundle.inputData?.[`${keyPrefix}phone`],
            'address': bundle.inputData?.[`${keyPrefix}address`],
            'address1': bundle.inputData?.[`${keyPrefix}address1`],
            'address2': bundle.inputData?.[`${keyPrefix}address2`],
            'postalCode': bundle.inputData?.[`${keyPrefix}postalCode`],
            'businessName': bundle.inputData?.[`${keyPrefix}businessName`],
            'commercialName': bundle.inputData?.[`${keyPrefix}commercialName`],
            'ticker': bundle.inputData?.[`${keyPrefix}ticker`],
            'duns': bundle.inputData?.[`${keyPrefix}duns`],
            'isPublicCompany': bundle.inputData?.[`${keyPrefix}isPublicCompany`],
            'isFactaCustomer': bundle.inputData?.[`${keyPrefix}isFactaCustomer`],
            'taxPayerType': bundle.inputData?.[`${keyPrefix}taxPayerType`],
            'countryId': bundle.inputData?.[`${keyPrefix}countryId`],
            'stateId': bundle.inputData?.[`${keyPrefix}stateId`],
            'cityId': bundle.inputData?.[`${keyPrefix}cityId`],
            'fiscalIdentificationTypeId': bundle.inputData?.[`${keyPrefix}fiscalIdentificationTypeId`],
            'fiscalAuthorityId': bundle.inputData?.[`${keyPrefix}fiscalAuthorityId`],
            'fiscalRegimeId': bundle.inputData?.[`${keyPrefix}fiscalRegimeId`],
            'contactName': bundle.inputData?.[`${keyPrefix}contactName`],
            'fiscalAuthorityName': bundle.inputData?.[`${keyPrefix}fiscalAuthorityName`],
            'countryName': bundle.inputData?.[`${keyPrefix}countryName`],
        }
    },
}
