const CompletionsApi = require('../apis/CompletionsApi');
const DiscountListsApi = require('../apis/DiscountListsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const PriceListsApi = require('../apis/PriceListsApi');
const PricesApi = require('../apis/PricesApi');
const PricingRulesApi = require('../apis/PricingRulesApi');
const RoundingPoliciesApi = require('../apis/RoundingPoliciesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [DiscountListsApi.createDiscountList.key]: DiscountListsApi.createDiscountList,
    [DiscountListsApi.createDiscountListEntry.key]: DiscountListsApi.createDiscountListEntry,
    [DiscountListsApi.deleteDiscountList.key]: DiscountListsApi.deleteDiscountList,
    [DiscountListsApi.deleteDiscountListEntry.key]: DiscountListsApi.deleteDiscountListEntry,
    [DiscountListsApi.getDiscountList.key]: DiscountListsApi.getDiscountList,
    [DiscountListsApi.getDiscountListEntries.key]: DiscountListsApi.getDiscountListEntries,
    [DiscountListsApi.getDiscountListEntriesCount.key]: DiscountListsApi.getDiscountListEntriesCount,
    [DiscountListsApi.getDiscountListEntry.key]: DiscountListsApi.getDiscountListEntry,
    [DiscountListsApi.getDiscountLists.key]: DiscountListsApi.getDiscountLists,
    [DiscountListsApi.getDiscountListsCount.key]: DiscountListsApi.getDiscountListsCount,
    [DiscountListsApi.patchDiscountList.key]: DiscountListsApi.patchDiscountList,
    [DiscountListsApi.patchDiscountListEntry.key]: DiscountListsApi.patchDiscountListEntry,
    [DiscountListsApi.updateDiscountList.key]: DiscountListsApi.updateDiscountList,
    [DiscountListsApi.updateDiscountListEntry.key]: DiscountListsApi.updateDiscountListEntry,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [PriceListsApi.createPriceListAsync.key]: PriceListsApi.createPriceListAsync,
    [PriceListsApi.createPriceListPricesAsync.key]: PriceListsApi.createPriceListPricesAsync,
    [PriceListsApi.deletePriceListAsync.key]: PriceListsApi.deletePriceListAsync,
    [PriceListsApi.deletePriceListPriceAsync.key]: PriceListsApi.deletePriceListPriceAsync,
    [PriceListsApi.getPriceListAsync.key]: PriceListsApi.getPriceListAsync,
    [PriceListsApi.getPriceListPriceAsync.key]: PriceListsApi.getPriceListPriceAsync,
    [PriceListsApi.getPriceListPricesAsync.key]: PriceListsApi.getPriceListPricesAsync,
    [PriceListsApi.getPriceListsAsync.key]: PriceListsApi.getPriceListsAsync,
    [PriceListsApi.getPriceListsCountAsync.key]: PriceListsApi.getPriceListsCountAsync,
    [PriceListsApi.patchPriceListAsync.key]: PriceListsApi.patchPriceListAsync,
    [PriceListsApi.patchPriceListPriceAsync.key]: PriceListsApi.patchPriceListPriceAsync,
    [PriceListsApi.updatePriceListAsync.key]: PriceListsApi.updatePriceListAsync,
    [PriceListsApi.updatePriceListPriceAsync.key]: PriceListsApi.updatePriceListPriceAsync,
    [PricesApi.getFinalPrice.key]: PricesApi.getFinalPrice,
    [PricesApi.getPrice.key]: PricesApi.getPrice,
    [PricesApi.getTotalSavingsInUsd.key]: PricesApi.getTotalSavingsInUsd,
    [PricesApi.getTotalTaxesInUsd.key]: PricesApi.getTotalTaxesInUsd,
    [PricingRulesApi.createPricingRule.key]: PricingRulesApi.createPricingRule,
    [PricingRulesApi.deletePricingRule.key]: PricingRulesApi.deletePricingRule,
    [PricingRulesApi.getPricingRuleById.key]: PricingRulesApi.getPricingRuleById,
    [PricingRulesApi.getPricingRules.key]: PricingRulesApi.getPricingRules,
    [PricingRulesApi.getPricingRulesCountAsync.key]: PricingRulesApi.getPricingRulesCountAsync,
    [PricingRulesApi.patchPricingRule.key]: PricingRulesApi.patchPricingRule,
    [PricingRulesApi.updatePricingRule.key]: PricingRulesApi.updatePricingRule,
    [RoundingPoliciesApi.createRoundingPolicyAsync.key]: RoundingPoliciesApi.createRoundingPolicyAsync,
    [RoundingPoliciesApi.deleteRoundingPolicyAsync.key]: RoundingPoliciesApi.deleteRoundingPolicyAsync,
    [RoundingPoliciesApi.getRoundingPoliciesAsync.key]: RoundingPoliciesApi.getRoundingPoliciesAsync,
    [RoundingPoliciesApi.getRoundingPoliciesCountAsync.key]: RoundingPoliciesApi.getRoundingPoliciesCountAsync,
    [RoundingPoliciesApi.getRoundingPolicyByIdAsync.key]: RoundingPoliciesApi.getRoundingPolicyByIdAsync,
    [RoundingPoliciesApi.patchRoundingPolicyAsync.key]: RoundingPoliciesApi.patchRoundingPolicyAsync,
    [RoundingPoliciesApi.updateRoundingPolicyAsync.key]: RoundingPoliciesApi.updateRoundingPolicyAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
