const utils = require('../utils/utils');
const AnyType = require('../models/AnyType');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}codeType`,
                label: `[${labelPrefix}codeType]`,
                type: 'string',
                choices: [
                    'Razor',
                    'CSharp',
                    'CSHtml',
                    'Liquid',
                    'Html5',
                    'Markdown',
                    'Markup',
                ],
            },
            {
                key: `${keyPrefix}order`,
                label: `[${labelPrefix}order]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}slug`,
                label: `[${labelPrefix}slug]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}name`,
                label: `[${labelPrefix}name]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}excerpt`,
                label: `[${labelPrefix}excerpt]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}password`,
                label: `[${labelPrefix}password]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}highlightImage`,
                label: `[${labelPrefix}highlightImage]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}canonicalUrl`,
                label: `[${labelPrefix}canonicalUrl]`,
                type: 'string',
            },
            ....fields(`${keyPrefix}emitResult`, isInput),
            {
                key: `${keyPrefix}seoTitle`,
                label: `[${labelPrefix}seoTitle]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}seoKeyWords`,
                label: `[${labelPrefix}seoKeyWords]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}seoKeyPhrases`,
                label: `[${labelPrefix}seoKeyPhrases]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}metaDescription`,
                label: `[${labelPrefix}metaDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}twitterImage`,
                label: `[${labelPrefix}twitterImage]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}twitterTitle`,
                label: `[${labelPrefix}twitterTitle]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}twitterDescription`,
                label: `[${labelPrefix}twitterDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}facebookImage`,
                label: `[${labelPrefix}facebookImage]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}facebookTitle`,
                label: `[${labelPrefix}facebookTitle]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}facebookDescription`,
                label: `[${labelPrefix}facebookDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}featuredImageUrl`,
                label: `[${labelPrefix}featuredImageUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}content`,
                label: `[${labelPrefix}content]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}code`,
                label: `[${labelPrefix}code]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}namespace`,
                label: `[${labelPrefix}namespace]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}typeName`,
                label: `[${labelPrefix}typeName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}generatedCode`,
                label: `[${labelPrefix}generatedCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}compilationPath`,
                label: `[${labelPrefix}compilationPath]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}htmlContent`,
                label: `[${labelPrefix}htmlContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cSharpContent`,
                label: `[${labelPrefix}cSharpContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}razorContent`,
                label: `[${labelPrefix}razorContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cssContent`,
                label: `[${labelPrefix}cssContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}jsContent`,
                label: `[${labelPrefix}jsContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cssFiles`,
                label: `[${labelPrefix}cssFiles]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}jsFiles`,
                label: `[${labelPrefix}jsFiles]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}razorGeneratedCode`,
                label: `[${labelPrefix}razorGeneratedCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cSharpGeneratedCode`,
                label: `[${labelPrefix}cSharpGeneratedCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}template`,
                label: `[${labelPrefix}template]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}default`,
                label: `[${labelPrefix}default]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}enable`,
                label: `[${labelPrefix}enable]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}enableComments`,
                label: `[${labelPrefix}enableComments]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displaySocialBox`,
                label: `[${labelPrefix}displaySocialBox]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}published`,
                label: `[${labelPrefix}published]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}inTrashCan`,
                label: `[${labelPrefix}inTrashCan]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}systemLocked`,
                label: `[${labelPrefix}systemLocked]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}allowPingBacks`,
                label: `[${labelPrefix}allowPingBacks]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}allowTrackbacks`,
                label: `[${labelPrefix}allowTrackbacks]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}cornerstoneContent`,
                label: `[${labelPrefix}cornerstoneContent]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isEssentialContent`,
                label: `[${labelPrefix}isEssentialContent]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}allowSearchEngineIndexing`,
                label: `[${labelPrefix}allowSearchEngineIndexing]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}tenantId`,
                label: `[${labelPrefix}tenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}webPortalId`,
                label: `[${labelPrefix}webPortalId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}websiteThemeId`,
                label: `[${labelPrefix}websiteThemeId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enrollmentId`,
                label: `[${labelPrefix}enrollmentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}socialProfileId`,
                label: `[${labelPrefix}socialProfileId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}parentWebContentId`,
                label: `[${labelPrefix}parentWebContentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}parentWebContentVersionId`,
                label: `[${labelPrefix}parentWebContentVersionId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}blogPostCategoryId`,
                label: `[${labelPrefix}blogPostCategoryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}webTemplateId`,
                label: `[${labelPrefix}webTemplateId]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'codeType': bundle.inputData?.[`${keyPrefix}codeType`],
            'order': bundle.inputData?.[`${keyPrefix}order`],
            'slug': bundle.inputData?.[`${keyPrefix}slug`],
            'name': bundle.inputData?.[`${keyPrefix}name`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'excerpt': bundle.inputData?.[`${keyPrefix}excerpt`],
            'password': bundle.inputData?.[`${keyPrefix}password`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'highlightImage': bundle.inputData?.[`${keyPrefix}highlightImage`],
            'canonicalUrl': bundle.inputData?.[`${keyPrefix}canonicalUrl`],
            'emitResult': utils.removeIfEmpty(.mapping(bundle, `${keyPrefix}emitResult`)),
            'seoTitle': bundle.inputData?.[`${keyPrefix}seoTitle`],
            'seoKeyWords': bundle.inputData?.[`${keyPrefix}seoKeyWords`],
            'seoKeyPhrases': bundle.inputData?.[`${keyPrefix}seoKeyPhrases`],
            'metaDescription': bundle.inputData?.[`${keyPrefix}metaDescription`],
            'twitterImage': bundle.inputData?.[`${keyPrefix}twitterImage`],
            'twitterTitle': bundle.inputData?.[`${keyPrefix}twitterTitle`],
            'twitterDescription': bundle.inputData?.[`${keyPrefix}twitterDescription`],
            'facebookImage': bundle.inputData?.[`${keyPrefix}facebookImage`],
            'facebookTitle': bundle.inputData?.[`${keyPrefix}facebookTitle`],
            'facebookDescription': bundle.inputData?.[`${keyPrefix}facebookDescription`],
            'featuredImageUrl': bundle.inputData?.[`${keyPrefix}featuredImageUrl`],
            'content': bundle.inputData?.[`${keyPrefix}content`],
            'code': bundle.inputData?.[`${keyPrefix}code`],
            'namespace': bundle.inputData?.[`${keyPrefix}namespace`],
            'typeName': bundle.inputData?.[`${keyPrefix}typeName`],
            'generatedCode': bundle.inputData?.[`${keyPrefix}generatedCode`],
            'compilationPath': bundle.inputData?.[`${keyPrefix}compilationPath`],
            'htmlContent': bundle.inputData?.[`${keyPrefix}htmlContent`],
            'cSharpContent': bundle.inputData?.[`${keyPrefix}cSharpContent`],
            'razorContent': bundle.inputData?.[`${keyPrefix}razorContent`],
            'cssContent': bundle.inputData?.[`${keyPrefix}cssContent`],
            'jsContent': bundle.inputData?.[`${keyPrefix}jsContent`],
            'cssFiles': bundle.inputData?.[`${keyPrefix}cssFiles`],
            'jsFiles': bundle.inputData?.[`${keyPrefix}jsFiles`],
            'razorGeneratedCode': bundle.inputData?.[`${keyPrefix}razorGeneratedCode`],
            'cSharpGeneratedCode': bundle.inputData?.[`${keyPrefix}cSharpGeneratedCode`],
            'template': bundle.inputData?.[`${keyPrefix}template`],
            'default': bundle.inputData?.[`${keyPrefix}default`],
            'enable': bundle.inputData?.[`${keyPrefix}enable`],
            'enableComments': bundle.inputData?.[`${keyPrefix}enableComments`],
            'displaySocialBox': bundle.inputData?.[`${keyPrefix}displaySocialBox`],
            'published': bundle.inputData?.[`${keyPrefix}published`],
            'inTrashCan': bundle.inputData?.[`${keyPrefix}inTrashCan`],
            'systemLocked': bundle.inputData?.[`${keyPrefix}systemLocked`],
            'allowPingBacks': bundle.inputData?.[`${keyPrefix}allowPingBacks`],
            'allowTrackbacks': bundle.inputData?.[`${keyPrefix}allowTrackbacks`],
            'cornerstoneContent': bundle.inputData?.[`${keyPrefix}cornerstoneContent`],
            'isEssentialContent': bundle.inputData?.[`${keyPrefix}isEssentialContent`],
            'allowSearchEngineIndexing': bundle.inputData?.[`${keyPrefix}allowSearchEngineIndexing`],
            'tenantId': bundle.inputData?.[`${keyPrefix}tenantId`],
            'webPortalId': bundle.inputData?.[`${keyPrefix}webPortalId`],
            'websiteThemeId': bundle.inputData?.[`${keyPrefix}websiteThemeId`],
            'enrollmentId': bundle.inputData?.[`${keyPrefix}enrollmentId`],
            'socialProfileId': bundle.inputData?.[`${keyPrefix}socialProfileId`],
            'parentWebContentId': bundle.inputData?.[`${keyPrefix}parentWebContentId`],
            'parentWebContentVersionId': bundle.inputData?.[`${keyPrefix}parentWebContentVersionId`],
            'blogPostCategoryId': bundle.inputData?.[`${keyPrefix}blogPostCategoryId`],
            'webTemplateId': bundle.inputData?.[`${keyPrefix}webTemplateId`],
        }
    },
}
