const utils = require('../utils/utils');
const CustomAttributeData = require('../models/CustomAttributeData');
const Module = require('../models/Module');
const RuntimeMethodHandle = require('../models/RuntimeMethodHandle');
const Type = require('../models/Type');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}name`,
                label: `[${labelPrefix}name]`,
                type: 'string',
            },
            ...Type.fields(`${keyPrefix}declaringType`, isInput),
            ...Type.fields(`${keyPrefix}reflectedType`, isInput),
            ...Module.fields(`${keyPrefix}module`, isInput),
            {
                key: `${keyPrefix}customAttributes`,
                label: `[${labelPrefix}customAttributes]`,
                children: CustomAttributeData.fields(`${keyPrefix}customAttributes${!isInput ? '[]' : ''}`, isInput, true), 
            },
            {
                key: `${keyPrefix}isCollectible`,
                label: `[${labelPrefix}isCollectible]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}metadataToken`,
                label: `[${labelPrefix}metadataToken]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}attributes`,
                label: `[${labelPrefix}attributes]`,
                type: 'string',
                choices: [
                    'PrivateScope',
                    'Private',
                    'FamANDAssem',
                    'Assembly',
                    'Family',
                    'FamORAssem',
                    'Public',
                    'MemberAccessMask',
                    'UnmanagedExport',
                    'Static',
                    'Final',
                    'Virtual',
                    'HideBySig',
                    'NewSlot',
                    'CheckAccessOnOverride',
                    'Abstract',
                    'SpecialName',
                    'RTSpecialName',
                    'PinvokeImpl',
                    'HasSecurity',
                    'RequireSecObject',
                    'ReservedMask',
                ],
            },
            {
                key: `${keyPrefix}methodImplementationFlags`,
                label: `[${labelPrefix}methodImplementationFlags]`,
                type: 'string',
                choices: [
                    'IL',
                    'Native',
                    'OPTIL',
                    'CodeTypeMask',
                    'ManagedMask',
                    'NoInlining',
                    'ForwardRef',
                    'Synchronized',
                    'NoOptimization',
                    'PreserveSig',
                    'AggressiveInlining',
                    'AggressiveOptimization',
                    'InternalCall',
                    'Async',
                    'MaxMethodImplVal',
                ],
            },
            {
                key: `${keyPrefix}callingConvention`,
                label: `[${labelPrefix}callingConvention]`,
                type: 'string',
                choices: [
                    'Standard',
                    'VarArgs',
                    'Any',
                    'HasThis',
                    'ExplicitThis',
                ],
            },
            {
                key: `${keyPrefix}isAbstract`,
                label: `[${labelPrefix}isAbstract]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isConstructor`,
                label: `[${labelPrefix}isConstructor]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isFinal`,
                label: `[${labelPrefix}isFinal]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isHideBySig`,
                label: `[${labelPrefix}isHideBySig]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSpecialName`,
                label: `[${labelPrefix}isSpecialName]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isStatic`,
                label: `[${labelPrefix}isStatic]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isVirtual`,
                label: `[${labelPrefix}isVirtual]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isAssembly`,
                label: `[${labelPrefix}isAssembly]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isFamily`,
                label: `[${labelPrefix}isFamily]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isFamilyAndAssembly`,
                label: `[${labelPrefix}isFamilyAndAssembly]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isFamilyOrAssembly`,
                label: `[${labelPrefix}isFamilyOrAssembly]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isPrivate`,
                label: `[${labelPrefix}isPrivate]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isPublic`,
                label: `[${labelPrefix}isPublic]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isConstructedGenericMethod`,
                label: `[${labelPrefix}isConstructedGenericMethod]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isGenericMethod`,
                label: `[${labelPrefix}isGenericMethod]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isGenericMethodDefinition`,
                label: `[${labelPrefix}isGenericMethodDefinition]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}containsGenericParameters`,
                label: `[${labelPrefix}containsGenericParameters]`,
                type: 'boolean',
            },
            ...RuntimeMethodHandle.fields(`${keyPrefix}methodHandle`, isInput),
            {
                key: `${keyPrefix}isSecurityCritical`,
                label: `[${labelPrefix}isSecurityCritical]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSecuritySafeCritical`,
                label: `[${labelPrefix}isSecuritySafeCritical]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSecurityTransparent`,
                label: `[${labelPrefix}isSecurityTransparent]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}memberType`,
                label: `[${labelPrefix}memberType]`,
                type: 'string',
                choices: [
                    'Constructor',
                    'Event',
                    'Field',
                    'Method',
                    'Property',
                    'TypeInfo',
                    'Custom',
                    'NestedType',
                    'All',
                ],
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'name': bundle.inputData?.[`${keyPrefix}name`],
            'declaringType': utils.removeIfEmpty(Type.mapping(bundle, `${keyPrefix}declaringType`)),
            'reflectedType': utils.removeIfEmpty(Type.mapping(bundle, `${keyPrefix}reflectedType`)),
            'module': utils.removeIfEmpty(Module.mapping(bundle, `${keyPrefix}module`)),
            'customAttributes': utils.childMapping(bundle.inputData?.[`${keyPrefix}customAttributes`], `${keyPrefix}customAttributes`, CustomAttributeData),
            'isCollectible': bundle.inputData?.[`${keyPrefix}isCollectible`],
            'metadataToken': bundle.inputData?.[`${keyPrefix}metadataToken`],
            'attributes': bundle.inputData?.[`${keyPrefix}attributes`],
            'methodImplementationFlags': bundle.inputData?.[`${keyPrefix}methodImplementationFlags`],
            'callingConvention': bundle.inputData?.[`${keyPrefix}callingConvention`],
            'isAbstract': bundle.inputData?.[`${keyPrefix}isAbstract`],
            'isConstructor': bundle.inputData?.[`${keyPrefix}isConstructor`],
            'isFinal': bundle.inputData?.[`${keyPrefix}isFinal`],
            'isHideBySig': bundle.inputData?.[`${keyPrefix}isHideBySig`],
            'isSpecialName': bundle.inputData?.[`${keyPrefix}isSpecialName`],
            'isStatic': bundle.inputData?.[`${keyPrefix}isStatic`],
            'isVirtual': bundle.inputData?.[`${keyPrefix}isVirtual`],
            'isAssembly': bundle.inputData?.[`${keyPrefix}isAssembly`],
            'isFamily': bundle.inputData?.[`${keyPrefix}isFamily`],
            'isFamilyAndAssembly': bundle.inputData?.[`${keyPrefix}isFamilyAndAssembly`],
            'isFamilyOrAssembly': bundle.inputData?.[`${keyPrefix}isFamilyOrAssembly`],
            'isPrivate': bundle.inputData?.[`${keyPrefix}isPrivate`],
            'isPublic': bundle.inputData?.[`${keyPrefix}isPublic`],
            'isConstructedGenericMethod': bundle.inputData?.[`${keyPrefix}isConstructedGenericMethod`],
            'isGenericMethod': bundle.inputData?.[`${keyPrefix}isGenericMethod`],
            'isGenericMethodDefinition': bundle.inputData?.[`${keyPrefix}isGenericMethodDefinition`],
            'containsGenericParameters': bundle.inputData?.[`${keyPrefix}containsGenericParameters`],
            'methodHandle': utils.removeIfEmpty(RuntimeMethodHandle.mapping(bundle, `${keyPrefix}methodHandle`)),
            'isSecurityCritical': bundle.inputData?.[`${keyPrefix}isSecurityCritical`],
            'isSecuritySafeCritical': bundle.inputData?.[`${keyPrefix}isSecuritySafeCritical`],
            'isSecurityTransparent': bundle.inputData?.[`${keyPrefix}isSecurityTransparent`],
            'memberType': bundle.inputData?.[`${keyPrefix}memberType`],
        }
    },
}
