const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}order`,
                label: `[${labelPrefix}order]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}slug`,
                label: `[${labelPrefix}slug]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}name`,
                label: `[${labelPrefix}name]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}excerpt`,
                label: `[${labelPrefix}excerpt]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}password`,
                label: `[${labelPrefix}password]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}highlightImage`,
                label: `[${labelPrefix}highlightImage]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}canonicalUrl`,
                label: `[${labelPrefix}canonicalUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}seoTitle`,
                label: `[${labelPrefix}seoTitle]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}seoKeyWords`,
                label: `[${labelPrefix}seoKeyWords]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}seoKeyPhrases`,
                label: `[${labelPrefix}seoKeyPhrases]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}metaDescription`,
                label: `[${labelPrefix}metaDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}twitterImage`,
                label: `[${labelPrefix}twitterImage]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}twitterTitle`,
                label: `[${labelPrefix}twitterTitle]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}twitterDescription`,
                label: `[${labelPrefix}twitterDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}facebookImage`,
                label: `[${labelPrefix}facebookImage]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}facebookTitle`,
                label: `[${labelPrefix}facebookTitle]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}facebookDescription`,
                label: `[${labelPrefix}facebookDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}featuredImageUrl`,
                label: `[${labelPrefix}featuredImageUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}content`,
                label: `[${labelPrefix}content]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}code`,
                label: `[${labelPrefix}code]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}namespace`,
                label: `[${labelPrefix}namespace]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}typeName`,
                label: `[${labelPrefix}typeName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}generatedCode`,
                label: `[${labelPrefix}generatedCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}compilationPath`,
                label: `[${labelPrefix}compilationPath]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}htmlContent`,
                label: `[${labelPrefix}htmlContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}codeType`,
                label: `[${labelPrefix}codeType]`,
                type: 'string',
                choices: [
                    'Razor',
                    'CSharp',
                    'CSHtml',
                    'Liquid',
                    'Html5',
                    'Markdown',
                ],
            },
            {
                key: `${keyPrefix}cSharpContent`,
                label: `[${labelPrefix}cSharpContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}razorContent`,
                label: `[${labelPrefix}razorContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cssContent`,
                label: `[${labelPrefix}cssContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}jsContent`,
                label: `[${labelPrefix}jsContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cssFiles`,
                label: `[${labelPrefix}cssFiles]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}jsFiles`,
                label: `[${labelPrefix}jsFiles]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}razorGeneratedCode`,
                label: `[${labelPrefix}razorGeneratedCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cSharpGeneratedCode`,
                label: `[${labelPrefix}cSharpGeneratedCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}precompiledLogicSize`,
                label: `[${labelPrefix}precompiledLogicSize]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}precompiledLogicSizeLong`,
                label: `[${labelPrefix}precompiledLogicSizeLong]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}precompiledViewSize`,
                label: `[${labelPrefix}precompiledViewSize]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}precompiledViewSizeLong`,
                label: `[${labelPrefix}precompiledViewSizeLong]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}precompiledLogicViewSize`,
                label: `[${labelPrefix}precompiledLogicViewSize]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}template`,
                label: `[${labelPrefix}template]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}default`,
                label: `[${labelPrefix}default]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}enable`,
                label: `[${labelPrefix}enable]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}enableComments`,
                label: `[${labelPrefix}enableComments]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displaySocialBox`,
                label: `[${labelPrefix}displaySocialBox]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}published`,
                label: `[${labelPrefix}published]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}inTrashCan`,
                label: `[${labelPrefix}inTrashCan]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}systemLocked`,
                label: `[${labelPrefix}systemLocked]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}allowPingbacks`,
                label: `[${labelPrefix}allowPingbacks]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}allowTrackbacks`,
                label: `[${labelPrefix}allowTrackbacks]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}cornerstoneContent`,
                label: `[${labelPrefix}cornerstoneContent]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isEssentialContent`,
                label: `[${labelPrefix}isEssentialContent]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}allowSearchEngineIndexing`,
                label: `[${labelPrefix}allowSearchEngineIndexing]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isHomePage`,
                label: `[${labelPrefix}isHomePage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isStorePage`,
                label: `[${labelPrefix}isStorePage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isCartPage`,
                label: `[${labelPrefix}isCartPage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isBlogPage`,
                label: `[${labelPrefix}isBlogPage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isAccountPage`,
                label: `[${labelPrefix}isAccountPage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isCheckoutPage`,
                label: `[${labelPrefix}isCheckoutPage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isWishListsPage`,
                label: `[${labelPrefix}isWishListsPage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isContactPage`,
                label: `[${labelPrefix}isContactPage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isPrivacyPolicyPage`,
                label: `[${labelPrefix}isPrivacyPolicyPage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isTermsOfServicePage`,
                label: `[${labelPrefix}isTermsOfServicePage]`,
                type: 'boolean',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'order': bundle.inputData?.[`${keyPrefix}order`],
            'slug': bundle.inputData?.[`${keyPrefix}slug`],
            'name': bundle.inputData?.[`${keyPrefix}name`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'excerpt': bundle.inputData?.[`${keyPrefix}excerpt`],
            'password': bundle.inputData?.[`${keyPrefix}password`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'highlightImage': bundle.inputData?.[`${keyPrefix}highlightImage`],
            'canonicalUrl': bundle.inputData?.[`${keyPrefix}canonicalUrl`],
            'seoTitle': bundle.inputData?.[`${keyPrefix}seoTitle`],
            'seoKeyWords': bundle.inputData?.[`${keyPrefix}seoKeyWords`],
            'seoKeyPhrases': bundle.inputData?.[`${keyPrefix}seoKeyPhrases`],
            'metaDescription': bundle.inputData?.[`${keyPrefix}metaDescription`],
            'twitterImage': bundle.inputData?.[`${keyPrefix}twitterImage`],
            'twitterTitle': bundle.inputData?.[`${keyPrefix}twitterTitle`],
            'twitterDescription': bundle.inputData?.[`${keyPrefix}twitterDescription`],
            'facebookImage': bundle.inputData?.[`${keyPrefix}facebookImage`],
            'facebookTitle': bundle.inputData?.[`${keyPrefix}facebookTitle`],
            'facebookDescription': bundle.inputData?.[`${keyPrefix}facebookDescription`],
            'featuredImageUrl': bundle.inputData?.[`${keyPrefix}featuredImageUrl`],
            'content': bundle.inputData?.[`${keyPrefix}content`],
            'code': bundle.inputData?.[`${keyPrefix}code`],
            'namespace': bundle.inputData?.[`${keyPrefix}namespace`],
            'typeName': bundle.inputData?.[`${keyPrefix}typeName`],
            'generatedCode': bundle.inputData?.[`${keyPrefix}generatedCode`],
            'compilationPath': bundle.inputData?.[`${keyPrefix}compilationPath`],
            'htmlContent': bundle.inputData?.[`${keyPrefix}htmlContent`],
            'codeType': bundle.inputData?.[`${keyPrefix}codeType`],
            'cSharpContent': bundle.inputData?.[`${keyPrefix}cSharpContent`],
            'razorContent': bundle.inputData?.[`${keyPrefix}razorContent`],
            'cssContent': bundle.inputData?.[`${keyPrefix}cssContent`],
            'jsContent': bundle.inputData?.[`${keyPrefix}jsContent`],
            'cssFiles': bundle.inputData?.[`${keyPrefix}cssFiles`],
            'jsFiles': bundle.inputData?.[`${keyPrefix}jsFiles`],
            'razorGeneratedCode': bundle.inputData?.[`${keyPrefix}razorGeneratedCode`],
            'cSharpGeneratedCode': bundle.inputData?.[`${keyPrefix}cSharpGeneratedCode`],
            'precompiledLogicSize': bundle.inputData?.[`${keyPrefix}precompiledLogicSize`],
            'precompiledLogicSizeLong': bundle.inputData?.[`${keyPrefix}precompiledLogicSizeLong`],
            'precompiledViewSize': bundle.inputData?.[`${keyPrefix}precompiledViewSize`],
            'precompiledViewSizeLong': bundle.inputData?.[`${keyPrefix}precompiledViewSizeLong`],
            'precompiledLogicViewSize': bundle.inputData?.[`${keyPrefix}precompiledLogicViewSize`],
            'template': bundle.inputData?.[`${keyPrefix}template`],
            'default': bundle.inputData?.[`${keyPrefix}default`],
            'enable': bundle.inputData?.[`${keyPrefix}enable`],
            'enableComments': bundle.inputData?.[`${keyPrefix}enableComments`],
            'displaySocialBox': bundle.inputData?.[`${keyPrefix}displaySocialBox`],
            'published': bundle.inputData?.[`${keyPrefix}published`],
            'inTrashCan': bundle.inputData?.[`${keyPrefix}inTrashCan`],
            'systemLocked': bundle.inputData?.[`${keyPrefix}systemLocked`],
            'allowPingbacks': bundle.inputData?.[`${keyPrefix}allowPingbacks`],
            'allowTrackbacks': bundle.inputData?.[`${keyPrefix}allowTrackbacks`],
            'cornerstoneContent': bundle.inputData?.[`${keyPrefix}cornerstoneContent`],
            'isEssentialContent': bundle.inputData?.[`${keyPrefix}isEssentialContent`],
            'allowSearchEngineIndexing': bundle.inputData?.[`${keyPrefix}allowSearchEngineIndexing`],
            'isHomePage': bundle.inputData?.[`${keyPrefix}isHomePage`],
            'isStorePage': bundle.inputData?.[`${keyPrefix}isStorePage`],
            'isCartPage': bundle.inputData?.[`${keyPrefix}isCartPage`],
            'isBlogPage': bundle.inputData?.[`${keyPrefix}isBlogPage`],
            'isAccountPage': bundle.inputData?.[`${keyPrefix}isAccountPage`],
            'isCheckoutPage': bundle.inputData?.[`${keyPrefix}isCheckoutPage`],
            'isWishListsPage': bundle.inputData?.[`${keyPrefix}isWishListsPage`],
            'isContactPage': bundle.inputData?.[`${keyPrefix}isContactPage`],
            'isPrivacyPolicyPage': bundle.inputData?.[`${keyPrefix}isPrivacyPolicyPage`],
            'isTermsOfServicePage': bundle.inputData?.[`${keyPrefix}isTermsOfServicePage`],
        }
    },
}
