const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const SignaturesApi = require('../apis/SignaturesApi');
const SignedDocumentArtifactsApi = require('../apis/SignedDocumentArtifactsApi');
const SignedDocumentAttachmentsApi = require('../apis/SignedDocumentAttachmentsApi');
const SignedDocumentsApi = require('../apis/SignedDocumentsApi');
const SigningCertificatesApi = require('../apis/SigningCertificatesApi');
const SigningEngineApi = require('../apis/SigningEngineApi');
const SigningLogsApi = require('../apis/SigningLogsApi');
const SigningParticipantsApi = require('../apis/SigningParticipantsApi');
const SigningProfileGraphicalRepresentationsApi = require('../apis/SigningProfileGraphicalRepresentationsApi');
const SigningProfilesApi = require('../apis/SigningProfilesApi');
const SigningRequestsApi = require('../apis/SigningRequestsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.apiV2AIServiceAgentsAgentIdAguiPost.key]: FenixAllianceABSWebApi.apiV2AIServiceAgentsAgentIdAguiPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [SignaturesApi.getSignatureByIdAsync.key]: SignaturesApi.getSignatureByIdAsync,
    [SignaturesApi.getSignaturesAsync.key]: SignaturesApi.getSignaturesAsync,
    [SignaturesApi.getSignaturesCountAsync.key]: SignaturesApi.getSignaturesCountAsync,
    [SignedDocumentArtifactsApi.freezeAsync.key]: SignedDocumentArtifactsApi.freezeAsync,
    [SignedDocumentArtifactsApi.getReferenceAsync.key]: SignedDocumentArtifactsApi.getReferenceAsync,
    [SignedDocumentArtifactsApi.setPrimaryAuthoringFileAsync.key]: SignedDocumentArtifactsApi.setPrimaryAuthoringFileAsync,
    [SignedDocumentArtifactsApi.verifyAsync.key]: SignedDocumentArtifactsApi.verifyAsync,
    [SignedDocumentAttachmentsApi.createSignedDocumentAttachmentAsync.key]: SignedDocumentAttachmentsApi.createSignedDocumentAttachmentAsync,
    [SignedDocumentAttachmentsApi.deleteSignedDocumentAttachmentAsync.key]: SignedDocumentAttachmentsApi.deleteSignedDocumentAttachmentAsync,
    [SignedDocumentAttachmentsApi.getSignedDocumentAttachmentByIdAsync.key]: SignedDocumentAttachmentsApi.getSignedDocumentAttachmentByIdAsync,
    [SignedDocumentAttachmentsApi.getSignedDocumentAttachmentsAsync.key]: SignedDocumentAttachmentsApi.getSignedDocumentAttachmentsAsync,
    [SignedDocumentAttachmentsApi.getSignedDocumentAttachmentsCountAsync.key]: SignedDocumentAttachmentsApi.getSignedDocumentAttachmentsCountAsync,
    [SignedDocumentAttachmentsApi.patchSignedDocumentAttachmentAsync.key]: SignedDocumentAttachmentsApi.patchSignedDocumentAttachmentAsync,
    [SignedDocumentAttachmentsApi.updateSignedDocumentAttachmentAsync.key]: SignedDocumentAttachmentsApi.updateSignedDocumentAttachmentAsync,
    [SignedDocumentsApi.createSignedDocumentAsync.key]: SignedDocumentsApi.createSignedDocumentAsync,
    [SignedDocumentsApi.deleteSignedDocumentAsync.key]: SignedDocumentsApi.deleteSignedDocumentAsync,
    [SignedDocumentsApi.getSignedDocumentByIdAsync.key]: SignedDocumentsApi.getSignedDocumentByIdAsync,
    [SignedDocumentsApi.getSignedDocumentsAsync.key]: SignedDocumentsApi.getSignedDocumentsAsync,
    [SignedDocumentsApi.getSignedDocumentsCountAsync.key]: SignedDocumentsApi.getSignedDocumentsCountAsync,
    [SignedDocumentsApi.patchSignedDocumentAsync.key]: SignedDocumentsApi.patchSignedDocumentAsync,
    [SignedDocumentsApi.prepareAndQuickSignAsync.key]: SignedDocumentsApi.prepareAndQuickSignAsync,
    [SignedDocumentsApi.quickSignSignedDocumentAsync.key]: SignedDocumentsApi.quickSignSignedDocumentAsync,
    [SignedDocumentsApi.updateSignedDocumentAsync.key]: SignedDocumentsApi.updateSignedDocumentAsync,
    [SignedDocumentsApi.verifySignedDocumentSignatureAsync.key]: SignedDocumentsApi.verifySignedDocumentSignatureAsync,
    [SigningCertificatesApi.createSigningCertificateAsync.key]: SigningCertificatesApi.createSigningCertificateAsync,
    [SigningCertificatesApi.deleteSigningCertificateAsync.key]: SigningCertificatesApi.deleteSigningCertificateAsync,
    [SigningCertificatesApi.getSigningCertificateByIdAsync.key]: SigningCertificatesApi.getSigningCertificateByIdAsync,
    [SigningCertificatesApi.getSigningCertificatesAsync.key]: SigningCertificatesApi.getSigningCertificatesAsync,
    [SigningCertificatesApi.getSigningCertificatesCountAsync.key]: SigningCertificatesApi.getSigningCertificatesCountAsync,
    [SigningCertificatesApi.importSigningCertificateAsync.key]: SigningCertificatesApi.importSigningCertificateAsync,
    [SigningCertificatesApi.patchSigningCertificateAsync.key]: SigningCertificatesApi.patchSigningCertificateAsync,
    [SigningCertificatesApi.updateSigningCertificateAsync.key]: SigningCertificatesApi.updateSigningCertificateAsync,
    [SigningEngineApi.getProvidersAsync.key]: SigningEngineApi.getProvidersAsync,
    [SigningEngineApi.getProvidersCountAsync.key]: SigningEngineApi.getProvidersCountAsync,
    [SigningEngineApi.previewAsync.key]: SigningEngineApi.previewAsync,
    [SigningLogsApi.getSigningLogByIdAsync.key]: SigningLogsApi.getSigningLogByIdAsync,
    [SigningLogsApi.getSigningLogsAsync.key]: SigningLogsApi.getSigningLogsAsync,
    [SigningLogsApi.getSigningLogsCountAsync.key]: SigningLogsApi.getSigningLogsCountAsync,
    [SigningParticipantsApi.getSigningParticipantByIdAsync.key]: SigningParticipantsApi.getSigningParticipantByIdAsync,
    [SigningParticipantsApi.getSigningParticipantsAsync.key]: SigningParticipantsApi.getSigningParticipantsAsync,
    [SigningParticipantsApi.getSigningParticipantsCountAsync.key]: SigningParticipantsApi.getSigningParticipantsCountAsync,
    [SigningParticipantsApi.markViewedAsync.key]: SigningParticipantsApi.markViewedAsync,
    [SigningParticipantsApi.recordOutcomeAsync.key]: SigningParticipantsApi.recordOutcomeAsync,
    [SigningProfileGraphicalRepresentationsApi.createSigningProfileGraphicalRepresentationAsync.key]: SigningProfileGraphicalRepresentationsApi.createSigningProfileGraphicalRepresentationAsync,
    [SigningProfileGraphicalRepresentationsApi.deleteSigningProfileGraphicalRepresentationAsync.key]: SigningProfileGraphicalRepresentationsApi.deleteSigningProfileGraphicalRepresentationAsync,
    [SigningProfileGraphicalRepresentationsApi.getSigningProfileGraphicalRepresentationByIdAsync.key]: SigningProfileGraphicalRepresentationsApi.getSigningProfileGraphicalRepresentationByIdAsync,
    [SigningProfileGraphicalRepresentationsApi.getSigningProfileGraphicalRepresentationsAsync.key]: SigningProfileGraphicalRepresentationsApi.getSigningProfileGraphicalRepresentationsAsync,
    [SigningProfileGraphicalRepresentationsApi.getSigningProfileGraphicalRepresentationsCountAsync.key]: SigningProfileGraphicalRepresentationsApi.getSigningProfileGraphicalRepresentationsCountAsync,
    [SigningProfileGraphicalRepresentationsApi.patchSigningProfileGraphicalRepresentationAsync.key]: SigningProfileGraphicalRepresentationsApi.patchSigningProfileGraphicalRepresentationAsync,
    [SigningProfileGraphicalRepresentationsApi.updateSigningProfileGraphicalRepresentationAsync.key]: SigningProfileGraphicalRepresentationsApi.updateSigningProfileGraphicalRepresentationAsync,
    [SigningProfilesApi.createSigningProfileAsync.key]: SigningProfilesApi.createSigningProfileAsync,
    [SigningProfilesApi.deleteSigningProfileAsync.key]: SigningProfilesApi.deleteSigningProfileAsync,
    [SigningProfilesApi.getSigningProfileByIdAsync.key]: SigningProfilesApi.getSigningProfileByIdAsync,
    [SigningProfilesApi.getSigningProfilesAsync.key]: SigningProfilesApi.getSigningProfilesAsync,
    [SigningProfilesApi.getSigningProfilesCountAsync.key]: SigningProfilesApi.getSigningProfilesCountAsync,
    [SigningProfilesApi.patchSigningProfileAsync.key]: SigningProfilesApi.patchSigningProfileAsync,
    [SigningProfilesApi.updateSigningProfileAsync.key]: SigningProfilesApi.updateSigningProfileAsync,
    [SigningRequestsApi.addParticipantAsync.key]: SigningRequestsApi.addParticipantAsync,
    [SigningRequestsApi.createFromDocumentAsync.key]: SigningRequestsApi.createFromDocumentAsync,
    [SigningRequestsApi.executeProviderAsync.key]: SigningRequestsApi.executeProviderAsync,
    [SigningRequestsApi.expireAsync.key]: SigningRequestsApi.expireAsync,
    [SigningRequestsApi.finalizeAsync.key]: SigningRequestsApi.finalizeAsync,
    [SigningRequestsApi.getSigningRequestByIdAsync.key]: SigningRequestsApi.getSigningRequestByIdAsync,
    [SigningRequestsApi.getSigningRequestParticipantsAsync.key]: SigningRequestsApi.getSigningRequestParticipantsAsync,
    [SigningRequestsApi.getSigningRequestsAsync.key]: SigningRequestsApi.getSigningRequestsAsync,
    [SigningRequestsApi.getSigningRequestsCountAsync.key]: SigningRequestsApi.getSigningRequestsCountAsync,
    [SigningRequestsApi.prepareAndCreateAsync.key]: SigningRequestsApi.prepareAndCreateAsync,
    [SigningRequestsApi.sendAsync.key]: SigningRequestsApi.sendAsync,
    [SigningRequestsApi.voidAsync.key]: SigningRequestsApi.voidAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
