const AppraisalStagesApi = require('../apis/AppraisalStagesApi');
const AppraisalWorkflowsApi = require('../apis/AppraisalWorkflowsApi');
const CompletionsApi = require('../apis/CompletionsApi');
const EmployeeAppraisalSessionsApi = require('../apis/EmployeeAppraisalSessionsApi');
const EmployeeTypesApi = require('../apis/EmployeeTypesApi');
const EmployeesApi = require('../apis/EmployeesApi');
const EmployersApi = require('../apis/EmployersApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const GigsApi = require('../apis/GigsApi');
const JobOffersApi = require('../apis/JobOffersApi');
const JobTitlesApi = require('../apis/JobTitlesApi');
const LeaveApplicationsApi = require('../apis/LeaveApplicationsApi');
const LeaveTypesApi = require('../apis/LeaveTypesApi');
const PayrollPeriodsApi = require('../apis/PayrollPeriodsApi');
const PayrollsApi = require('../apis/PayrollsApi');
const SalariesApi = require('../apis/SalariesApi');
const SchedulesApi = require('../apis/SchedulesApi');
const ShiftsApi = require('../apis/ShiftsApi');
const TimeIntervalsApi = require('../apis/TimeIntervalsApi');
const TrainingProgramCoursesApi = require('../apis/TrainingProgramCoursesApi');
const TrainingProgramEventsApi = require('../apis/TrainingProgramEventsApi');
const TrainingProgramsApi = require('../apis/TrainingProgramsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [AppraisalStagesApi.createAppraisalStageAsync.key]: AppraisalStagesApi.createAppraisalStageAsync,
    [AppraisalStagesApi.deleteAppraisalStageAsync.key]: AppraisalStagesApi.deleteAppraisalStageAsync,
    [AppraisalStagesApi.getAppraisalStageByIdAsync.key]: AppraisalStagesApi.getAppraisalStageByIdAsync,
    [AppraisalStagesApi.getAppraisalStagesAsync.key]: AppraisalStagesApi.getAppraisalStagesAsync,
    [AppraisalStagesApi.getAppraisalStagesCountAsync.key]: AppraisalStagesApi.getAppraisalStagesCountAsync,
    [AppraisalStagesApi.updateAppraisalStageAsync.key]: AppraisalStagesApi.updateAppraisalStageAsync,
    [AppraisalWorkflowsApi.createAppraisalWorkflowAsync.key]: AppraisalWorkflowsApi.createAppraisalWorkflowAsync,
    [AppraisalWorkflowsApi.deleteAppraisalWorkflowAsync.key]: AppraisalWorkflowsApi.deleteAppraisalWorkflowAsync,
    [AppraisalWorkflowsApi.getAppraisalWorkflowByIdAsync.key]: AppraisalWorkflowsApi.getAppraisalWorkflowByIdAsync,
    [AppraisalWorkflowsApi.getAppraisalWorkflowsAsync.key]: AppraisalWorkflowsApi.getAppraisalWorkflowsAsync,
    [AppraisalWorkflowsApi.getAppraisalWorkflowsCountAsync.key]: AppraisalWorkflowsApi.getAppraisalWorkflowsCountAsync,
    [AppraisalWorkflowsApi.updateAppraisalWorkflowAsync.key]: AppraisalWorkflowsApi.updateAppraisalWorkflowAsync,
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [EmployeeAppraisalSessionsApi.createEmployeeAppraisalSessionAsync.key]: EmployeeAppraisalSessionsApi.createEmployeeAppraisalSessionAsync,
    [EmployeeAppraisalSessionsApi.deleteEmployeeAppraisalSessionAsync.key]: EmployeeAppraisalSessionsApi.deleteEmployeeAppraisalSessionAsync,
    [EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionByIdAsync.key]: EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionByIdAsync,
    [EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionsAsync.key]: EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionsAsync,
    [EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionsCountAsync.key]: EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionsCountAsync,
    [EmployeeAppraisalSessionsApi.patchEmployeeAppraisalSessionAsync.key]: EmployeeAppraisalSessionsApi.patchEmployeeAppraisalSessionAsync,
    [EmployeeAppraisalSessionsApi.updateEmployeeAppraisalSessionAsync.key]: EmployeeAppraisalSessionsApi.updateEmployeeAppraisalSessionAsync,
    [EmployeeTypesApi.createEmployeeTypeAsync.key]: EmployeeTypesApi.createEmployeeTypeAsync,
    [EmployeeTypesApi.deleteEmployeeTypeAsync.key]: EmployeeTypesApi.deleteEmployeeTypeAsync,
    [EmployeeTypesApi.getEmployeeTypeByIdAsync.key]: EmployeeTypesApi.getEmployeeTypeByIdAsync,
    [EmployeeTypesApi.getEmployeeTypesAsync.key]: EmployeeTypesApi.getEmployeeTypesAsync,
    [EmployeeTypesApi.getEmployeeTypesCountAsync.key]: EmployeeTypesApi.getEmployeeTypesCountAsync,
    [EmployeeTypesApi.patchEmployeeTypeAsync.key]: EmployeeTypesApi.patchEmployeeTypeAsync,
    [EmployeeTypesApi.updateEmployeeTypeAsync.key]: EmployeeTypesApi.updateEmployeeTypeAsync,
    [EmployeesApi.createEmployeeAsync.key]: EmployeesApi.createEmployeeAsync,
    [EmployeesApi.deleteEmployeeAsync.key]: EmployeesApi.deleteEmployeeAsync,
    [EmployeesApi.getEmployeeByIdAsync.key]: EmployeesApi.getEmployeeByIdAsync,
    [EmployeesApi.getEmployeesAsync.key]: EmployeesApi.getEmployeesAsync,
    [EmployeesApi.getEmployeesCountAsync.key]: EmployeesApi.getEmployeesCountAsync,
    [EmployeesApi.patchEmployeeAsync.key]: EmployeesApi.patchEmployeeAsync,
    [EmployeesApi.updateEmployeeAsync.key]: EmployeesApi.updateEmployeeAsync,
    [EmployersApi.createEmployerAsync.key]: EmployersApi.createEmployerAsync,
    [EmployersApi.deleteEmployerAsync.key]: EmployersApi.deleteEmployerAsync,
    [EmployersApi.getEmployerByIdAsync.key]: EmployersApi.getEmployerByIdAsync,
    [EmployersApi.getEmployersAsync.key]: EmployersApi.getEmployersAsync,
    [EmployersApi.getEmployersCountAsync.key]: EmployersApi.getEmployersCountAsync,
    [EmployersApi.patchEmployerAsync.key]: EmployersApi.patchEmployerAsync,
    [EmployersApi.updateEmployerAsync.key]: EmployersApi.updateEmployerAsync,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [GigsApi.createGigAsync.key]: GigsApi.createGigAsync,
    [GigsApi.deleteGigAsync.key]: GigsApi.deleteGigAsync,
    [GigsApi.getGigByIdAsync.key]: GigsApi.getGigByIdAsync,
    [GigsApi.getGigsAsync.key]: GigsApi.getGigsAsync,
    [GigsApi.getGigsCountAsync.key]: GigsApi.getGigsCountAsync,
    [GigsApi.patchGigAsync.key]: GigsApi.patchGigAsync,
    [GigsApi.updateGigAsync.key]: GigsApi.updateGigAsync,
    [JobOffersApi.createJobOfferAsync.key]: JobOffersApi.createJobOfferAsync,
    [JobOffersApi.deleteJobOfferAsync.key]: JobOffersApi.deleteJobOfferAsync,
    [JobOffersApi.getJobOfferByIdAsync.key]: JobOffersApi.getJobOfferByIdAsync,
    [JobOffersApi.getJobOffersAsync.key]: JobOffersApi.getJobOffersAsync,
    [JobOffersApi.getJobOffersCountAsync.key]: JobOffersApi.getJobOffersCountAsync,
    [JobOffersApi.patchJobOfferAsync.key]: JobOffersApi.patchJobOfferAsync,
    [JobOffersApi.updateJobOfferAsync.key]: JobOffersApi.updateJobOfferAsync,
    [JobTitlesApi.createJobTitleAsync.key]: JobTitlesApi.createJobTitleAsync,
    [JobTitlesApi.deleteJobTitleAsync.key]: JobTitlesApi.deleteJobTitleAsync,
    [JobTitlesApi.getJobTitleByIdAsync.key]: JobTitlesApi.getJobTitleByIdAsync,
    [JobTitlesApi.getJobTitlesAsync.key]: JobTitlesApi.getJobTitlesAsync,
    [JobTitlesApi.getJobTitlesCountAsync.key]: JobTitlesApi.getJobTitlesCountAsync,
    [JobTitlesApi.patchJobTitleAsync.key]: JobTitlesApi.patchJobTitleAsync,
    [JobTitlesApi.updateJobTitleAsync.key]: JobTitlesApi.updateJobTitleAsync,
    [LeaveApplicationsApi.createLeaveApplicationAsync.key]: LeaveApplicationsApi.createLeaveApplicationAsync,
    [LeaveApplicationsApi.deleteLeaveApplicationAsync.key]: LeaveApplicationsApi.deleteLeaveApplicationAsync,
    [LeaveApplicationsApi.getLeaveApplicationByIdAsync.key]: LeaveApplicationsApi.getLeaveApplicationByIdAsync,
    [LeaveApplicationsApi.getLeaveApplicationsAsync.key]: LeaveApplicationsApi.getLeaveApplicationsAsync,
    [LeaveApplicationsApi.getLeaveApplicationsCountAsync.key]: LeaveApplicationsApi.getLeaveApplicationsCountAsync,
    [LeaveApplicationsApi.patchLeaveApplicationAsync.key]: LeaveApplicationsApi.patchLeaveApplicationAsync,
    [LeaveApplicationsApi.updateLeaveApplicationAsync.key]: LeaveApplicationsApi.updateLeaveApplicationAsync,
    [LeaveTypesApi.createLeaveTypeAsync.key]: LeaveTypesApi.createLeaveTypeAsync,
    [LeaveTypesApi.deleteLeaveTypeAsync.key]: LeaveTypesApi.deleteLeaveTypeAsync,
    [LeaveTypesApi.getLeaveTypeByIdAsync.key]: LeaveTypesApi.getLeaveTypeByIdAsync,
    [LeaveTypesApi.getLeaveTypesAsync.key]: LeaveTypesApi.getLeaveTypesAsync,
    [LeaveTypesApi.getLeaveTypesCountAsync.key]: LeaveTypesApi.getLeaveTypesCountAsync,
    [LeaveTypesApi.updateLeaveTypeAsync.key]: LeaveTypesApi.updateLeaveTypeAsync,
    [PayrollPeriodsApi.createPayrollPeriodAsync.key]: PayrollPeriodsApi.createPayrollPeriodAsync,
    [PayrollPeriodsApi.deletePayrollPeriodAsync.key]: PayrollPeriodsApi.deletePayrollPeriodAsync,
    [PayrollPeriodsApi.getPayrollPeriodByIdAsync.key]: PayrollPeriodsApi.getPayrollPeriodByIdAsync,
    [PayrollPeriodsApi.getPayrollPeriodsAsync.key]: PayrollPeriodsApi.getPayrollPeriodsAsync,
    [PayrollPeriodsApi.getPayrollPeriodsCountAsync.key]: PayrollPeriodsApi.getPayrollPeriodsCountAsync,
    [PayrollPeriodsApi.updatePayrollPeriodAsync.key]: PayrollPeriodsApi.updatePayrollPeriodAsync,
    [PayrollsApi.createPayrollAsync.key]: PayrollsApi.createPayrollAsync,
    [PayrollsApi.deletePayrollAsync.key]: PayrollsApi.deletePayrollAsync,
    [PayrollsApi.getPayrollByIdAsync.key]: PayrollsApi.getPayrollByIdAsync,
    [PayrollsApi.getPayrollsAsync.key]: PayrollsApi.getPayrollsAsync,
    [PayrollsApi.getPayrollsCountAsync.key]: PayrollsApi.getPayrollsCountAsync,
    [PayrollsApi.patchPayrollAsync.key]: PayrollsApi.patchPayrollAsync,
    [PayrollsApi.updatePayrollAsync.key]: PayrollsApi.updatePayrollAsync,
    [SalariesApi.createSalaryAsync.key]: SalariesApi.createSalaryAsync,
    [SalariesApi.deleteSalaryAsync.key]: SalariesApi.deleteSalaryAsync,
    [SalariesApi.getSalariesAsync.key]: SalariesApi.getSalariesAsync,
    [SalariesApi.getSalariesCountAsync.key]: SalariesApi.getSalariesCountAsync,
    [SalariesApi.getSalaryByIdAsync.key]: SalariesApi.getSalaryByIdAsync,
    [SalariesApi.patchSalaryAsync.key]: SalariesApi.patchSalaryAsync,
    [SalariesApi.updateSalaryAsync.key]: SalariesApi.updateSalaryAsync,
    [SchedulesApi.createScheduleAsync.key]: SchedulesApi.createScheduleAsync,
    [SchedulesApi.deleteScheduleAsync.key]: SchedulesApi.deleteScheduleAsync,
    [SchedulesApi.getScheduleByIdAsync.key]: SchedulesApi.getScheduleByIdAsync,
    [SchedulesApi.getSchedulesAsync.key]: SchedulesApi.getSchedulesAsync,
    [SchedulesApi.getSchedulesCountAsync.key]: SchedulesApi.getSchedulesCountAsync,
    [SchedulesApi.patchScheduleAsync.key]: SchedulesApi.patchScheduleAsync,
    [SchedulesApi.updateScheduleAsync.key]: SchedulesApi.updateScheduleAsync,
    [ShiftsApi.createShiftAsync.key]: ShiftsApi.createShiftAsync,
    [ShiftsApi.deleteShiftAsync.key]: ShiftsApi.deleteShiftAsync,
    [ShiftsApi.getShiftByIdAsync.key]: ShiftsApi.getShiftByIdAsync,
    [ShiftsApi.getShiftsAsync.key]: ShiftsApi.getShiftsAsync,
    [ShiftsApi.getShiftsCountAsync.key]: ShiftsApi.getShiftsCountAsync,
    [ShiftsApi.patchShiftAsync.key]: ShiftsApi.patchShiftAsync,
    [ShiftsApi.updateShiftAsync.key]: ShiftsApi.updateShiftAsync,
    [TimeIntervalsApi.createTimeIntervalAsync.key]: TimeIntervalsApi.createTimeIntervalAsync,
    [TimeIntervalsApi.deleteTimeIntervalAsync.key]: TimeIntervalsApi.deleteTimeIntervalAsync,
    [TimeIntervalsApi.getTimeIntervalByIdAsync.key]: TimeIntervalsApi.getTimeIntervalByIdAsync,
    [TimeIntervalsApi.getTimeIntervalsAsync.key]: TimeIntervalsApi.getTimeIntervalsAsync,
    [TimeIntervalsApi.getTimeIntervalsCountAsync.key]: TimeIntervalsApi.getTimeIntervalsCountAsync,
    [TimeIntervalsApi.patchTimeIntervalAsync.key]: TimeIntervalsApi.patchTimeIntervalAsync,
    [TimeIntervalsApi.updateTimeIntervalAsync.key]: TimeIntervalsApi.updateTimeIntervalAsync,
    [TrainingProgramCoursesApi.createTrainingProgramCourseAsync.key]: TrainingProgramCoursesApi.createTrainingProgramCourseAsync,
    [TrainingProgramCoursesApi.deleteTrainingProgramCourseAsync.key]: TrainingProgramCoursesApi.deleteTrainingProgramCourseAsync,
    [TrainingProgramCoursesApi.getTrainingProgramCourseByIdAsync.key]: TrainingProgramCoursesApi.getTrainingProgramCourseByIdAsync,
    [TrainingProgramCoursesApi.getTrainingProgramCoursesAsync.key]: TrainingProgramCoursesApi.getTrainingProgramCoursesAsync,
    [TrainingProgramCoursesApi.getTrainingProgramCoursesCountAsync.key]: TrainingProgramCoursesApi.getTrainingProgramCoursesCountAsync,
    [TrainingProgramCoursesApi.patchTrainingProgramCourseAsync.key]: TrainingProgramCoursesApi.patchTrainingProgramCourseAsync,
    [TrainingProgramCoursesApi.updateTrainingProgramCourseAsync.key]: TrainingProgramCoursesApi.updateTrainingProgramCourseAsync,
    [TrainingProgramEventsApi.createTrainingProgramEventAsync.key]: TrainingProgramEventsApi.createTrainingProgramEventAsync,
    [TrainingProgramEventsApi.deleteTrainingProgramEventAsync.key]: TrainingProgramEventsApi.deleteTrainingProgramEventAsync,
    [TrainingProgramEventsApi.getTrainingProgramEventByIdAsync.key]: TrainingProgramEventsApi.getTrainingProgramEventByIdAsync,
    [TrainingProgramEventsApi.getTrainingProgramEventsAsync.key]: TrainingProgramEventsApi.getTrainingProgramEventsAsync,
    [TrainingProgramEventsApi.getTrainingProgramEventsCountAsync.key]: TrainingProgramEventsApi.getTrainingProgramEventsCountAsync,
    [TrainingProgramEventsApi.patchTrainingProgramEventAsync.key]: TrainingProgramEventsApi.patchTrainingProgramEventAsync,
    [TrainingProgramEventsApi.updateTrainingProgramEventAsync.key]: TrainingProgramEventsApi.updateTrainingProgramEventAsync,
    [TrainingProgramsApi.createTrainingProgramAsync.key]: TrainingProgramsApi.createTrainingProgramAsync,
    [TrainingProgramsApi.deleteTrainingProgramAsync.key]: TrainingProgramsApi.deleteTrainingProgramAsync,
    [TrainingProgramsApi.getTrainingProgramByIdAsync.key]: TrainingProgramsApi.getTrainingProgramByIdAsync,
    [TrainingProgramsApi.getTrainingProgramsAsync.key]: TrainingProgramsApi.getTrainingProgramsAsync,
    [TrainingProgramsApi.getTrainingProgramsCountAsync.key]: TrainingProgramsApi.getTrainingProgramsCountAsync,
    [TrainingProgramsApi.updateTrainingProgramAsync.key]: TrainingProgramsApi.updateTrainingProgramAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
