const AppraisalStagesApi = require('../apis/AppraisalStagesApi');
const AppraisalWorkflowsApi = require('../apis/AppraisalWorkflowsApi');
const EmployeeAppraisalSessionsApi = require('../apis/EmployeeAppraisalSessionsApi');
const EmployeeTypesApi = require('../apis/EmployeeTypesApi');
const EmployeesApi = require('../apis/EmployeesApi');
const EmployersApi = require('../apis/EmployersApi');
const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const GigApplicationsApi = require('../apis/GigApplicationsApi');
const GigsApi = require('../apis/GigsApi');
const JobApplicantsApi = require('../apis/JobApplicantsApi');
const JobApplicationsApi = require('../apis/JobApplicationsApi');
const JobFieldsApi = require('../apis/JobFieldsApi');
const JobOfferFieldsApi = require('../apis/JobOfferFieldsApi');
const JobOffersApi = require('../apis/JobOffersApi');
const JobTitlesApi = require('../apis/JobTitlesApi');
const LeaveApplicationsApi = require('../apis/LeaveApplicationsApi');
const LeaveTypesApi = require('../apis/LeaveTypesApi');
const PayrollPeriodsApi = require('../apis/PayrollPeriodsApi');
const PayrollsApi = require('../apis/PayrollsApi');
const RequiredSkillsApi = require('../apis/RequiredSkillsApi');
const SalariesApi = require('../apis/SalariesApi');
const SchedulesApi = require('../apis/SchedulesApi');
const ShiftsApi = require('../apis/ShiftsApi');
const TimeIntervalsApi = require('../apis/TimeIntervalsApi');
const TrainingProgramCoursesApi = require('../apis/TrainingProgramCoursesApi');
const TrainingProgramEventsApi = require('../apis/TrainingProgramEventsApi');
const TrainingProgramsApi = require('../apis/TrainingProgramsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [AppraisalStagesApi.createAppraisalStageAsync.key]: AppraisalStagesApi.createAppraisalStageAsync,
    [AppraisalStagesApi.deleteAppraisalStageAsync.key]: AppraisalStagesApi.deleteAppraisalStageAsync,
    [AppraisalStagesApi.getAppraisalStageByIdAsync.key]: AppraisalStagesApi.getAppraisalStageByIdAsync,
    [AppraisalStagesApi.getAppraisalStagesAsync.key]: AppraisalStagesApi.getAppraisalStagesAsync,
    [AppraisalStagesApi.getAppraisalStagesCountAsync.key]: AppraisalStagesApi.getAppraisalStagesCountAsync,
    [AppraisalStagesApi.updateAppraisalStageAsync.key]: AppraisalStagesApi.updateAppraisalStageAsync,
    [AppraisalWorkflowsApi.createAppraisalWorkflowAsync.key]: AppraisalWorkflowsApi.createAppraisalWorkflowAsync,
    [AppraisalWorkflowsApi.deleteAppraisalWorkflowAsync.key]: AppraisalWorkflowsApi.deleteAppraisalWorkflowAsync,
    [AppraisalWorkflowsApi.getAppraisalWorkflowByIdAsync.key]: AppraisalWorkflowsApi.getAppraisalWorkflowByIdAsync,
    [AppraisalWorkflowsApi.getAppraisalWorkflowsAsync.key]: AppraisalWorkflowsApi.getAppraisalWorkflowsAsync,
    [AppraisalWorkflowsApi.getAppraisalWorkflowsCountAsync.key]: AppraisalWorkflowsApi.getAppraisalWorkflowsCountAsync,
    [AppraisalWorkflowsApi.updateAppraisalWorkflowAsync.key]: AppraisalWorkflowsApi.updateAppraisalWorkflowAsync,
    [EmployeeAppraisalSessionsApi.createEmployeeAppraisalSessionAsync.key]: EmployeeAppraisalSessionsApi.createEmployeeAppraisalSessionAsync,
    [EmployeeAppraisalSessionsApi.deleteEmployeeAppraisalSessionAsync.key]: EmployeeAppraisalSessionsApi.deleteEmployeeAppraisalSessionAsync,
    [EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionByIdAsync.key]: EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionByIdAsync,
    [EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionsAsync.key]: EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionsAsync,
    [EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionsCountAsync.key]: EmployeeAppraisalSessionsApi.getEmployeeAppraisalSessionsCountAsync,
    [EmployeeAppraisalSessionsApi.patchEmployeeAppraisalSessionAsync.key]: EmployeeAppraisalSessionsApi.patchEmployeeAppraisalSessionAsync,
    [EmployeeAppraisalSessionsApi.updateEmployeeAppraisalSessionAsync.key]: EmployeeAppraisalSessionsApi.updateEmployeeAppraisalSessionAsync,
    [EmployeeTypesApi.createEmployeeTypeAsync.key]: EmployeeTypesApi.createEmployeeTypeAsync,
    [EmployeeTypesApi.deleteEmployeeTypeAsync.key]: EmployeeTypesApi.deleteEmployeeTypeAsync,
    [EmployeeTypesApi.getEmployeeTypeByIdAsync.key]: EmployeeTypesApi.getEmployeeTypeByIdAsync,
    [EmployeeTypesApi.getEmployeeTypesAsync.key]: EmployeeTypesApi.getEmployeeTypesAsync,
    [EmployeeTypesApi.getEmployeeTypesCountAsync.key]: EmployeeTypesApi.getEmployeeTypesCountAsync,
    [EmployeeTypesApi.patchEmployeeTypeAsync.key]: EmployeeTypesApi.patchEmployeeTypeAsync,
    [EmployeeTypesApi.updateEmployeeTypeAsync.key]: EmployeeTypesApi.updateEmployeeTypeAsync,
    [EmployeesApi.createEmployeeAsync.key]: EmployeesApi.createEmployeeAsync,
    [EmployeesApi.deleteEmployeeAsync.key]: EmployeesApi.deleteEmployeeAsync,
    [EmployeesApi.getEmployeeByIdAsync.key]: EmployeesApi.getEmployeeByIdAsync,
    [EmployeesApi.getEmployeesAsync.key]: EmployeesApi.getEmployeesAsync,
    [EmployeesApi.getEmployeesCountAsync.key]: EmployeesApi.getEmployeesCountAsync,
    [EmployeesApi.patchEmployeeAsync.key]: EmployeesApi.patchEmployeeAsync,
    [EmployeesApi.updateEmployeeAsync.key]: EmployeesApi.updateEmployeeAsync,
    [EmployersApi.createEmployerAsync.key]: EmployersApi.createEmployerAsync,
    [EmployersApi.deleteEmployerAsync.key]: EmployersApi.deleteEmployerAsync,
    [EmployersApi.getEmployerByIdAsync.key]: EmployersApi.getEmployerByIdAsync,
    [EmployersApi.getEmployersAsync.key]: EmployersApi.getEmployersAsync,
    [EmployersApi.getEmployersCountAsync.key]: EmployersApi.getEmployersCountAsync,
    [EmployersApi.patchEmployerAsync.key]: EmployersApi.patchEmployerAsync,
    [EmployersApi.updateEmployerAsync.key]: EmployersApi.updateEmployerAsync,
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [GigApplicationsApi.acceptGigApplicationAsync.key]: GigApplicationsApi.acceptGigApplicationAsync,
    [GigApplicationsApi.createGigApplicationAsync.key]: GigApplicationsApi.createGigApplicationAsync,
    [GigApplicationsApi.deleteGigApplicationAsync.key]: GigApplicationsApi.deleteGigApplicationAsync,
    [GigApplicationsApi.getGigApplicationByIdAsync.key]: GigApplicationsApi.getGigApplicationByIdAsync,
    [GigApplicationsApi.getGigApplicationsAsync.key]: GigApplicationsApi.getGigApplicationsAsync,
    [GigApplicationsApi.getGigApplicationsCountAsync.key]: GigApplicationsApi.getGigApplicationsCountAsync,
    [GigApplicationsApi.patchGigApplicationAsync.key]: GigApplicationsApi.patchGigApplicationAsync,
    [GigApplicationsApi.updateGigApplicationAsync.key]: GigApplicationsApi.updateGigApplicationAsync,
    [GigsApi.createGigAsync.key]: GigsApi.createGigAsync,
    [GigsApi.deleteGigAsync.key]: GigsApi.deleteGigAsync,
    [GigsApi.getGigByIdAsync.key]: GigsApi.getGigByIdAsync,
    [GigsApi.getGigsAsync.key]: GigsApi.getGigsAsync,
    [GigsApi.getGigsCountAsync.key]: GigsApi.getGigsCountAsync,
    [GigsApi.patchGigAsync.key]: GigsApi.patchGigAsync,
    [GigsApi.updateGigAsync.key]: GigsApi.updateGigAsync,
    [JobApplicantsApi.createJobApplicantAsync.key]: JobApplicantsApi.createJobApplicantAsync,
    [JobApplicantsApi.deleteJobApplicantAsync.key]: JobApplicantsApi.deleteJobApplicantAsync,
    [JobApplicantsApi.getJobApplicantByIdAsync.key]: JobApplicantsApi.getJobApplicantByIdAsync,
    [JobApplicantsApi.getJobApplicantsAsync.key]: JobApplicantsApi.getJobApplicantsAsync,
    [JobApplicantsApi.getJobApplicantsCountAsync.key]: JobApplicantsApi.getJobApplicantsCountAsync,
    [JobApplicantsApi.patchJobApplicantAsync.key]: JobApplicantsApi.patchJobApplicantAsync,
    [JobApplicantsApi.updateJobApplicantAsync.key]: JobApplicantsApi.updateJobApplicantAsync,
    [JobApplicationsApi.changeJobApplicationStatusAsync.key]: JobApplicationsApi.changeJobApplicationStatusAsync,
    [JobApplicationsApi.createJobApplicationAsync.key]: JobApplicationsApi.createJobApplicationAsync,
    [JobApplicationsApi.deleteJobApplicationAsync.key]: JobApplicationsApi.deleteJobApplicationAsync,
    [JobApplicationsApi.getJobApplicationByIdAsync.key]: JobApplicationsApi.getJobApplicationByIdAsync,
    [JobApplicationsApi.getJobApplicationsAsync.key]: JobApplicationsApi.getJobApplicationsAsync,
    [JobApplicationsApi.getJobApplicationsCountAsync.key]: JobApplicationsApi.getJobApplicationsCountAsync,
    [JobApplicationsApi.patchJobApplicationAsync.key]: JobApplicationsApi.patchJobApplicationAsync,
    [JobApplicationsApi.updateJobApplicationAsync.key]: JobApplicationsApi.updateJobApplicationAsync,
    [JobFieldsApi.createJobFieldAsync.key]: JobFieldsApi.createJobFieldAsync,
    [JobFieldsApi.deleteJobFieldAsync.key]: JobFieldsApi.deleteJobFieldAsync,
    [JobFieldsApi.getJobFieldByIdAsync.key]: JobFieldsApi.getJobFieldByIdAsync,
    [JobFieldsApi.getJobFieldsAsync.key]: JobFieldsApi.getJobFieldsAsync,
    [JobFieldsApi.getJobFieldsCountAsync.key]: JobFieldsApi.getJobFieldsCountAsync,
    [JobFieldsApi.patchJobFieldAsync.key]: JobFieldsApi.patchJobFieldAsync,
    [JobFieldsApi.updateJobFieldAsync.key]: JobFieldsApi.updateJobFieldAsync,
    [JobOfferFieldsApi.createJobOfferFieldAsync.key]: JobOfferFieldsApi.createJobOfferFieldAsync,
    [JobOfferFieldsApi.deleteJobOfferFieldAsync.key]: JobOfferFieldsApi.deleteJobOfferFieldAsync,
    [JobOfferFieldsApi.getJobOfferFieldByIdAsync.key]: JobOfferFieldsApi.getJobOfferFieldByIdAsync,
    [JobOfferFieldsApi.getJobOfferFieldsAsync.key]: JobOfferFieldsApi.getJobOfferFieldsAsync,
    [JobOfferFieldsApi.getJobOfferFieldsCountAsync.key]: JobOfferFieldsApi.getJobOfferFieldsCountAsync,
    [JobOfferFieldsApi.patchJobOfferFieldAsync.key]: JobOfferFieldsApi.patchJobOfferFieldAsync,
    [JobOfferFieldsApi.updateJobOfferFieldAsync.key]: JobOfferFieldsApi.updateJobOfferFieldAsync,
    [JobOffersApi.closeJobOfferAsync.key]: JobOffersApi.closeJobOfferAsync,
    [JobOffersApi.createJobOfferAsync.key]: JobOffersApi.createJobOfferAsync,
    [JobOffersApi.deleteJobOfferAsync.key]: JobOffersApi.deleteJobOfferAsync,
    [JobOffersApi.fillJobOfferAsync.key]: JobOffersApi.fillJobOfferAsync,
    [JobOffersApi.getJobOfferByIdAsync.key]: JobOffersApi.getJobOfferByIdAsync,
    [JobOffersApi.getJobOffersAsync.key]: JobOffersApi.getJobOffersAsync,
    [JobOffersApi.getJobOffersCountAsync.key]: JobOffersApi.getJobOffersCountAsync,
    [JobOffersApi.getPublicJobOfferByIdAsync.key]: JobOffersApi.getPublicJobOfferByIdAsync,
    [JobOffersApi.getPublicJobOffersAsync.key]: JobOffersApi.getPublicJobOffersAsync,
    [JobOffersApi.getPublicJobOffersCountAsync.key]: JobOffersApi.getPublicJobOffersCountAsync,
    [JobOffersApi.patchJobOfferAsync.key]: JobOffersApi.patchJobOfferAsync,
    [JobOffersApi.publishJobOfferAsync.key]: JobOffersApi.publishJobOfferAsync,
    [JobOffersApi.updateJobOfferAsync.key]: JobOffersApi.updateJobOfferAsync,
    [JobTitlesApi.createJobTitleAsync.key]: JobTitlesApi.createJobTitleAsync,
    [JobTitlesApi.deleteJobTitleAsync.key]: JobTitlesApi.deleteJobTitleAsync,
    [JobTitlesApi.getJobTitleByIdAsync.key]: JobTitlesApi.getJobTitleByIdAsync,
    [JobTitlesApi.getJobTitlesAsync.key]: JobTitlesApi.getJobTitlesAsync,
    [JobTitlesApi.getJobTitlesCountAsync.key]: JobTitlesApi.getJobTitlesCountAsync,
    [JobTitlesApi.patchJobTitleAsync.key]: JobTitlesApi.patchJobTitleAsync,
    [JobTitlesApi.updateJobTitleAsync.key]: JobTitlesApi.updateJobTitleAsync,
    [LeaveApplicationsApi.createLeaveApplicationAsync.key]: LeaveApplicationsApi.createLeaveApplicationAsync,
    [LeaveApplicationsApi.deleteLeaveApplicationAsync.key]: LeaveApplicationsApi.deleteLeaveApplicationAsync,
    [LeaveApplicationsApi.getLeaveApplicationByIdAsync.key]: LeaveApplicationsApi.getLeaveApplicationByIdAsync,
    [LeaveApplicationsApi.getLeaveApplicationsAsync.key]: LeaveApplicationsApi.getLeaveApplicationsAsync,
    [LeaveApplicationsApi.getLeaveApplicationsCountAsync.key]: LeaveApplicationsApi.getLeaveApplicationsCountAsync,
    [LeaveApplicationsApi.patchLeaveApplicationAsync.key]: LeaveApplicationsApi.patchLeaveApplicationAsync,
    [LeaveApplicationsApi.updateLeaveApplicationAsync.key]: LeaveApplicationsApi.updateLeaveApplicationAsync,
    [LeaveTypesApi.createLeaveTypeAsync.key]: LeaveTypesApi.createLeaveTypeAsync,
    [LeaveTypesApi.deleteLeaveTypeAsync.key]: LeaveTypesApi.deleteLeaveTypeAsync,
    [LeaveTypesApi.getLeaveTypeByIdAsync.key]: LeaveTypesApi.getLeaveTypeByIdAsync,
    [LeaveTypesApi.getLeaveTypesAsync.key]: LeaveTypesApi.getLeaveTypesAsync,
    [LeaveTypesApi.getLeaveTypesCountAsync.key]: LeaveTypesApi.getLeaveTypesCountAsync,
    [LeaveTypesApi.updateLeaveTypeAsync.key]: LeaveTypesApi.updateLeaveTypeAsync,
    [PayrollPeriodsApi.createPayrollPeriodAsync.key]: PayrollPeriodsApi.createPayrollPeriodAsync,
    [PayrollPeriodsApi.deletePayrollPeriodAsync.key]: PayrollPeriodsApi.deletePayrollPeriodAsync,
    [PayrollPeriodsApi.getPayrollPeriodByIdAsync.key]: PayrollPeriodsApi.getPayrollPeriodByIdAsync,
    [PayrollPeriodsApi.getPayrollPeriodsAsync.key]: PayrollPeriodsApi.getPayrollPeriodsAsync,
    [PayrollPeriodsApi.getPayrollPeriodsCountAsync.key]: PayrollPeriodsApi.getPayrollPeriodsCountAsync,
    [PayrollPeriodsApi.updatePayrollPeriodAsync.key]: PayrollPeriodsApi.updatePayrollPeriodAsync,
    [PayrollsApi.createPayrollAsync.key]: PayrollsApi.createPayrollAsync,
    [PayrollsApi.deletePayrollAsync.key]: PayrollsApi.deletePayrollAsync,
    [PayrollsApi.getPayrollByIdAsync.key]: PayrollsApi.getPayrollByIdAsync,
    [PayrollsApi.getPayrollsAsync.key]: PayrollsApi.getPayrollsAsync,
    [PayrollsApi.getPayrollsCountAsync.key]: PayrollsApi.getPayrollsCountAsync,
    [PayrollsApi.patchPayrollAsync.key]: PayrollsApi.patchPayrollAsync,
    [PayrollsApi.updatePayrollAsync.key]: PayrollsApi.updatePayrollAsync,
    [RequiredSkillsApi.createRequiredSkillAsync.key]: RequiredSkillsApi.createRequiredSkillAsync,
    [RequiredSkillsApi.deleteRequiredSkillAsync.key]: RequiredSkillsApi.deleteRequiredSkillAsync,
    [RequiredSkillsApi.getRequiredSkillByIdAsync.key]: RequiredSkillsApi.getRequiredSkillByIdAsync,
    [RequiredSkillsApi.getRequiredSkillsAsync.key]: RequiredSkillsApi.getRequiredSkillsAsync,
    [RequiredSkillsApi.getRequiredSkillsCountAsync.key]: RequiredSkillsApi.getRequiredSkillsCountAsync,
    [RequiredSkillsApi.patchRequiredSkillAsync.key]: RequiredSkillsApi.patchRequiredSkillAsync,
    [RequiredSkillsApi.updateRequiredSkillAsync.key]: RequiredSkillsApi.updateRequiredSkillAsync,
    [SalariesApi.createSalaryAsync.key]: SalariesApi.createSalaryAsync,
    [SalariesApi.deleteSalaryAsync.key]: SalariesApi.deleteSalaryAsync,
    [SalariesApi.getSalariesAsync.key]: SalariesApi.getSalariesAsync,
    [SalariesApi.getSalariesCountAsync.key]: SalariesApi.getSalariesCountAsync,
    [SalariesApi.getSalaryByIdAsync.key]: SalariesApi.getSalaryByIdAsync,
    [SalariesApi.patchSalaryAsync.key]: SalariesApi.patchSalaryAsync,
    [SalariesApi.updateSalaryAsync.key]: SalariesApi.updateSalaryAsync,
    [SchedulesApi.createScheduleAsync.key]: SchedulesApi.createScheduleAsync,
    [SchedulesApi.deleteScheduleAsync.key]: SchedulesApi.deleteScheduleAsync,
    [SchedulesApi.getScheduleByIdAsync.key]: SchedulesApi.getScheduleByIdAsync,
    [SchedulesApi.getSchedulesAsync.key]: SchedulesApi.getSchedulesAsync,
    [SchedulesApi.getSchedulesCountAsync.key]: SchedulesApi.getSchedulesCountAsync,
    [SchedulesApi.patchScheduleAsync.key]: SchedulesApi.patchScheduleAsync,
    [SchedulesApi.updateScheduleAsync.key]: SchedulesApi.updateScheduleAsync,
    [ShiftsApi.createShiftAsync.key]: ShiftsApi.createShiftAsync,
    [ShiftsApi.deleteShiftAsync.key]: ShiftsApi.deleteShiftAsync,
    [ShiftsApi.getShiftByIdAsync.key]: ShiftsApi.getShiftByIdAsync,
    [ShiftsApi.getShiftsAsync.key]: ShiftsApi.getShiftsAsync,
    [ShiftsApi.getShiftsCountAsync.key]: ShiftsApi.getShiftsCountAsync,
    [ShiftsApi.patchShiftAsync.key]: ShiftsApi.patchShiftAsync,
    [ShiftsApi.updateShiftAsync.key]: ShiftsApi.updateShiftAsync,
    [TimeIntervalsApi.createTimeIntervalAsync.key]: TimeIntervalsApi.createTimeIntervalAsync,
    [TimeIntervalsApi.deleteTimeIntervalAsync.key]: TimeIntervalsApi.deleteTimeIntervalAsync,
    [TimeIntervalsApi.getTimeIntervalByIdAsync.key]: TimeIntervalsApi.getTimeIntervalByIdAsync,
    [TimeIntervalsApi.getTimeIntervalsAsync.key]: TimeIntervalsApi.getTimeIntervalsAsync,
    [TimeIntervalsApi.getTimeIntervalsCountAsync.key]: TimeIntervalsApi.getTimeIntervalsCountAsync,
    [TimeIntervalsApi.patchTimeIntervalAsync.key]: TimeIntervalsApi.patchTimeIntervalAsync,
    [TimeIntervalsApi.updateTimeIntervalAsync.key]: TimeIntervalsApi.updateTimeIntervalAsync,
    [TrainingProgramCoursesApi.createTrainingProgramCourseAsync.key]: TrainingProgramCoursesApi.createTrainingProgramCourseAsync,
    [TrainingProgramCoursesApi.deleteTrainingProgramCourseAsync.key]: TrainingProgramCoursesApi.deleteTrainingProgramCourseAsync,
    [TrainingProgramCoursesApi.getTrainingProgramCourseByIdAsync.key]: TrainingProgramCoursesApi.getTrainingProgramCourseByIdAsync,
    [TrainingProgramCoursesApi.getTrainingProgramCoursesAsync.key]: TrainingProgramCoursesApi.getTrainingProgramCoursesAsync,
    [TrainingProgramCoursesApi.getTrainingProgramCoursesCountAsync.key]: TrainingProgramCoursesApi.getTrainingProgramCoursesCountAsync,
    [TrainingProgramCoursesApi.patchTrainingProgramCourseAsync.key]: TrainingProgramCoursesApi.patchTrainingProgramCourseAsync,
    [TrainingProgramCoursesApi.updateTrainingProgramCourseAsync.key]: TrainingProgramCoursesApi.updateTrainingProgramCourseAsync,
    [TrainingProgramEventsApi.createTrainingProgramEventAsync.key]: TrainingProgramEventsApi.createTrainingProgramEventAsync,
    [TrainingProgramEventsApi.deleteTrainingProgramEventAsync.key]: TrainingProgramEventsApi.deleteTrainingProgramEventAsync,
    [TrainingProgramEventsApi.getTrainingProgramEventByIdAsync.key]: TrainingProgramEventsApi.getTrainingProgramEventByIdAsync,
    [TrainingProgramEventsApi.getTrainingProgramEventsAsync.key]: TrainingProgramEventsApi.getTrainingProgramEventsAsync,
    [TrainingProgramEventsApi.getTrainingProgramEventsCountAsync.key]: TrainingProgramEventsApi.getTrainingProgramEventsCountAsync,
    [TrainingProgramEventsApi.patchTrainingProgramEventAsync.key]: TrainingProgramEventsApi.patchTrainingProgramEventAsync,
    [TrainingProgramEventsApi.updateTrainingProgramEventAsync.key]: TrainingProgramEventsApi.updateTrainingProgramEventAsync,
    [TrainingProgramsApi.createTrainingProgramAsync.key]: TrainingProgramsApi.createTrainingProgramAsync,
    [TrainingProgramsApi.deleteTrainingProgramAsync.key]: TrainingProgramsApi.deleteTrainingProgramAsync,
    [TrainingProgramsApi.getTrainingProgramByIdAsync.key]: TrainingProgramsApi.getTrainingProgramByIdAsync,
    [TrainingProgramsApi.getTrainingProgramsAsync.key]: TrainingProgramsApi.getTrainingProgramsAsync,
    [TrainingProgramsApi.getTrainingProgramsCountAsync.key]: TrainingProgramsApi.getTrainingProgramsCountAsync,
    [TrainingProgramsApi.updateTrainingProgramAsync.key]: TrainingProgramsApi.updateTrainingProgramAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
