const BillsOfLadingApi = require('../apis/BillsOfLadingApi');
const CompletionsApi = require('../apis/CompletionsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const ItemShippingPoliciesApi = require('../apis/ItemShippingPoliciesApi');
const ShipmentsApi = require('../apis/ShipmentsApi');
const ShippingClassesApi = require('../apis/ShippingClassesApi');
const ShippingCouriersApi = require('../apis/ShippingCouriersApi');
const ShippingLabelsApi = require('../apis/ShippingLabelsApi');
const ShippingMethodsApi = require('../apis/ShippingMethodsApi');
const ShippingRegionsApi = require('../apis/ShippingRegionsApi');
const ShippingZonesApi = require('../apis/ShippingZonesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [BillsOfLadingApi.createBillOfLadingAsync.key]: BillsOfLadingApi.createBillOfLadingAsync,
    [BillsOfLadingApi.createBillOfLadingLineAsync.key]: BillsOfLadingApi.createBillOfLadingLineAsync,
    [BillsOfLadingApi.deleteBillOfLadingAsync.key]: BillsOfLadingApi.deleteBillOfLadingAsync,
    [BillsOfLadingApi.deleteBillOfLadingLineAsync.key]: BillsOfLadingApi.deleteBillOfLadingLineAsync,
    [BillsOfLadingApi.getBillOfLadingByIdAsync.key]: BillsOfLadingApi.getBillOfLadingByIdAsync,
    [BillsOfLadingApi.getBillOfLadingLineByIdAsync.key]: BillsOfLadingApi.getBillOfLadingLineByIdAsync,
    [BillsOfLadingApi.getBillOfLadingLinesAsync.key]: BillsOfLadingApi.getBillOfLadingLinesAsync,
    [BillsOfLadingApi.getBillOfLadingLinesCountAsync.key]: BillsOfLadingApi.getBillOfLadingLinesCountAsync,
    [BillsOfLadingApi.getBillsOfLadingAsync.key]: BillsOfLadingApi.getBillsOfLadingAsync,
    [BillsOfLadingApi.getBillsOfLadingCountAsync.key]: BillsOfLadingApi.getBillsOfLadingCountAsync,
    [BillsOfLadingApi.updateBillOfLadingAsync.key]: BillsOfLadingApi.updateBillOfLadingAsync,
    [BillsOfLadingApi.updateBillOfLadingLineAsync.key]: BillsOfLadingApi.updateBillOfLadingLineAsync,
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [ItemShippingPoliciesApi.createItemShippingPolicyAsync.key]: ItemShippingPoliciesApi.createItemShippingPolicyAsync,
    [ItemShippingPoliciesApi.deleteItemShippingPolicyAsync.key]: ItemShippingPoliciesApi.deleteItemShippingPolicyAsync,
    [ItemShippingPoliciesApi.getItemShippingPoliciesAsync.key]: ItemShippingPoliciesApi.getItemShippingPoliciesAsync,
    [ItemShippingPoliciesApi.getItemShippingPoliciesCountAsync.key]: ItemShippingPoliciesApi.getItemShippingPoliciesCountAsync,
    [ItemShippingPoliciesApi.getItemShippingPolicyByIdAsync.key]: ItemShippingPoliciesApi.getItemShippingPolicyByIdAsync,
    [ItemShippingPoliciesApi.updateItemShippingPolicyAsync.key]: ItemShippingPoliciesApi.updateItemShippingPolicyAsync,
    [ShipmentsApi.createShipmentAsync.key]: ShipmentsApi.createShipmentAsync,
    [ShipmentsApi.deleteShipmentAsync.key]: ShipmentsApi.deleteShipmentAsync,
    [ShipmentsApi.getShipmentByIdAsync.key]: ShipmentsApi.getShipmentByIdAsync,
    [ShipmentsApi.getShipmentsAsync.key]: ShipmentsApi.getShipmentsAsync,
    [ShipmentsApi.getShipmentsCountAsync.key]: ShipmentsApi.getShipmentsCountAsync,
    [ShipmentsApi.updateShipmentAsync.key]: ShipmentsApi.updateShipmentAsync,
    [ShippingClassesApi.createShippingClassAsync.key]: ShippingClassesApi.createShippingClassAsync,
    [ShippingClassesApi.deleteShippingClassAsync.key]: ShippingClassesApi.deleteShippingClassAsync,
    [ShippingClassesApi.getShippingClassByIdAsync.key]: ShippingClassesApi.getShippingClassByIdAsync,
    [ShippingClassesApi.getShippingClassesAsync.key]: ShippingClassesApi.getShippingClassesAsync,
    [ShippingClassesApi.getShippingClassesCountAsync.key]: ShippingClassesApi.getShippingClassesCountAsync,
    [ShippingClassesApi.updateShippingClassAsync.key]: ShippingClassesApi.updateShippingClassAsync,
    [ShippingCouriersApi.createShippingCourierAsync.key]: ShippingCouriersApi.createShippingCourierAsync,
    [ShippingCouriersApi.deleteShippingCourierAsync.key]: ShippingCouriersApi.deleteShippingCourierAsync,
    [ShippingCouriersApi.getShippingCourierByIdAsync.key]: ShippingCouriersApi.getShippingCourierByIdAsync,
    [ShippingCouriersApi.getShippingCouriersAsync.key]: ShippingCouriersApi.getShippingCouriersAsync,
    [ShippingCouriersApi.getShippingCouriersCountAsync.key]: ShippingCouriersApi.getShippingCouriersCountAsync,
    [ShippingCouriersApi.updateShippingCourierAsync.key]: ShippingCouriersApi.updateShippingCourierAsync,
    [ShippingLabelsApi.createShippingLabelAsync.key]: ShippingLabelsApi.createShippingLabelAsync,
    [ShippingLabelsApi.deleteShippingLabelAsync.key]: ShippingLabelsApi.deleteShippingLabelAsync,
    [ShippingLabelsApi.getShippingLabelByIdAsync.key]: ShippingLabelsApi.getShippingLabelByIdAsync,
    [ShippingLabelsApi.getShippingLabelsAsync.key]: ShippingLabelsApi.getShippingLabelsAsync,
    [ShippingLabelsApi.getShippingLabelsCountAsync.key]: ShippingLabelsApi.getShippingLabelsCountAsync,
    [ShippingLabelsApi.updateShippingLabelAsync.key]: ShippingLabelsApi.updateShippingLabelAsync,
    [ShippingMethodsApi.createShippingMethodAsync.key]: ShippingMethodsApi.createShippingMethodAsync,
    [ShippingMethodsApi.deleteShippingMethodAsync.key]: ShippingMethodsApi.deleteShippingMethodAsync,
    [ShippingMethodsApi.getShippingMethodByIdAsync.key]: ShippingMethodsApi.getShippingMethodByIdAsync,
    [ShippingMethodsApi.getShippingMethodsAsync.key]: ShippingMethodsApi.getShippingMethodsAsync,
    [ShippingMethodsApi.getShippingMethodsCountAsync.key]: ShippingMethodsApi.getShippingMethodsCountAsync,
    [ShippingMethodsApi.updateShippingMethodAsync.key]: ShippingMethodsApi.updateShippingMethodAsync,
    [ShippingRegionsApi.createShippingRegionAsync.key]: ShippingRegionsApi.createShippingRegionAsync,
    [ShippingRegionsApi.deleteShippingRegionAsync.key]: ShippingRegionsApi.deleteShippingRegionAsync,
    [ShippingRegionsApi.getShippingRegionByIdAsync.key]: ShippingRegionsApi.getShippingRegionByIdAsync,
    [ShippingRegionsApi.getShippingRegionsAsync.key]: ShippingRegionsApi.getShippingRegionsAsync,
    [ShippingRegionsApi.getShippingRegionsCountAsync.key]: ShippingRegionsApi.getShippingRegionsCountAsync,
    [ShippingRegionsApi.updateShippingRegionAsync.key]: ShippingRegionsApi.updateShippingRegionAsync,
    [ShippingZonesApi.createShippingZoneAsync.key]: ShippingZonesApi.createShippingZoneAsync,
    [ShippingZonesApi.deleteShippingZoneAsync.key]: ShippingZonesApi.deleteShippingZoneAsync,
    [ShippingZonesApi.getShippingZoneByIdAsync.key]: ShippingZonesApi.getShippingZoneByIdAsync,
    [ShippingZonesApi.getShippingZonesAsync.key]: ShippingZonesApi.getShippingZonesAsync,
    [ShippingZonesApi.getShippingZonesCountAsync.key]: ShippingZonesApi.getShippingZonesCountAsync,
    [ShippingZonesApi.updateShippingZoneAsync.key]: ShippingZonesApi.updateShippingZoneAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
