const FenixAllianceABPWebApi = require('../apis/FenixAllianceABPWebApi');
const SocialFeedsApi = require('../apis/SocialFeedsApi');
const SocialGroupsApi = require('../apis/SocialGroupsApi');
const SocialPostsApi = require('../apis/SocialPostsApi');
const SocialProfilesApi = require('../apis/SocialProfilesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABPWebApi.forgotPasswordPost.key]: FenixAllianceABPWebApi.forgotPasswordPost,
    [FenixAllianceABPWebApi.healthGet.key]: FenixAllianceABPWebApi.healthGet,
    [FenixAllianceABPWebApi.helloGet.key]: FenixAllianceABPWebApi.helloGet,
    [FenixAllianceABPWebApi.loginPost.key]: FenixAllianceABPWebApi.loginPost,
    [FenixAllianceABPWebApi.manage2faPost.key]: FenixAllianceABPWebApi.manage2faPost,
    [FenixAllianceABPWebApi.manageInfoGet.key]: FenixAllianceABPWebApi.manageInfoGet,
    [FenixAllianceABPWebApi.manageInfoPost.key]: FenixAllianceABPWebApi.manageInfoPost,
    [FenixAllianceABPWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABPWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABPWebApi.refreshPost.key]: FenixAllianceABPWebApi.refreshPost,
    [FenixAllianceABPWebApi.registerPost.key]: FenixAllianceABPWebApi.registerPost,
    [FenixAllianceABPWebApi.resendConfirmationEmailPost.key]: FenixAllianceABPWebApi.resendConfirmationEmailPost,
    [FenixAllianceABPWebApi.resetPasswordPost.key]: FenixAllianceABPWebApi.resetPasswordPost,
    [FenixAllianceABPWebApi.versionGet.key]: FenixAllianceABPWebApi.versionGet,
    [SocialFeedsApi.createFeedPostAsync.key]: SocialFeedsApi.createFeedPostAsync,
    [SocialFeedsApi.deleteFeedPostAsync.key]: SocialFeedsApi.deleteFeedPostAsync,
    [SocialFeedsApi.getFeedNotifications.key]: SocialFeedsApi.getFeedNotifications,
    [SocialFeedsApi.getFeedPostAsync.key]: SocialFeedsApi.getFeedPostAsync,
    [SocialFeedsApi.getFeedPostsAsync.key]: SocialFeedsApi.getFeedPostsAsync,
    [SocialFeedsApi.getFeedPostsCountAsync.key]: SocialFeedsApi.getFeedPostsCountAsync,
    [SocialFeedsApi.getNotificationAsync.key]: SocialFeedsApi.getNotificationAsync,
    [SocialFeedsApi.getNotificationsCountAsync.key]: SocialFeedsApi.getNotificationsCountAsync,
    [SocialFeedsApi.updateFeedPostAsync.key]: SocialFeedsApi.updateFeedPostAsync,
    [SocialGroupsApi.countSocialGroupsAsync.key]: SocialGroupsApi.countSocialGroupsAsync,
    [SocialGroupsApi.createSocialGroupAsync.key]: SocialGroupsApi.createSocialGroupAsync,
    [SocialGroupsApi.deleteSocialGroupAsync.key]: SocialGroupsApi.deleteSocialGroupAsync,
    [SocialGroupsApi.getSocialGroupByIdAsync.key]: SocialGroupsApi.getSocialGroupByIdAsync,
    [SocialGroupsApi.getSocialGroupsAsync.key]: SocialGroupsApi.getSocialGroupsAsync,
    [SocialGroupsApi.updateSocialGroupAsync.key]: SocialGroupsApi.updateSocialGroupAsync,
    [SocialPostsApi.createSocialPostAsync.key]: SocialPostsApi.createSocialPostAsync,
    [SocialPostsApi.createSocialPostAttachmentAsync.key]: SocialPostsApi.createSocialPostAttachmentAsync,
    [SocialPostsApi.createSocialPostCommentAsync.key]: SocialPostsApi.createSocialPostCommentAsync,
    [SocialPostsApi.createSocialPostReactionAsync.key]: SocialPostsApi.createSocialPostReactionAsync,
    [SocialPostsApi.deleteSocialPostAsync.key]: SocialPostsApi.deleteSocialPostAsync,
    [SocialPostsApi.deleteSocialPostAttachmentAsync.key]: SocialPostsApi.deleteSocialPostAttachmentAsync,
    [SocialPostsApi.deleteSocialPostCommentAsync.key]: SocialPostsApi.deleteSocialPostCommentAsync,
    [SocialPostsApi.deleteSocialPostReactionAsync.key]: SocialPostsApi.deleteSocialPostReactionAsync,
    [SocialPostsApi.getSocialPostAsync.key]: SocialPostsApi.getSocialPostAsync,
    [SocialPostsApi.getSocialPostAttachmentAsync.key]: SocialPostsApi.getSocialPostAttachmentAsync,
    [SocialPostsApi.getSocialPostAttachmentsAsync.key]: SocialPostsApi.getSocialPostAttachmentsAsync,
    [SocialPostsApi.getSocialPostAttachmentsCountAsync.key]: SocialPostsApi.getSocialPostAttachmentsCountAsync,
    [SocialPostsApi.getSocialPostCommentAsync.key]: SocialPostsApi.getSocialPostCommentAsync,
    [SocialPostsApi.getSocialPostCommentsAsync.key]: SocialPostsApi.getSocialPostCommentsAsync,
    [SocialPostsApi.getSocialPostCommentsCountAsync.key]: SocialPostsApi.getSocialPostCommentsCountAsync,
    [SocialPostsApi.getSocialPostReactionAsync.key]: SocialPostsApi.getSocialPostReactionAsync,
    [SocialPostsApi.getSocialPostReactionsAsync.key]: SocialPostsApi.getSocialPostReactionsAsync,
    [SocialPostsApi.getSocialPostReactionsCountAsync.key]: SocialPostsApi.getSocialPostReactionsCountAsync,
    [SocialPostsApi.getSocialPostsAsync.key]: SocialPostsApi.getSocialPostsAsync,
    [SocialPostsApi.getSocialPostsCountAsync.key]: SocialPostsApi.getSocialPostsCountAsync,
    [SocialPostsApi.updateSocialPostAsync.key]: SocialPostsApi.updateSocialPostAsync,
    [SocialPostsApi.updateSocialPostAttachmentAsync.key]: SocialPostsApi.updateSocialPostAttachmentAsync,
    [SocialPostsApi.updateSocialPostCommentAsync.key]: SocialPostsApi.updateSocialPostCommentAsync,
    [SocialPostsApi.updateSocialPostReactionAsync.key]: SocialPostsApi.updateSocialPostReactionAsync,
    [SocialProfilesApi.countConversationsAsync.key]: SocialProfilesApi.countConversationsAsync,
    [SocialProfilesApi.countFollowedProfilesAsync.key]: SocialProfilesApi.countFollowedProfilesAsync,
    [SocialProfilesApi.countFollowerProfilesAsync.key]: SocialProfilesApi.countFollowerProfilesAsync,
    [SocialProfilesApi.countFollowersAsync.key]: SocialProfilesApi.countFollowersAsync,
    [SocialProfilesApi.countFollowsAsync.key]: SocialProfilesApi.countFollowsAsync,
    [SocialProfilesApi.countMessagesAsync.key]: SocialProfilesApi.countMessagesAsync,
    [SocialProfilesApi.countNotificationsAsync.key]: SocialProfilesApi.countNotificationsAsync,
    [SocialProfilesApi.countSocialProfilesAsync.key]: SocialProfilesApi.countSocialProfilesAsync,
    [SocialProfilesApi.createConversationAsync.key]: SocialProfilesApi.createConversationAsync,
    [SocialProfilesApi.createMessageAsync.key]: SocialProfilesApi.createMessageAsync,
    [SocialProfilesApi.deleteMessageAsync.key]: SocialProfilesApi.deleteMessageAsync,
    [SocialProfilesApi.followAsync.key]: SocialProfilesApi.followAsync,
    [SocialProfilesApi.followExistsAsync.key]: SocialProfilesApi.followExistsAsync,
    [SocialProfilesApi.getConversationsAsync.key]: SocialProfilesApi.getConversationsAsync,
    [SocialProfilesApi.getFollowedProfilesAsync.key]: SocialProfilesApi.getFollowedProfilesAsync,
    [SocialProfilesApi.getFollowerProfilesAsync.key]: SocialProfilesApi.getFollowerProfilesAsync,
    [SocialProfilesApi.getFollowersAsync.key]: SocialProfilesApi.getFollowersAsync,
    [SocialProfilesApi.getFollowsAsync.key]: SocialProfilesApi.getFollowsAsync,
    [SocialProfilesApi.getMessagesAsync.key]: SocialProfilesApi.getMessagesAsync,
    [SocialProfilesApi.getNotificationsAsync.key]: SocialProfilesApi.getNotificationsAsync,
    [SocialProfilesApi.getSocialProfileAsync.key]: SocialProfilesApi.getSocialProfileAsync,
    [SocialProfilesApi.getSocialProfilesAsync.key]: SocialProfilesApi.getSocialProfilesAsync,
    [SocialProfilesApi.unfollowAsync.key]: SocialProfilesApi.unfollowAsync,
    [SocialProfilesApi.updateMessageAsync.key]: SocialProfilesApi.updateMessageAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
