const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const HelpdeskApi = require('../apis/HelpdeskApi');
const PoliciesApi = require('../apis/PoliciesApi');
const SupportEntitlementsApi = require('../apis/SupportEntitlementsApi');
const SupportRequestAttachmentsApi = require('../apis/SupportRequestAttachmentsApi');
const SupportRequestsApi = require('../apis/SupportRequestsApi');
const SupportTicketPrioritiesApi = require('../apis/SupportTicketPrioritiesApi');
const SupportTicketTypesApi = require('../apis/SupportTicketTypesApi');
const SupportTicketsApi = require('../apis/SupportTicketsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [HelpdeskApi.createInquiryRequestAsync.key]: HelpdeskApi.createInquiryRequestAsync,
    [HelpdeskApi.createKnowledgeArticleAsync.key]: HelpdeskApi.createKnowledgeArticleAsync,
    [HelpdeskApi.createMaintenanceVisitAsync.key]: HelpdeskApi.createMaintenanceVisitAsync,
    [HelpdeskApi.createRefundRequestAsync.key]: HelpdeskApi.createRefundRequestAsync,
    [HelpdeskApi.createReturnRequestAsync.key]: HelpdeskApi.createReturnRequestAsync,
    [HelpdeskApi.createWarrantyRequestAsync.key]: HelpdeskApi.createWarrantyRequestAsync,
    [HelpdeskApi.deleteInquiryRequestAsync.key]: HelpdeskApi.deleteInquiryRequestAsync,
    [HelpdeskApi.deleteKnowledgeArticleAsync.key]: HelpdeskApi.deleteKnowledgeArticleAsync,
    [HelpdeskApi.deleteMaintenanceVisitAsync.key]: HelpdeskApi.deleteMaintenanceVisitAsync,
    [HelpdeskApi.deleteRefundRequestAsync.key]: HelpdeskApi.deleteRefundRequestAsync,
    [HelpdeskApi.deleteReturnRequestAsync.key]: HelpdeskApi.deleteReturnRequestAsync,
    [HelpdeskApi.deleteWarrantyRequestAsync.key]: HelpdeskApi.deleteWarrantyRequestAsync,
    [HelpdeskApi.getInquiryRequestAsync.key]: HelpdeskApi.getInquiryRequestAsync,
    [HelpdeskApi.getInquiryRequestsAsync.key]: HelpdeskApi.getInquiryRequestsAsync,
    [HelpdeskApi.getInquiryRequestsCountAsync.key]: HelpdeskApi.getInquiryRequestsCountAsync,
    [HelpdeskApi.getKnowledgeArticleAsync.key]: HelpdeskApi.getKnowledgeArticleAsync,
    [HelpdeskApi.getKnowledgeArticlesAsync.key]: HelpdeskApi.getKnowledgeArticlesAsync,
    [HelpdeskApi.getKnowledgeArticlesCountAsync.key]: HelpdeskApi.getKnowledgeArticlesCountAsync,
    [HelpdeskApi.getMaintenanceVisitAsync.key]: HelpdeskApi.getMaintenanceVisitAsync,
    [HelpdeskApi.getMaintenanceVisitsAsync.key]: HelpdeskApi.getMaintenanceVisitsAsync,
    [HelpdeskApi.getMaintenanceVisitsCountAsync.key]: HelpdeskApi.getMaintenanceVisitsCountAsync,
    [HelpdeskApi.getRefundRequestAsync.key]: HelpdeskApi.getRefundRequestAsync,
    [HelpdeskApi.getRefundRequestsAsync.key]: HelpdeskApi.getRefundRequestsAsync,
    [HelpdeskApi.getRefundRequestsCountAsync.key]: HelpdeskApi.getRefundRequestsCountAsync,
    [HelpdeskApi.getReturnRequestAsync.key]: HelpdeskApi.getReturnRequestAsync,
    [HelpdeskApi.getReturnRequestsAsync.key]: HelpdeskApi.getReturnRequestsAsync,
    [HelpdeskApi.getReturnRequestsCountAsync.key]: HelpdeskApi.getReturnRequestsCountAsync,
    [HelpdeskApi.getWarrantyRequestAsync.key]: HelpdeskApi.getWarrantyRequestAsync,
    [HelpdeskApi.getWarrantyRequestsAsync.key]: HelpdeskApi.getWarrantyRequestsAsync,
    [HelpdeskApi.getWarrantyRequestsCountAsync.key]: HelpdeskApi.getWarrantyRequestsCountAsync,
    [HelpdeskApi.updateInquiryRequestAsync.key]: HelpdeskApi.updateInquiryRequestAsync,
    [HelpdeskApi.updateKnowledgeArticleAsync.key]: HelpdeskApi.updateKnowledgeArticleAsync,
    [HelpdeskApi.updateMaintenanceVisitAsync.key]: HelpdeskApi.updateMaintenanceVisitAsync,
    [HelpdeskApi.updateRefundRequestAsync.key]: HelpdeskApi.updateRefundRequestAsync,
    [HelpdeskApi.updateReturnRequestAsync.key]: HelpdeskApi.updateReturnRequestAsync,
    [HelpdeskApi.updateWarrantyRequestAsync.key]: HelpdeskApi.updateWarrantyRequestAsync,
    [PoliciesApi.createRefundPolicyAsync.key]: PoliciesApi.createRefundPolicyAsync,
    [PoliciesApi.createReturnPolicyAsync.key]: PoliciesApi.createReturnPolicyAsync,
    [PoliciesApi.createWarrantyPolicyAsync.key]: PoliciesApi.createWarrantyPolicyAsync,
    [PoliciesApi.deleteRefundPolicyAsync.key]: PoliciesApi.deleteRefundPolicyAsync,
    [PoliciesApi.deleteReturnPolicyAsync.key]: PoliciesApi.deleteReturnPolicyAsync,
    [PoliciesApi.deleteWarrantyPolicyAsync.key]: PoliciesApi.deleteWarrantyPolicyAsync,
    [PoliciesApi.getRefundPoliciesAsync.key]: PoliciesApi.getRefundPoliciesAsync,
    [PoliciesApi.getRefundPoliciesCountAsync.key]: PoliciesApi.getRefundPoliciesCountAsync,
    [PoliciesApi.getRefundPolicyAsync.key]: PoliciesApi.getRefundPolicyAsync,
    [PoliciesApi.getReturnPoliciesAsync.key]: PoliciesApi.getReturnPoliciesAsync,
    [PoliciesApi.getReturnPoliciesCountAsync.key]: PoliciesApi.getReturnPoliciesCountAsync,
    [PoliciesApi.getReturnPolicyAsync.key]: PoliciesApi.getReturnPolicyAsync,
    [PoliciesApi.getWarrantyPoliciesAsync.key]: PoliciesApi.getWarrantyPoliciesAsync,
    [PoliciesApi.getWarrantyPoliciesCountAsync.key]: PoliciesApi.getWarrantyPoliciesCountAsync,
    [PoliciesApi.getWarrantyPolicyAsync.key]: PoliciesApi.getWarrantyPolicyAsync,
    [PoliciesApi.updateRefundPolicyAsync.key]: PoliciesApi.updateRefundPolicyAsync,
    [PoliciesApi.updateReturnPolicyAsync.key]: PoliciesApi.updateReturnPolicyAsync,
    [PoliciesApi.updateWarrantyPolicyAsync.key]: PoliciesApi.updateWarrantyPolicyAsync,
    [SupportEntitlementsApi.createSupportEntitlementAsync.key]: SupportEntitlementsApi.createSupportEntitlementAsync,
    [SupportEntitlementsApi.deleteSupportEntitlementAsync.key]: SupportEntitlementsApi.deleteSupportEntitlementAsync,
    [SupportEntitlementsApi.getSupportEntitlementAsync.key]: SupportEntitlementsApi.getSupportEntitlementAsync,
    [SupportEntitlementsApi.getSupportEntitlementsAsync.key]: SupportEntitlementsApi.getSupportEntitlementsAsync,
    [SupportEntitlementsApi.getSupportEntitlementsCountAsync.key]: SupportEntitlementsApi.getSupportEntitlementsCountAsync,
    [SupportEntitlementsApi.updateSupportEntitlementAsync.key]: SupportEntitlementsApi.updateSupportEntitlementAsync,
    [SupportRequestAttachmentsApi.createSupportRequestAttachmentAsync.key]: SupportRequestAttachmentsApi.createSupportRequestAttachmentAsync,
    [SupportRequestAttachmentsApi.deleteSupportRequestAttachmentAsync.key]: SupportRequestAttachmentsApi.deleteSupportRequestAttachmentAsync,
    [SupportRequestAttachmentsApi.getSupportRequestAttachmentAsync.key]: SupportRequestAttachmentsApi.getSupportRequestAttachmentAsync,
    [SupportRequestAttachmentsApi.getSupportRequestAttachmentsAsync.key]: SupportRequestAttachmentsApi.getSupportRequestAttachmentsAsync,
    [SupportRequestAttachmentsApi.getSupportRequestAttachmentsCountAsync.key]: SupportRequestAttachmentsApi.getSupportRequestAttachmentsCountAsync,
    [SupportRequestAttachmentsApi.updateSupportRequestAttachmentAsync.key]: SupportRequestAttachmentsApi.updateSupportRequestAttachmentAsync,
    [SupportRequestsApi.createSupportRequestAsync.key]: SupportRequestsApi.createSupportRequestAsync,
    [SupportRequestsApi.deleteSupportRequestAsync.key]: SupportRequestsApi.deleteSupportRequestAsync,
    [SupportRequestsApi.getSupportRequestAsync.key]: SupportRequestsApi.getSupportRequestAsync,
    [SupportRequestsApi.getSupportRequestAttachmentByRequest.key]: SupportRequestsApi.getSupportRequestAttachmentByRequest,
    [SupportRequestsApi.getSupportRequestAttachmentsByRequest.key]: SupportRequestsApi.getSupportRequestAttachmentsByRequest,
    [SupportRequestsApi.getSupportRequestAttachmentsCountByRequest.key]: SupportRequestsApi.getSupportRequestAttachmentsCountByRequest,
    [SupportRequestsApi.getSupportRequestTicketsAsync.key]: SupportRequestsApi.getSupportRequestTicketsAsync,
    [SupportRequestsApi.getSupportRequestsAsync.key]: SupportRequestsApi.getSupportRequestsAsync,
    [SupportRequestsApi.getSupportRequestsCountAsync.key]: SupportRequestsApi.getSupportRequestsCountAsync,
    [SupportRequestsApi.relateSupportRequestToAttachmentAsync.key]: SupportRequestsApi.relateSupportRequestToAttachmentAsync,
    [SupportRequestsApi.updateSupportRequestAsync.key]: SupportRequestsApi.updateSupportRequestAsync,
    [SupportTicketPrioritiesApi.createSupportTicketPriorityAsync.key]: SupportTicketPrioritiesApi.createSupportTicketPriorityAsync,
    [SupportTicketPrioritiesApi.deleteSupportTicketPriorityAsync.key]: SupportTicketPrioritiesApi.deleteSupportTicketPriorityAsync,
    [SupportTicketPrioritiesApi.getSupportTicketPrioritiesAsync.key]: SupportTicketPrioritiesApi.getSupportTicketPrioritiesAsync,
    [SupportTicketPrioritiesApi.getSupportTicketPrioritiesCountAsync.key]: SupportTicketPrioritiesApi.getSupportTicketPrioritiesCountAsync,
    [SupportTicketPrioritiesApi.getSupportTicketPriorityAsync.key]: SupportTicketPrioritiesApi.getSupportTicketPriorityAsync,
    [SupportTicketPrioritiesApi.updateSupportTicketPriorityAsync.key]: SupportTicketPrioritiesApi.updateSupportTicketPriorityAsync,
    [SupportTicketTypesApi.createSupportTicketTypeAsync.key]: SupportTicketTypesApi.createSupportTicketTypeAsync,
    [SupportTicketTypesApi.deleteSupportTicketTypeAsync.key]: SupportTicketTypesApi.deleteSupportTicketTypeAsync,
    [SupportTicketTypesApi.getSupportTicketTypeAsync.key]: SupportTicketTypesApi.getSupportTicketTypeAsync,
    [SupportTicketTypesApi.getSupportTicketTypesAsync.key]: SupportTicketTypesApi.getSupportTicketTypesAsync,
    [SupportTicketTypesApi.getSupportTicketTypesCountAsync.key]: SupportTicketTypesApi.getSupportTicketTypesCountAsync,
    [SupportTicketTypesApi.updateSupportTicketTypeAsync.key]: SupportTicketTypesApi.updateSupportTicketTypeAsync,
    [SupportTicketsApi.createSupportTicketAsync.key]: SupportTicketsApi.createSupportTicketAsync,
    [SupportTicketsApi.deleteSupportTicketAsync.key]: SupportTicketsApi.deleteSupportTicketAsync,
    [SupportTicketsApi.deleteSupportTicketConversationAsync.key]: SupportTicketsApi.deleteSupportTicketConversationAsync,
    [SupportTicketsApi.getSupportTicketAsync.key]: SupportTicketsApi.getSupportTicketAsync,
    [SupportTicketsApi.getSupportTicketConversationAsync.key]: SupportTicketsApi.getSupportTicketConversationAsync,
    [SupportTicketsApi.getSupportTicketConversationMessagesAsync.key]: SupportTicketsApi.getSupportTicketConversationMessagesAsync,
    [SupportTicketsApi.getSupportTicketConversationsAsync.key]: SupportTicketsApi.getSupportTicketConversationsAsync,
    [SupportTicketsApi.getSupportTicketsAsync.key]: SupportTicketsApi.getSupportTicketsAsync,
    [SupportTicketsApi.getSupportTicketsCountAsync.key]: SupportTicketsApi.getSupportTicketsCountAsync,
    [SupportTicketsApi.relateSupportTicketToConversationAsync.key]: SupportTicketsApi.relateSupportTicketToConversationAsync,
    [SupportTicketsApi.updateSupportTicketAsync.key]: SupportTicketsApi.updateSupportTicketAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
