const utils = require('../utils/utils');
const Assembly = require('../models/Assembly');
const ConstructorInfo = require('../models/ConstructorInfo');
const CustomAttributeData = require('../models/CustomAttributeData');
const MethodBase = require('../models/MethodBase');
const Module = require('../models/Module');
const RuntimeTypeHandle = require('../models/RuntimeTypeHandle');
const StructLayoutAttribute = require('../models/StructLayoutAttribute');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}name`,
                label: `[${labelPrefix}name]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}customAttributes`,
                label: `[${labelPrefix}customAttributes]`,
                children: CustomAttributeData.fields(`${keyPrefix}customAttributes${!isInput ? '[]' : ''}`, isInput, true), 
            },
            {
                key: `${keyPrefix}isCollectible`,
                label: `[${labelPrefix}isCollectible]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}metadataToken`,
                label: `[${labelPrefix}metadataToken]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}memberType`,
                label: `[${labelPrefix}memberType]`,
                type: 'string',
                choices: [
                    'Constructor',
                    'Event',
                    'Field',
                    'Method',
                    'Property',
                    'TypeInfo',
                    'Custom',
                    'NestedType',
                    'All',
                ],
            },
            {
                key: `${keyPrefix}namespace`,
                label: `[${labelPrefix}namespace]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}assemblyQualifiedName`,
                label: `[${labelPrefix}assemblyQualifiedName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}fullName`,
                label: `[${labelPrefix}fullName]`,
                type: 'string',
            },
            ...Assembly.fields(`${keyPrefix}assembly`, isInput),
            ...Module.fields(`${keyPrefix}module`, isInput),
            {
                key: `${keyPrefix}isInterface`,
                label: `[${labelPrefix}isInterface]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNested`,
                label: `[${labelPrefix}isNested]`,
                type: 'boolean',
            },
            ...Type.fields(`${keyPrefix}declaringType`, isInput),
            ...MethodBase.fields(`${keyPrefix}declaringMethod`, isInput),
            ...Type.fields(`${keyPrefix}reflectedType`, isInput),
            ...Type.fields(`${keyPrefix}underlyingSystemType`, isInput),
            {
                key: `${keyPrefix}isTypeDefinition`,
                label: `[${labelPrefix}isTypeDefinition]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isArray`,
                label: `[${labelPrefix}isArray]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isByRef`,
                label: `[${labelPrefix}isByRef]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isPointer`,
                label: `[${labelPrefix}isPointer]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isConstructedGenericType`,
                label: `[${labelPrefix}isConstructedGenericType]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isGenericParameter`,
                label: `[${labelPrefix}isGenericParameter]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isGenericTypeParameter`,
                label: `[${labelPrefix}isGenericTypeParameter]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isGenericMethodParameter`,
                label: `[${labelPrefix}isGenericMethodParameter]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isGenericType`,
                label: `[${labelPrefix}isGenericType]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isGenericTypeDefinition`,
                label: `[${labelPrefix}isGenericTypeDefinition]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSZArray`,
                label: `[${labelPrefix}isSZArray]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isVariableBoundArray`,
                label: `[${labelPrefix}isVariableBoundArray]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isByRefLike`,
                label: `[${labelPrefix}isByRefLike]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isFunctionPointer`,
                label: `[${labelPrefix}isFunctionPointer]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isUnmanagedFunctionPointer`,
                label: `[${labelPrefix}isUnmanagedFunctionPointer]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}hasElementType`,
                label: `[${labelPrefix}hasElementType]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}genericTypeArguments`,
                label: `[${labelPrefix}genericTypeArguments]`,
                children: Type.fields(`${keyPrefix}genericTypeArguments${!isInput ? '[]' : ''}`, isInput, true), 
            },
            {
                key: `${keyPrefix}genericParameterPosition`,
                label: `[${labelPrefix}genericParameterPosition]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}genericParameterAttributes`,
                label: `[${labelPrefix}genericParameterAttributes]`,
                type: 'string',
                choices: [
                    'None',
                    'Covariant',
                    'Contravariant',
                    'VarianceMask',
                    'ReferenceTypeConstraint',
                    'NotNullableValueTypeConstraint',
                    'DefaultConstructorConstraint',
                    'SpecialConstraintMask',
                    'AllowByRefLike',
                ],
            },
            {
                key: `${keyPrefix}attributes`,
                label: `[${labelPrefix}attributes]`,
                type: 'string',
                choices: [
                    'NotPublic',
                    'Public',
                    'NestedPublic',
                    'NestedPrivate',
                    'NestedFamily',
                    'NestedAssembly',
                    'NestedFamANDAssem',
                    'VisibilityMask',
                    'SequentialLayout',
                    'ExplicitLayout',
                    'LayoutMask',
                    'Interface',
                    'Abstract',
                    'Sealed',
                    'SpecialName',
                    'RTSpecialName',
                    'Import',
                    'Serializable',
                    'WindowsRuntime',
                    'UnicodeClass',
                    'AutoClass',
                    'StringFormatMask',
                    'HasSecurity',
                    'ReservedMask',
                    'BeforeFieldInit',
                    'CustomFormatMask',
                ],
            },
            {
                key: `${keyPrefix}isAbstract`,
                label: `[${labelPrefix}isAbstract]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isImport`,
                label: `[${labelPrefix}isImport]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSealed`,
                label: `[${labelPrefix}isSealed]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSpecialName`,
                label: `[${labelPrefix}isSpecialName]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isClass`,
                label: `[${labelPrefix}isClass]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNestedAssembly`,
                label: `[${labelPrefix}isNestedAssembly]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNestedFamANDAssem`,
                label: `[${labelPrefix}isNestedFamANDAssem]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNestedFamily`,
                label: `[${labelPrefix}isNestedFamily]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNestedFamORAssem`,
                label: `[${labelPrefix}isNestedFamORAssem]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNestedPrivate`,
                label: `[${labelPrefix}isNestedPrivate]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNestedPublic`,
                label: `[${labelPrefix}isNestedPublic]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNotPublic`,
                label: `[${labelPrefix}isNotPublic]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isPublic`,
                label: `[${labelPrefix}isPublic]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isAutoLayout`,
                label: `[${labelPrefix}isAutoLayout]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isExplicitLayout`,
                label: `[${labelPrefix}isExplicitLayout]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isLayoutSequential`,
                label: `[${labelPrefix}isLayoutSequential]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isAnsiClass`,
                label: `[${labelPrefix}isAnsiClass]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isAutoClass`,
                label: `[${labelPrefix}isAutoClass]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isUnicodeClass`,
                label: `[${labelPrefix}isUnicodeClass]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isCOMObject`,
                label: `[${labelPrefix}isCOMObject]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isContextful`,
                label: `[${labelPrefix}isContextful]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isEnum`,
                label: `[${labelPrefix}isEnum]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isMarshalByRef`,
                label: `[${labelPrefix}isMarshalByRef]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isPrimitive`,
                label: `[${labelPrefix}isPrimitive]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isValueType`,
                label: `[${labelPrefix}isValueType]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSignatureType`,
                label: `[${labelPrefix}isSignatureType]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSecurityCritical`,
                label: `[${labelPrefix}isSecurityCritical]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSecuritySafeCritical`,
                label: `[${labelPrefix}isSecuritySafeCritical]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isSecurityTransparent`,
                label: `[${labelPrefix}isSecurityTransparent]`,
                type: 'boolean',
            },
            ...StructLayoutAttribute.fields(`${keyPrefix}structLayoutAttribute`, isInput),
            ...ConstructorInfo.fields(`${keyPrefix}typeInitializer`, isInput),
            ...RuntimeTypeHandle.fields(`${keyPrefix}typeHandle`, isInput),
            {
                key: `${keyPrefix}guid`,
                label: `[${labelPrefix}guid]`,
                type: 'string',
            },
            ...Type.fields(`${keyPrefix}baseType`, isInput),
            {
                key: `${keyPrefix}isSerializable`,
                label: `[${labelPrefix}isSerializable]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}containsGenericParameters`,
                label: `[${labelPrefix}containsGenericParameters]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isVisible`,
                label: `[${labelPrefix}isVisible]`,
                type: 'boolean',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'name': bundle.inputData?.[`${keyPrefix}name`],
            'customAttributes': utils.childMapping(bundle.inputData?.[`${keyPrefix}customAttributes`], `${keyPrefix}customAttributes`, CustomAttributeData),
            'isCollectible': bundle.inputData?.[`${keyPrefix}isCollectible`],
            'metadataToken': bundle.inputData?.[`${keyPrefix}metadataToken`],
            'memberType': bundle.inputData?.[`${keyPrefix}memberType`],
            'namespace': bundle.inputData?.[`${keyPrefix}namespace`],
            'assemblyQualifiedName': bundle.inputData?.[`${keyPrefix}assemblyQualifiedName`],
            'fullName': bundle.inputData?.[`${keyPrefix}fullName`],
            'assembly': utils.removeIfEmpty(Assembly.mapping(bundle, `${keyPrefix}assembly`)),
            'module': utils.removeIfEmpty(Module.mapping(bundle, `${keyPrefix}module`)),
            'isInterface': bundle.inputData?.[`${keyPrefix}isInterface`],
            'isNested': bundle.inputData?.[`${keyPrefix}isNested`],
            'declaringType': utils.removeIfEmpty(Type.mapping(bundle, `${keyPrefix}declaringType`)),
            'declaringMethod': utils.removeIfEmpty(MethodBase.mapping(bundle, `${keyPrefix}declaringMethod`)),
            'reflectedType': utils.removeIfEmpty(Type.mapping(bundle, `${keyPrefix}reflectedType`)),
            'underlyingSystemType': utils.removeIfEmpty(Type.mapping(bundle, `${keyPrefix}underlyingSystemType`)),
            'isTypeDefinition': bundle.inputData?.[`${keyPrefix}isTypeDefinition`],
            'isArray': bundle.inputData?.[`${keyPrefix}isArray`],
            'isByRef': bundle.inputData?.[`${keyPrefix}isByRef`],
            'isPointer': bundle.inputData?.[`${keyPrefix}isPointer`],
            'isConstructedGenericType': bundle.inputData?.[`${keyPrefix}isConstructedGenericType`],
            'isGenericParameter': bundle.inputData?.[`${keyPrefix}isGenericParameter`],
            'isGenericTypeParameter': bundle.inputData?.[`${keyPrefix}isGenericTypeParameter`],
            'isGenericMethodParameter': bundle.inputData?.[`${keyPrefix}isGenericMethodParameter`],
            'isGenericType': bundle.inputData?.[`${keyPrefix}isGenericType`],
            'isGenericTypeDefinition': bundle.inputData?.[`${keyPrefix}isGenericTypeDefinition`],
            'isSZArray': bundle.inputData?.[`${keyPrefix}isSZArray`],
            'isVariableBoundArray': bundle.inputData?.[`${keyPrefix}isVariableBoundArray`],
            'isByRefLike': bundle.inputData?.[`${keyPrefix}isByRefLike`],
            'isFunctionPointer': bundle.inputData?.[`${keyPrefix}isFunctionPointer`],
            'isUnmanagedFunctionPointer': bundle.inputData?.[`${keyPrefix}isUnmanagedFunctionPointer`],
            'hasElementType': bundle.inputData?.[`${keyPrefix}hasElementType`],
            'genericTypeArguments': utils.childMapping(bundle.inputData?.[`${keyPrefix}genericTypeArguments`], `${keyPrefix}genericTypeArguments`, Type),
            'genericParameterPosition': bundle.inputData?.[`${keyPrefix}genericParameterPosition`],
            'genericParameterAttributes': bundle.inputData?.[`${keyPrefix}genericParameterAttributes`],
            'attributes': bundle.inputData?.[`${keyPrefix}attributes`],
            'isAbstract': bundle.inputData?.[`${keyPrefix}isAbstract`],
            'isImport': bundle.inputData?.[`${keyPrefix}isImport`],
            'isSealed': bundle.inputData?.[`${keyPrefix}isSealed`],
            'isSpecialName': bundle.inputData?.[`${keyPrefix}isSpecialName`],
            'isClass': bundle.inputData?.[`${keyPrefix}isClass`],
            'isNestedAssembly': bundle.inputData?.[`${keyPrefix}isNestedAssembly`],
            'isNestedFamANDAssem': bundle.inputData?.[`${keyPrefix}isNestedFamANDAssem`],
            'isNestedFamily': bundle.inputData?.[`${keyPrefix}isNestedFamily`],
            'isNestedFamORAssem': bundle.inputData?.[`${keyPrefix}isNestedFamORAssem`],
            'isNestedPrivate': bundle.inputData?.[`${keyPrefix}isNestedPrivate`],
            'isNestedPublic': bundle.inputData?.[`${keyPrefix}isNestedPublic`],
            'isNotPublic': bundle.inputData?.[`${keyPrefix}isNotPublic`],
            'isPublic': bundle.inputData?.[`${keyPrefix}isPublic`],
            'isAutoLayout': bundle.inputData?.[`${keyPrefix}isAutoLayout`],
            'isExplicitLayout': bundle.inputData?.[`${keyPrefix}isExplicitLayout`],
            'isLayoutSequential': bundle.inputData?.[`${keyPrefix}isLayoutSequential`],
            'isAnsiClass': bundle.inputData?.[`${keyPrefix}isAnsiClass`],
            'isAutoClass': bundle.inputData?.[`${keyPrefix}isAutoClass`],
            'isUnicodeClass': bundle.inputData?.[`${keyPrefix}isUnicodeClass`],
            'isCOMObject': bundle.inputData?.[`${keyPrefix}isCOMObject`],
            'isContextful': bundle.inputData?.[`${keyPrefix}isContextful`],
            'isEnum': bundle.inputData?.[`${keyPrefix}isEnum`],
            'isMarshalByRef': bundle.inputData?.[`${keyPrefix}isMarshalByRef`],
            'isPrimitive': bundle.inputData?.[`${keyPrefix}isPrimitive`],
            'isValueType': bundle.inputData?.[`${keyPrefix}isValueType`],
            'isSignatureType': bundle.inputData?.[`${keyPrefix}isSignatureType`],
            'isSecurityCritical': bundle.inputData?.[`${keyPrefix}isSecurityCritical`],
            'isSecuritySafeCritical': bundle.inputData?.[`${keyPrefix}isSecuritySafeCritical`],
            'isSecurityTransparent': bundle.inputData?.[`${keyPrefix}isSecurityTransparent`],
            'structLayoutAttribute': utils.removeIfEmpty(StructLayoutAttribute.mapping(bundle, `${keyPrefix}structLayoutAttribute`)),
            'typeInitializer': utils.removeIfEmpty(ConstructorInfo.mapping(bundle, `${keyPrefix}typeInitializer`)),
            'typeHandle': utils.removeIfEmpty(RuntimeTypeHandle.mapping(bundle, `${keyPrefix}typeHandle`)),
            'guid': bundle.inputData?.[`${keyPrefix}guid`],
            'baseType': utils.removeIfEmpty(Type.mapping(bundle, `${keyPrefix}baseType`)),
            'isSerializable': bundle.inputData?.[`${keyPrefix}isSerializable`],
            'containsGenericParameters': bundle.inputData?.[`${keyPrefix}containsGenericParameters`],
            'isVisible': bundle.inputData?.[`${keyPrefix}isVisible`],
        }
    },
}
