const AirwayBillsApi = require('../apis/AirwayBillsApi');
const CompletionsApi = require('../apis/CompletionsApi');
const DeliveryNotesApi = require('../apis/DeliveryNotesApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const ItemPackingSlipsApi = require('../apis/ItemPackingSlipsApi');
const ItemPickListsApi = require('../apis/ItemPickListsApi');
const ItemRestocksApi = require('../apis/ItemRestocksApi');
const ItemRetainSamplesApi = require('../apis/ItemRetainSamplesApi');
const PortsApi = require('../apis/PortsApi');
const ProofsOfDeliveryApi = require('../apis/ProofsOfDeliveryApi');
const RailWaybillsApi = require('../apis/RailWaybillsApi');
const RoadWaybillsApi = require('../apis/RoadWaybillsApi');
const SeawayBillsApi = require('../apis/SeawayBillsApi');
const SupplierProfilesApi = require('../apis/SupplierProfilesApi');
const TruckDriversApi = require('../apis/TruckDriversApi');
const TrucksApi = require('../apis/TrucksApi');
const VesselsApi = require('../apis/VesselsApi');
const VoyagesApi = require('../apis/VoyagesApi');
const WarehousesApi = require('../apis/WarehousesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [AirwayBillsApi.addAirwayBillLineAsync.key]: AirwayBillsApi.addAirwayBillLineAsync,
    [AirwayBillsApi.cancelAirwayBillAsync.key]: AirwayBillsApi.cancelAirwayBillAsync,
    [AirwayBillsApi.createAirwayBillAsync.key]: AirwayBillsApi.createAirwayBillAsync,
    [AirwayBillsApi.deleteAirwayBillAsync.key]: AirwayBillsApi.deleteAirwayBillAsync,
    [AirwayBillsApi.getAirwayBillByIdAsync.key]: AirwayBillsApi.getAirwayBillByIdAsync,
    [AirwayBillsApi.getAirwayBillLinesAsync.key]: AirwayBillsApi.getAirwayBillLinesAsync,
    [AirwayBillsApi.getAirwayBillLinesCountAsync.key]: AirwayBillsApi.getAirwayBillLinesCountAsync,
    [AirwayBillsApi.getAirwayBillsAsync.key]: AirwayBillsApi.getAirwayBillsAsync,
    [AirwayBillsApi.getAirwayBillsCountAsync.key]: AirwayBillsApi.getAirwayBillsCountAsync,
    [AirwayBillsApi.issueAirwayBillAsync.key]: AirwayBillsApi.issueAirwayBillAsync,
    [AirwayBillsApi.markAirwayBillArrivedAsync.key]: AirwayBillsApi.markAirwayBillArrivedAsync,
    [AirwayBillsApi.markAirwayBillDeliveredAsync.key]: AirwayBillsApi.markAirwayBillDeliveredAsync,
    [AirwayBillsApi.markAirwayBillInTransitAsync.key]: AirwayBillsApi.markAirwayBillInTransitAsync,
    [AirwayBillsApi.patchAirwayBillAsync.key]: AirwayBillsApi.patchAirwayBillAsync,
    [AirwayBillsApi.patchAirwayBillLineAsync.key]: AirwayBillsApi.patchAirwayBillLineAsync,
    [AirwayBillsApi.removeAirwayBillLineAsync.key]: AirwayBillsApi.removeAirwayBillLineAsync,
    [AirwayBillsApi.updateAirwayBillAsync.key]: AirwayBillsApi.updateAirwayBillAsync,
    [AirwayBillsApi.updateAirwayBillLineAsync.key]: AirwayBillsApi.updateAirwayBillLineAsync,
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [DeliveryNotesApi.createDeliveryNoteAsync.key]: DeliveryNotesApi.createDeliveryNoteAsync,
    [DeliveryNotesApi.deleteDeliveryNoteAsync.key]: DeliveryNotesApi.deleteDeliveryNoteAsync,
    [DeliveryNotesApi.getDeliveryNoteByIdAsync.key]: DeliveryNotesApi.getDeliveryNoteByIdAsync,
    [DeliveryNotesApi.getDeliveryNotesAsync.key]: DeliveryNotesApi.getDeliveryNotesAsync,
    [DeliveryNotesApi.getDeliveryNotesCountAsync.key]: DeliveryNotesApi.getDeliveryNotesCountAsync,
    [DeliveryNotesApi.updateDeliveryNoteAsync.key]: DeliveryNotesApi.updateDeliveryNoteAsync,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [ItemPackingSlipsApi.createItemPackingSlipAsync.key]: ItemPackingSlipsApi.createItemPackingSlipAsync,
    [ItemPackingSlipsApi.createItemPackingSlipEntryAsync.key]: ItemPackingSlipsApi.createItemPackingSlipEntryAsync,
    [ItemPackingSlipsApi.deleteItemPackingSlipAsync.key]: ItemPackingSlipsApi.deleteItemPackingSlipAsync,
    [ItemPackingSlipsApi.deleteItemPackingSlipEntryAsync.key]: ItemPackingSlipsApi.deleteItemPackingSlipEntryAsync,
    [ItemPackingSlipsApi.getItemPackingSlipByIdAsync.key]: ItemPackingSlipsApi.getItemPackingSlipByIdAsync,
    [ItemPackingSlipsApi.getItemPackingSlipEntriesAsync.key]: ItemPackingSlipsApi.getItemPackingSlipEntriesAsync,
    [ItemPackingSlipsApi.getItemPackingSlipEntriesCountAsync.key]: ItemPackingSlipsApi.getItemPackingSlipEntriesCountAsync,
    [ItemPackingSlipsApi.getItemPackingSlipEntryByIdAsync.key]: ItemPackingSlipsApi.getItemPackingSlipEntryByIdAsync,
    [ItemPackingSlipsApi.getItemPackingSlipsAsync.key]: ItemPackingSlipsApi.getItemPackingSlipsAsync,
    [ItemPackingSlipsApi.getItemPackingSlipsCountAsync.key]: ItemPackingSlipsApi.getItemPackingSlipsCountAsync,
    [ItemPackingSlipsApi.patchItemPackingSlipAsync.key]: ItemPackingSlipsApi.patchItemPackingSlipAsync,
    [ItemPackingSlipsApi.patchItemPackingSlipEntryAsync.key]: ItemPackingSlipsApi.patchItemPackingSlipEntryAsync,
    [ItemPackingSlipsApi.updateItemPackingSlipAsync.key]: ItemPackingSlipsApi.updateItemPackingSlipAsync,
    [ItemPackingSlipsApi.updateItemPackingSlipEntryAsync.key]: ItemPackingSlipsApi.updateItemPackingSlipEntryAsync,
    [ItemPickListsApi.createItemPickListAsync.key]: ItemPickListsApi.createItemPickListAsync,
    [ItemPickListsApi.createItemPickListEntryAsync.key]: ItemPickListsApi.createItemPickListEntryAsync,
    [ItemPickListsApi.deleteItemPickListAsync.key]: ItemPickListsApi.deleteItemPickListAsync,
    [ItemPickListsApi.deleteItemPickListEntryAsync.key]: ItemPickListsApi.deleteItemPickListEntryAsync,
    [ItemPickListsApi.getItemPickListByIdAsync.key]: ItemPickListsApi.getItemPickListByIdAsync,
    [ItemPickListsApi.getItemPickListEntriesAsync.key]: ItemPickListsApi.getItemPickListEntriesAsync,
    [ItemPickListsApi.getItemPickListEntriesCountAsync.key]: ItemPickListsApi.getItemPickListEntriesCountAsync,
    [ItemPickListsApi.getItemPickListEntryByIdAsync.key]: ItemPickListsApi.getItemPickListEntryByIdAsync,
    [ItemPickListsApi.getItemPickListsAsync.key]: ItemPickListsApi.getItemPickListsAsync,
    [ItemPickListsApi.getItemPickListsCountAsync.key]: ItemPickListsApi.getItemPickListsCountAsync,
    [ItemPickListsApi.patchItemPickListAsync.key]: ItemPickListsApi.patchItemPickListAsync,
    [ItemPickListsApi.patchItemPickListEntryAsync.key]: ItemPickListsApi.patchItemPickListEntryAsync,
    [ItemPickListsApi.updateItemPickListAsync.key]: ItemPickListsApi.updateItemPickListAsync,
    [ItemPickListsApi.updateItemPickListEntryAsync.key]: ItemPickListsApi.updateItemPickListEntryAsync,
    [ItemRestocksApi.createItemRestockAsync.key]: ItemRestocksApi.createItemRestockAsync,
    [ItemRestocksApi.createItemRestockEntryAsync.key]: ItemRestocksApi.createItemRestockEntryAsync,
    [ItemRestocksApi.deleteItemRestockAsync.key]: ItemRestocksApi.deleteItemRestockAsync,
    [ItemRestocksApi.deleteItemRestockEntryAsync.key]: ItemRestocksApi.deleteItemRestockEntryAsync,
    [ItemRestocksApi.getItemRestockByIdAsync.key]: ItemRestocksApi.getItemRestockByIdAsync,
    [ItemRestocksApi.getItemRestockEntriesAsync.key]: ItemRestocksApi.getItemRestockEntriesAsync,
    [ItemRestocksApi.getItemRestockEntriesCountAsync.key]: ItemRestocksApi.getItemRestockEntriesCountAsync,
    [ItemRestocksApi.getItemRestockEntryByIdAsync.key]: ItemRestocksApi.getItemRestockEntryByIdAsync,
    [ItemRestocksApi.getItemRestocksAsync.key]: ItemRestocksApi.getItemRestocksAsync,
    [ItemRestocksApi.getItemRestocksCountAsync.key]: ItemRestocksApi.getItemRestocksCountAsync,
    [ItemRestocksApi.patchItemRestockAsync.key]: ItemRestocksApi.patchItemRestockAsync,
    [ItemRestocksApi.patchItemRestockEntryAsync.key]: ItemRestocksApi.patchItemRestockEntryAsync,
    [ItemRestocksApi.updateItemRestockAsync.key]: ItemRestocksApi.updateItemRestockAsync,
    [ItemRestocksApi.updateItemRestockEntryAsync.key]: ItemRestocksApi.updateItemRestockEntryAsync,
    [ItemRetainSamplesApi.createItemRetainSampleAsync.key]: ItemRetainSamplesApi.createItemRetainSampleAsync,
    [ItemRetainSamplesApi.deleteItemRetainSampleAsync.key]: ItemRetainSamplesApi.deleteItemRetainSampleAsync,
    [ItemRetainSamplesApi.getItemRetainSampleByIdAsync.key]: ItemRetainSamplesApi.getItemRetainSampleByIdAsync,
    [ItemRetainSamplesApi.getItemRetainSamplesAsync.key]: ItemRetainSamplesApi.getItemRetainSamplesAsync,
    [ItemRetainSamplesApi.getItemRetainSamplesCountAsync.key]: ItemRetainSamplesApi.getItemRetainSamplesCountAsync,
    [ItemRetainSamplesApi.patchItemRetainSampleAsync.key]: ItemRetainSamplesApi.patchItemRetainSampleAsync,
    [ItemRetainSamplesApi.updateItemRetainSampleAsync.key]: ItemRetainSamplesApi.updateItemRetainSampleAsync,
    [PortsApi.createPortAsync.key]: PortsApi.createPortAsync,
    [PortsApi.deletePortAsync.key]: PortsApi.deletePortAsync,
    [PortsApi.getPortByIdAsync.key]: PortsApi.getPortByIdAsync,
    [PortsApi.getPortsAsync.key]: PortsApi.getPortsAsync,
    [PortsApi.getPortsCountAsync.key]: PortsApi.getPortsCountAsync,
    [PortsApi.patchPortAsync.key]: PortsApi.patchPortAsync,
    [PortsApi.updatePortAsync.key]: PortsApi.updatePortAsync,
    [ProofsOfDeliveryApi.addProofOfDeliveryLineAsync.key]: ProofsOfDeliveryApi.addProofOfDeliveryLineAsync,
    [ProofsOfDeliveryApi.attachDeliveryNoteAsync.key]: ProofsOfDeliveryApi.attachDeliveryNoteAsync,
    [ProofsOfDeliveryApi.createProofOfDeliveryAsync.key]: ProofsOfDeliveryApi.createProofOfDeliveryAsync,
    [ProofsOfDeliveryApi.deleteProofOfDeliveryAsync.key]: ProofsOfDeliveryApi.deleteProofOfDeliveryAsync,
    [ProofsOfDeliveryApi.detachDeliveryNoteAsync.key]: ProofsOfDeliveryApi.detachDeliveryNoteAsync,
    [ProofsOfDeliveryApi.disputeProofOfDeliveryAsync.key]: ProofsOfDeliveryApi.disputeProofOfDeliveryAsync,
    [ProofsOfDeliveryApi.getProofOfDeliveryByIdAsync.key]: ProofsOfDeliveryApi.getProofOfDeliveryByIdAsync,
    [ProofsOfDeliveryApi.getProofOfDeliveryDeliveryNotesAsync.key]: ProofsOfDeliveryApi.getProofOfDeliveryDeliveryNotesAsync,
    [ProofsOfDeliveryApi.getProofOfDeliveryDeliveryNotesCountAsync.key]: ProofsOfDeliveryApi.getProofOfDeliveryDeliveryNotesCountAsync,
    [ProofsOfDeliveryApi.getProofOfDeliveryLinesAsync.key]: ProofsOfDeliveryApi.getProofOfDeliveryLinesAsync,
    [ProofsOfDeliveryApi.getProofOfDeliveryLinesCountAsync.key]: ProofsOfDeliveryApi.getProofOfDeliveryLinesCountAsync,
    [ProofsOfDeliveryApi.getProofsOfDeliveryAsync.key]: ProofsOfDeliveryApi.getProofsOfDeliveryAsync,
    [ProofsOfDeliveryApi.getProofsOfDeliveryCountAsync.key]: ProofsOfDeliveryApi.getProofsOfDeliveryCountAsync,
    [ProofsOfDeliveryApi.patchProofOfDeliveryAsync.key]: ProofsOfDeliveryApi.patchProofOfDeliveryAsync,
    [ProofsOfDeliveryApi.patchProofOfDeliveryLineAsync.key]: ProofsOfDeliveryApi.patchProofOfDeliveryLineAsync,
    [ProofsOfDeliveryApi.rejectProofOfDeliveryAsync.key]: ProofsOfDeliveryApi.rejectProofOfDeliveryAsync,
    [ProofsOfDeliveryApi.removeProofOfDeliveryLineAsync.key]: ProofsOfDeliveryApi.removeProofOfDeliveryLineAsync,
    [ProofsOfDeliveryApi.signProofOfDeliveryAsync.key]: ProofsOfDeliveryApi.signProofOfDeliveryAsync,
    [ProofsOfDeliveryApi.updateProofOfDeliveryAsync.key]: ProofsOfDeliveryApi.updateProofOfDeliveryAsync,
    [ProofsOfDeliveryApi.updateProofOfDeliveryLineAsync.key]: ProofsOfDeliveryApi.updateProofOfDeliveryLineAsync,
    [RailWaybillsApi.addRailWaybillLineAsync.key]: RailWaybillsApi.addRailWaybillLineAsync,
    [RailWaybillsApi.cancelRailWaybillAsync.key]: RailWaybillsApi.cancelRailWaybillAsync,
    [RailWaybillsApi.createRailWaybillAsync.key]: RailWaybillsApi.createRailWaybillAsync,
    [RailWaybillsApi.deleteRailWaybillAsync.key]: RailWaybillsApi.deleteRailWaybillAsync,
    [RailWaybillsApi.getRailWaybillByIdAsync.key]: RailWaybillsApi.getRailWaybillByIdAsync,
    [RailWaybillsApi.getRailWaybillLinesAsync.key]: RailWaybillsApi.getRailWaybillLinesAsync,
    [RailWaybillsApi.getRailWaybillLinesCountAsync.key]: RailWaybillsApi.getRailWaybillLinesCountAsync,
    [RailWaybillsApi.getRailWaybillsAsync.key]: RailWaybillsApi.getRailWaybillsAsync,
    [RailWaybillsApi.getRailWaybillsCountAsync.key]: RailWaybillsApi.getRailWaybillsCountAsync,
    [RailWaybillsApi.issueRailWaybillAsync.key]: RailWaybillsApi.issueRailWaybillAsync,
    [RailWaybillsApi.markRailWaybillDeliveredAsync.key]: RailWaybillsApi.markRailWaybillDeliveredAsync,
    [RailWaybillsApi.markRailWaybillInTransitAsync.key]: RailWaybillsApi.markRailWaybillInTransitAsync,
    [RailWaybillsApi.patchRailWaybillAsync.key]: RailWaybillsApi.patchRailWaybillAsync,
    [RailWaybillsApi.patchRailWaybillLineAsync.key]: RailWaybillsApi.patchRailWaybillLineAsync,
    [RailWaybillsApi.removeRailWaybillLineAsync.key]: RailWaybillsApi.removeRailWaybillLineAsync,
    [RailWaybillsApi.updateRailWaybillAsync.key]: RailWaybillsApi.updateRailWaybillAsync,
    [RailWaybillsApi.updateRailWaybillLineAsync.key]: RailWaybillsApi.updateRailWaybillLineAsync,
    [RoadWaybillsApi.addRoadWaybillLineAsync.key]: RoadWaybillsApi.addRoadWaybillLineAsync,
    [RoadWaybillsApi.cancelRoadWaybillAsync.key]: RoadWaybillsApi.cancelRoadWaybillAsync,
    [RoadWaybillsApi.createRoadWaybillAsync.key]: RoadWaybillsApi.createRoadWaybillAsync,
    [RoadWaybillsApi.deleteRoadWaybillAsync.key]: RoadWaybillsApi.deleteRoadWaybillAsync,
    [RoadWaybillsApi.disputeRoadWaybillAsync.key]: RoadWaybillsApi.disputeRoadWaybillAsync,
    [RoadWaybillsApi.getRoadWaybillByIdAsync.key]: RoadWaybillsApi.getRoadWaybillByIdAsync,
    [RoadWaybillsApi.getRoadWaybillLinesAsync.key]: RoadWaybillsApi.getRoadWaybillLinesAsync,
    [RoadWaybillsApi.getRoadWaybillLinesCountAsync.key]: RoadWaybillsApi.getRoadWaybillLinesCountAsync,
    [RoadWaybillsApi.getRoadWaybillsAsync.key]: RoadWaybillsApi.getRoadWaybillsAsync,
    [RoadWaybillsApi.getRoadWaybillsCountAsync.key]: RoadWaybillsApi.getRoadWaybillsCountAsync,
    [RoadWaybillsApi.issueRoadWaybillAsync.key]: RoadWaybillsApi.issueRoadWaybillAsync,
    [RoadWaybillsApi.markRoadWaybillDeliveredAsync.key]: RoadWaybillsApi.markRoadWaybillDeliveredAsync,
    [RoadWaybillsApi.markRoadWaybillInTransitAsync.key]: RoadWaybillsApi.markRoadWaybillInTransitAsync,
    [RoadWaybillsApi.patchRoadWaybillAsync.key]: RoadWaybillsApi.patchRoadWaybillAsync,
    [RoadWaybillsApi.patchRoadWaybillLineAsync.key]: RoadWaybillsApi.patchRoadWaybillLineAsync,
    [RoadWaybillsApi.removeRoadWaybillLineAsync.key]: RoadWaybillsApi.removeRoadWaybillLineAsync,
    [RoadWaybillsApi.updateRoadWaybillAsync.key]: RoadWaybillsApi.updateRoadWaybillAsync,
    [RoadWaybillsApi.updateRoadWaybillLineAsync.key]: RoadWaybillsApi.updateRoadWaybillLineAsync,
    [SeawayBillsApi.addSeawayBillLineAsync.key]: SeawayBillsApi.addSeawayBillLineAsync,
    [SeawayBillsApi.cancelSeawayBillAsync.key]: SeawayBillsApi.cancelSeawayBillAsync,
    [SeawayBillsApi.createSeawayBillAsync.key]: SeawayBillsApi.createSeawayBillAsync,
    [SeawayBillsApi.deleteSeawayBillAsync.key]: SeawayBillsApi.deleteSeawayBillAsync,
    [SeawayBillsApi.getSeawayBillByIdAsync.key]: SeawayBillsApi.getSeawayBillByIdAsync,
    [SeawayBillsApi.getSeawayBillLinesAsync.key]: SeawayBillsApi.getSeawayBillLinesAsync,
    [SeawayBillsApi.getSeawayBillLinesCountAsync.key]: SeawayBillsApi.getSeawayBillLinesCountAsync,
    [SeawayBillsApi.getSeawayBillsAsync.key]: SeawayBillsApi.getSeawayBillsAsync,
    [SeawayBillsApi.getSeawayBillsCountAsync.key]: SeawayBillsApi.getSeawayBillsCountAsync,
    [SeawayBillsApi.issueSeawayBillAsync.key]: SeawayBillsApi.issueSeawayBillAsync,
    [SeawayBillsApi.markSeawayBillArrivedAsync.key]: SeawayBillsApi.markSeawayBillArrivedAsync,
    [SeawayBillsApi.markSeawayBillInTransitAsync.key]: SeawayBillsApi.markSeawayBillInTransitAsync,
    [SeawayBillsApi.patchSeawayBillAsync.key]: SeawayBillsApi.patchSeawayBillAsync,
    [SeawayBillsApi.patchSeawayBillLineAsync.key]: SeawayBillsApi.patchSeawayBillLineAsync,
    [SeawayBillsApi.releaseSeawayBillAsync.key]: SeawayBillsApi.releaseSeawayBillAsync,
    [SeawayBillsApi.removeSeawayBillLineAsync.key]: SeawayBillsApi.removeSeawayBillLineAsync,
    [SeawayBillsApi.updateSeawayBillAsync.key]: SeawayBillsApi.updateSeawayBillAsync,
    [SeawayBillsApi.updateSeawayBillLineAsync.key]: SeawayBillsApi.updateSeawayBillLineAsync,
    [SupplierProfilesApi.createSupplierProfileAsync.key]: SupplierProfilesApi.createSupplierProfileAsync,
    [SupplierProfilesApi.deleteSupplierProfileAsync.key]: SupplierProfilesApi.deleteSupplierProfileAsync,
    [SupplierProfilesApi.getSupplierProfileByIdAsync.key]: SupplierProfilesApi.getSupplierProfileByIdAsync,
    [SupplierProfilesApi.getSupplierProfilesAsync.key]: SupplierProfilesApi.getSupplierProfilesAsync,
    [SupplierProfilesApi.getSupplierProfilesCountAsync.key]: SupplierProfilesApi.getSupplierProfilesCountAsync,
    [SupplierProfilesApi.patchSupplierProfileAsync.key]: SupplierProfilesApi.patchSupplierProfileAsync,
    [SupplierProfilesApi.updateSupplierProfileAsync.key]: SupplierProfilesApi.updateSupplierProfileAsync,
    [TruckDriversApi.activateTruckDriverAsync.key]: TruckDriversApi.activateTruckDriverAsync,
    [TruckDriversApi.createTruckDriverAsync.key]: TruckDriversApi.createTruckDriverAsync,
    [TruckDriversApi.deactivateTruckDriverAsync.key]: TruckDriversApi.deactivateTruckDriverAsync,
    [TruckDriversApi.deleteTruckDriverAsync.key]: TruckDriversApi.deleteTruckDriverAsync,
    [TruckDriversApi.getTruckDriverByIdAsync.key]: TruckDriversApi.getTruckDriverByIdAsync,
    [TruckDriversApi.getTruckDriversAsync.key]: TruckDriversApi.getTruckDriversAsync,
    [TruckDriversApi.getTruckDriversCountAsync.key]: TruckDriversApi.getTruckDriversCountAsync,
    [TruckDriversApi.patchTruckDriverAsync.key]: TruckDriversApi.patchTruckDriverAsync,
    [TruckDriversApi.updateTruckDriverAsync.key]: TruckDriversApi.updateTruckDriverAsync,
    [TrucksApi.arriveTripAsync.key]: TrucksApi.arriveTripAsync,
    [TrucksApi.cancelTripAsync.key]: TrucksApi.cancelTripAsync,
    [TrucksApi.createTruckAsync.key]: TrucksApi.createTruckAsync,
    [TrucksApi.createTruckTripAsync.key]: TrucksApi.createTruckTripAsync,
    [TrucksApi.deleteTruckAsync.key]: TrucksApi.deleteTruckAsync,
    [TrucksApi.deleteTruckTripAsync.key]: TrucksApi.deleteTruckTripAsync,
    [TrucksApi.deliverTripAsync.key]: TrucksApi.deliverTripAsync,
    [TrucksApi.departTripAsync.key]: TrucksApi.departTripAsync,
    [TrucksApi.dispatchTripAsync.key]: TrucksApi.dispatchTripAsync,
    [TrucksApi.getTruckByIdAsync.key]: TrucksApi.getTruckByIdAsync,
    [TrucksApi.getTruckTripsAsync.key]: TrucksApi.getTruckTripsAsync,
    [TrucksApi.getTruckTripsCountAsync.key]: TrucksApi.getTruckTripsCountAsync,
    [TrucksApi.getTrucksAsync.key]: TrucksApi.getTrucksAsync,
    [TrucksApi.getTrucksCountAsync.key]: TrucksApi.getTrucksCountAsync,
    [TrucksApi.patchTruckAsync.key]: TrucksApi.patchTruckAsync,
    [TrucksApi.patchTruckTripAsync.key]: TrucksApi.patchTruckTripAsync,
    [TrucksApi.updateTruckAsync.key]: TrucksApi.updateTruckAsync,
    [TrucksApi.updateTruckTripAsync.key]: TrucksApi.updateTruckTripAsync,
    [VesselsApi.createVesselAsync.key]: VesselsApi.createVesselAsync,
    [VesselsApi.deleteVesselAsync.key]: VesselsApi.deleteVesselAsync,
    [VesselsApi.getVesselByIdAsync.key]: VesselsApi.getVesselByIdAsync,
    [VesselsApi.getVesselsAsync.key]: VesselsApi.getVesselsAsync,
    [VesselsApi.getVesselsCountAsync.key]: VesselsApi.getVesselsCountAsync,
    [VesselsApi.patchVesselAsync.key]: VesselsApi.patchVesselAsync,
    [VesselsApi.updateVesselAsync.key]: VesselsApi.updateVesselAsync,
    [VoyagesApi.cancelVoyageAsync.key]: VoyagesApi.cancelVoyageAsync,
    [VoyagesApi.completeVoyageAsync.key]: VoyagesApi.completeVoyageAsync,
    [VoyagesApi.createVoyageAsync.key]: VoyagesApi.createVoyageAsync,
    [VoyagesApi.createVoyagePortCallAsync.key]: VoyagesApi.createVoyagePortCallAsync,
    [VoyagesApi.deleteVoyageAsync.key]: VoyagesApi.deleteVoyageAsync,
    [VoyagesApi.deleteVoyagePortCallAsync.key]: VoyagesApi.deleteVoyagePortCallAsync,
    [VoyagesApi.getVoyageByIdAsync.key]: VoyagesApi.getVoyageByIdAsync,
    [VoyagesApi.getVoyagePortCallsAsync.key]: VoyagesApi.getVoyagePortCallsAsync,
    [VoyagesApi.getVoyagePortCallsCountAsync.key]: VoyagesApi.getVoyagePortCallsCountAsync,
    [VoyagesApi.getVoyagesAsync.key]: VoyagesApi.getVoyagesAsync,
    [VoyagesApi.getVoyagesCountAsync.key]: VoyagesApi.getVoyagesCountAsync,
    [VoyagesApi.patchVoyageAsync.key]: VoyagesApi.patchVoyageAsync,
    [VoyagesApi.patchVoyagePortCallAsync.key]: VoyagesApi.patchVoyagePortCallAsync,
    [VoyagesApi.startVoyageAsync.key]: VoyagesApi.startVoyageAsync,
    [VoyagesApi.updateVoyageAsync.key]: VoyagesApi.updateVoyageAsync,
    [VoyagesApi.updateVoyagePortCallAsync.key]: VoyagesApi.updateVoyagePortCallAsync,
    [WarehousesApi.createWarehouseAsync.key]: WarehousesApi.createWarehouseAsync,
    [WarehousesApi.deleteWarehouseAsync.key]: WarehousesApi.deleteWarehouseAsync,
    [WarehousesApi.getWarehouseByIdAsync.key]: WarehousesApi.getWarehouseByIdAsync,
    [WarehousesApi.getWarehousesAsync.key]: WarehousesApi.getWarehousesAsync,
    [WarehousesApi.getWarehousesCountAsync.key]: WarehousesApi.getWarehousesCountAsync,
    [WarehousesApi.patchWarehouseAsync.key]: WarehousesApi.patchWarehouseAsync,
    [WarehousesApi.updateWarehouseAsync.key]: WarehousesApi.updateWarehouseAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
