const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const StockApi = require('../apis/StockApi');
const WarehousingApi = require('../apis/WarehousingApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [StockApi.getContactsAsync.key]: StockApi.getContactsAsync,
    [WarehousingApi.createItemPackingSlipAsync.key]: WarehousingApi.createItemPackingSlipAsync,
    [WarehousingApi.createItemPackingSlipEntryAsync.key]: WarehousingApi.createItemPackingSlipEntryAsync,
    [WarehousingApi.createItemPickListAsync.key]: WarehousingApi.createItemPickListAsync,
    [WarehousingApi.createItemPickListEntryAsync.key]: WarehousingApi.createItemPickListEntryAsync,
    [WarehousingApi.createItemRestockAsync.key]: WarehousingApi.createItemRestockAsync,
    [WarehousingApi.createItemRestockEntryAsync.key]: WarehousingApi.createItemRestockEntryAsync,
    [WarehousingApi.createItemRetainSampleAsync.key]: WarehousingApi.createItemRetainSampleAsync,
    [WarehousingApi.createWarehouseAsync.key]: WarehousingApi.createWarehouseAsync,
    [WarehousingApi.deleteItemPackingSlipAsync.key]: WarehousingApi.deleteItemPackingSlipAsync,
    [WarehousingApi.deleteItemPackingSlipEntryAsync.key]: WarehousingApi.deleteItemPackingSlipEntryAsync,
    [WarehousingApi.deleteItemPickListAsync.key]: WarehousingApi.deleteItemPickListAsync,
    [WarehousingApi.deleteItemPickListEntryAsync.key]: WarehousingApi.deleteItemPickListEntryAsync,
    [WarehousingApi.deleteItemRestockAsync.key]: WarehousingApi.deleteItemRestockAsync,
    [WarehousingApi.deleteItemRestockEntryAsync.key]: WarehousingApi.deleteItemRestockEntryAsync,
    [WarehousingApi.deleteItemRetainSampleAsync.key]: WarehousingApi.deleteItemRetainSampleAsync,
    [WarehousingApi.deleteWarehouseAsync.key]: WarehousingApi.deleteWarehouseAsync,
    [WarehousingApi.getItemPackingSlipByIdAsync.key]: WarehousingApi.getItemPackingSlipByIdAsync,
    [WarehousingApi.getItemPackingSlipEntriesAsync.key]: WarehousingApi.getItemPackingSlipEntriesAsync,
    [WarehousingApi.getItemPackingSlipEntriesCountAsync.key]: WarehousingApi.getItemPackingSlipEntriesCountAsync,
    [WarehousingApi.getItemPackingSlipEntryByIdAsync.key]: WarehousingApi.getItemPackingSlipEntryByIdAsync,
    [WarehousingApi.getItemPackingSlipsAsync.key]: WarehousingApi.getItemPackingSlipsAsync,
    [WarehousingApi.getItemPackingSlipsCountAsync.key]: WarehousingApi.getItemPackingSlipsCountAsync,
    [WarehousingApi.getItemPickListByIdAsync.key]: WarehousingApi.getItemPickListByIdAsync,
    [WarehousingApi.getItemPickListEntriesAsync.key]: WarehousingApi.getItemPickListEntriesAsync,
    [WarehousingApi.getItemPickListEntriesCountAsync.key]: WarehousingApi.getItemPickListEntriesCountAsync,
    [WarehousingApi.getItemPickListEntryByIdAsync.key]: WarehousingApi.getItemPickListEntryByIdAsync,
    [WarehousingApi.getItemPickListsAsync.key]: WarehousingApi.getItemPickListsAsync,
    [WarehousingApi.getItemPickListsCountAsync.key]: WarehousingApi.getItemPickListsCountAsync,
    [WarehousingApi.getItemRestockByIdAsync.key]: WarehousingApi.getItemRestockByIdAsync,
    [WarehousingApi.getItemRestockEntriesAsync.key]: WarehousingApi.getItemRestockEntriesAsync,
    [WarehousingApi.getItemRestockEntriesCountAsync.key]: WarehousingApi.getItemRestockEntriesCountAsync,
    [WarehousingApi.getItemRestockEntryByIdAsync.key]: WarehousingApi.getItemRestockEntryByIdAsync,
    [WarehousingApi.getItemRestocksAsync.key]: WarehousingApi.getItemRestocksAsync,
    [WarehousingApi.getItemRestocksCountAsync.key]: WarehousingApi.getItemRestocksCountAsync,
    [WarehousingApi.getItemRetainSampleByIdAsync.key]: WarehousingApi.getItemRetainSampleByIdAsync,
    [WarehousingApi.getItemRetainSamplesAsync.key]: WarehousingApi.getItemRetainSamplesAsync,
    [WarehousingApi.getItemRetainSamplesCountAsync.key]: WarehousingApi.getItemRetainSamplesCountAsync,
    [WarehousingApi.getWarehouseByIdAsync.key]: WarehousingApi.getWarehouseByIdAsync,
    [WarehousingApi.getWarehousesAsync.key]: WarehousingApi.getWarehousesAsync,
    [WarehousingApi.getWarehousesCountAsync.key]: WarehousingApi.getWarehousesCountAsync,
    [WarehousingApi.updateItemPackingSlipAsync.key]: WarehousingApi.updateItemPackingSlipAsync,
    [WarehousingApi.updateItemPackingSlipEntryAsync.key]: WarehousingApi.updateItemPackingSlipEntryAsync,
    [WarehousingApi.updateItemPickListAsync.key]: WarehousingApi.updateItemPickListAsync,
    [WarehousingApi.updateItemPickListEntryAsync.key]: WarehousingApi.updateItemPickListEntryAsync,
    [WarehousingApi.updateItemRestockAsync.key]: WarehousingApi.updateItemRestockAsync,
    [WarehousingApi.updateItemRestockEntryAsync.key]: WarehousingApi.updateItemRestockEntryAsync,
    [WarehousingApi.updateItemRetainSampleAsync.key]: WarehousingApi.updateItemRetainSampleAsync,
    [WarehousingApi.updateWarehouseAsync.key]: WarehousingApi.updateWarehouseAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
