const AntiforgeryApi = require('../apis/AntiforgeryApi');
const ApplicationPrincipalsApi = require('../apis/ApplicationPrincipalsApi');
const BusinessDomainsApi = require('../apis/BusinessDomainsApi');
const CartsApi = require('../apis/CartsApi');
const ContactOptionsApi = require('../apis/ContactOptionsApi');
const EmailsApi = require('../apis/EmailsApi');
const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const IPLookupsApi = require('../apis/IPLookupsApi');
const InboxApi = require('../apis/InboxApi');
const LicensingApi = require('../apis/LicensingApi');
const MigrationsApi = require('../apis/MigrationsApi');
const ModulesApi = require('../apis/ModulesApi');
const OptionsApi = require('../apis/OptionsApi');
const OutboxApi = require('../apis/OutboxApi');
const OverviewApi = require('../apis/OverviewApi');
const PortalsApi = require('../apis/PortalsApi');
const TenantOptionsApi = require('../apis/TenantOptionsApi');
const TenantsApi = require('../apis/TenantsApi');
const UserOptionsApi = require('../apis/UserOptionsApi');
const UsersApi = require('../apis/UsersApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [AntiforgeryApi.getAndStoreTokens.key]: AntiforgeryApi.getAndStoreTokens,
    [AntiforgeryApi.isRequestValidAsync.key]: AntiforgeryApi.isRequestValidAsync,
    [ApplicationPrincipalsApi.disableGlobalApplicationPrincipal.key]: ApplicationPrincipalsApi.disableGlobalApplicationPrincipal,
    [ApplicationPrincipalsApi.enableGlobalApplicationPrincipal.key]: ApplicationPrincipalsApi.enableGlobalApplicationPrincipal,
    [ApplicationPrincipalsApi.getGlobalApplicationPrincipal.key]: ApplicationPrincipalsApi.getGlobalApplicationPrincipal,
    [ApplicationPrincipalsApi.getGlobalApplicationPrincipals.key]: ApplicationPrincipalsApi.getGlobalApplicationPrincipals,
    [ApplicationPrincipalsApi.getGlobalApplicationPrincipalsCount.key]: ApplicationPrincipalsApi.getGlobalApplicationPrincipalsCount,
    [ApplicationPrincipalsApi.grantGlobalApplicationPrincipalPermission.key]: ApplicationPrincipalsApi.grantGlobalApplicationPrincipalPermission,
    [ApplicationPrincipalsApi.provisionGlobalApplicationPrincipal.key]: ApplicationPrincipalsApi.provisionGlobalApplicationPrincipal,
    [ApplicationPrincipalsApi.provisionPaymentsConnector.key]: ApplicationPrincipalsApi.provisionPaymentsConnector,
    [ApplicationPrincipalsApi.revokeGlobalApplicationPrincipalPermission.key]: ApplicationPrincipalsApi.revokeGlobalApplicationPrincipalPermission,
    [ApplicationPrincipalsApi.suspendGlobalApplicationPrincipal.key]: ApplicationPrincipalsApi.suspendGlobalApplicationPrincipal,
    [BusinessDomainsApi.deleteSystemBusinessDomain.key]: BusinessDomainsApi.deleteSystemBusinessDomain,
    [BusinessDomainsApi.getSystemBusinessDomainById.key]: BusinessDomainsApi.getSystemBusinessDomainById,
    [BusinessDomainsApi.getSystemBusinessDomains.key]: BusinessDomainsApi.getSystemBusinessDomains,
    [BusinessDomainsApi.getSystemBusinessDomainsCount.key]: BusinessDomainsApi.getSystemBusinessDomainsCount,
    [BusinessDomainsApi.verifySystemBusinessDomain.key]: BusinessDomainsApi.verifySystemBusinessDomain,
    [CartsApi.deleteSystemCart.key]: CartsApi.deleteSystemCart,
    [CartsApi.getSystemCartById.key]: CartsApi.getSystemCartById,
    [CartsApi.getSystemCarts.key]: CartsApi.getSystemCarts,
    [CartsApi.getSystemCartsCount.key]: CartsApi.getSystemCartsCount,
    [CartsApi.purgeSystemGuestCarts.key]: CartsApi.purgeSystemGuestCarts,
    [ContactOptionsApi.createSystemContactOption.key]: ContactOptionsApi.createSystemContactOption,
    [ContactOptionsApi.deleteSystemContactOption.key]: ContactOptionsApi.deleteSystemContactOption,
    [ContactOptionsApi.getSystemContactOptionById.key]: ContactOptionsApi.getSystemContactOptionById,
    [ContactOptionsApi.getSystemContactOptions.key]: ContactOptionsApi.getSystemContactOptions,
    [ContactOptionsApi.getSystemContactOptionsCount.key]: ContactOptionsApi.getSystemContactOptionsCount,
    [ContactOptionsApi.patchSystemContactOption.key]: ContactOptionsApi.patchSystemContactOption,
    [ContactOptionsApi.updateSystemContactOption.key]: ContactOptionsApi.updateSystemContactOption,
    [EmailsApi.adminPreviewBasicEmailTemplate.key]: EmailsApi.adminPreviewBasicEmailTemplate,
    [EmailsApi.adminSendBasicEmail.key]: EmailsApi.adminSendBasicEmail,
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [IPLookupsApi.deleteSystemIPLookup.key]: IPLookupsApi.deleteSystemIPLookup,
    [IPLookupsApi.getSystemIPLookupById.key]: IPLookupsApi.getSystemIPLookupById,
    [IPLookupsApi.getSystemIPLookups.key]: IPLookupsApi.getSystemIPLookups,
    [IPLookupsApi.getSystemIPLookupsCount.key]: IPLookupsApi.getSystemIPLookupsCount,
    [InboxApi.cancelInboxMessageRetry.key]: InboxApi.cancelInboxMessageRetry,
    [InboxApi.deadLetterInboxMessage.key]: InboxApi.deadLetterInboxMessage,
    [InboxApi.expediteInboxMessage.key]: InboxApi.expediteInboxMessage,
    [InboxApi.getDuplicateInboxMessages.key]: InboxApi.getDuplicateInboxMessages,
    [InboxApi.getDuplicateInboxMessagesCount.key]: InboxApi.getDuplicateInboxMessagesCount,
    [InboxApi.getInboxCorrelationChain.key]: InboxApi.getInboxCorrelationChain,
    [InboxApi.getInboxHealth.key]: InboxApi.getInboxHealth,
    [InboxApi.getInboxMessage.key]: InboxApi.getInboxMessage,
    [InboxApi.getInboxMessages.key]: InboxApi.getInboxMessages,
    [InboxApi.getInboxMessagesCount.key]: InboxApi.getInboxMessagesCount,
    [InboxApi.quarantineInboxMessage.key]: InboxApi.quarantineInboxMessage,
    [InboxApi.releaseInboxMessageLease.key]: InboxApi.releaseInboxMessageLease,
    [InboxApi.replayInboxMessage.key]: InboxApi.replayInboxMessage,
    [LicensingApi.getAttributesForLicenseAsync.key]: LicensingApi.getAttributesForLicenseAsync,
    [LicensingApi.getFeaturesForLicenseAsync.key]: LicensingApi.getFeaturesForLicenseAsync,
    [LicensingApi.getLicenseAssignmentsAsync.key]: LicensingApi.getLicenseAssignmentsAsync,
    [LicensingApi.getLicenseByIdAsync.key]: LicensingApi.getLicenseByIdAsync,
    [LicensingApi.getLicenseRecordsQuotaAsync.key]: LicensingApi.getLicenseRecordsQuotaAsync,
    [LicensingApi.getLicensesAsync.key]: LicensingApi.getLicensesAsync,
    [LicensingApi.redeemLicenseAsync.key]: LicensingApi.redeemLicenseAsync,
    [LicensingApi.validateLicenseAsync.key]: LicensingApi.validateLicenseAsync,
    [MigrationsApi.migrate.key]: MigrationsApi.migrate,
    [MigrationsApi.migrations.key]: MigrationsApi.migrations,
    [ModulesApi.getAllModules.key]: ModulesApi.getAllModules,
    [ModulesApi.getAvailableModules.key]: ModulesApi.getAvailableModules,
    [OptionsApi.createSystemOption.key]: OptionsApi.createSystemOption,
    [OptionsApi.deleteSystemOption.key]: OptionsApi.deleteSystemOption,
    [OptionsApi.getSystemOptionById.key]: OptionsApi.getSystemOptionById,
    [OptionsApi.getSystemOptionByKey.key]: OptionsApi.getSystemOptionByKey,
    [OptionsApi.getSystemOptions.key]: OptionsApi.getSystemOptions,
    [OptionsApi.getSystemOptionsCount.key]: OptionsApi.getSystemOptionsCount,
    [OptionsApi.patchSystemOption.key]: OptionsApi.patchSystemOption,
    [OptionsApi.updateSystemOption.key]: OptionsApi.updateSystemOption,
    [OptionsApi.upsertSystemOption.key]: OptionsApi.upsertSystemOption,
    [OutboxApi.cancelOutboxMessage.key]: OutboxApi.cancelOutboxMessage,
    [OutboxApi.deadLetterOutboxMessage.key]: OutboxApi.deadLetterOutboxMessage,
    [OutboxApi.expediteOutboxMessage.key]: OutboxApi.expediteOutboxMessage,
    [OutboxApi.getOutboxCorrelationChain.key]: OutboxApi.getOutboxCorrelationChain,
    [OutboxApi.getOutboxHealth.key]: OutboxApi.getOutboxHealth,
    [OutboxApi.getOutboxMessage.key]: OutboxApi.getOutboxMessage,
    [OutboxApi.getOutboxMessages.key]: OutboxApi.getOutboxMessages,
    [OutboxApi.getOutboxMessagesCount.key]: OutboxApi.getOutboxMessagesCount,
    [OutboxApi.releaseOutboxMessageLease.key]: OutboxApi.releaseOutboxMessageLease,
    [OutboxApi.replayOutboxMessage.key]: OutboxApi.replayOutboxMessage,
    [OverviewApi.getSystemOverview.key]: OverviewApi.getSystemOverview,
    [PortalsApi.createSystemPortal.key]: PortalsApi.createSystemPortal,
    [PortalsApi.deleteSystemPortal.key]: PortalsApi.deleteSystemPortal,
    [PortalsApi.getSystemPortalById.key]: PortalsApi.getSystemPortalById,
    [PortalsApi.getSystemPortals.key]: PortalsApi.getSystemPortals,
    [PortalsApi.getSystemPortalsCount.key]: PortalsApi.getSystemPortalsCount,
    [PortalsApi.patchSystemPortal.key]: PortalsApi.patchSystemPortal,
    [PortalsApi.updateSystemPortal.key]: PortalsApi.updateSystemPortal,
    [TenantOptionsApi.createSystemTenantOption.key]: TenantOptionsApi.createSystemTenantOption,
    [TenantOptionsApi.deleteSystemTenantOption.key]: TenantOptionsApi.deleteSystemTenantOption,
    [TenantOptionsApi.getSystemTenantOptionById.key]: TenantOptionsApi.getSystemTenantOptionById,
    [TenantOptionsApi.getSystemTenantOptions.key]: TenantOptionsApi.getSystemTenantOptions,
    [TenantOptionsApi.getSystemTenantOptionsCount.key]: TenantOptionsApi.getSystemTenantOptionsCount,
    [TenantOptionsApi.patchSystemTenantOption.key]: TenantOptionsApi.patchSystemTenantOption,
    [TenantOptionsApi.updateSystemTenantOption.key]: TenantOptionsApi.updateSystemTenantOption,
    [TenantsApi.adminPreviewTenantEmail.key]: TenantsApi.adminPreviewTenantEmail,
    [TenantsApi.adminSendTenantEmail.key]: TenantsApi.adminSendTenantEmail,
    [TenantsApi.createTenant.key]: TenantsApi.createTenant,
    [TenantsApi.deleteTenant.key]: TenantsApi.deleteTenant,
    [TenantsApi.getAllExtendedTenants.key]: TenantsApi.getAllExtendedTenants,
    [TenantsApi.getAllTenants.key]: TenantsApi.getAllTenants,
    [TenantsApi.getExtendedTenantsCount.key]: TenantsApi.getExtendedTenantsCount,
    [TenantsApi.getTenant.key]: TenantsApi.getTenant,
    [TenantsApi.getTenantModuleGrants.key]: TenantsApi.getTenantModuleGrants,
    [TenantsApi.getTenantsCount.key]: TenantsApi.getTenantsCount,
    [TenantsApi.patchTenant.key]: TenantsApi.patchTenant,
    [TenantsApi.setTenantModuleGrants.key]: TenantsApi.setTenantModuleGrants,
    [TenantsApi.updateTenant.key]: TenantsApi.updateTenant,
    [UserOptionsApi.createSystemUserOption.key]: UserOptionsApi.createSystemUserOption,
    [UserOptionsApi.deleteSystemUserOption.key]: UserOptionsApi.deleteSystemUserOption,
    [UserOptionsApi.getSystemUserOptionById.key]: UserOptionsApi.getSystemUserOptionById,
    [UserOptionsApi.getSystemUserOptions.key]: UserOptionsApi.getSystemUserOptions,
    [UserOptionsApi.getSystemUserOptionsCount.key]: UserOptionsApi.getSystemUserOptionsCount,
    [UserOptionsApi.patchSystemUserOption.key]: UserOptionsApi.patchSystemUserOption,
    [UserOptionsApi.updateSystemUserOption.key]: UserOptionsApi.updateSystemUserOption,
    [UsersApi.adminPreviewUserEmailTemplate.key]: UsersApi.adminPreviewUserEmailTemplate,
    [UsersApi.adminSendUserEmail.key]: UsersApi.adminSendUserEmail,
    [UsersApi.createAccountHolderAsync.key]: UsersApi.createAccountHolderAsync,
    [UsersApi.deleteAccountHolderAsync.key]: UsersApi.deleteAccountHolderAsync,
    [UsersApi.getExtendedAccountHolderAsync.key]: UsersApi.getExtendedAccountHolderAsync,
    [UsersApi.getExtendedUsersAsync.key]: UsersApi.getExtendedUsersAsync,
    [UsersApi.getExtendedUsersCountAsync.key]: UsersApi.getExtendedUsersCountAsync,
    [UsersApi.getUserAdminDetailAsync.key]: UsersApi.getUserAdminDetailAsync,
    [UsersApi.getUserAsync.key]: UsersApi.getUserAsync,
    [UsersApi.getUsersAsync.key]: UsersApi.getUsersAsync,
    [UsersApi.getUsersCountAsync.key]: UsersApi.getUsersCountAsync,
    [UsersApi.patchAccountHolderAsync.key]: UsersApi.patchAccountHolderAsync,
    [UsersApi.setUserPasswordAsync.key]: UsersApi.setUserPasswordAsync,
    [UsersApi.updateAccountHolderAdminProfileAsync.key]: UsersApi.updateAccountHolderAdminProfileAsync,
    [UsersApi.updateAccountHolderAsync.key]: UsersApi.updateAccountHolderAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
