const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}invoiceId`,
                label: `[${labelPrefix}invoiceId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}emisorWalletId`,
                label: `[${labelPrefix}emisorWalletId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}receiverWalletId`,
                label: `[${labelPrefix}receiverWalletId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}currencyId`,
                label: `[${labelPrefix}currencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}forexRate`,
                label: `[${labelPrefix}forexRate]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalCost`,
                label: `[${labelPrefix}totalCost]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxes`,
                label: `[${labelPrefix}totalTaxes]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}closed`,
                label: `[${labelPrefix}closed]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}data`,
                label: `[${labelPrefix}data]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dataLabel`,
                label: `[${labelPrefix}dataLabel]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data1`,
                label: `[${labelPrefix}data1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data1Label`,
                label: `[${labelPrefix}data1Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}response`,
                label: `[${labelPrefix}response]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}authorization`,
                label: `[${labelPrefix}authorization]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}referenceCode`,
                label: `[${labelPrefix}referenceCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}correlationCode`,
                label: `[${labelPrefix}correlationCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lastUpdated`,
                label: `[${labelPrefix}lastUpdated]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}onBehalfOf`,
                label: `[${labelPrefix}onBehalfOf]`,
                type: 'string',
                choices: [
                    'Self',
                    'Tenant',
                    'Individual',
                    'Organization',
                ],
            },
            {
                key: `${keyPrefix}paymentType`,
                label: `[${labelPrefix}paymentType]`,
                type: 'string',
                choices: [
                    'Paid',
                    'Received',
                    'Internal',
                ],
            },
            {
                key: `${keyPrefix}paymentStatus`,
                label: `[${labelPrefix}paymentStatus]`,
                type: 'string',
                choices: [
                    'Unset',
                    'Accepted',
                    'Rejected',
                    'OnHold',
                    'Failed',
                    'Reversed',
                    'Retained',
                    'Initialized',
                    'Expired',
                    'Abandoned',
                    'Cancelled',
                    'AcceptedRetained',
                ],
            },
            {
                key: `${keyPrefix}baseCost`,
                label: `[${labelPrefix}baseCost]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}signature`,
                label: `[${labelPrefix}signature]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}signatureMismatch`,
                label: `[${labelPrefix}signatureMismatch]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isExternal`,
                label: `[${labelPrefix}isExternal]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}markedForRevision`,
                label: `[${labelPrefix}markedForRevision]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}forexRatesSnapshot`,
                label: `[${labelPrefix}forexRatesSnapshot]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}officialId`,
                label: `[${labelPrefix}officialId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}officialIdExpeditionDate`,
                label: `[${labelPrefix}officialIdExpeditionDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}fiscalIdentificationTypeId`,
                label: `[${labelPrefix}fiscalIdentificationTypeId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingAddress`,
                label: `[${labelPrefix}billingAddress]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}phone`,
                label: `[${labelPrefix}phone]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cellphone`,
                label: `[${labelPrefix}cellphone]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}department`,
                label: `[${labelPrefix}department]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}city`,
                label: `[${labelPrefix}city]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryId`,
                label: `[${labelPrefix}countryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}locationId`,
                label: `[${labelPrefix}locationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}entitlementId`,
                label: `[${labelPrefix}entitlementId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}antiFraudScore`,
                label: `[${labelPrefix}antiFraudScore]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}callRecordURL`,
                label: `[${labelPrefix}callRecordURL]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}called`,
                label: `[${labelPrefix}called]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}verified`,
                label: `[${labelPrefix}verified]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}payerPictureTimestamp`,
                label: `[${labelPrefix}payerPictureTimestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}payerPicture`,
                label: `[${labelPrefix}payerPicture]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}identificationPictureTimestamp`,
                label: `[${labelPrefix}identificationPictureTimestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}identificationPicture`,
                label: `[${labelPrefix}identificationPicture]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}identificationBackPicture`,
                label: `[${labelPrefix}identificationBackPicture]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}identificationBackPictureTimestamp`,
                label: `[${labelPrefix}identificationBackPictureTimestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ipLookupId`,
                label: `[${labelPrefix}ipLookupId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}orderId`,
                label: `[${labelPrefix}orderId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}accountingEntryId`,
                label: `[${labelPrefix}accountingEntryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}paymentGatewayId`,
                label: `[${labelPrefix}paymentGatewayId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}bankAccountId`,
                label: `[${labelPrefix}bankAccountId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}bankId`,
                label: `[${labelPrefix}bankId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}paymentTokenId`,
                label: `[${labelPrefix}paymentTokenId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}emisorWalletAccountId`,
                label: `[${labelPrefix}emisorWalletAccountId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}receiverWalletAccountId`,
                label: `[${labelPrefix}receiverWalletAccountId]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'invoiceId': bundle.inputData?.[`${keyPrefix}invoiceId`],
            'emisorWalletId': bundle.inputData?.[`${keyPrefix}emisorWalletId`],
            'receiverWalletId': bundle.inputData?.[`${keyPrefix}receiverWalletId`],
            'currencyId': bundle.inputData?.[`${keyPrefix}currencyId`],
            'forexRate': bundle.inputData?.[`${keyPrefix}forexRate`],
            'totalCost': bundle.inputData?.[`${keyPrefix}totalCost`],
            'totalTaxes': bundle.inputData?.[`${keyPrefix}totalTaxes`],
            'closed': bundle.inputData?.[`${keyPrefix}closed`],
            'data': bundle.inputData?.[`${keyPrefix}data`],
            'dataLabel': bundle.inputData?.[`${keyPrefix}dataLabel`],
            'data1': bundle.inputData?.[`${keyPrefix}data1`],
            'data1Label': bundle.inputData?.[`${keyPrefix}data1Label`],
            'response': bundle.inputData?.[`${keyPrefix}response`],
            'authorization': bundle.inputData?.[`${keyPrefix}authorization`],
            'referenceCode': bundle.inputData?.[`${keyPrefix}referenceCode`],
            'correlationCode': bundle.inputData?.[`${keyPrefix}correlationCode`],
            'lastUpdated': bundle.inputData?.[`${keyPrefix}lastUpdated`],
            'onBehalfOf': bundle.inputData?.[`${keyPrefix}onBehalfOf`],
            'paymentType': bundle.inputData?.[`${keyPrefix}paymentType`],
            'paymentStatus': bundle.inputData?.[`${keyPrefix}paymentStatus`],
            'baseCost': bundle.inputData?.[`${keyPrefix}baseCost`],
            'signature': bundle.inputData?.[`${keyPrefix}signature`],
            'signatureMismatch': bundle.inputData?.[`${keyPrefix}signatureMismatch`],
            'isExternal': bundle.inputData?.[`${keyPrefix}isExternal`],
            'markedForRevision': bundle.inputData?.[`${keyPrefix}markedForRevision`],
            'forexRatesSnapshot': bundle.inputData?.[`${keyPrefix}forexRatesSnapshot`],
            'officialId': bundle.inputData?.[`${keyPrefix}officialId`],
            'officialIdExpeditionDate': bundle.inputData?.[`${keyPrefix}officialIdExpeditionDate`],
            'fiscalIdentificationTypeId': bundle.inputData?.[`${keyPrefix}fiscalIdentificationTypeId`],
            'billingAddress': bundle.inputData?.[`${keyPrefix}billingAddress`],
            'phone': bundle.inputData?.[`${keyPrefix}phone`],
            'cellphone': bundle.inputData?.[`${keyPrefix}cellphone`],
            'department': bundle.inputData?.[`${keyPrefix}department`],
            'city': bundle.inputData?.[`${keyPrefix}city`],
            'countryId': bundle.inputData?.[`${keyPrefix}countryId`],
            'locationId': bundle.inputData?.[`${keyPrefix}locationId`],
            'entitlementId': bundle.inputData?.[`${keyPrefix}entitlementId`],
            'antiFraudScore': bundle.inputData?.[`${keyPrefix}antiFraudScore`],
            'callRecordURL': bundle.inputData?.[`${keyPrefix}callRecordURL`],
            'called': bundle.inputData?.[`${keyPrefix}called`],
            'verified': bundle.inputData?.[`${keyPrefix}verified`],
            'payerPictureTimestamp': bundle.inputData?.[`${keyPrefix}payerPictureTimestamp`],
            'payerPicture': bundle.inputData?.[`${keyPrefix}payerPicture`],
            'identificationPictureTimestamp': bundle.inputData?.[`${keyPrefix}identificationPictureTimestamp`],
            'identificationPicture': bundle.inputData?.[`${keyPrefix}identificationPicture`],
            'identificationBackPicture': bundle.inputData?.[`${keyPrefix}identificationBackPicture`],
            'identificationBackPictureTimestamp': bundle.inputData?.[`${keyPrefix}identificationBackPictureTimestamp`],
            'ipLookupId': bundle.inputData?.[`${keyPrefix}ipLookupId`],
            'orderId': bundle.inputData?.[`${keyPrefix}orderId`],
            'accountingEntryId': bundle.inputData?.[`${keyPrefix}accountingEntryId`],
            'paymentGatewayId': bundle.inputData?.[`${keyPrefix}paymentGatewayId`],
            'bankAccountId': bundle.inputData?.[`${keyPrefix}bankAccountId`],
            'bankId': bundle.inputData?.[`${keyPrefix}bankId`],
            'paymentTokenId': bundle.inputData?.[`${keyPrefix}paymentTokenId`],
            'emisorWalletAccountId': bundle.inputData?.[`${keyPrefix}emisorWalletAccountId`],
            'receiverWalletAccountId': bundle.inputData?.[`${keyPrefix}receiverWalletAccountId`],
        }
    },
}
