const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const ProjectTasksApi = require('../apis/ProjectTasksApi');
const ProjectsApi = require('../apis/ProjectsApi');
const TaskCategoriesApi = require('../apis/TaskCategoriesApi');
const TaskTypesApi = require('../apis/TaskTypesApi');
const TimeLogApprovalsApi = require('../apis/TimeLogApprovalsApi');
const TimeLogsApi = require('../apis/TimeLogsApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [ProjectTasksApi.createProjectTaskAsync.key]: ProjectTasksApi.createProjectTaskAsync,
    [ProjectTasksApi.deleteProjectTaskAsync.key]: ProjectTasksApi.deleteProjectTaskAsync,
    [ProjectTasksApi.getProjectTaskByIdAsync.key]: ProjectTasksApi.getProjectTaskByIdAsync,
    [ProjectTasksApi.getProjectTasksAsync.key]: ProjectTasksApi.getProjectTasksAsync,
    [ProjectTasksApi.getProjectTasksCountAsync.key]: ProjectTasksApi.getProjectTasksCountAsync,
    [ProjectTasksApi.patchProjectTaskAsync.key]: ProjectTasksApi.patchProjectTaskAsync,
    [ProjectTasksApi.updateProjectTaskAsync.key]: ProjectTasksApi.updateProjectTaskAsync,
    [ProjectsApi.createProjectAsync.key]: ProjectsApi.createProjectAsync,
    [ProjectsApi.createProjectPeriodAsync.key]: ProjectsApi.createProjectPeriodAsync,
    [ProjectsApi.createTaskForProjectAsync.key]: ProjectsApi.createTaskForProjectAsync,
    [ProjectsApi.deleteProjectAsync.key]: ProjectsApi.deleteProjectAsync,
    [ProjectsApi.deleteProjectPeriodAsync.key]: ProjectsApi.deleteProjectPeriodAsync,
    [ProjectsApi.deleteTaskForProjectAsync.key]: ProjectsApi.deleteTaskForProjectAsync,
    [ProjectsApi.getProjectByIdAsync.key]: ProjectsApi.getProjectByIdAsync,
    [ProjectsApi.getProjectPeriodsAsync.key]: ProjectsApi.getProjectPeriodsAsync,
    [ProjectsApi.getProjectTaskCategoriesAsync.key]: ProjectsApi.getProjectTaskCategoriesAsync,
    [ProjectsApi.getProjectTaskCategoriesCountAsync.key]: ProjectsApi.getProjectTaskCategoriesCountAsync,
    [ProjectsApi.getProjectTimeLogsCountAsync.key]: ProjectsApi.getProjectTimeLogsCountAsync,
    [ProjectsApi.getProjectsByTenantIdAsync.key]: ProjectsApi.getProjectsByTenantIdAsync,
    [ProjectsApi.getProjectsCountByTenantIdAsync.key]: ProjectsApi.getProjectsCountByTenantIdAsync,
    [ProjectsApi.getTasksForProjectAsync.key]: ProjectsApi.getTasksForProjectAsync,
    [ProjectsApi.getTasksForProjectCountAsync.key]: ProjectsApi.getTasksForProjectCountAsync,
    [ProjectsApi.getTimeLogsForProjectAsync.key]: ProjectsApi.getTimeLogsForProjectAsync,
    [ProjectsApi.patchProjectAsync.key]: ProjectsApi.patchProjectAsync,
    [ProjectsApi.patchProjectPeriodAsync.key]: ProjectsApi.patchProjectPeriodAsync,
    [ProjectsApi.patchTaskForProjectAsync.key]: ProjectsApi.patchTaskForProjectAsync,
    [ProjectsApi.updateProjectAsync.key]: ProjectsApi.updateProjectAsync,
    [ProjectsApi.updateProjectPeriodAsync.key]: ProjectsApi.updateProjectPeriodAsync,
    [ProjectsApi.updateTaskForProjectAsync.key]: ProjectsApi.updateTaskForProjectAsync,
    [TaskCategoriesApi.countTenantTaskCategoriesAsync.key]: TaskCategoriesApi.countTenantTaskCategoriesAsync,
    [TaskCategoriesApi.createTaskCategoryAsync.key]: TaskCategoriesApi.createTaskCategoryAsync,
    [TaskCategoriesApi.deleteTaskCategoryAsync.key]: TaskCategoriesApi.deleteTaskCategoryAsync,
    [TaskCategoriesApi.getTaskCategoryByIdAsync.key]: TaskCategoriesApi.getTaskCategoryByIdAsync,
    [TaskCategoriesApi.getTaskCategoryTaskTypesAsync.key]: TaskCategoriesApi.getTaskCategoryTaskTypesAsync,
    [TaskCategoriesApi.getTenantTaskCategoriesAsync.key]: TaskCategoriesApi.getTenantTaskCategoriesAsync,
    [TaskCategoriesApi.patchTaskCategoryAsync.key]: TaskCategoriesApi.patchTaskCategoryAsync,
    [TaskCategoriesApi.updateTaskCategoryAsync.key]: TaskCategoriesApi.updateTaskCategoryAsync,
    [TaskTypesApi.createTaskTypeAsync.key]: TaskTypesApi.createTaskTypeAsync,
    [TaskTypesApi.deleteTaskTypeAsync.key]: TaskTypesApi.deleteTaskTypeAsync,
    [TaskTypesApi.getTaskTypeByIdAsync.key]: TaskTypesApi.getTaskTypeByIdAsync,
    [TaskTypesApi.patchTaskTypeAsync.key]: TaskTypesApi.patchTaskTypeAsync,
    [TaskTypesApi.updateTaskTypeAsync.key]: TaskTypesApi.updateTaskTypeAsync,
    [TimeLogApprovalsApi.requestProjectHoursApprovalAsync.key]: TimeLogApprovalsApi.requestProjectHoursApprovalAsync,
    [TimeLogApprovalsApi.updateProjectHoursApprovalApproverAsync.key]: TimeLogApprovalsApi.updateProjectHoursApprovalApproverAsync,
    [TimeLogApprovalsApi.updateProjectHoursApprovalStatusAsync.key]: TimeLogApprovalsApi.updateProjectHoursApprovalStatusAsync,
    [TimeLogsApi.countProjectPeriodTimeLogsAsync.key]: TimeLogsApi.countProjectPeriodTimeLogsAsync,
    [TimeLogsApi.createProjectTimeLogAsync.key]: TimeLogsApi.createProjectTimeLogAsync,
    [TimeLogsApi.deleteProjectTimeLogAsync.key]: TimeLogsApi.deleteProjectTimeLogAsync,
    [TimeLogsApi.getProjectPeriodTimeLogsAsync.key]: TimeLogsApi.getProjectPeriodTimeLogsAsync,
    [TimeLogsApi.getProjectTimeLogByIdAsync.key]: TimeLogsApi.getProjectTimeLogByIdAsync,
    [TimeLogsApi.getProjectTimeLogsAsync.key]: TimeLogsApi.getProjectTimeLogsAsync,
    [TimeLogsApi.getProjectTimeLogsByResponsibleContactAsync.key]: TimeLogsApi.getProjectTimeLogsByResponsibleContactAsync,
    [TimeLogsApi.getProjectTimeLogsCreatedByContactAsync.key]: TimeLogsApi.getProjectTimeLogsCreatedByContactAsync,
    [TimeLogsApi.patchProjectTimeLogAsync.key]: TimeLogsApi.patchProjectTimeLogAsync,
    [TimeLogsApi.updateProjectTimeLogAsync.key]: TimeLogsApi.updateProjectTimeLogAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
