const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const ProjectsApi = require('../apis/ProjectsApi');
const TaskCategoriesApi = require('../apis/TaskCategoriesApi');
const TaskTypesApi = require('../apis/TaskTypesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [ProjectsApi.createProjectAsync.key]: ProjectsApi.createProjectAsync,
    [ProjectsApi.createProjectPeriodAsync.key]: ProjectsApi.createProjectPeriodAsync,
    [ProjectsApi.createProjectTaskAsync.key]: ProjectsApi.createProjectTaskAsync,
    [ProjectsApi.deleteProjectAsync.key]: ProjectsApi.deleteProjectAsync,
    [ProjectsApi.deleteProjectPeriodAsync.key]: ProjectsApi.deleteProjectPeriodAsync,
    [ProjectsApi.deleteProjectTaskAsync.key]: ProjectsApi.deleteProjectTaskAsync,
    [ProjectsApi.getProjectByIdAsync.key]: ProjectsApi.getProjectByIdAsync,
    [ProjectsApi.getProjectPeriodsAsync.key]: ProjectsApi.getProjectPeriodsAsync,
    [ProjectsApi.getProjectTaskCategoriesAsync.key]: ProjectsApi.getProjectTaskCategoriesAsync,
    [ProjectsApi.getProjectTaskCategoriesCountAsync.key]: ProjectsApi.getProjectTaskCategoriesCountAsync,
    [ProjectsApi.getProjectTasksAsync.key]: ProjectsApi.getProjectTasksAsync,
    [ProjectsApi.getProjectTasksCountAsync.key]: ProjectsApi.getProjectTasksCountAsync,
    [ProjectsApi.getProjectTimeLogsAsync.key]: ProjectsApi.getProjectTimeLogsAsync,
    [ProjectsApi.getProjectTimeLogsCountAsync.key]: ProjectsApi.getProjectTimeLogsCountAsync,
    [ProjectsApi.getProjectsByTenantIdAsync.key]: ProjectsApi.getProjectsByTenantIdAsync,
    [ProjectsApi.getProjectsCountByTenantIdAsync.key]: ProjectsApi.getProjectsCountByTenantIdAsync,
    [ProjectsApi.updateProjectAsync.key]: ProjectsApi.updateProjectAsync,
    [ProjectsApi.updateProjectPeriodAsync.key]: ProjectsApi.updateProjectPeriodAsync,
    [ProjectsApi.updateProjectTaskAsync.key]: ProjectsApi.updateProjectTaskAsync,
    [TaskCategoriesApi.countTenantTaskCategoriesAsync.key]: TaskCategoriesApi.countTenantTaskCategoriesAsync,
    [TaskCategoriesApi.createTaskCategoryAsync.key]: TaskCategoriesApi.createTaskCategoryAsync,
    [TaskCategoriesApi.deleteTaskCategoryAsync.key]: TaskCategoriesApi.deleteTaskCategoryAsync,
    [TaskCategoriesApi.getTaskCategoryByIdAsync.key]: TaskCategoriesApi.getTaskCategoryByIdAsync,
    [TaskCategoriesApi.getTaskCategoryTaskTypesAsync.key]: TaskCategoriesApi.getTaskCategoryTaskTypesAsync,
    [TaskCategoriesApi.getTenantTaskCategoriesAsync.key]: TaskCategoriesApi.getTenantTaskCategoriesAsync,
    [TaskCategoriesApi.updateTaskCategoryAsync.key]: TaskCategoriesApi.updateTaskCategoryAsync,
    [TaskTypesApi.createTaskTypeAsync.key]: TaskTypesApi.createTaskTypeAsync,
    [TaskTypesApi.deleteTaskTypeAsync.key]: TaskTypesApi.deleteTaskTypeAsync,
    [TaskTypesApi.getTaskTypeByIdAsync.key]: TaskTypesApi.getTaskTypeByIdAsync,
    [TaskTypesApi.updateTaskTypeAsync.key]: TaskTypesApi.updateTaskTypeAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
