const utils = require('../utils/utils');
const OrderLineCreateDto = require('../models/OrderLineCreateDto');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}closed`,
                label: `[${labelPrefix}closed]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}priceListId`,
                label: `[${labelPrefix}priceListId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}individualId`,
                label: `[${labelPrefix}individualId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}paymentTermId`,
                label: `[${labelPrefix}paymentTermId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}organizationId`,
                label: `[${labelPrefix}organizationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}firstName`,
                label: `[${labelPrefix}firstName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lastName`,
                label: `[${labelPrefix}lastName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}companyName`,
                label: `[${labelPrefix}companyName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingEmail`,
                label: `[${labelPrefix}billingEmail]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine1`,
                label: `[${labelPrefix}addressLine1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine2`,
                label: `[${labelPrefix}addressLine2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}postalCode`,
                label: `[${labelPrefix}postalCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryId`,
                label: `[${labelPrefix}countryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}stateId`,
                label: `[${labelPrefix}stateId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cityId`,
                label: `[${labelPrefix}cityId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}forexRate`,
                label: `[${labelPrefix}forexRate]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}currencyId`,
                label: `[${labelPrefix}currencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDetail`,
                label: `[${labelPrefix}totalDetail]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDetailCurrencyId`,
                label: `[${labelPrefix}totalDetailCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalProfit`,
                label: `[${labelPrefix}totalProfit]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalProfitCurrencyId`,
                label: `[${labelPrefix}totalProfitCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDiscounts`,
                label: `[${labelPrefix}totalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalSurcharges`,
                label: `[${labelPrefix}totalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingCost`,
                label: `[${labelPrefix}totalShippingCost]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingCostCurrencyId`,
                label: `[${labelPrefix}totalShippingCostCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingTax`,
                label: `[${labelPrefix}totalShippingTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingTaxCurrencyId`,
                label: `[${labelPrefix}totalShippingTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalWithheldTax`,
                label: `[${labelPrefix}totalWithheldTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalWithheldTaxCurrencyId`,
                label: `[${labelPrefix}totalWithheldTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxBase`,
                label: `[${labelPrefix}totalTaxBase]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxBaseCurrencyId`,
                label: `[${labelPrefix}totalTaxBaseCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxes`,
                label: `[${labelPrefix}totalTaxes]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxesCurrencyId`,
                label: `[${labelPrefix}totalTaxesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalSurcharges`,
                label: `[${labelPrefix}totalGlobalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalGlobalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalDiscounts`,
                label: `[${labelPrefix}totalGlobalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalGlobalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}total`,
                label: `[${labelPrefix}total]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalCurrencyId`,
                label: `[${labelPrefix}totalCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}costCalculationMethod`,
                label: `[${labelPrefix}costCalculationMethod]`,
                type: 'string',
                choices: [
                    'Automatic',
                    'Custom',
                ],
            },
            {
                key: `${keyPrefix}taxCalculationMethod`,
                label: `[${labelPrefix}taxCalculationMethod]`,
                type: 'string',
                choices: [
                    'Included',
                    'Excluded',
                ],
            },
            {
                key: `${keyPrefix}cartId`,
                label: `[${labelPrefix}cartId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}quoteId`,
                label: `[${labelPrefix}quoteId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}walletId`,
                label: `[${labelPrefix}walletId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}parentOrderId`,
                label: `[${labelPrefix}parentOrderId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingMethodId`,
                label: `[${labelPrefix}shippingMethodId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingLocationId`,
                label: `[${labelPrefix}billingLocationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}customerNotes`,
                label: `[${labelPrefix}customerNotes]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}orderStatus`,
                label: `[${labelPrefix}orderStatus]`,
                type: 'string',
                choices: [
                    'New',
                    'Processing',
                    'Accepted',
                    'Declined',
                    'Shipped',
                    'Delivered',
                    'OnHold',
                    'Failed',
                    'Fulfilled',
                    'Cancelled',
                ],
            },
            {
                key: `${keyPrefix}quoteStatus`,
                label: `[${labelPrefix}quoteStatus]`,
                type: 'string',
                choices: [
                    'Draft',
                    'New',
                    'Accepted',
                    'Declined',
                    'Expired',
                ],
            },
            {
                key: `${keyPrefix}freightTerms`,
                label: `[${labelPrefix}freightTerms]`,
                type: 'string',
                choices: [
                    'FOB',
                    'NoCharge',
                ],
            },
            {
                key: `${keyPrefix}receiverTenantId`,
                label: `[${labelPrefix}receiverTenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingLocationId`,
                label: `[${labelPrefix}shippingLocationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}qualifiedIdentifier`,
                label: `[${labelPrefix}qualifiedIdentifier]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxesInUsd`,
                label: `[${labelPrefix}totalTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDiscountsInUsd`,
                label: `[${labelPrefix}totalDiscountsInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalSurchargesInUsd`,
                label: `[${labelPrefix}totalSurchargesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingCostInUsd`,
                label: `[${labelPrefix}totalShippingCostInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingTaxInUsd`,
                label: `[${labelPrefix}totalShippingTaxInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalAmountInUsd`,
                label: `[${labelPrefix}totalAmountInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}effectiveTo`,
                label: `[${labelPrefix}effectiveTo]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}effectiveFrom`,
                label: `[${labelPrefix}effectiveFrom]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}orderLines`,
                label: `[${labelPrefix}orderLines]`,
                children: OrderLineCreateDto.fields(`${keyPrefix}orderLines${!isInput ? '[]' : ''}`, isInput, true), 
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'closed': bundle.inputData?.[`${keyPrefix}closed`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'priceListId': bundle.inputData?.[`${keyPrefix}priceListId`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'individualId': bundle.inputData?.[`${keyPrefix}individualId`],
            'paymentTermId': bundle.inputData?.[`${keyPrefix}paymentTermId`],
            'organizationId': bundle.inputData?.[`${keyPrefix}organizationId`],
            'firstName': bundle.inputData?.[`${keyPrefix}firstName`],
            'lastName': bundle.inputData?.[`${keyPrefix}lastName`],
            'companyName': bundle.inputData?.[`${keyPrefix}companyName`],
            'billingEmail': bundle.inputData?.[`${keyPrefix}billingEmail`],
            'addressLine1': bundle.inputData?.[`${keyPrefix}addressLine1`],
            'addressLine2': bundle.inputData?.[`${keyPrefix}addressLine2`],
            'postalCode': bundle.inputData?.[`${keyPrefix}postalCode`],
            'countryId': bundle.inputData?.[`${keyPrefix}countryId`],
            'stateId': bundle.inputData?.[`${keyPrefix}stateId`],
            'cityId': bundle.inputData?.[`${keyPrefix}cityId`],
            'forexRate': bundle.inputData?.[`${keyPrefix}forexRate`],
            'currencyId': bundle.inputData?.[`${keyPrefix}currencyId`],
            'totalDetail': bundle.inputData?.[`${keyPrefix}totalDetail`],
            'totalDetailCurrencyId': bundle.inputData?.[`${keyPrefix}totalDetailCurrencyId`],
            'totalProfit': bundle.inputData?.[`${keyPrefix}totalProfit`],
            'totalProfitCurrencyId': bundle.inputData?.[`${keyPrefix}totalProfitCurrencyId`],
            'totalDiscounts': bundle.inputData?.[`${keyPrefix}totalDiscounts`],
            'totalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalDiscountsCurrencyId`],
            'totalSurcharges': bundle.inputData?.[`${keyPrefix}totalSurcharges`],
            'totalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalSurchargesCurrencyId`],
            'totalShippingCost': bundle.inputData?.[`${keyPrefix}totalShippingCost`],
            'totalShippingCostCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingCostCurrencyId`],
            'totalShippingTax': bundle.inputData?.[`${keyPrefix}totalShippingTax`],
            'totalShippingTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingTaxCurrencyId`],
            'totalWithheldTax': bundle.inputData?.[`${keyPrefix}totalWithheldTax`],
            'totalWithheldTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalWithheldTaxCurrencyId`],
            'totalTaxBase': bundle.inputData?.[`${keyPrefix}totalTaxBase`],
            'totalTaxBaseCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxBaseCurrencyId`],
            'totalTaxes': bundle.inputData?.[`${keyPrefix}totalTaxes`],
            'totalTaxesCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxesCurrencyId`],
            'totalGlobalSurcharges': bundle.inputData?.[`${keyPrefix}totalGlobalSurcharges`],
            'totalGlobalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalSurchargesCurrencyId`],
            'totalGlobalDiscounts': bundle.inputData?.[`${keyPrefix}totalGlobalDiscounts`],
            'totalGlobalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalDiscountsCurrencyId`],
            'total': bundle.inputData?.[`${keyPrefix}total`],
            'totalCurrencyId': bundle.inputData?.[`${keyPrefix}totalCurrencyId`],
            'costCalculationMethod': bundle.inputData?.[`${keyPrefix}costCalculationMethod`],
            'taxCalculationMethod': bundle.inputData?.[`${keyPrefix}taxCalculationMethod`],
            'cartId': bundle.inputData?.[`${keyPrefix}cartId`],
            'quoteId': bundle.inputData?.[`${keyPrefix}quoteId`],
            'walletId': bundle.inputData?.[`${keyPrefix}walletId`],
            'parentOrderId': bundle.inputData?.[`${keyPrefix}parentOrderId`],
            'shippingMethodId': bundle.inputData?.[`${keyPrefix}shippingMethodId`],
            'billingLocationId': bundle.inputData?.[`${keyPrefix}billingLocationId`],
            'customerNotes': bundle.inputData?.[`${keyPrefix}customerNotes`],
            'orderStatus': bundle.inputData?.[`${keyPrefix}orderStatus`],
            'quoteStatus': bundle.inputData?.[`${keyPrefix}quoteStatus`],
            'freightTerms': bundle.inputData?.[`${keyPrefix}freightTerms`],
            'receiverTenantId': bundle.inputData?.[`${keyPrefix}receiverTenantId`],
            'shippingLocationId': bundle.inputData?.[`${keyPrefix}shippingLocationId`],
            'qualifiedIdentifier': bundle.inputData?.[`${keyPrefix}qualifiedIdentifier`],
            'totalTaxesInUsd': bundle.inputData?.[`${keyPrefix}totalTaxesInUsd`],
            'totalDiscountsInUsd': bundle.inputData?.[`${keyPrefix}totalDiscountsInUsd`],
            'totalSurchargesInUsd': bundle.inputData?.[`${keyPrefix}totalSurchargesInUsd`],
            'totalShippingCostInUsd': bundle.inputData?.[`${keyPrefix}totalShippingCostInUsd`],
            'totalShippingTaxInUsd': bundle.inputData?.[`${keyPrefix}totalShippingTaxInUsd`],
            'totalAmountInUsd': bundle.inputData?.[`${keyPrefix}totalAmountInUsd`],
            'effectiveTo': bundle.inputData?.[`${keyPrefix}effectiveTo`],
            'effectiveFrom': bundle.inputData?.[`${keyPrefix}effectiveFrom`],
            'orderLines': utils.childMapping(bundle.inputData?.[`${keyPrefix}orderLines`], `${keyPrefix}orderLines`, OrderLineCreateDto),
        }
    },
}
