const CompletionsApi = require('../apis/CompletionsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const ServiceCaseTypesApi = require('../apis/ServiceCaseTypesApi');
const ServiceCasesApi = require('../apis/ServiceCasesApi');
const ServiceLevelAgreementsApi = require('../apis/ServiceLevelAgreementsApi');
const ServiceLevelsApi = require('../apis/ServiceLevelsApi');
const ServiceQueuesApi = require('../apis/ServiceQueuesApi');
const ServicesApi = require('../apis/ServicesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [ServiceCaseTypesApi.createServiceCaseTypeAsync.key]: ServiceCaseTypesApi.createServiceCaseTypeAsync,
    [ServiceCaseTypesApi.deleteServiceCaseTypeAsync.key]: ServiceCaseTypesApi.deleteServiceCaseTypeAsync,
    [ServiceCaseTypesApi.getServiceCaseTypeByIdAsync.key]: ServiceCaseTypesApi.getServiceCaseTypeByIdAsync,
    [ServiceCaseTypesApi.getServiceCaseTypesAsync.key]: ServiceCaseTypesApi.getServiceCaseTypesAsync,
    [ServiceCaseTypesApi.getServiceCaseTypesCountAsync.key]: ServiceCaseTypesApi.getServiceCaseTypesCountAsync,
    [ServiceCaseTypesApi.patchServiceCaseTypeAsync.key]: ServiceCaseTypesApi.patchServiceCaseTypeAsync,
    [ServiceCaseTypesApi.updateServiceCaseTypeAsync.key]: ServiceCaseTypesApi.updateServiceCaseTypeAsync,
    [ServiceCasesApi.createServiceCaseAsync.key]: ServiceCasesApi.createServiceCaseAsync,
    [ServiceCasesApi.deleteServiceCaseAsync.key]: ServiceCasesApi.deleteServiceCaseAsync,
    [ServiceCasesApi.getServiceCaseByIdAsync.key]: ServiceCasesApi.getServiceCaseByIdAsync,
    [ServiceCasesApi.getServiceCasesAsync.key]: ServiceCasesApi.getServiceCasesAsync,
    [ServiceCasesApi.getServiceCasesCountAsync.key]: ServiceCasesApi.getServiceCasesCountAsync,
    [ServiceCasesApi.patchServiceCaseAsync.key]: ServiceCasesApi.patchServiceCaseAsync,
    [ServiceCasesApi.updateServiceCaseAsync.key]: ServiceCasesApi.updateServiceCaseAsync,
    [ServiceLevelAgreementsApi.createServiceLevelAgreementAsync.key]: ServiceLevelAgreementsApi.createServiceLevelAgreementAsync,
    [ServiceLevelAgreementsApi.deleteServiceLevelAgreementAsync.key]: ServiceLevelAgreementsApi.deleteServiceLevelAgreementAsync,
    [ServiceLevelAgreementsApi.getServiceLevelAgreementByIdAsync.key]: ServiceLevelAgreementsApi.getServiceLevelAgreementByIdAsync,
    [ServiceLevelAgreementsApi.getServiceLevelAgreementsAsync.key]: ServiceLevelAgreementsApi.getServiceLevelAgreementsAsync,
    [ServiceLevelAgreementsApi.getServiceLevelAgreementsCountAsync.key]: ServiceLevelAgreementsApi.getServiceLevelAgreementsCountAsync,
    [ServiceLevelAgreementsApi.patchServiceLevelAgreementAsync.key]: ServiceLevelAgreementsApi.patchServiceLevelAgreementAsync,
    [ServiceLevelAgreementsApi.updateServiceLevelAgreementAsync.key]: ServiceLevelAgreementsApi.updateServiceLevelAgreementAsync,
    [ServiceLevelsApi.countAllServiceLevelsAsync.key]: ServiceLevelsApi.countAllServiceLevelsAsync,
    [ServiceLevelsApi.createServiceLevelAsync.key]: ServiceLevelsApi.createServiceLevelAsync,
    [ServiceLevelsApi.deleteServiceLevelAsync.key]: ServiceLevelsApi.deleteServiceLevelAsync,
    [ServiceLevelsApi.getAllServiceLevelsAsync.key]: ServiceLevelsApi.getAllServiceLevelsAsync,
    [ServiceLevelsApi.getServiceLevelByIdAsync.key]: ServiceLevelsApi.getServiceLevelByIdAsync,
    [ServiceLevelsApi.getServiceLevelsAsync.key]: ServiceLevelsApi.getServiceLevelsAsync,
    [ServiceLevelsApi.getServiceLevelsCountAsync.key]: ServiceLevelsApi.getServiceLevelsCountAsync,
    [ServiceLevelsApi.patchServiceLevelAsync.key]: ServiceLevelsApi.patchServiceLevelAsync,
    [ServiceLevelsApi.updateServiceLevelAsync.key]: ServiceLevelsApi.updateServiceLevelAsync,
    [ServiceQueuesApi.createServiceQueueAsync.key]: ServiceQueuesApi.createServiceQueueAsync,
    [ServiceQueuesApi.deleteServiceQueueAsync.key]: ServiceQueuesApi.deleteServiceQueueAsync,
    [ServiceQueuesApi.getServiceQueueByIdAsync.key]: ServiceQueuesApi.getServiceQueueByIdAsync,
    [ServiceQueuesApi.getServiceQueuesAsync.key]: ServiceQueuesApi.getServiceQueuesAsync,
    [ServiceQueuesApi.getServiceQueuesCountAsync.key]: ServiceQueuesApi.getServiceQueuesCountAsync,
    [ServiceQueuesApi.patchServiceQueueAsync.key]: ServiceQueuesApi.patchServiceQueueAsync,
    [ServiceQueuesApi.updateServiceQueueAsync.key]: ServiceQueuesApi.updateServiceQueueAsync,
    [ServicesApi.createServiceAsync.key]: ServicesApi.createServiceAsync,
    [ServicesApi.deleteServiceAsync.key]: ServicesApi.deleteServiceAsync,
    [ServicesApi.getServiceByIdAsync.key]: ServicesApi.getServiceByIdAsync,
    [ServicesApi.getServicesAsync.key]: ServicesApi.getServicesAsync,
    [ServicesApi.getServicesCountAsync.key]: ServicesApi.getServicesCountAsync,
    [ServicesApi.patchServiceAsync.key]: ServicesApi.patchServiceAsync,
    [ServicesApi.updateServiceAsync.key]: ServicesApi.updateServiceAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
