const CompletionsApi = require('../apis/CompletionsApi');
const CourseArticlesApi = require('../apis/CourseArticlesApi');
const CourseAssignmentComponentsApi = require('../apis/CourseAssignmentComponentsApi');
const CourseAssignmentTypesApi = require('../apis/CourseAssignmentTypesApi');
const CourseAssignmentsApi = require('../apis/CourseAssignmentsApi');
const CourseCategoriesApi = require('../apis/CourseCategoriesApi');
const CourseCertificatesApi = require('../apis/CourseCertificatesApi');
const CourseCohortsApi = require('../apis/CourseCohortsApi');
const CourseContentGroupsApi = require('../apis/CourseContentGroupsApi');
const CourseEnrollmentsApi = require('../apis/CourseEnrollmentsApi');
const CourseFilesApi = require('../apis/CourseFilesApi');
const CourseForumsApi = require('../apis/CourseForumsApi');
const CourseGradingRubricsApi = require('../apis/CourseGradingRubricsApi');
const CourseHandoutsApi = require('../apis/CourseHandoutsApi');
const CourseLibrariesApi = require('../apis/CourseLibrariesApi');
const CoursePagesApi = require('../apis/CoursePagesApi');
const CourseProblemSetsApi = require('../apis/CourseProblemSetsApi');
const CourseSectionsApi = require('../apis/CourseSectionsApi');
const CourseTeamMembershipsApi = require('../apis/CourseTeamMembershipsApi');
const CourseUnitComponentsApi = require('../apis/CourseUnitComponentsApi');
const CourseUnitsApi = require('../apis/CourseUnitsApi');
const CourseUpdatesApi = require('../apis/CourseUpdatesApi');
const CourseWikisApi = require('../apis/CourseWikisApi');
const CoursesApi = require('../apis/CoursesApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const InstructorProfilesApi = require('../apis/InstructorProfilesApi');
const MeApi = require('../apis/MeApi');
const StudentProfilesApi = require('../apis/StudentProfilesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [CourseArticlesApi.createCourseArticleAsync.key]: CourseArticlesApi.createCourseArticleAsync,
    [CourseArticlesApi.deleteCourseArticleAsync.key]: CourseArticlesApi.deleteCourseArticleAsync,
    [CourseArticlesApi.getCourseArticleByIdAsync.key]: CourseArticlesApi.getCourseArticleByIdAsync,
    [CourseArticlesApi.getCourseArticlesAsync.key]: CourseArticlesApi.getCourseArticlesAsync,
    [CourseArticlesApi.getCourseArticlesCountAsync.key]: CourseArticlesApi.getCourseArticlesCountAsync,
    [CourseArticlesApi.patchCourseArticleAsync.key]: CourseArticlesApi.patchCourseArticleAsync,
    [CourseArticlesApi.updateCourseArticleAsync.key]: CourseArticlesApi.updateCourseArticleAsync,
    [CourseAssignmentComponentsApi.createCourseAssignmentComponentAsync.key]: CourseAssignmentComponentsApi.createCourseAssignmentComponentAsync,
    [CourseAssignmentComponentsApi.deleteCourseAssignmentComponentAsync.key]: CourseAssignmentComponentsApi.deleteCourseAssignmentComponentAsync,
    [CourseAssignmentComponentsApi.getCourseAssignmentComponentByIdAsync.key]: CourseAssignmentComponentsApi.getCourseAssignmentComponentByIdAsync,
    [CourseAssignmentComponentsApi.getCourseAssignmentComponentsAsync.key]: CourseAssignmentComponentsApi.getCourseAssignmentComponentsAsync,
    [CourseAssignmentComponentsApi.getCourseAssignmentComponentsCountAsync.key]: CourseAssignmentComponentsApi.getCourseAssignmentComponentsCountAsync,
    [CourseAssignmentComponentsApi.patchCourseAssignmentComponentAsync.key]: CourseAssignmentComponentsApi.patchCourseAssignmentComponentAsync,
    [CourseAssignmentComponentsApi.updateCourseAssignmentComponentAsync.key]: CourseAssignmentComponentsApi.updateCourseAssignmentComponentAsync,
    [CourseAssignmentTypesApi.createCourseAssignmentTypeAsync.key]: CourseAssignmentTypesApi.createCourseAssignmentTypeAsync,
    [CourseAssignmentTypesApi.deleteCourseAssignmentTypeAsync.key]: CourseAssignmentTypesApi.deleteCourseAssignmentTypeAsync,
    [CourseAssignmentTypesApi.getCourseAssignmentTypeByIdAsync.key]: CourseAssignmentTypesApi.getCourseAssignmentTypeByIdAsync,
    [CourseAssignmentTypesApi.getCourseAssignmentTypesAsync.key]: CourseAssignmentTypesApi.getCourseAssignmentTypesAsync,
    [CourseAssignmentTypesApi.getCourseAssignmentTypesCountAsync.key]: CourseAssignmentTypesApi.getCourseAssignmentTypesCountAsync,
    [CourseAssignmentTypesApi.patchCourseAssignmentTypeAsync.key]: CourseAssignmentTypesApi.patchCourseAssignmentTypeAsync,
    [CourseAssignmentTypesApi.updateCourseAssignmentTypeAsync.key]: CourseAssignmentTypesApi.updateCourseAssignmentTypeAsync,
    [CourseAssignmentsApi.createCourseAssignmentAsync.key]: CourseAssignmentsApi.createCourseAssignmentAsync,
    [CourseAssignmentsApi.deleteCourseAssignmentAsync.key]: CourseAssignmentsApi.deleteCourseAssignmentAsync,
    [CourseAssignmentsApi.getCourseAssignmentByIdAsync.key]: CourseAssignmentsApi.getCourseAssignmentByIdAsync,
    [CourseAssignmentsApi.getCourseAssignmentsAsync.key]: CourseAssignmentsApi.getCourseAssignmentsAsync,
    [CourseAssignmentsApi.getCourseAssignmentsCountAsync.key]: CourseAssignmentsApi.getCourseAssignmentsCountAsync,
    [CourseAssignmentsApi.patchCourseAssignmentAsync.key]: CourseAssignmentsApi.patchCourseAssignmentAsync,
    [CourseAssignmentsApi.updateCourseAssignmentAsync.key]: CourseAssignmentsApi.updateCourseAssignmentAsync,
    [CourseCategoriesApi.createCourseCategoryAsync.key]: CourseCategoriesApi.createCourseCategoryAsync,
    [CourseCategoriesApi.deleteCourseCategoryAsync.key]: CourseCategoriesApi.deleteCourseCategoryAsync,
    [CourseCategoriesApi.getCourseCategoriesAsync.key]: CourseCategoriesApi.getCourseCategoriesAsync,
    [CourseCategoriesApi.getCourseCategoriesCountAsync.key]: CourseCategoriesApi.getCourseCategoriesCountAsync,
    [CourseCategoriesApi.getCourseCategoryByIdAsync.key]: CourseCategoriesApi.getCourseCategoryByIdAsync,
    [CourseCategoriesApi.patchCourseCategoryAsync.key]: CourseCategoriesApi.patchCourseCategoryAsync,
    [CourseCategoriesApi.updateCourseCategoryAsync.key]: CourseCategoriesApi.updateCourseCategoryAsync,
    [CourseCertificatesApi.createCourseCertificateAsync.key]: CourseCertificatesApi.createCourseCertificateAsync,
    [CourseCertificatesApi.createCourseCertificateTemplateAsync.key]: CourseCertificatesApi.createCourseCertificateTemplateAsync,
    [CourseCertificatesApi.deleteCourseCertificateAsync.key]: CourseCertificatesApi.deleteCourseCertificateAsync,
    [CourseCertificatesApi.deleteCourseCertificateTemplateAsync.key]: CourseCertificatesApi.deleteCourseCertificateTemplateAsync,
    [CourseCertificatesApi.getCourseCertificateAsync.key]: CourseCertificatesApi.getCourseCertificateAsync,
    [CourseCertificatesApi.getCourseCertificateTemplateAsync.key]: CourseCertificatesApi.getCourseCertificateTemplateAsync,
    [CourseCertificatesApi.getCourseCertificateTemplatesAsync.key]: CourseCertificatesApi.getCourseCertificateTemplatesAsync,
    [CourseCertificatesApi.getCourseCertificateTemplatesCountAsync.key]: CourseCertificatesApi.getCourseCertificateTemplatesCountAsync,
    [CourseCertificatesApi.getCourseCertificatesAsync.key]: CourseCertificatesApi.getCourseCertificatesAsync,
    [CourseCertificatesApi.getCourseCertificatesCountAsync.key]: CourseCertificatesApi.getCourseCertificatesCountAsync,
    [CourseCertificatesApi.patchCourseCertificateAsync.key]: CourseCertificatesApi.patchCourseCertificateAsync,
    [CourseCertificatesApi.patchCourseCertificateTemplateAsync.key]: CourseCertificatesApi.patchCourseCertificateTemplateAsync,
    [CourseCertificatesApi.updateCourseCertificateAsync.key]: CourseCertificatesApi.updateCourseCertificateAsync,
    [CourseCertificatesApi.updateCourseCertificateTemplateAsync.key]: CourseCertificatesApi.updateCourseCertificateTemplateAsync,
    [CourseCohortsApi.createCourseCohortAsync.key]: CourseCohortsApi.createCourseCohortAsync,
    [CourseCohortsApi.deleteCourseCohortAsync.key]: CourseCohortsApi.deleteCourseCohortAsync,
    [CourseCohortsApi.getCourseCohortByIdAsync.key]: CourseCohortsApi.getCourseCohortByIdAsync,
    [CourseCohortsApi.getCourseCohortsAsync.key]: CourseCohortsApi.getCourseCohortsAsync,
    [CourseCohortsApi.getCourseCohortsCountAsync.key]: CourseCohortsApi.getCourseCohortsCountAsync,
    [CourseCohortsApi.patchCourseCohortAsync.key]: CourseCohortsApi.patchCourseCohortAsync,
    [CourseCohortsApi.updateCourseCohortAsync.key]: CourseCohortsApi.updateCourseCohortAsync,
    [CourseContentGroupsApi.createCourseContentGroupAsync.key]: CourseContentGroupsApi.createCourseContentGroupAsync,
    [CourseContentGroupsApi.deleteCourseContentGroupAsync.key]: CourseContentGroupsApi.deleteCourseContentGroupAsync,
    [CourseContentGroupsApi.getCourseContentGroupByIdAsync.key]: CourseContentGroupsApi.getCourseContentGroupByIdAsync,
    [CourseContentGroupsApi.getCourseContentGroupsAsync.key]: CourseContentGroupsApi.getCourseContentGroupsAsync,
    [CourseContentGroupsApi.getCourseContentGroupsByCourseAsync.key]: CourseContentGroupsApi.getCourseContentGroupsByCourseAsync,
    [CourseContentGroupsApi.getCourseContentGroupsByCourseCountAsync.key]: CourseContentGroupsApi.getCourseContentGroupsByCourseCountAsync,
    [CourseContentGroupsApi.getCourseContentGroupsCountAsync.key]: CourseContentGroupsApi.getCourseContentGroupsCountAsync,
    [CourseContentGroupsApi.patchCourseContentGroupAsync.key]: CourseContentGroupsApi.patchCourseContentGroupAsync,
    [CourseContentGroupsApi.updateCourseContentGroupAsync.key]: CourseContentGroupsApi.updateCourseContentGroupAsync,
    [CourseEnrollmentsApi.createCourseEnrollmentAsync.key]: CourseEnrollmentsApi.createCourseEnrollmentAsync,
    [CourseEnrollmentsApi.deleteCourseEnrollmentAsync.key]: CourseEnrollmentsApi.deleteCourseEnrollmentAsync,
    [CourseEnrollmentsApi.getCourseEnrollmentAsync.key]: CourseEnrollmentsApi.getCourseEnrollmentAsync,
    [CourseEnrollmentsApi.getEnrollmentsAsync.key]: CourseEnrollmentsApi.getEnrollmentsAsync,
    [CourseEnrollmentsApi.getEnrollmentsCountAsync.key]: CourseEnrollmentsApi.getEnrollmentsCountAsync,
    [CourseEnrollmentsApi.getStudentCourseEnrollmentsAsync.key]: CourseEnrollmentsApi.getStudentCourseEnrollmentsAsync,
    [CourseEnrollmentsApi.patchCourseEnrollmentAsync.key]: CourseEnrollmentsApi.patchCourseEnrollmentAsync,
    [CourseEnrollmentsApi.updateCourseEnrollmentAsync.key]: CourseEnrollmentsApi.updateCourseEnrollmentAsync,
    [CourseFilesApi.createCourseFileAsync.key]: CourseFilesApi.createCourseFileAsync,
    [CourseFilesApi.deleteCourseFileAsync.key]: CourseFilesApi.deleteCourseFileAsync,
    [CourseFilesApi.getCourseFileByIdAsync.key]: CourseFilesApi.getCourseFileByIdAsync,
    [CourseFilesApi.getCourseFilesAsync.key]: CourseFilesApi.getCourseFilesAsync,
    [CourseFilesApi.getCourseFilesCountAsync.key]: CourseFilesApi.getCourseFilesCountAsync,
    [CourseFilesApi.patchCourseFileAsync.key]: CourseFilesApi.patchCourseFileAsync,
    [CourseFilesApi.updateCourseFileAsync.key]: CourseFilesApi.updateCourseFileAsync,
    [CourseForumsApi.createCourseForumAsync.key]: CourseForumsApi.createCourseForumAsync,
    [CourseForumsApi.deleteCourseForumAsync.key]: CourseForumsApi.deleteCourseForumAsync,
    [CourseForumsApi.getCourseForumByIdAsync.key]: CourseForumsApi.getCourseForumByIdAsync,
    [CourseForumsApi.getCourseForumsAsync.key]: CourseForumsApi.getCourseForumsAsync,
    [CourseForumsApi.getCourseForumsCountAsync.key]: CourseForumsApi.getCourseForumsCountAsync,
    [CourseForumsApi.patchCourseForumAsync.key]: CourseForumsApi.patchCourseForumAsync,
    [CourseForumsApi.updateCourseForumAsync.key]: CourseForumsApi.updateCourseForumAsync,
    [CourseGradingRubricsApi.createCourseGradingRubricAsync.key]: CourseGradingRubricsApi.createCourseGradingRubricAsync,
    [CourseGradingRubricsApi.deleteCourseGradingRubricAsync.key]: CourseGradingRubricsApi.deleteCourseGradingRubricAsync,
    [CourseGradingRubricsApi.getCourseGradingRubricByIdAsync.key]: CourseGradingRubricsApi.getCourseGradingRubricByIdAsync,
    [CourseGradingRubricsApi.getCourseGradingRubricsAsync.key]: CourseGradingRubricsApi.getCourseGradingRubricsAsync,
    [CourseGradingRubricsApi.getCourseGradingRubricsCountAsync.key]: CourseGradingRubricsApi.getCourseGradingRubricsCountAsync,
    [CourseGradingRubricsApi.patchCourseGradingRubricAsync.key]: CourseGradingRubricsApi.patchCourseGradingRubricAsync,
    [CourseGradingRubricsApi.updateCourseGradingRubricAsync.key]: CourseGradingRubricsApi.updateCourseGradingRubricAsync,
    [CourseHandoutsApi.createCourseHandoutAsync.key]: CourseHandoutsApi.createCourseHandoutAsync,
    [CourseHandoutsApi.deleteCourseHandoutAsync.key]: CourseHandoutsApi.deleteCourseHandoutAsync,
    [CourseHandoutsApi.getCourseHandoutByIdAsync.key]: CourseHandoutsApi.getCourseHandoutByIdAsync,
    [CourseHandoutsApi.getCourseHandoutsAsync.key]: CourseHandoutsApi.getCourseHandoutsAsync,
    [CourseHandoutsApi.getCourseHandoutsCountAsync.key]: CourseHandoutsApi.getCourseHandoutsCountAsync,
    [CourseHandoutsApi.patchCourseHandoutAsync.key]: CourseHandoutsApi.patchCourseHandoutAsync,
    [CourseHandoutsApi.updateCourseHandoutAsync.key]: CourseHandoutsApi.updateCourseHandoutAsync,
    [CourseLibrariesApi.createCourseLibraryAsync.key]: CourseLibrariesApi.createCourseLibraryAsync,
    [CourseLibrariesApi.deleteCourseLibraryAsync.key]: CourseLibrariesApi.deleteCourseLibraryAsync,
    [CourseLibrariesApi.getCourseLibrariesAsync.key]: CourseLibrariesApi.getCourseLibrariesAsync,
    [CourseLibrariesApi.getCourseLibrariesCountAsync.key]: CourseLibrariesApi.getCourseLibrariesCountAsync,
    [CourseLibrariesApi.getCourseLibraryByIdAsync.key]: CourseLibrariesApi.getCourseLibraryByIdAsync,
    [CourseLibrariesApi.patchCourseLibraryAsync.key]: CourseLibrariesApi.patchCourseLibraryAsync,
    [CourseLibrariesApi.updateCourseLibraryAsync.key]: CourseLibrariesApi.updateCourseLibraryAsync,
    [CoursePagesApi.createCoursePageAsync.key]: CoursePagesApi.createCoursePageAsync,
    [CoursePagesApi.deleteCoursePageAsync.key]: CoursePagesApi.deleteCoursePageAsync,
    [CoursePagesApi.getCoursePageByIdAsync.key]: CoursePagesApi.getCoursePageByIdAsync,
    [CoursePagesApi.getCoursePagesAsync.key]: CoursePagesApi.getCoursePagesAsync,
    [CoursePagesApi.getCoursePagesCountAsync.key]: CoursePagesApi.getCoursePagesCountAsync,
    [CoursePagesApi.patchCoursePageAsync.key]: CoursePagesApi.patchCoursePageAsync,
    [CoursePagesApi.updateCoursePageAsync.key]: CoursePagesApi.updateCoursePageAsync,
    [CourseProblemSetsApi.createCourseProblemSetAsync.key]: CourseProblemSetsApi.createCourseProblemSetAsync,
    [CourseProblemSetsApi.deleteCourseProblemSetAsync.key]: CourseProblemSetsApi.deleteCourseProblemSetAsync,
    [CourseProblemSetsApi.getCourseProblemSetByIdAsync.key]: CourseProblemSetsApi.getCourseProblemSetByIdAsync,
    [CourseProblemSetsApi.getCourseProblemSetsAsync.key]: CourseProblemSetsApi.getCourseProblemSetsAsync,
    [CourseProblemSetsApi.getCourseProblemSetsCountAsync.key]: CourseProblemSetsApi.getCourseProblemSetsCountAsync,
    [CourseProblemSetsApi.patchCourseProblemSetAsync.key]: CourseProblemSetsApi.patchCourseProblemSetAsync,
    [CourseProblemSetsApi.updateCourseProblemSetAsync.key]: CourseProblemSetsApi.updateCourseProblemSetAsync,
    [CourseSectionsApi.createCourseSectionAsync.key]: CourseSectionsApi.createCourseSectionAsync,
    [CourseSectionsApi.deleteCourseSectionAsync.key]: CourseSectionsApi.deleteCourseSectionAsync,
    [CourseSectionsApi.getCourseSectionByIdAsync.key]: CourseSectionsApi.getCourseSectionByIdAsync,
    [CourseSectionsApi.getCourseSectionsAsync.key]: CourseSectionsApi.getCourseSectionsAsync,
    [CourseSectionsApi.getCourseSectionsCountAsync.key]: CourseSectionsApi.getCourseSectionsCountAsync,
    [CourseSectionsApi.patchCourseSectionAsync.key]: CourseSectionsApi.patchCourseSectionAsync,
    [CourseSectionsApi.updateCourseSectionAsync.key]: CourseSectionsApi.updateCourseSectionAsync,
    [CourseTeamMembershipsApi.createCourseTeamMembershipAsync.key]: CourseTeamMembershipsApi.createCourseTeamMembershipAsync,
    [CourseTeamMembershipsApi.deleteCourseTeamMembershipAsync.key]: CourseTeamMembershipsApi.deleteCourseTeamMembershipAsync,
    [CourseTeamMembershipsApi.getCourseTeamMembershipByIdAsync.key]: CourseTeamMembershipsApi.getCourseTeamMembershipByIdAsync,
    [CourseTeamMembershipsApi.getCourseTeamMembershipsAsync.key]: CourseTeamMembershipsApi.getCourseTeamMembershipsAsync,
    [CourseTeamMembershipsApi.getCourseTeamMembershipsCountAsync.key]: CourseTeamMembershipsApi.getCourseTeamMembershipsCountAsync,
    [CourseTeamMembershipsApi.patchCourseTeamMembershipAsync.key]: CourseTeamMembershipsApi.patchCourseTeamMembershipAsync,
    [CourseTeamMembershipsApi.updateCourseTeamMembershipAsync.key]: CourseTeamMembershipsApi.updateCourseTeamMembershipAsync,
    [CourseUnitComponentsApi.createCourseUnitComponentAsync.key]: CourseUnitComponentsApi.createCourseUnitComponentAsync,
    [CourseUnitComponentsApi.deleteCourseUnitComponentAsync.key]: CourseUnitComponentsApi.deleteCourseUnitComponentAsync,
    [CourseUnitComponentsApi.getCourseUnitComponentByIdAsync.key]: CourseUnitComponentsApi.getCourseUnitComponentByIdAsync,
    [CourseUnitComponentsApi.getCourseUnitComponentsAsync.key]: CourseUnitComponentsApi.getCourseUnitComponentsAsync,
    [CourseUnitComponentsApi.getCourseUnitComponentsCountAsync.key]: CourseUnitComponentsApi.getCourseUnitComponentsCountAsync,
    [CourseUnitComponentsApi.patchCourseUnitComponentAsync.key]: CourseUnitComponentsApi.patchCourseUnitComponentAsync,
    [CourseUnitComponentsApi.updateCourseUnitComponentAsync.key]: CourseUnitComponentsApi.updateCourseUnitComponentAsync,
    [CourseUnitsApi.createCourseUnitAsync.key]: CourseUnitsApi.createCourseUnitAsync,
    [CourseUnitsApi.deleteCourseUnitAsync.key]: CourseUnitsApi.deleteCourseUnitAsync,
    [CourseUnitsApi.getCourseUnitByIdAsync.key]: CourseUnitsApi.getCourseUnitByIdAsync,
    [CourseUnitsApi.getCourseUnitsAsync.key]: CourseUnitsApi.getCourseUnitsAsync,
    [CourseUnitsApi.getCourseUnitsCountAsync.key]: CourseUnitsApi.getCourseUnitsCountAsync,
    [CourseUnitsApi.patchCourseUnitAsync.key]: CourseUnitsApi.patchCourseUnitAsync,
    [CourseUnitsApi.updateCourseUnitAsync.key]: CourseUnitsApi.updateCourseUnitAsync,
    [CourseUpdatesApi.createCourseUpdateAsync.key]: CourseUpdatesApi.createCourseUpdateAsync,
    [CourseUpdatesApi.deleteCourseUpdateAsync.key]: CourseUpdatesApi.deleteCourseUpdateAsync,
    [CourseUpdatesApi.getCourseUpdateByIdAsync.key]: CourseUpdatesApi.getCourseUpdateByIdAsync,
    [CourseUpdatesApi.getCourseUpdatesAsync.key]: CourseUpdatesApi.getCourseUpdatesAsync,
    [CourseUpdatesApi.getCourseUpdatesCountAsync.key]: CourseUpdatesApi.getCourseUpdatesCountAsync,
    [CourseUpdatesApi.patchCourseUpdateAsync.key]: CourseUpdatesApi.patchCourseUpdateAsync,
    [CourseUpdatesApi.updateCourseUpdateAsync.key]: CourseUpdatesApi.updateCourseUpdateAsync,
    [CourseWikisApi.createCourseWikiAsync.key]: CourseWikisApi.createCourseWikiAsync,
    [CourseWikisApi.deleteCourseWikiAsync.key]: CourseWikisApi.deleteCourseWikiAsync,
    [CourseWikisApi.getCourseWikiByIdAsync.key]: CourseWikisApi.getCourseWikiByIdAsync,
    [CourseWikisApi.getCourseWikisAsync.key]: CourseWikisApi.getCourseWikisAsync,
    [CourseWikisApi.getCourseWikisCountAsync.key]: CourseWikisApi.getCourseWikisCountAsync,
    [CourseWikisApi.patchCourseWikiAsync.key]: CourseWikisApi.patchCourseWikiAsync,
    [CourseWikisApi.updateCourseWikiAsync.key]: CourseWikisApi.updateCourseWikiAsync,
    [CoursesApi.createCourseAsync.key]: CoursesApi.createCourseAsync,
    [CoursesApi.deleteCourseAsync.key]: CoursesApi.deleteCourseAsync,
    [CoursesApi.getCourseArticlesByCourseWikiAsync.key]: CoursesApi.getCourseArticlesByCourseWikiAsync,
    [CoursesApi.getCourseArticlesByCourseWikiCountAsync.key]: CoursesApi.getCourseArticlesByCourseWikiCountAsync,
    [CoursesApi.getCourseAssignmentsByCourseAsync.key]: CoursesApi.getCourseAssignmentsByCourseAsync,
    [CoursesApi.getCourseAssignmentsByCourseCountAsync.key]: CoursesApi.getCourseAssignmentsByCourseCountAsync,
    [CoursesApi.getCourseByIdAsync.key]: CoursesApi.getCourseByIdAsync,
    [CoursesApi.getCourseCategoriesByCourseAsync.key]: CoursesApi.getCourseCategoriesByCourseAsync,
    [CoursesApi.getCourseCategoriesByCourseCountAsync.key]: CoursesApi.getCourseCategoriesByCourseCountAsync,
    [CoursesApi.getCourseCohortsByCourseAsync.key]: CoursesApi.getCourseCohortsByCourseAsync,
    [CoursesApi.getCourseCohortsByCourseCountAsync.key]: CoursesApi.getCourseCohortsByCourseCountAsync,
    [CoursesApi.getCourseEnrollmentsByCourseAsync.key]: CoursesApi.getCourseEnrollmentsByCourseAsync,
    [CoursesApi.getCourseFilesByCourseAsync.key]: CoursesApi.getCourseFilesByCourseAsync,
    [CoursesApi.getCourseFilesByCourseCountAsync.key]: CoursesApi.getCourseFilesByCourseCountAsync,
    [CoursesApi.getCourseForumsByCourseAsync.key]: CoursesApi.getCourseForumsByCourseAsync,
    [CoursesApi.getCourseForumsByCourseCountAsync.key]: CoursesApi.getCourseForumsByCourseCountAsync,
    [CoursesApi.getCourseHandoutsByCourseAsync.key]: CoursesApi.getCourseHandoutsByCourseAsync,
    [CoursesApi.getCourseHandoutsByCourseCountAsync.key]: CoursesApi.getCourseHandoutsByCourseCountAsync,
    [CoursesApi.getCourseLibrariesByCourseAsync.key]: CoursesApi.getCourseLibrariesByCourseAsync,
    [CoursesApi.getCourseLibrariesByCourseCountAsync.key]: CoursesApi.getCourseLibrariesByCourseCountAsync,
    [CoursesApi.getCoursePagesByCourseAsync.key]: CoursesApi.getCoursePagesByCourseAsync,
    [CoursesApi.getCoursePagesByCourseCountAsync.key]: CoursesApi.getCoursePagesByCourseCountAsync,
    [CoursesApi.getCourseProblemSetsByCourseAsync.key]: CoursesApi.getCourseProblemSetsByCourseAsync,
    [CoursesApi.getCourseProblemSetsByCourseCountAsync.key]: CoursesApi.getCourseProblemSetsByCourseCountAsync,
    [CoursesApi.getCourseSectionsByCourseAsync.key]: CoursesApi.getCourseSectionsByCourseAsync,
    [CoursesApi.getCourseSectionsByCourseCountAsync.key]: CoursesApi.getCourseSectionsByCourseCountAsync,
    [CoursesApi.getCourseUnitComponentsByCourseAsync.key]: CoursesApi.getCourseUnitComponentsByCourseAsync,
    [CoursesApi.getCourseUnitComponentsByCourseCountAsync.key]: CoursesApi.getCourseUnitComponentsByCourseCountAsync,
    [CoursesApi.getCourseUnitsBySectionAsync.key]: CoursesApi.getCourseUnitsBySectionAsync,
    [CoursesApi.getCourseUnitsBySectionCountAsync.key]: CoursesApi.getCourseUnitsBySectionCountAsync,
    [CoursesApi.getCourseUpdatesByCourseAsync.key]: CoursesApi.getCourseUpdatesByCourseAsync,
    [CoursesApi.getCourseUpdatesByCourseCountAsync.key]: CoursesApi.getCourseUpdatesByCourseCountAsync,
    [CoursesApi.getCourseWikisByCourseAsync.key]: CoursesApi.getCourseWikisByCourseAsync,
    [CoursesApi.getCourseWikisByCourseCountAsync.key]: CoursesApi.getCourseWikisByCourseCountAsync,
    [CoursesApi.getCoursesAsync.key]: CoursesApi.getCoursesAsync,
    [CoursesApi.getCoursesCountAsync.key]: CoursesApi.getCoursesCountAsync,
    [CoursesApi.getInstructorProfilesByCourseAsync.key]: CoursesApi.getInstructorProfilesByCourseAsync,
    [CoursesApi.getInstructorProfilesByCourseCountAsync.key]: CoursesApi.getInstructorProfilesByCourseCountAsync,
    [CoursesApi.getStudentProfilesByCourseAsync.key]: CoursesApi.getStudentProfilesByCourseAsync,
    [CoursesApi.getStudentProfilesByCourseCountAsync.key]: CoursesApi.getStudentProfilesByCourseCountAsync,
    [CoursesApi.patchCourseAsync.key]: CoursesApi.patchCourseAsync,
    [CoursesApi.updateCourseAsync.key]: CoursesApi.updateCourseAsync,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesCountGet.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesCountGet,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesGet.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesGet,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdDelete.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdDelete,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdGet.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdGet,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdPatch.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdPatch,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdPut.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdPut,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesPost.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesPost,
    [MeApi.getMyAverageScoreAsync.key]: MeApi.getMyAverageScoreAsync,
    [MeApi.getMyCertificatesAsync.key]: MeApi.getMyCertificatesAsync,
    [MeApi.getMyCertificatesCountAsync.key]: MeApi.getMyCertificatesCountAsync,
    [MeApi.getMyEnrollmentsAsync.key]: MeApi.getMyEnrollmentsAsync,
    [MeApi.getMyEnrollmentsCountAsync.key]: MeApi.getMyEnrollmentsCountAsync,
    [MeApi.getMyHoursCompletedAsync.key]: MeApi.getMyHoursCompletedAsync,
    [MeApi.getMyInstructorCoursesAsync.key]: MeApi.getMyInstructorCoursesAsync,
    [MeApi.getMyInstructorCoursesCountAsync.key]: MeApi.getMyInstructorCoursesCountAsync,
    [MeApi.getMyInstructorProfilesAsync.key]: MeApi.getMyInstructorProfilesAsync,
    [MeApi.getMyInstructorProfilesCountAsync.key]: MeApi.getMyInstructorProfilesCountAsync,
    [MeApi.getMyPendingTaskCountAsync.key]: MeApi.getMyPendingTaskCountAsync,
    [MeApi.getMyStudentCoursesAsync.key]: MeApi.getMyStudentCoursesAsync,
    [MeApi.getMyStudentCoursesCountAsync.key]: MeApi.getMyStudentCoursesCountAsync,
    [MeApi.getMyStudentProfilesAsync.key]: MeApi.getMyStudentProfilesAsync,
    [MeApi.getMyStudentProfilesCountAsync.key]: MeApi.getMyStudentProfilesCountAsync,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesCountGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesCountGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesPost.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesPost,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdAverageGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdAverageGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdDelete.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdDelete,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdHoursCompletedGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdHoursCompletedGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdPatch.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdPatch,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdPut.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdPut,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
