const CourseArticlesApi = require('../apis/CourseArticlesApi');
const CourseAssignmentsApi = require('../apis/CourseAssignmentsApi');
const CourseCategoriesApi = require('../apis/CourseCategoriesApi');
const CourseCertificatesApi = require('../apis/CourseCertificatesApi');
const CourseCohortsApi = require('../apis/CourseCohortsApi');
const CourseEnrollmentsApi = require('../apis/CourseEnrollmentsApi');
const CourseFilesApi = require('../apis/CourseFilesApi');
const CourseForumsApi = require('../apis/CourseForumsApi');
const CourseHandoutsApi = require('../apis/CourseHandoutsApi');
const CourseLibrariesApi = require('../apis/CourseLibrariesApi');
const CoursePagesApi = require('../apis/CoursePagesApi');
const CourseProblemSetsApi = require('../apis/CourseProblemSetsApi');
const CourseSectionsApi = require('../apis/CourseSectionsApi');
const CourseUnitComponentsApi = require('../apis/CourseUnitComponentsApi');
const CourseUnitsApi = require('../apis/CourseUnitsApi');
const CourseUpdatesApi = require('../apis/CourseUpdatesApi');
const CourseWikisApi = require('../apis/CourseWikisApi');
const CoursesApi = require('../apis/CoursesApi');
const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const InstructorProfilesApi = require('../apis/InstructorProfilesApi');
const StudentProfilesApi = require('../apis/StudentProfilesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CourseArticlesApi.createCourseArticleAsync.key]: CourseArticlesApi.createCourseArticleAsync,
    [CourseArticlesApi.deleteCourseArticleAsync.key]: CourseArticlesApi.deleteCourseArticleAsync,
    [CourseArticlesApi.getCourseArticleByIdAsync.key]: CourseArticlesApi.getCourseArticleByIdAsync,
    [CourseArticlesApi.getCourseArticlesAsync.key]: CourseArticlesApi.getCourseArticlesAsync,
    [CourseArticlesApi.getCourseArticlesCountAsync.key]: CourseArticlesApi.getCourseArticlesCountAsync,
    [CourseArticlesApi.updateCourseArticleAsync.key]: CourseArticlesApi.updateCourseArticleAsync,
    [CourseAssignmentsApi.createCourseAssignmentAsync.key]: CourseAssignmentsApi.createCourseAssignmentAsync,
    [CourseAssignmentsApi.deleteCourseAssignmentAsync.key]: CourseAssignmentsApi.deleteCourseAssignmentAsync,
    [CourseAssignmentsApi.getCourseAssignmentByIdAsync.key]: CourseAssignmentsApi.getCourseAssignmentByIdAsync,
    [CourseAssignmentsApi.getCourseAssignmentsAsync.key]: CourseAssignmentsApi.getCourseAssignmentsAsync,
    [CourseAssignmentsApi.getCourseAssignmentsCountAsync.key]: CourseAssignmentsApi.getCourseAssignmentsCountAsync,
    [CourseAssignmentsApi.updateCourseAssignmentAsync.key]: CourseAssignmentsApi.updateCourseAssignmentAsync,
    [CourseCategoriesApi.createCourseCategoryAsync.key]: CourseCategoriesApi.createCourseCategoryAsync,
    [CourseCategoriesApi.deleteCourseCategoryAsync.key]: CourseCategoriesApi.deleteCourseCategoryAsync,
    [CourseCategoriesApi.getCourseCategoriesAsync.key]: CourseCategoriesApi.getCourseCategoriesAsync,
    [CourseCategoriesApi.getCourseCategoriesCountAsync.key]: CourseCategoriesApi.getCourseCategoriesCountAsync,
    [CourseCategoriesApi.getCourseCategoryByIdAsync.key]: CourseCategoriesApi.getCourseCategoryByIdAsync,
    [CourseCategoriesApi.updateCourseCategoryAsync.key]: CourseCategoriesApi.updateCourseCategoryAsync,
    [CourseCertificatesApi.createCourseCertificateAsync.key]: CourseCertificatesApi.createCourseCertificateAsync,
    [CourseCertificatesApi.createCourseCertificateTemplateAsync.key]: CourseCertificatesApi.createCourseCertificateTemplateAsync,
    [CourseCertificatesApi.deleteCourseCertificateAsync.key]: CourseCertificatesApi.deleteCourseCertificateAsync,
    [CourseCertificatesApi.deleteCourseCertificateTemplateAsync.key]: CourseCertificatesApi.deleteCourseCertificateTemplateAsync,
    [CourseCertificatesApi.getCourseCertificateAsync.key]: CourseCertificatesApi.getCourseCertificateAsync,
    [CourseCertificatesApi.getCourseCertificateTemplateAsync.key]: CourseCertificatesApi.getCourseCertificateTemplateAsync,
    [CourseCertificatesApi.getCourseCertificateTemplatesAsync.key]: CourseCertificatesApi.getCourseCertificateTemplatesAsync,
    [CourseCertificatesApi.getCourseCertificatesAsync.key]: CourseCertificatesApi.getCourseCertificatesAsync,
    [CourseCertificatesApi.getCourseCertificatesCountAsync.key]: CourseCertificatesApi.getCourseCertificatesCountAsync,
    [CourseCertificatesApi.updateCourseCertificateAsync.key]: CourseCertificatesApi.updateCourseCertificateAsync,
    [CourseCohortsApi.createCourseCohortAsync.key]: CourseCohortsApi.createCourseCohortAsync,
    [CourseCohortsApi.deleteCourseCohortAsync.key]: CourseCohortsApi.deleteCourseCohortAsync,
    [CourseCohortsApi.getCourseCohortByIdAsync.key]: CourseCohortsApi.getCourseCohortByIdAsync,
    [CourseCohortsApi.getCourseCohortsAsync.key]: CourseCohortsApi.getCourseCohortsAsync,
    [CourseCohortsApi.getCourseCohortsCountAsync.key]: CourseCohortsApi.getCourseCohortsCountAsync,
    [CourseCohortsApi.updateCourseCohortAsync.key]: CourseCohortsApi.updateCourseCohortAsync,
    [CourseEnrollmentsApi.createCourseEnrollmentAsync.key]: CourseEnrollmentsApi.createCourseEnrollmentAsync,
    [CourseEnrollmentsApi.deleteCourseEnrollmentAsync.key]: CourseEnrollmentsApi.deleteCourseEnrollmentAsync,
    [CourseEnrollmentsApi.getCourseEnrollmentAsync.key]: CourseEnrollmentsApi.getCourseEnrollmentAsync,
    [CourseEnrollmentsApi.getEnrollmentsAsync.key]: CourseEnrollmentsApi.getEnrollmentsAsync,
    [CourseEnrollmentsApi.getEnrollmentsCountAsync.key]: CourseEnrollmentsApi.getEnrollmentsCountAsync,
    [CourseEnrollmentsApi.getStudentCourseEnrollmentsAsync.key]: CourseEnrollmentsApi.getStudentCourseEnrollmentsAsync,
    [CourseEnrollmentsApi.updateCourseEnrollmentAsync.key]: CourseEnrollmentsApi.updateCourseEnrollmentAsync,
    [CourseFilesApi.createCourseFileAsync.key]: CourseFilesApi.createCourseFileAsync,
    [CourseFilesApi.deleteCourseFileAsync.key]: CourseFilesApi.deleteCourseFileAsync,
    [CourseFilesApi.getCourseFileByIdAsync.key]: CourseFilesApi.getCourseFileByIdAsync,
    [CourseFilesApi.getCourseFilesAsync.key]: CourseFilesApi.getCourseFilesAsync,
    [CourseFilesApi.getCourseFilesCountAsync.key]: CourseFilesApi.getCourseFilesCountAsync,
    [CourseFilesApi.updateCourseFileAsync.key]: CourseFilesApi.updateCourseFileAsync,
    [CourseForumsApi.createCourseForumAsync.key]: CourseForumsApi.createCourseForumAsync,
    [CourseForumsApi.deleteCourseForumAsync.key]: CourseForumsApi.deleteCourseForumAsync,
    [CourseForumsApi.getCourseForumByIdAsync.key]: CourseForumsApi.getCourseForumByIdAsync,
    [CourseForumsApi.getCourseForumsAsync.key]: CourseForumsApi.getCourseForumsAsync,
    [CourseForumsApi.getCourseForumsCountAsync.key]: CourseForumsApi.getCourseForumsCountAsync,
    [CourseForumsApi.updateCourseForumAsync.key]: CourseForumsApi.updateCourseForumAsync,
    [CourseHandoutsApi.createCourseHandoutAsync.key]: CourseHandoutsApi.createCourseHandoutAsync,
    [CourseHandoutsApi.deleteCourseHandoutAsync.key]: CourseHandoutsApi.deleteCourseHandoutAsync,
    [CourseHandoutsApi.getCourseHandoutByIdAsync.key]: CourseHandoutsApi.getCourseHandoutByIdAsync,
    [CourseHandoutsApi.getCourseHandoutsAsync.key]: CourseHandoutsApi.getCourseHandoutsAsync,
    [CourseHandoutsApi.getCourseHandoutsCountAsync.key]: CourseHandoutsApi.getCourseHandoutsCountAsync,
    [CourseHandoutsApi.updateCourseHandoutAsync.key]: CourseHandoutsApi.updateCourseHandoutAsync,
    [CourseLibrariesApi.createCourseLibraryAsync.key]: CourseLibrariesApi.createCourseLibraryAsync,
    [CourseLibrariesApi.deleteCourseLibraryAsync.key]: CourseLibrariesApi.deleteCourseLibraryAsync,
    [CourseLibrariesApi.getCourseLibrariesAsync.key]: CourseLibrariesApi.getCourseLibrariesAsync,
    [CourseLibrariesApi.getCourseLibrariesCountAsync.key]: CourseLibrariesApi.getCourseLibrariesCountAsync,
    [CourseLibrariesApi.getCourseLibraryByIdAsync.key]: CourseLibrariesApi.getCourseLibraryByIdAsync,
    [CourseLibrariesApi.updateCourseLibraryAsync.key]: CourseLibrariesApi.updateCourseLibraryAsync,
    [CoursePagesApi.createCoursePageAsync.key]: CoursePagesApi.createCoursePageAsync,
    [CoursePagesApi.deleteCoursePageAsync.key]: CoursePagesApi.deleteCoursePageAsync,
    [CoursePagesApi.getCoursePageByIdAsync.key]: CoursePagesApi.getCoursePageByIdAsync,
    [CoursePagesApi.getCoursePagesAsync.key]: CoursePagesApi.getCoursePagesAsync,
    [CoursePagesApi.getCoursePagesCountAsync.key]: CoursePagesApi.getCoursePagesCountAsync,
    [CoursePagesApi.updateCoursePageAsync.key]: CoursePagesApi.updateCoursePageAsync,
    [CourseProblemSetsApi.createCourseProblemSetAsync.key]: CourseProblemSetsApi.createCourseProblemSetAsync,
    [CourseProblemSetsApi.deleteCourseProblemSetAsync.key]: CourseProblemSetsApi.deleteCourseProblemSetAsync,
    [CourseProblemSetsApi.getCourseProblemSetByIdAsync.key]: CourseProblemSetsApi.getCourseProblemSetByIdAsync,
    [CourseProblemSetsApi.getCourseProblemSetsAsync.key]: CourseProblemSetsApi.getCourseProblemSetsAsync,
    [CourseProblemSetsApi.getCourseProblemSetsCountAsync.key]: CourseProblemSetsApi.getCourseProblemSetsCountAsync,
    [CourseProblemSetsApi.updateCourseProblemSetAsync.key]: CourseProblemSetsApi.updateCourseProblemSetAsync,
    [CourseSectionsApi.createCourseSectionAsync.key]: CourseSectionsApi.createCourseSectionAsync,
    [CourseSectionsApi.deleteCourseSectionAsync.key]: CourseSectionsApi.deleteCourseSectionAsync,
    [CourseSectionsApi.getCourseSectionByIdAsync.key]: CourseSectionsApi.getCourseSectionByIdAsync,
    [CourseSectionsApi.getCourseSectionsAsync.key]: CourseSectionsApi.getCourseSectionsAsync,
    [CourseSectionsApi.getCourseSectionsCountAsync.key]: CourseSectionsApi.getCourseSectionsCountAsync,
    [CourseSectionsApi.updateCourseSectionAsync.key]: CourseSectionsApi.updateCourseSectionAsync,
    [CourseUnitComponentsApi.createCourseUnitComponentAsync.key]: CourseUnitComponentsApi.createCourseUnitComponentAsync,
    [CourseUnitComponentsApi.deleteCourseUnitComponentAsync.key]: CourseUnitComponentsApi.deleteCourseUnitComponentAsync,
    [CourseUnitComponentsApi.getCourseUnitComponentByIdAsync.key]: CourseUnitComponentsApi.getCourseUnitComponentByIdAsync,
    [CourseUnitComponentsApi.getCourseUnitComponentsAsync.key]: CourseUnitComponentsApi.getCourseUnitComponentsAsync,
    [CourseUnitComponentsApi.getCourseUnitComponentsCountAsync.key]: CourseUnitComponentsApi.getCourseUnitComponentsCountAsync,
    [CourseUnitComponentsApi.updateCourseUnitComponentAsync.key]: CourseUnitComponentsApi.updateCourseUnitComponentAsync,
    [CourseUnitsApi.createCourseUnitAsync.key]: CourseUnitsApi.createCourseUnitAsync,
    [CourseUnitsApi.deleteCourseUnitAsync.key]: CourseUnitsApi.deleteCourseUnitAsync,
    [CourseUnitsApi.getCourseUnitByIdAsync.key]: CourseUnitsApi.getCourseUnitByIdAsync,
    [CourseUnitsApi.getCourseUnitsAsync.key]: CourseUnitsApi.getCourseUnitsAsync,
    [CourseUnitsApi.getCourseUnitsCountAsync.key]: CourseUnitsApi.getCourseUnitsCountAsync,
    [CourseUnitsApi.updateCourseUnitAsync.key]: CourseUnitsApi.updateCourseUnitAsync,
    [CourseUpdatesApi.createCourseUpdateAsync.key]: CourseUpdatesApi.createCourseUpdateAsync,
    [CourseUpdatesApi.deleteCourseUpdateAsync.key]: CourseUpdatesApi.deleteCourseUpdateAsync,
    [CourseUpdatesApi.getCourseUpdateByIdAsync.key]: CourseUpdatesApi.getCourseUpdateByIdAsync,
    [CourseUpdatesApi.getCourseUpdatesAsync.key]: CourseUpdatesApi.getCourseUpdatesAsync,
    [CourseUpdatesApi.getCourseUpdatesCountAsync.key]: CourseUpdatesApi.getCourseUpdatesCountAsync,
    [CourseUpdatesApi.updateCourseUpdateAsync.key]: CourseUpdatesApi.updateCourseUpdateAsync,
    [CourseWikisApi.createCourseWikiAsync.key]: CourseWikisApi.createCourseWikiAsync,
    [CourseWikisApi.deleteCourseWikiAsync.key]: CourseWikisApi.deleteCourseWikiAsync,
    [CourseWikisApi.getCourseWikiByIdAsync.key]: CourseWikisApi.getCourseWikiByIdAsync,
    [CourseWikisApi.getCourseWikisAsync.key]: CourseWikisApi.getCourseWikisAsync,
    [CourseWikisApi.getCourseWikisCountAsync.key]: CourseWikisApi.getCourseWikisCountAsync,
    [CourseWikisApi.updateCourseWikiAsync.key]: CourseWikisApi.updateCourseWikiAsync,
    [CoursesApi.createCourseAsync.key]: CoursesApi.createCourseAsync,
    [CoursesApi.deleteCourseAsync.key]: CoursesApi.deleteCourseAsync,
    [CoursesApi.getCourseArticlesByCourseWikiAsync.key]: CoursesApi.getCourseArticlesByCourseWikiAsync,
    [CoursesApi.getCourseArticlesByCourseWikiCountAsync.key]: CoursesApi.getCourseArticlesByCourseWikiCountAsync,
    [CoursesApi.getCourseAssignmentsByCourseAsync.key]: CoursesApi.getCourseAssignmentsByCourseAsync,
    [CoursesApi.getCourseAssignmentsByCourseCountAsync.key]: CoursesApi.getCourseAssignmentsByCourseCountAsync,
    [CoursesApi.getCourseByIdAsync.key]: CoursesApi.getCourseByIdAsync,
    [CoursesApi.getCourseCategoriesByCourseAsync.key]: CoursesApi.getCourseCategoriesByCourseAsync,
    [CoursesApi.getCourseCategoriesByCourseCountAsync.key]: CoursesApi.getCourseCategoriesByCourseCountAsync,
    [CoursesApi.getCourseCohortsByCourseAsync.key]: CoursesApi.getCourseCohortsByCourseAsync,
    [CoursesApi.getCourseCohortsByCourseCountAsync.key]: CoursesApi.getCourseCohortsByCourseCountAsync,
    [CoursesApi.getCourseEnrollmentsByCourseAsync.key]: CoursesApi.getCourseEnrollmentsByCourseAsync,
    [CoursesApi.getCourseFilesByCourseAsync.key]: CoursesApi.getCourseFilesByCourseAsync,
    [CoursesApi.getCourseFilesByCourseCountAsync.key]: CoursesApi.getCourseFilesByCourseCountAsync,
    [CoursesApi.getCourseForumsByCourseAsync.key]: CoursesApi.getCourseForumsByCourseAsync,
    [CoursesApi.getCourseForumsByCourseCountAsync.key]: CoursesApi.getCourseForumsByCourseCountAsync,
    [CoursesApi.getCourseHandoutsByCourseAsync.key]: CoursesApi.getCourseHandoutsByCourseAsync,
    [CoursesApi.getCourseHandoutsByCourseCountAsync.key]: CoursesApi.getCourseHandoutsByCourseCountAsync,
    [CoursesApi.getCourseLibrariesByCourseAsync.key]: CoursesApi.getCourseLibrariesByCourseAsync,
    [CoursesApi.getCourseLibrariesByCourseCountAsync.key]: CoursesApi.getCourseLibrariesByCourseCountAsync,
    [CoursesApi.getCoursePagesByCourseAsync.key]: CoursesApi.getCoursePagesByCourseAsync,
    [CoursesApi.getCoursePagesByCourseCountAsync.key]: CoursesApi.getCoursePagesByCourseCountAsync,
    [CoursesApi.getCourseProblemSetsByCourseAsync.key]: CoursesApi.getCourseProblemSetsByCourseAsync,
    [CoursesApi.getCourseProblemSetsByCourseCountAsync.key]: CoursesApi.getCourseProblemSetsByCourseCountAsync,
    [CoursesApi.getCourseSectionsByCourseAsync.key]: CoursesApi.getCourseSectionsByCourseAsync,
    [CoursesApi.getCourseSectionsByCourseCountAsync.key]: CoursesApi.getCourseSectionsByCourseCountAsync,
    [CoursesApi.getCourseUnitComponentsByCourseAsync.key]: CoursesApi.getCourseUnitComponentsByCourseAsync,
    [CoursesApi.getCourseUnitComponentsByCourseCountAsync.key]: CoursesApi.getCourseUnitComponentsByCourseCountAsync,
    [CoursesApi.getCourseUnitsBySectionAsync.key]: CoursesApi.getCourseUnitsBySectionAsync,
    [CoursesApi.getCourseUnitsBySectionCountAsync.key]: CoursesApi.getCourseUnitsBySectionCountAsync,
    [CoursesApi.getCourseUpdatesByCourseAsync.key]: CoursesApi.getCourseUpdatesByCourseAsync,
    [CoursesApi.getCourseUpdatesByCourseCountAsync.key]: CoursesApi.getCourseUpdatesByCourseCountAsync,
    [CoursesApi.getCourseWikisByCourseAsync.key]: CoursesApi.getCourseWikisByCourseAsync,
    [CoursesApi.getCourseWikisByCourseCountAsync.key]: CoursesApi.getCourseWikisByCourseCountAsync,
    [CoursesApi.getCoursesAsync.key]: CoursesApi.getCoursesAsync,
    [CoursesApi.getCoursesCountAsync.key]: CoursesApi.getCoursesCountAsync,
    [CoursesApi.getInstructorProfilesByCourseAsync.key]: CoursesApi.getInstructorProfilesByCourseAsync,
    [CoursesApi.getInstructorProfilesByCourseCountAsync.key]: CoursesApi.getInstructorProfilesByCourseCountAsync,
    [CoursesApi.getStudentProfilesByCourseAsync.key]: CoursesApi.getStudentProfilesByCourseAsync,
    [CoursesApi.getStudentProfilesByCourseCountAsync.key]: CoursesApi.getStudentProfilesByCourseCountAsync,
    [CoursesApi.updateCourseAsync.key]: CoursesApi.updateCourseAsync,
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesCountGet.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesCountGet,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesGet.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesGet,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdDelete.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdDelete,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdGet.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdGet,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdPut.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesInstructorProfileIdPut,
    [InstructorProfilesApi.apiV2LearningServiceInstructorProfilesPost.key]: InstructorProfilesApi.apiV2LearningServiceInstructorProfilesPost,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesCountGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesCountGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesPost.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesPost,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdAverageGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdAverageGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdDelete.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdDelete,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdHoursCompletedGet.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdHoursCompletedGet,
    [StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdPut.key]: StudentProfilesApi.apiV2LearningServiceStudentProfilesStudentProfileIdPut,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
