const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const QuotesApi = require('../apis/QuotesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [QuotesApi.calculateQuote.key]: QuotesApi.calculateQuote,
    [QuotesApi.calculateQuoteLine.key]: QuotesApi.calculateQuoteLine,
    [QuotesApi.closeQuote.key]: QuotesApi.closeQuote,
    [QuotesApi.createOrderFromQuote.key]: QuotesApi.createOrderFromQuote,
    [QuotesApi.createQuote.key]: QuotesApi.createQuote,
    [QuotesApi.createQuoteLine.key]: QuotesApi.createQuoteLine,
    [QuotesApi.deleteQuote.key]: QuotesApi.deleteQuote,
    [QuotesApi.deleteQuoteLine.key]: QuotesApi.deleteQuoteLine,
    [QuotesApi.getExtendedQuotes.key]: QuotesApi.getExtendedQuotes,
    [QuotesApi.getQuote.key]: QuotesApi.getQuote,
    [QuotesApi.getQuoteLine.key]: QuotesApi.getQuoteLine,
    [QuotesApi.getQuoteLines.key]: QuotesApi.getQuoteLines,
    [QuotesApi.getQuoteLinesCount.key]: QuotesApi.getQuoteLinesCount,
    [QuotesApi.getQuotes.key]: QuotesApi.getQuotes,
    [QuotesApi.getQuotesCount.key]: QuotesApi.getQuotesCount,
    [QuotesApi.previewQuoteEmailTemplate.key]: QuotesApi.previewQuoteEmailTemplate,
    [QuotesApi.quoteLineExists.key]: QuotesApi.quoteLineExists,
    [QuotesApi.reopenQuote.key]: QuotesApi.reopenQuote,
    [QuotesApi.sendQuoteEmail.key]: QuotesApi.sendQuoteEmail,
    [QuotesApi.updateQuote.key]: QuotesApi.updateQuote,
    [QuotesApi.updateQuoteLine.key]: QuotesApi.updateQuoteLine,
    [QuotesApi.upsertQuoteLine.key]: QuotesApi.upsertQuoteLine,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
