const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const ItemAttachmentsApi = require('../apis/ItemAttachmentsApi');
const ItemAttributesApi = require('../apis/ItemAttributesApi');
const ItemBrandsApi = require('../apis/ItemBrandsApi');
const ItemCategoriesApi = require('../apis/ItemCategoriesApi');
const ItemGoogleCategoriesApi = require('../apis/ItemGoogleCategoriesApi');
const ItemImagesApi = require('../apis/ItemImagesApi');
const ItemQuestionsApi = require('../apis/ItemQuestionsApi');
const ItemRefundPoliciesApi = require('../apis/ItemRefundPoliciesApi');
const ItemReturnPoliciesApi = require('../apis/ItemReturnPoliciesApi');
const ItemReviewsApi = require('../apis/ItemReviewsApi');
const ItemShippingPoliciesApi = require('../apis/ItemShippingPoliciesApi');
const ItemTagsApi = require('../apis/ItemTagsApi');
const ItemTaxPoliciesApi = require('../apis/ItemTaxPoliciesApi');
const ItemTypesApi = require('../apis/ItemTypesApi');
const ItemWarrantyPoliciesApi = require('../apis/ItemWarrantyPoliciesApi');
const ItemsApi = require('../apis/ItemsApi');
const MerchantsApi = require('../apis/MerchantsApi');
const PricingRulesApi = require('../apis/PricingRulesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [ItemAttachmentsApi.createItemAttachmentAsync.key]: ItemAttachmentsApi.createItemAttachmentAsync,
    [ItemAttachmentsApi.deleteItemAttachmentAsync.key]: ItemAttachmentsApi.deleteItemAttachmentAsync,
    [ItemAttachmentsApi.getItemAttachmentByIdAsync.key]: ItemAttachmentsApi.getItemAttachmentByIdAsync,
    [ItemAttachmentsApi.getItemAttachmentsAsync.key]: ItemAttachmentsApi.getItemAttachmentsAsync,
    [ItemAttachmentsApi.updateItemAttachmentAsync.key]: ItemAttachmentsApi.updateItemAttachmentAsync,
    [ItemAttributesApi.countItemAttributesAsync.key]: ItemAttributesApi.countItemAttributesAsync,
    [ItemAttributesApi.createItemAttributeAsync.key]: ItemAttributesApi.createItemAttributeAsync,
    [ItemAttributesApi.deleteItemAttributeAsync.key]: ItemAttributesApi.deleteItemAttributeAsync,
    [ItemAttributesApi.getItemAttributeByIdAsync.key]: ItemAttributesApi.getItemAttributeByIdAsync,
    [ItemAttributesApi.getItemAttributesAsync.key]: ItemAttributesApi.getItemAttributesAsync,
    [ItemAttributesApi.updateItemAttributeAsync.key]: ItemAttributesApi.updateItemAttributeAsync,
    [ItemBrandsApi.createItemBrandAsync.key]: ItemBrandsApi.createItemBrandAsync,
    [ItemBrandsApi.deleteItemBrandAsync.key]: ItemBrandsApi.deleteItemBrandAsync,
    [ItemBrandsApi.getItemBrandByIdAsync.key]: ItemBrandsApi.getItemBrandByIdAsync,
    [ItemBrandsApi.getItemBrandsAsync.key]: ItemBrandsApi.getItemBrandsAsync,
    [ItemBrandsApi.updateItemBrandAsync.key]: ItemBrandsApi.updateItemBrandAsync,
    [ItemCategoriesApi.countItemCategoriesAsync.key]: ItemCategoriesApi.countItemCategoriesAsync,
    [ItemCategoriesApi.createItemCategoryAsync.key]: ItemCategoriesApi.createItemCategoryAsync,
    [ItemCategoriesApi.deleteItemCategoryAsync.key]: ItemCategoriesApi.deleteItemCategoryAsync,
    [ItemCategoriesApi.getItemCategoriesAsync.key]: ItemCategoriesApi.getItemCategoriesAsync,
    [ItemCategoriesApi.getItemCategoryByIdAsync.key]: ItemCategoriesApi.getItemCategoryByIdAsync,
    [ItemCategoriesApi.updateItemCategoryAsync.key]: ItemCategoriesApi.updateItemCategoryAsync,
    [ItemGoogleCategoriesApi.getAllItemGoogleCategoriesAsync.key]: ItemGoogleCategoriesApi.getAllItemGoogleCategoriesAsync,
    [ItemGoogleCategoriesApi.getChildrenItemGoogleCategoriesByIdAsync.key]: ItemGoogleCategoriesApi.getChildrenItemGoogleCategoriesByIdAsync,
    [ItemGoogleCategoriesApi.getItemGoogleCategoriesAsync.key]: ItemGoogleCategoriesApi.getItemGoogleCategoriesAsync,
    [ItemGoogleCategoriesApi.getItemGoogleCategoriesCountAsync.key]: ItemGoogleCategoriesApi.getItemGoogleCategoriesCountAsync,
    [ItemGoogleCategoriesApi.getItemGoogleCategoriesTreeAsync.key]: ItemGoogleCategoriesApi.getItemGoogleCategoriesTreeAsync,
    [ItemGoogleCategoriesApi.getItemGoogleCategoryByIdAsync.key]: ItemGoogleCategoriesApi.getItemGoogleCategoryByIdAsync,
    [ItemGoogleCategoriesApi.getRootItemGoogleCategoriesAsync.key]: ItemGoogleCategoriesApi.getRootItemGoogleCategoriesAsync,
    [ItemGoogleCategoriesApi.mapItemGoogleCategoriesTreeAsync.key]: ItemGoogleCategoriesApi.mapItemGoogleCategoriesTreeAsync,
    [ItemImagesApi.createItemImageAsync.key]: ItemImagesApi.createItemImageAsync,
    [ItemImagesApi.deleteItemImageAsync.key]: ItemImagesApi.deleteItemImageAsync,
    [ItemImagesApi.getItemImageByIdAsync.key]: ItemImagesApi.getItemImageByIdAsync,
    [ItemImagesApi.getItemImagesAsync.key]: ItemImagesApi.getItemImagesAsync,
    [ItemImagesApi.updateItemImageAsync.key]: ItemImagesApi.updateItemImageAsync,
    [ItemQuestionsApi.createItemQuestionAsync.key]: ItemQuestionsApi.createItemQuestionAsync,
    [ItemQuestionsApi.deleteItemQuestionAsync.key]: ItemQuestionsApi.deleteItemQuestionAsync,
    [ItemQuestionsApi.getItemQuestionByIdAsync.key]: ItemQuestionsApi.getItemQuestionByIdAsync,
    [ItemQuestionsApi.getItemQuestionsAsync.key]: ItemQuestionsApi.getItemQuestionsAsync,
    [ItemQuestionsApi.updateItemQuestionAsync.key]: ItemQuestionsApi.updateItemQuestionAsync,
    [ItemRefundPoliciesApi.countItemRefundPoliciesAsync.key]: ItemRefundPoliciesApi.countItemRefundPoliciesAsync,
    [ItemRefundPoliciesApi.getItemRefundPoliciesAsync.key]: ItemRefundPoliciesApi.getItemRefundPoliciesAsync,
    [ItemRefundPoliciesApi.getItemRefundPolicyByIdAsync.key]: ItemRefundPoliciesApi.getItemRefundPolicyByIdAsync,
    [ItemRefundPoliciesApi.relateItemToRefundPolicyAsync.key]: ItemRefundPoliciesApi.relateItemToRefundPolicyAsync,
    [ItemRefundPoliciesApi.removeRefundPolicyFromItemAsync.key]: ItemRefundPoliciesApi.removeRefundPolicyFromItemAsync,
    [ItemReturnPoliciesApi.countItemReturnPoliciesAsync.key]: ItemReturnPoliciesApi.countItemReturnPoliciesAsync,
    [ItemReturnPoliciesApi.getItemReturnPoliciesAsync.key]: ItemReturnPoliciesApi.getItemReturnPoliciesAsync,
    [ItemReturnPoliciesApi.getItemReturnPolicyByIdAsync.key]: ItemReturnPoliciesApi.getItemReturnPolicyByIdAsync,
    [ItemReturnPoliciesApi.relateItemToReturnPolicyAsync.key]: ItemReturnPoliciesApi.relateItemToReturnPolicyAsync,
    [ItemReturnPoliciesApi.removeReturnPolicyFromItemAsync.key]: ItemReturnPoliciesApi.removeReturnPolicyFromItemAsync,
    [ItemReviewsApi.createItemReviewAsync.key]: ItemReviewsApi.createItemReviewAsync,
    [ItemReviewsApi.deleteItemReviewAsync.key]: ItemReviewsApi.deleteItemReviewAsync,
    [ItemReviewsApi.getItemReviewByIdAsync.key]: ItemReviewsApi.getItemReviewByIdAsync,
    [ItemReviewsApi.getItemReviewsAsync.key]: ItemReviewsApi.getItemReviewsAsync,
    [ItemReviewsApi.updateItemReviewAsync.key]: ItemReviewsApi.updateItemReviewAsync,
    [ItemShippingPoliciesApi.countItemShippingPoliciesAsync.key]: ItemShippingPoliciesApi.countItemShippingPoliciesAsync,
    [ItemShippingPoliciesApi.getItemShippingPoliciesAsync.key]: ItemShippingPoliciesApi.getItemShippingPoliciesAsync,
    [ItemShippingPoliciesApi.getItemShippingPolicyByIdAsync.key]: ItemShippingPoliciesApi.getItemShippingPolicyByIdAsync,
    [ItemShippingPoliciesApi.relateItemToShippingPolicyAsync.key]: ItemShippingPoliciesApi.relateItemToShippingPolicyAsync,
    [ItemShippingPoliciesApi.removeShippingPolicyFromItemAsync.key]: ItemShippingPoliciesApi.removeShippingPolicyFromItemAsync,
    [ItemTagsApi.createItemTagAsync.key]: ItemTagsApi.createItemTagAsync,
    [ItemTagsApi.deleteItemTagAsync.key]: ItemTagsApi.deleteItemTagAsync,
    [ItemTagsApi.getItemTagByIdAsync.key]: ItemTagsApi.getItemTagByIdAsync,
    [ItemTagsApi.getItemTagsAsync.key]: ItemTagsApi.getItemTagsAsync,
    [ItemTagsApi.updateItemTagAsync.key]: ItemTagsApi.updateItemTagAsync,
    [ItemTaxPoliciesApi.countItemTaxPoliciesAsync.key]: ItemTaxPoliciesApi.countItemTaxPoliciesAsync,
    [ItemTaxPoliciesApi.getItemTaxPoliciesAsync.key]: ItemTaxPoliciesApi.getItemTaxPoliciesAsync,
    [ItemTaxPoliciesApi.getItemTaxPolicyByIdAsync.key]: ItemTaxPoliciesApi.getItemTaxPolicyByIdAsync,
    [ItemTaxPoliciesApi.relateItemToTaxPolicyAsync.key]: ItemTaxPoliciesApi.relateItemToTaxPolicyAsync,
    [ItemTaxPoliciesApi.removeTaxPolicyFromItemAsync.key]: ItemTaxPoliciesApi.removeTaxPolicyFromItemAsync,
    [ItemTypesApi.countItemTypesAsync.key]: ItemTypesApi.countItemTypesAsync,
    [ItemTypesApi.createItemTypeAsync.key]: ItemTypesApi.createItemTypeAsync,
    [ItemTypesApi.deleteItemTypeAsync.key]: ItemTypesApi.deleteItemTypeAsync,
    [ItemTypesApi.getItemTypeByIdAsync.key]: ItemTypesApi.getItemTypeByIdAsync,
    [ItemTypesApi.getItemTypesAsync.key]: ItemTypesApi.getItemTypesAsync,
    [ItemTypesApi.updateItemTypeAsync.key]: ItemTypesApi.updateItemTypeAsync,
    [ItemWarrantyPoliciesApi.countItemWarrantyPoliciesAsync.key]: ItemWarrantyPoliciesApi.countItemWarrantyPoliciesAsync,
    [ItemWarrantyPoliciesApi.getItemWarrantyPoliciesAsync.key]: ItemWarrantyPoliciesApi.getItemWarrantyPoliciesAsync,
    [ItemWarrantyPoliciesApi.getItemWarrantyPolicyByIdAsync.key]: ItemWarrantyPoliciesApi.getItemWarrantyPolicyByIdAsync,
    [ItemWarrantyPoliciesApi.relateItemToWarrantyPolicyAsync.key]: ItemWarrantyPoliciesApi.relateItemToWarrantyPolicyAsync,
    [ItemWarrantyPoliciesApi.removeWarrantyPolicyFromItemAsync.key]: ItemWarrantyPoliciesApi.removeWarrantyPolicyFromItemAsync,
    [ItemsApi.countStockItemTagsByItemId.key]: ItemsApi.countStockItemTagsByItemId,
    [ItemsApi.countStockItemsByBusiness.key]: ItemsApi.countStockItemsByBusiness,
    [ItemsApi.createStockItem.key]: ItemsApi.createStockItem,
    [ItemsApi.deleteStockItem.key]: ItemsApi.deleteStockItem,
    [ItemsApi.getExtendedStockItemById.key]: ItemsApi.getExtendedStockItemById,
    [ItemsApi.getProductPrimaryImageAsync.key]: ItemsApi.getProductPrimaryImageAsync,
    [ItemsApi.getStockItemAttachmentById.key]: ItemsApi.getStockItemAttachmentById,
    [ItemsApi.getStockItemAttachmentsByItemId.key]: ItemsApi.getStockItemAttachmentsByItemId,
    [ItemsApi.getStockItemAttributeOptionById.key]: ItemsApi.getStockItemAttributeOptionById,
    [ItemsApi.getStockItemAttributeOptionsByItemId.key]: ItemsApi.getStockItemAttributeOptionsByItemId,
    [ItemsApi.getStockItemBrandById.key]: ItemsApi.getStockItemBrandById,
    [ItemsApi.getStockItemBrandsByItemId.key]: ItemsApi.getStockItemBrandsByItemId,
    [ItemsApi.getStockItemById.key]: ItemsApi.getStockItemById,
    [ItemsApi.getStockItemCategoriesByItemId.key]: ItemsApi.getStockItemCategoriesByItemId,
    [ItemsApi.getStockItemCategoryById.key]: ItemsApi.getStockItemCategoryById,
    [ItemsApi.getStockItemGoogleCategoriesByItemId.key]: ItemsApi.getStockItemGoogleCategoriesByItemId,
    [ItemsApi.getStockItemGoogleCategoryById.key]: ItemsApi.getStockItemGoogleCategoryById,
    [ItemsApi.getStockItemImageById.key]: ItemsApi.getStockItemImageById,
    [ItemsApi.getStockItemImagesByItemId.key]: ItemsApi.getStockItemImagesByItemId,
    [ItemsApi.getStockItemPriceRuleById.key]: ItemsApi.getStockItemPriceRuleById,
    [ItemsApi.getStockItemPriceRulesByItemId.key]: ItemsApi.getStockItemPriceRulesByItemId,
    [ItemsApi.getStockItemQuestionById.key]: ItemsApi.getStockItemQuestionById,
    [ItemsApi.getStockItemQuestionsByItemId.key]: ItemsApi.getStockItemQuestionsByItemId,
    [ItemsApi.getStockItemRefundPoliciesByItemId.key]: ItemsApi.getStockItemRefundPoliciesByItemId,
    [ItemsApi.getStockItemRefundPolicyById.key]: ItemsApi.getStockItemRefundPolicyById,
    [ItemsApi.getStockItemReturnPoliciesByItemId.key]: ItemsApi.getStockItemReturnPoliciesByItemId,
    [ItemsApi.getStockItemReturnPolicyById.key]: ItemsApi.getStockItemReturnPolicyById,
    [ItemsApi.getStockItemReviewById.key]: ItemsApi.getStockItemReviewById,
    [ItemsApi.getStockItemReviewsByItemId.key]: ItemsApi.getStockItemReviewsByItemId,
    [ItemsApi.getStockItemShippingPoliciesByItemId.key]: ItemsApi.getStockItemShippingPoliciesByItemId,
    [ItemsApi.getStockItemShippingPolicyById.key]: ItemsApi.getStockItemShippingPolicyById,
    [ItemsApi.getStockItemTagById.key]: ItemsApi.getStockItemTagById,
    [ItemsApi.getStockItemTagsByItemId.key]: ItemsApi.getStockItemTagsByItemId,
    [ItemsApi.getStockItemTaxPoliciesByItemId.key]: ItemsApi.getStockItemTaxPoliciesByItemId,
    [ItemsApi.getStockItemTaxPolicyById.key]: ItemsApi.getStockItemTaxPolicyById,
    [ItemsApi.getStockItemTypeById.key]: ItemsApi.getStockItemTypeById,
    [ItemsApi.getStockItemTypesByItemId.key]: ItemsApi.getStockItemTypesByItemId,
    [ItemsApi.getStockItemWarrantyPoliciesByItemId.key]: ItemsApi.getStockItemWarrantyPoliciesByItemId,
    [ItemsApi.getStockItemWarrantyPolicyById.key]: ItemsApi.getStockItemWarrantyPolicyById,
    [ItemsApi.getStockItemsOdataMaxPrice.key]: ItemsApi.getStockItemsOdataMaxPrice,
    [ItemsApi.getStockItemsOdataMinPrice.key]: ItemsApi.getStockItemsOdataMinPrice,
    [ItemsApi.getStockItemsQuery.key]: ItemsApi.getStockItemsQuery,
    [ItemsApi.relateAttachmentToStockItem.key]: ItemsApi.relateAttachmentToStockItem,
    [ItemsApi.relateAttributeOptionToStockItem.key]: ItemsApi.relateAttributeOptionToStockItem,
    [ItemsApi.relateBrandToStockItem.key]: ItemsApi.relateBrandToStockItem,
    [ItemsApi.relateCategoryToStockItem.key]: ItemsApi.relateCategoryToStockItem,
    [ItemsApi.relateGoogleCategoryToStockItem.key]: ItemsApi.relateGoogleCategoryToStockItem,
    [ItemsApi.relateImageToStockItem.key]: ItemsApi.relateImageToStockItem,
    [ItemsApi.relatePriceRuleToStockItem.key]: ItemsApi.relatePriceRuleToStockItem,
    [ItemsApi.relateQuestionToStockItem.key]: ItemsApi.relateQuestionToStockItem,
    [ItemsApi.relateRefundPolicyToStockItem.key]: ItemsApi.relateRefundPolicyToStockItem,
    [ItemsApi.relateReturnPolicyToStockItem.key]: ItemsApi.relateReturnPolicyToStockItem,
    [ItemsApi.relateReviewToStockItem.key]: ItemsApi.relateReviewToStockItem,
    [ItemsApi.relateShippingPolicyToStockItem.key]: ItemsApi.relateShippingPolicyToStockItem,
    [ItemsApi.relateTagToStockItem.key]: ItemsApi.relateTagToStockItem,
    [ItemsApi.relateTaxPolicyToStockItem.key]: ItemsApi.relateTaxPolicyToStockItem,
    [ItemsApi.relateTypeToStockItem.key]: ItemsApi.relateTypeToStockItem,
    [ItemsApi.relateWarrantyPolicyToStockItem.key]: ItemsApi.relateWarrantyPolicyToStockItem,
    [ItemsApi.removeAttachmentFromStockItem.key]: ItemsApi.removeAttachmentFromStockItem,
    [ItemsApi.removeAttributeOptionFromStockItem.key]: ItemsApi.removeAttributeOptionFromStockItem,
    [ItemsApi.removeBrandFromStockItem.key]: ItemsApi.removeBrandFromStockItem,
    [ItemsApi.removeCategoryFromStockItem.key]: ItemsApi.removeCategoryFromStockItem,
    [ItemsApi.removeGoogleCategoryFromStockItem.key]: ItemsApi.removeGoogleCategoryFromStockItem,
    [ItemsApi.removeImageFromStockItem.key]: ItemsApi.removeImageFromStockItem,
    [ItemsApi.removePriceRuleFromStockItem.key]: ItemsApi.removePriceRuleFromStockItem,
    [ItemsApi.removeQuestionFromStockItem.key]: ItemsApi.removeQuestionFromStockItem,
    [ItemsApi.removeRefundPolicyFromStockItem.key]: ItemsApi.removeRefundPolicyFromStockItem,
    [ItemsApi.removeReturnPolicyFromStockItem.key]: ItemsApi.removeReturnPolicyFromStockItem,
    [ItemsApi.removeReviewFromStockItem.key]: ItemsApi.removeReviewFromStockItem,
    [ItemsApi.removeShippingPolicyFromStockItem.key]: ItemsApi.removeShippingPolicyFromStockItem,
    [ItemsApi.removeTagFromStockItem.key]: ItemsApi.removeTagFromStockItem,
    [ItemsApi.removeTaxPolicyFromStockItem.key]: ItemsApi.removeTaxPolicyFromStockItem,
    [ItemsApi.removeTypeFromStockItem.key]: ItemsApi.removeTypeFromStockItem,
    [ItemsApi.removeWarrantyPolicyFromStockItem.key]: ItemsApi.removeWarrantyPolicyFromStockItem,
    [ItemsApi.updateProductPrimaryImageAsync.key]: ItemsApi.updateProductPrimaryImageAsync,
    [ItemsApi.updateStockItem.key]: ItemsApi.updateStockItem,
    [MerchantsApi.getMerchantById.key]: MerchantsApi.getMerchantById,
    [MerchantsApi.getMerchants.key]: MerchantsApi.getMerchants,
    [MerchantsApi.getMerchantsCount.key]: MerchantsApi.getMerchantsCount,
    [PricingRulesApi.createPricingRule.key]: PricingRulesApi.createPricingRule,
    [PricingRulesApi.deletePricingRule.key]: PricingRulesApi.deletePricingRule,
    [PricingRulesApi.getPricingRuleById.key]: PricingRulesApi.getPricingRuleById,
    [PricingRulesApi.getPricingRules.key]: PricingRulesApi.getPricingRules,
    [PricingRulesApi.updatePricingRule.key]: PricingRulesApi.updatePricingRule,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
