const DealUnitFlowsApi = require('../apis/DealUnitFlowsApi');
const DealUnitsApi = require('../apis/DealUnitsApi');
const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const SalesLiteraturesApi = require('../apis/SalesLiteraturesApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [DealUnitFlowsApi.createDealUnitFlowAsync.key]: DealUnitFlowsApi.createDealUnitFlowAsync,
    [DealUnitFlowsApi.createDealUnitFlowStageAsync.key]: DealUnitFlowsApi.createDealUnitFlowStageAsync,
    [DealUnitFlowsApi.deleteDealUnitFlowAsync.key]: DealUnitFlowsApi.deleteDealUnitFlowAsync,
    [DealUnitFlowsApi.deleteDealUnitFlowStageAsync.key]: DealUnitFlowsApi.deleteDealUnitFlowStageAsync,
    [DealUnitFlowsApi.getDealUnitFlowAsync.key]: DealUnitFlowsApi.getDealUnitFlowAsync,
    [DealUnitFlowsApi.getDealUnitFlowStageAsync.key]: DealUnitFlowsApi.getDealUnitFlowStageAsync,
    [DealUnitFlowsApi.getDealUnitFlowStagesAsync.key]: DealUnitFlowsApi.getDealUnitFlowStagesAsync,
    [DealUnitFlowsApi.getDealUnitFlowStagesCountAsync.key]: DealUnitFlowsApi.getDealUnitFlowStagesCountAsync,
    [DealUnitFlowsApi.getDealUnitFlowsAsync.key]: DealUnitFlowsApi.getDealUnitFlowsAsync,
    [DealUnitFlowsApi.getDealUnitFlowsCountAsync.key]: DealUnitFlowsApi.getDealUnitFlowsCountAsync,
    [DealUnitFlowsApi.updateDealUnitFlowAsync.key]: DealUnitFlowsApi.updateDealUnitFlowAsync,
    [DealUnitFlowsApi.updateDealUnitFlowStageAsync.key]: DealUnitFlowsApi.updateDealUnitFlowStageAsync,
    [DealUnitsApi.calculateDealUnitAsync.key]: DealUnitsApi.calculateDealUnitAsync,
    [DealUnitsApi.calculateDealUnitLineAsync.key]: DealUnitsApi.calculateDealUnitLineAsync,
    [DealUnitsApi.createDealUnitAsync.key]: DealUnitsApi.createDealUnitAsync,
    [DealUnitsApi.createGetDealUnitLinesAsync.key]: DealUnitsApi.createGetDealUnitLinesAsync,
    [DealUnitsApi.deleteDealUnitAsync.key]: DealUnitsApi.deleteDealUnitAsync,
    [DealUnitsApi.deleteDealUnitPriceAsync.key]: DealUnitsApi.deleteDealUnitPriceAsync,
    [DealUnitsApi.getDealUnitAsync.key]: DealUnitsApi.getDealUnitAsync,
    [DealUnitsApi.getDealUnitLinesAsync.key]: DealUnitsApi.getDealUnitLinesAsync,
    [DealUnitsApi.getDealUnitLinesCountAsync.key]: DealUnitsApi.getDealUnitLinesCountAsync,
    [DealUnitsApi.getDealUnitPriceAsync.key]: DealUnitsApi.getDealUnitPriceAsync,
    [DealUnitsApi.getDealUnitsAsync.key]: DealUnitsApi.getDealUnitsAsync,
    [DealUnitsApi.getDealUnitsCountAsync.key]: DealUnitsApi.getDealUnitsCountAsync,
    [DealUnitsApi.getExtendedDealUnitAsync.key]: DealUnitsApi.getExtendedDealUnitAsync,
    [DealUnitsApi.getExtendedDealUnitsAsync.key]: DealUnitsApi.getExtendedDealUnitsAsync,
    [DealUnitsApi.updateDealUnitAsync.key]: DealUnitsApi.updateDealUnitAsync,
    [DealUnitsApi.updateDealUnitPriceAsync.key]: DealUnitsApi.updateDealUnitPriceAsync,
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [SalesLiteraturesApi.countSalesLiteraturesAsync.key]: SalesLiteraturesApi.countSalesLiteraturesAsync,
    [SalesLiteraturesApi.createSalesLiteratureAsync.key]: SalesLiteraturesApi.createSalesLiteratureAsync,
    [SalesLiteraturesApi.deleteSalesLiteratureAsync.key]: SalesLiteraturesApi.deleteSalesLiteratureAsync,
    [SalesLiteraturesApi.getExtendedSalesLiteraturesAsync.key]: SalesLiteraturesApi.getExtendedSalesLiteraturesAsync,
    [SalesLiteraturesApi.getSalesLiteratureAsync.key]: SalesLiteraturesApi.getSalesLiteratureAsync,
    [SalesLiteraturesApi.getSalesLiteraturesAsync.key]: SalesLiteraturesApi.getSalesLiteraturesAsync,
    [SalesLiteraturesApi.updateSalesLiteratureAsync.key]: SalesLiteraturesApi.updateSalesLiteratureAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
