const CompletionsApi = require('../apis/CompletionsApi');
const DealUnitFlowsApi = require('../apis/DealUnitFlowsApi');
const DealUnitsApi = require('../apis/DealUnitsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [DealUnitFlowsApi.createDealUnitFlowAsync.key]: DealUnitFlowsApi.createDealUnitFlowAsync,
    [DealUnitFlowsApi.createDealUnitFlowStageAsync.key]: DealUnitFlowsApi.createDealUnitFlowStageAsync,
    [DealUnitFlowsApi.deleteDealUnitFlowAsync.key]: DealUnitFlowsApi.deleteDealUnitFlowAsync,
    [DealUnitFlowsApi.deleteDealUnitFlowStageAsync.key]: DealUnitFlowsApi.deleteDealUnitFlowStageAsync,
    [DealUnitFlowsApi.getDealUnitFlowAsync.key]: DealUnitFlowsApi.getDealUnitFlowAsync,
    [DealUnitFlowsApi.getDealUnitFlowStageAsync.key]: DealUnitFlowsApi.getDealUnitFlowStageAsync,
    [DealUnitFlowsApi.getDealUnitFlowStagesAsync.key]: DealUnitFlowsApi.getDealUnitFlowStagesAsync,
    [DealUnitFlowsApi.getDealUnitFlowStagesCountAsync.key]: DealUnitFlowsApi.getDealUnitFlowStagesCountAsync,
    [DealUnitFlowsApi.getDealUnitFlowsAsync.key]: DealUnitFlowsApi.getDealUnitFlowsAsync,
    [DealUnitFlowsApi.getDealUnitFlowsCountAsync.key]: DealUnitFlowsApi.getDealUnitFlowsCountAsync,
    [DealUnitFlowsApi.patchDealUnitFlowAsync.key]: DealUnitFlowsApi.patchDealUnitFlowAsync,
    [DealUnitFlowsApi.patchDealUnitFlowStageAsync.key]: DealUnitFlowsApi.patchDealUnitFlowStageAsync,
    [DealUnitFlowsApi.updateDealUnitFlowAsync.key]: DealUnitFlowsApi.updateDealUnitFlowAsync,
    [DealUnitFlowsApi.updateDealUnitFlowStageAsync.key]: DealUnitFlowsApi.updateDealUnitFlowStageAsync,
    [DealUnitsApi.calculateDealUnitAsync.key]: DealUnitsApi.calculateDealUnitAsync,
    [DealUnitsApi.calculateDealUnitLineAsync.key]: DealUnitsApi.calculateDealUnitLineAsync,
    [DealUnitsApi.createDealUnitAsync.key]: DealUnitsApi.createDealUnitAsync,
    [DealUnitsApi.createGetDealUnitLinesAsync.key]: DealUnitsApi.createGetDealUnitLinesAsync,
    [DealUnitsApi.deleteDealUnitAsync.key]: DealUnitsApi.deleteDealUnitAsync,
    [DealUnitsApi.deleteDealUnitPriceAsync.key]: DealUnitsApi.deleteDealUnitPriceAsync,
    [DealUnitsApi.getDealUnitAsync.key]: DealUnitsApi.getDealUnitAsync,
    [DealUnitsApi.getDealUnitLinesAsync.key]: DealUnitsApi.getDealUnitLinesAsync,
    [DealUnitsApi.getDealUnitLinesCountAsync.key]: DealUnitsApi.getDealUnitLinesCountAsync,
    [DealUnitsApi.getDealUnitPriceAsync.key]: DealUnitsApi.getDealUnitPriceAsync,
    [DealUnitsApi.getDealUnitsAsync.key]: DealUnitsApi.getDealUnitsAsync,
    [DealUnitsApi.getDealUnitsCountAsync.key]: DealUnitsApi.getDealUnitsCountAsync,
    [DealUnitsApi.getExtendedDealUnitAsync.key]: DealUnitsApi.getExtendedDealUnitAsync,
    [DealUnitsApi.getExtendedDealUnitsAsync.key]: DealUnitsApi.getExtendedDealUnitsAsync,
    [DealUnitsApi.patchDealUnitAsync.key]: DealUnitsApi.patchDealUnitAsync,
    [DealUnitsApi.patchDealUnitLineAsync.key]: DealUnitsApi.patchDealUnitLineAsync,
    [DealUnitsApi.updateDealUnitAsync.key]: DealUnitsApi.updateDealUnitAsync,
    [DealUnitsApi.updateDealUnitPriceAsync.key]: DealUnitsApi.updateDealUnitPriceAsync,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
