const CompletionsApi = require('../apis/CompletionsApi');
const FenixAlliancePortalsWebsiteApi = require('../apis/FenixAlliancePortalsWebsiteApi');
const OptionsApi = require('../apis/OptionsApi');
const UsersApi = require('../apis/UsersApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [CompletionsApi.apiV2AiServiceCompletionsCompleteGet.key]: CompletionsApi.apiV2AiServiceCompletionsCompleteGet,
    [FenixAlliancePortalsWebsiteApi.accountLogoutPost.key]: FenixAlliancePortalsWebsiteApi.accountLogoutPost,
    [FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost.key]: FenixAlliancePortalsWebsiteApi.accountManageDownloadPersonalDataPost,
    [FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountManageLinkExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost.key]: FenixAlliancePortalsWebsiteApi.accountPerformExternalLoginPost,
    [FenixAlliancePortalsWebsiteApi.forgotPasswordPost.key]: FenixAlliancePortalsWebsiteApi.forgotPasswordPost,
    [FenixAlliancePortalsWebsiteApi.healthGet.key]: FenixAlliancePortalsWebsiteApi.healthGet,
    [FenixAlliancePortalsWebsiteApi.helloGet.key]: FenixAlliancePortalsWebsiteApi.helloGet,
    [FenixAlliancePortalsWebsiteApi.loginPost.key]: FenixAlliancePortalsWebsiteApi.loginPost,
    [FenixAlliancePortalsWebsiteApi.manage2faPost.key]: FenixAlliancePortalsWebsiteApi.manage2faPost,
    [FenixAlliancePortalsWebsiteApi.manageInfoGet.key]: FenixAlliancePortalsWebsiteApi.manageInfoGet,
    [FenixAlliancePortalsWebsiteApi.manageInfoPost.key]: FenixAlliancePortalsWebsiteApi.manageInfoPost,
    [FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail.key]: FenixAlliancePortalsWebsiteApi.mapIdentityApi/confirmEmail,
    [FenixAlliancePortalsWebsiteApi.refreshPost.key]: FenixAlliancePortalsWebsiteApi.refreshPost,
    [FenixAlliancePortalsWebsiteApi.registerPost.key]: FenixAlliancePortalsWebsiteApi.registerPost,
    [FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost.key]: FenixAlliancePortalsWebsiteApi.resendConfirmationEmailPost,
    [FenixAlliancePortalsWebsiteApi.resetPasswordPost.key]: FenixAlliancePortalsWebsiteApi.resetPasswordPost,
    [FenixAlliancePortalsWebsiteApi.versionGet.key]: FenixAlliancePortalsWebsiteApi.versionGet,
    [OptionsApi.createUserOption.key]: OptionsApi.createUserOption,
    [OptionsApi.deleteUserOption.key]: OptionsApi.deleteUserOption,
    [OptionsApi.getUserOptionById.key]: OptionsApi.getUserOptionById,
    [OptionsApi.getUserOptionByKey.key]: OptionsApi.getUserOptionByKey,
    [OptionsApi.getUserOptions.key]: OptionsApi.getUserOptions,
    [OptionsApi.getUserOptionsCount.key]: OptionsApi.getUserOptionsCount,
    [OptionsApi.patchUserOption.key]: OptionsApi.patchUserOption,
    [OptionsApi.updateUserOption.key]: OptionsApi.updateUserOption,
    [OptionsApi.upsertUserOption.key]: OptionsApi.upsertUserOption,
    [UsersApi.countCurrentUserFollowersAsync.key]: UsersApi.countCurrentUserFollowersAsync,
    [UsersApi.countCurrentUserFollowsAsync.key]: UsersApi.countCurrentUserFollowsAsync,
    [UsersApi.countCurrentUserNotificationsAsync.key]: UsersApi.countCurrentUserNotificationsAsync,
    [UsersApi.countCurrentUserTenantsAsync.key]: UsersApi.countCurrentUserTenantsAsync,
    [UsersApi.getCurrentUserAddressesAsync.key]: UsersApi.getCurrentUserAddressesAsync,
    [UsersApi.getCurrentUserAsync.key]: UsersApi.getCurrentUserAsync,
    [UsersApi.getCurrentUserAvatarAsync.key]: UsersApi.getCurrentUserAvatarAsync,
    [UsersApi.getCurrentUserCartAsync.key]: UsersApi.getCurrentUserCartAsync,
    [UsersApi.getCurrentUserEnrollmentsAsync.key]: UsersApi.getCurrentUserEnrollmentsAsync,
    [UsersApi.getCurrentUserEnrollmentsExtendedAsync.key]: UsersApi.getCurrentUserEnrollmentsExtendedAsync,
    [UsersApi.getCurrentUserFollowersAsync.key]: UsersApi.getCurrentUserFollowersAsync,
    [UsersApi.getCurrentUserFollowsAsync.key]: UsersApi.getCurrentUserFollowsAsync,
    [UsersApi.getCurrentUserInvitationAsync.key]: UsersApi.getCurrentUserInvitationAsync,
    [UsersApi.getCurrentUserNotificationsAsync.key]: UsersApi.getCurrentUserNotificationsAsync,
    [UsersApi.getCurrentUserSettingsAsync.key]: UsersApi.getCurrentUserSettingsAsync,
    [UsersApi.getCurrentUserSocialProfileAsync.key]: UsersApi.getCurrentUserSocialProfileAsync,
    [UsersApi.getCurrentUserTenantsAsync.key]: UsersApi.getCurrentUserTenantsAsync,
    [UsersApi.getCurrentUserTenantsExtendedAsync.key]: UsersApi.getCurrentUserTenantsExtendedAsync,
    [UsersApi.getCurrentUserWalletAsync.key]: UsersApi.getCurrentUserWalletAsync,
    [UsersApi.getEnrollmentAsync.key]: UsersApi.getEnrollmentAsync,
    [UsersApi.getExtendedCurrentUserAsync.key]: UsersApi.getExtendedCurrentUserAsync,
    [UsersApi.patchCurrentUserAsync.key]: UsersApi.patchCurrentUserAsync,
    [UsersApi.updateAvatarAsync.key]: UsersApi.updateAvatarAsync,
    [UsersApi.updateCurrentUserAsync.key]: UsersApi.updateCurrentUserAsync,
    [UsersApi.updateCurrentUserSettingsAsync.key]: UsersApi.updateCurrentUserSettingsAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
