const FenixAllianceABSWebApi = require('../apis/FenixAllianceABSWebApi');
const OptionsApi = require('../apis/OptionsApi');
const UsersApi = require('../apis/UsersApi');
const { triggerMiddleware, isTrigger, searchMiddleware, hasSearchRequisites, isSearchAction, isCreateAction } = require('../utils/utils');

const actions = {
    [FenixAllianceABSWebApi.accountLogoutPost.key]: FenixAllianceABSWebApi.accountLogoutPost,
    [FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost.key]: FenixAllianceABSWebApi.accountManageDownloadPersonalDataPost,
    [FenixAllianceABSWebApi.accountManageLinkExternalLoginPost.key]: FenixAllianceABSWebApi.accountManageLinkExternalLoginPost,
    [FenixAllianceABSWebApi.accountPerformExternalLoginPost.key]: FenixAllianceABSWebApi.accountPerformExternalLoginPost,
    [FenixAllianceABSWebApi.forgotPasswordPost.key]: FenixAllianceABSWebApi.forgotPasswordPost,
    [FenixAllianceABSWebApi.healthGet.key]: FenixAllianceABSWebApi.healthGet,
    [FenixAllianceABSWebApi.helloGet.key]: FenixAllianceABSWebApi.helloGet,
    [FenixAllianceABSWebApi.loginPost.key]: FenixAllianceABSWebApi.loginPost,
    [FenixAllianceABSWebApi.manage2faPost.key]: FenixAllianceABSWebApi.manage2faPost,
    [FenixAllianceABSWebApi.manageInfoGet.key]: FenixAllianceABSWebApi.manageInfoGet,
    [FenixAllianceABSWebApi.manageInfoPost.key]: FenixAllianceABSWebApi.manageInfoPost,
    [FenixAllianceABSWebApi.mapIdentityApi/confirmEmail.key]: FenixAllianceABSWebApi.mapIdentityApi/confirmEmail,
    [FenixAllianceABSWebApi.refreshPost.key]: FenixAllianceABSWebApi.refreshPost,
    [FenixAllianceABSWebApi.registerPost.key]: FenixAllianceABSWebApi.registerPost,
    [FenixAllianceABSWebApi.resendConfirmationEmailPost.key]: FenixAllianceABSWebApi.resendConfirmationEmailPost,
    [FenixAllianceABSWebApi.resetPasswordPost.key]: FenixAllianceABSWebApi.resetPasswordPost,
    [FenixAllianceABSWebApi.versionGet.key]: FenixAllianceABSWebApi.versionGet,
    [OptionsApi.createUserOption.key]: OptionsApi.createUserOption,
    [OptionsApi.deleteUserOption.key]: OptionsApi.deleteUserOption,
    [OptionsApi.getUserOptionById.key]: OptionsApi.getUserOptionById,
    [OptionsApi.getUserOptionByKey.key]: OptionsApi.getUserOptionByKey,
    [OptionsApi.getUserOptions.key]: OptionsApi.getUserOptions,
    [OptionsApi.getUserOptionsCount.key]: OptionsApi.getUserOptionsCount,
    [OptionsApi.updateUserOption.key]: OptionsApi.updateUserOption,
    [OptionsApi.upsertUserOption.key]: OptionsApi.upsertUserOption,
    [UsersApi.countCurrentUserFollowersAsync.key]: UsersApi.countCurrentUserFollowersAsync,
    [UsersApi.countCurrentUserFollowsAsync.key]: UsersApi.countCurrentUserFollowsAsync,
    [UsersApi.countCurrentUserNotificationsAsync.key]: UsersApi.countCurrentUserNotificationsAsync,
    [UsersApi.countCurrentUserTenantsAsync.key]: UsersApi.countCurrentUserTenantsAsync,
    [UsersApi.getCurrentUserAddressesAsync.key]: UsersApi.getCurrentUserAddressesAsync,
    [UsersApi.getCurrentUserAsync.key]: UsersApi.getCurrentUserAsync,
    [UsersApi.getCurrentUserAvatarAsync.key]: UsersApi.getCurrentUserAvatarAsync,
    [UsersApi.getCurrentUserCartAsync.key]: UsersApi.getCurrentUserCartAsync,
    [UsersApi.getCurrentUserEnrollmentsAsync.key]: UsersApi.getCurrentUserEnrollmentsAsync,
    [UsersApi.getCurrentUserEnrollmentsExtendedAsync.key]: UsersApi.getCurrentUserEnrollmentsExtendedAsync,
    [UsersApi.getCurrentUserFollowersAsync.key]: UsersApi.getCurrentUserFollowersAsync,
    [UsersApi.getCurrentUserFollowsAsync.key]: UsersApi.getCurrentUserFollowsAsync,
    [UsersApi.getCurrentUserInvitationAsync.key]: UsersApi.getCurrentUserInvitationAsync,
    [UsersApi.getCurrentUserNotificationsAsync.key]: UsersApi.getCurrentUserNotificationsAsync,
    [UsersApi.getCurrentUserSettingsAsync.key]: UsersApi.getCurrentUserSettingsAsync,
    [UsersApi.getCurrentUserSocialProfileAsync.key]: UsersApi.getCurrentUserSocialProfileAsync,
    [UsersApi.getCurrentUserTenantsAsync.key]: UsersApi.getCurrentUserTenantsAsync,
    [UsersApi.getCurrentUserTenantsExtendedAsync.key]: UsersApi.getCurrentUserTenantsExtendedAsync,
    [UsersApi.getCurrentUserWalletAsync.key]: UsersApi.getCurrentUserWalletAsync,
    [UsersApi.getEnrollmentAsync.key]: UsersApi.getEnrollmentAsync,
    [UsersApi.getExtendedCurrentUserAsync.key]: UsersApi.getExtendedCurrentUserAsync,
    [UsersApi.patchCurrentUserAsync.key]: UsersApi.patchCurrentUserAsync,
    [UsersApi.updateAvatarAsync.key]: UsersApi.updateAvatarAsync,
    [UsersApi.updateCurrentUserAsync.key]: UsersApi.updateCurrentUserAsync,
    [UsersApi.updateCurrentUserSettingsAsync.key]: UsersApi.updateCurrentUserSettingsAsync,
}

module.exports = {
    searchActions: () => Object.entries(actions).reduce((actions, [key, value]) => isSearchAction(key) && hasSearchRequisites(value) ? {...actions, [key]: searchMiddleware(value)} : actions, {}),
    createActions: () => Object.entries(actions).reduce((actions, [key, value]) => isCreateAction(key) ? {...actions, [key]: value} : actions, {}),
    triggers: () => Object.entries(actions).reduce((actions, [key, value]) => isTrigger(key) ? {...actions, [key]: triggerMiddleware(value)} : actions, {}),
}
