const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}sku`,
                label: `[${labelPrefix}sku]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}upc`,
                label: `[${labelPrefix}upc]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ean`,
                label: `[${labelPrefix}ean]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mpn`,
                label: `[${labelPrefix}mpn]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}skUs`,
                label: `[${labelPrefix}skUs]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}isbn`,
                label: `[${labelPrefix}isbn]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}upCs`,
                label: `[${labelPrefix}upCs]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}eaNs`,
                label: `[${labelPrefix}eaNs]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}asin`,
                label: `[${labelPrefix}asin]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}gtin`,
                label: `[${labelPrefix}gtin]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mpNs`,
                label: `[${labelPrefix}mpNs]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}part`,
                label: `[${labelPrefix}part]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}name`,
                label: `[${labelPrefix}name]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}isbNs`,
                label: `[${labelPrefix}isbNs]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}asiNs`,
                label: `[${labelPrefix}asiNs]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}gtiNs`,
                label: `[${labelPrefix}gtiNs]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}model`,
                label: `[${labelPrefix}model]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}color`,
                label: `[${labelPrefix}color]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}isbN13`,
                label: `[${labelPrefix}isbN13]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}unspsc`,
                label: `[${labelPrefix}unspsc]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}unitId`,
                label: `[${labelPrefix}unitId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}series`,
                label: `[${labelPrefix}series]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}barcode`,
                label: `[${labelPrefix}barcode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}unspsCs`,
                label: `[${labelPrefix}unspsCs]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}pattern`,
                label: `[${labelPrefix}pattern]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}summary`,
                label: `[${labelPrefix}summary]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}brandId`,
                label: `[${labelPrefix}brandId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}features`,
                label: `[${labelPrefix}features]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}material`,
                label: `[${labelPrefix}material]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tenantId`,
                label: `[${labelPrefix}tenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}permalink`,
                label: `[${labelPrefix}permalink]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}brandName`,
                label: `[${labelPrefix}brandName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}languageId`,
                label: `[${labelPrefix}languageId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}itemTypeId`,
                label: `[${labelPrefix}itemTypeId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}categoryId`,
                label: `[${labelPrefix}categoryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}currencyId`,
                label: `[${labelPrefix}currencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}unitGroupId`,
                label: `[${labelPrefix}unitGroupId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}ingredients`,
                label: `[${labelPrefix}ingredients]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}releaseDate`,
                label: `[${labelPrefix}releaseDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enrollmentId`,
                label: `[${labelPrefix}enrollmentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}supplierCode`,
                label: `[${labelPrefix}supplierCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shipsToRules`,
                label: `[${labelPrefix}shipsToRules]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}purchaseNote`,
                label: `[${labelPrefix}purchaseNote]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}parentItemId`,
                label: `[${labelPrefix}parentItemId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}itemTypeName`,
                label: `[${labelPrefix}itemTypeName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}discriminator`,
                label: `[${labelPrefix}discriminator]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tariffHeading`,
                label: `[${labelPrefix}tariffHeading]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}nutritionFacts`,
                label: `[${labelPrefix}nutritionFacts]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}mozaicCoverUrl`,
                label: `[${labelPrefix}mozaicCoverUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}packageContent`,
                label: `[${labelPrefix}packageContent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}youtubeVideoId`,
                label: `[${labelPrefix}youtubeVideoId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}primaryImageUrl`,
                label: `[${labelPrefix}primaryImageUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}longDescription`,
                label: `[${labelPrefix}longDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}measurementUnit`,
                label: `[${labelPrefix}measurementUnit]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shortDescription`,
                label: `[${labelPrefix}shortDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}googleCategories`,
                label: `[${labelPrefix}googleCategories]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}supplierProfileId`,
                label: `[${labelPrefix}supplierProfileId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingCountryId`,
                label: `[${labelPrefix}shippingCountryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}systemRequirements`,
                label: `[${labelPrefix}systemRequirements]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}customTaxDescription`,
                label: `[${labelPrefix}customTaxDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}officialDescriptionUrl`,
                label: `[${labelPrefix}officialDescriptionUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}energyEfficiencyRating`,
                label: `[${labelPrefix}energyEfficiencyRating]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}pageCoverBackgroundUrl`,
                label: `[${labelPrefix}pageCoverBackgroundUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}primaryGoogleCategoryId`,
                label: `[${labelPrefix}primaryGoogleCategoryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}operatingSystemSupported`,
                label: `[${labelPrefix}operatingSystemSupported]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}supportedOperatingSystem`,
                label: `[${labelPrefix}supportedOperatingSystem]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}primaryGoogleCategoryName`,
                label: `[${labelPrefix}primaryGoogleCategoryName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}hot`,
                label: `[${labelPrefix}hot]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}onSale`,
                label: `[${labelPrefix}onSale]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}auction`,
                label: `[${labelPrefix}auction]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}deleted`,
                label: `[${labelPrefix}deleted]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}digital`,
                label: `[${labelPrefix}digital]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}preSale`,
                label: `[${labelPrefix}preSale]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}taxable`,
                label: `[${labelPrefix}taxable]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}inStock`,
                label: `[${labelPrefix}inStock]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}featured`,
                label: `[${labelPrefix}featured]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}trending`,
                label: `[${labelPrefix}trending]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}lowStock`,
                label: `[${labelPrefix}lowStock]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}published`,
                label: `[${labelPrefix}published]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}byRequest`,
                label: `[${labelPrefix}byRequest]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}onDiscount`,
                label: `[${labelPrefix}onDiscount]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isDailyDeal`,
                label: `[${labelPrefix}isDailyDeal]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isNewArrival`,
                label: `[${labelPrefix}isNewArrival]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isWeeklyDeal`,
                label: `[${labelPrefix}isWeeklyDeal]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isBestSeller`,
                label: `[${labelPrefix}isBestSeller]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isMonthlyDeal`,
                label: `[${labelPrefix}isMonthlyDeal]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}hasVariations`,
                label: `[${labelPrefix}hasVariations]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isFixedDiscount`,
                label: `[${labelPrefix}isFixedDiscount]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isDealersChoice`,
                label: `[${labelPrefix}isDealersChoice]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}manageInventory`,
                label: `[${labelPrefix}manageInventory]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isOfficialChoice`,
                label: `[${labelPrefix}isOfficialChoice]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}validPrimaryImage`,
                label: `[${labelPrefix}validPrimaryImage]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isDeadlineDiscount`,
                label: `[${labelPrefix}isDeadlineDiscount]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displayShowcaseTab`,
                label: `[${labelPrefix}displayShowcaseTab]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}taxIncludedInPrice`,
                label: `[${labelPrefix}taxIncludedInPrice]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isProductOfTheWeek`,
                label: `[${labelPrefix}isProductOfTheWeek]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isProductOfTheMonth`,
                label: `[${labelPrefix}isProductOfTheMonth]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}isPercentageDiscount`,
                label: `[${labelPrefix}isPercentageDiscount]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displayOnGlobalMozaic`,
                label: `[${labelPrefix}displayOnGlobalMozaic]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displayOnBrandsMozaic`,
                label: `[${labelPrefix}displayOnBrandsMozaic]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}disableDefaultPolicies`,
                label: `[${labelPrefix}disableDefaultPolicies]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displayOnCategoryMozaic`,
                label: `[${labelPrefix}displayOnCategoryMozaic]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displayDescriptionEditor`,
                label: `[${labelPrefix}displayDescriptionEditor]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displayShortDescriptionEditor`,
                label: `[${labelPrefix}displayShortDescriptionEditor]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}displayOnBannerMarketingRotation`,
                label: `[${labelPrefix}displayOnBannerMarketingRotation]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}auctionEnd`,
                label: `[${labelPrefix}auctionEnd]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}auctionStart`,
                label: `[${labelPrefix}auctionStart]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}publishedDate`,
                label: `[${labelPrefix}publishedDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}deadlineDiscountFromDate`,
                label: `[${labelPrefix}deadlineDiscountFromDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}deadlineDiscountDueDate`,
                label: `[${labelPrefix}deadlineDiscountDueDate]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lastFixedPricesUpdateDateTime`,
                label: `[${labelPrefix}lastFixedPricesUpdateDateTime]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}images`,
                label: `[${labelPrefix}images]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}viewsCount`,
                label: `[${labelPrefix}viewsCount]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}reviewsCount`,
                label: `[${labelPrefix}reviewsCount]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}questionsCount`,
                label: `[${labelPrefix}questionsCount]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}packagedQuantity`,
                label: `[${labelPrefix}packagedQuantity]`,
                type: 'integer',
            },
            {
                key: `${keyPrefix}reviewsAvg`,
                label: `[${labelPrefix}reviewsAvg]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}recurrency`,
                label: `[${labelPrefix}recurrency]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}currentStock`,
                label: `[${labelPrefix}currentStock]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}width`,
                label: `[${labelPrefix}width]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}weight`,
                label: `[${labelPrefix}weight]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}length`,
                label: `[${labelPrefix}length]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}height`,
                label: `[${labelPrefix}height]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}regularPrice`,
                label: `[${labelPrefix}regularPrice]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}discountPrice`,
                label: `[${labelPrefix}discountPrice]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}customTaxValue`,
                label: `[${labelPrefix}customTaxValue]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}discountAmount`,
                label: `[${labelPrefix}discountAmount]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}inCartQuantity`,
                label: `[${labelPrefix}inCartQuantity]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}customTaxAmount`,
                label: `[${labelPrefix}customTaxAmount]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}discountPercentage`,
                label: `[${labelPrefix}discountPercentage]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}customTaxPercentage`,
                label: `[${labelPrefix}customTaxPercentage]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedTaxesInUsd`,
                label: `[${labelPrefix}estimatedTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedProfitInUsd`,
                label: `[${labelPrefix}estimatedProfitInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedBasePriceInUsd`,
                label: `[${labelPrefix}estimatedBasePriceInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedDiscountsInUsd`,
                label: `[${labelPrefix}estimatedDiscountsInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedSurchargesInUsd`,
                label: `[${labelPrefix}estimatedSurchargesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedPaymentTaxInUsd`,
                label: `[${labelPrefix}estimatedPaymentTaxInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedTotalPriceInUsd`,
                label: `[${labelPrefix}estimatedTotalPriceInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedPaymentCostInUsd`,
                label: `[${labelPrefix}estimatedPaymentCostInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedDealSavingsInUsd`,
                label: `[${labelPrefix}estimatedDealSavingsInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedRegularPriceInUsd`,
                label: `[${labelPrefix}estimatedRegularPriceInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedTaxBasePriceInUsd`,
                label: `[${labelPrefix}estimatedTaxBasePriceInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedWithholdingTaxesInUsd`,
                label: `[${labelPrefix}estimatedWithholdingTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedDefaultShippingTaxInUsd`,
                label: `[${labelPrefix}estimatedDefaultShippingTaxInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}estimatedDefaultShippingCostInUsd`,
                label: `[${labelPrefix}estimatedDefaultShippingCostInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}selectedTags`,
                label: `[${labelPrefix}selectedTags]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedTypes`,
                label: `[${labelPrefix}selectedTypes]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedBrands`,
                label: `[${labelPrefix}selectedBrands]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedCategories`,
                label: `[${labelPrefix}selectedCategories]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedTaxPolicies`,
                label: `[${labelPrefix}selectedTaxPolicies]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedPricingRules`,
                label: `[${labelPrefix}selectedPricingRules]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedRefundPolicies`,
                label: `[${labelPrefix}selectedRefundPolicies]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedReturnPolicies`,
                label: `[${labelPrefix}selectedReturnPolicies]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedPricingPolicies`,
                label: `[${labelPrefix}selectedPricingPolicies]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedGoogleCategories`,
                label: `[${labelPrefix}selectedGoogleCategories]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedWarrantyPolicies`,
                label: `[${labelPrefix}selectedWarrantyPolicies]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedShipmentPolicies`,
                label: `[${labelPrefix}selectedShipmentPolicies]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedAttributesOptions`,
                label: `[${labelPrefix}selectedAttributesOptions]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}selectedSellingMarginPolicies`,
                label: `[${labelPrefix}selectedSellingMarginPolicies]`,
                list: true,
                type: 'string',
            },
            {
                key: `${keyPrefix}serviceId`,
                label: `[${labelPrefix}serviceId]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'sku': bundle.inputData?.[`${keyPrefix}sku`],
            'upc': bundle.inputData?.[`${keyPrefix}upc`],
            'ean': bundle.inputData?.[`${keyPrefix}ean`],
            'mpn': bundle.inputData?.[`${keyPrefix}mpn`],
            'skUs': bundle.inputData?.[`${keyPrefix}skUs`],
            'isbn': bundle.inputData?.[`${keyPrefix}isbn`],
            'upCs': bundle.inputData?.[`${keyPrefix}upCs`],
            'eaNs': bundle.inputData?.[`${keyPrefix}eaNs`],
            'asin': bundle.inputData?.[`${keyPrefix}asin`],
            'gtin': bundle.inputData?.[`${keyPrefix}gtin`],
            'mpNs': bundle.inputData?.[`${keyPrefix}mpNs`],
            'part': bundle.inputData?.[`${keyPrefix}part`],
            'name': bundle.inputData?.[`${keyPrefix}name`],
            'isbNs': bundle.inputData?.[`${keyPrefix}isbNs`],
            'asiNs': bundle.inputData?.[`${keyPrefix}asiNs`],
            'gtiNs': bundle.inputData?.[`${keyPrefix}gtiNs`],
            'model': bundle.inputData?.[`${keyPrefix}model`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'color': bundle.inputData?.[`${keyPrefix}color`],
            'isbN13': bundle.inputData?.[`${keyPrefix}isbN13`],
            'unspsc': bundle.inputData?.[`${keyPrefix}unspsc`],
            'unitId': bundle.inputData?.[`${keyPrefix}unitId`],
            'series': bundle.inputData?.[`${keyPrefix}series`],
            'barcode': bundle.inputData?.[`${keyPrefix}barcode`],
            'unspsCs': bundle.inputData?.[`${keyPrefix}unspsCs`],
            'pattern': bundle.inputData?.[`${keyPrefix}pattern`],
            'summary': bundle.inputData?.[`${keyPrefix}summary`],
            'brandId': bundle.inputData?.[`${keyPrefix}brandId`],
            'features': bundle.inputData?.[`${keyPrefix}features`],
            'material': bundle.inputData?.[`${keyPrefix}material`],
            'tenantId': bundle.inputData?.[`${keyPrefix}tenantId`],
            'permalink': bundle.inputData?.[`${keyPrefix}permalink`],
            'brandName': bundle.inputData?.[`${keyPrefix}brandName`],
            'languageId': bundle.inputData?.[`${keyPrefix}languageId`],
            'itemTypeId': bundle.inputData?.[`${keyPrefix}itemTypeId`],
            'categoryId': bundle.inputData?.[`${keyPrefix}categoryId`],
            'currencyId': bundle.inputData?.[`${keyPrefix}currencyId`],
            'unitGroupId': bundle.inputData?.[`${keyPrefix}unitGroupId`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'ingredients': bundle.inputData?.[`${keyPrefix}ingredients`],
            'releaseDate': bundle.inputData?.[`${keyPrefix}releaseDate`],
            'enrollmentId': bundle.inputData?.[`${keyPrefix}enrollmentId`],
            'supplierCode': bundle.inputData?.[`${keyPrefix}supplierCode`],
            'shipsToRules': bundle.inputData?.[`${keyPrefix}shipsToRules`],
            'purchaseNote': bundle.inputData?.[`${keyPrefix}purchaseNote`],
            'parentItemId': bundle.inputData?.[`${keyPrefix}parentItemId`],
            'itemTypeName': bundle.inputData?.[`${keyPrefix}itemTypeName`],
            'discriminator': bundle.inputData?.[`${keyPrefix}discriminator`],
            'tariffHeading': bundle.inputData?.[`${keyPrefix}tariffHeading`],
            'nutritionFacts': bundle.inputData?.[`${keyPrefix}nutritionFacts`],
            'mozaicCoverUrl': bundle.inputData?.[`${keyPrefix}mozaicCoverUrl`],
            'packageContent': bundle.inputData?.[`${keyPrefix}packageContent`],
            'youtubeVideoId': bundle.inputData?.[`${keyPrefix}youtubeVideoId`],
            'primaryImageUrl': bundle.inputData?.[`${keyPrefix}primaryImageUrl`],
            'longDescription': bundle.inputData?.[`${keyPrefix}longDescription`],
            'measurementUnit': bundle.inputData?.[`${keyPrefix}measurementUnit`],
            'shortDescription': bundle.inputData?.[`${keyPrefix}shortDescription`],
            'googleCategories': bundle.inputData?.[`${keyPrefix}googleCategories`],
            'supplierProfileId': bundle.inputData?.[`${keyPrefix}supplierProfileId`],
            'shippingCountryId': bundle.inputData?.[`${keyPrefix}shippingCountryId`],
            'systemRequirements': bundle.inputData?.[`${keyPrefix}systemRequirements`],
            'customTaxDescription': bundle.inputData?.[`${keyPrefix}customTaxDescription`],
            'officialDescriptionUrl': bundle.inputData?.[`${keyPrefix}officialDescriptionUrl`],
            'energyEfficiencyRating': bundle.inputData?.[`${keyPrefix}energyEfficiencyRating`],
            'pageCoverBackgroundUrl': bundle.inputData?.[`${keyPrefix}pageCoverBackgroundUrl`],
            'primaryGoogleCategoryId': bundle.inputData?.[`${keyPrefix}primaryGoogleCategoryId`],
            'operatingSystemSupported': bundle.inputData?.[`${keyPrefix}operatingSystemSupported`],
            'supportedOperatingSystem': bundle.inputData?.[`${keyPrefix}supportedOperatingSystem`],
            'primaryGoogleCategoryName': bundle.inputData?.[`${keyPrefix}primaryGoogleCategoryName`],
            'hot': bundle.inputData?.[`${keyPrefix}hot`],
            'onSale': bundle.inputData?.[`${keyPrefix}onSale`],
            'auction': bundle.inputData?.[`${keyPrefix}auction`],
            'deleted': bundle.inputData?.[`${keyPrefix}deleted`],
            'digital': bundle.inputData?.[`${keyPrefix}digital`],
            'preSale': bundle.inputData?.[`${keyPrefix}preSale`],
            'taxable': bundle.inputData?.[`${keyPrefix}taxable`],
            'inStock': bundle.inputData?.[`${keyPrefix}inStock`],
            'featured': bundle.inputData?.[`${keyPrefix}featured`],
            'trending': bundle.inputData?.[`${keyPrefix}trending`],
            'lowStock': bundle.inputData?.[`${keyPrefix}lowStock`],
            'published': bundle.inputData?.[`${keyPrefix}published`],
            'byRequest': bundle.inputData?.[`${keyPrefix}byRequest`],
            'onDiscount': bundle.inputData?.[`${keyPrefix}onDiscount`],
            'isDailyDeal': bundle.inputData?.[`${keyPrefix}isDailyDeal`],
            'isNewArrival': bundle.inputData?.[`${keyPrefix}isNewArrival`],
            'isWeeklyDeal': bundle.inputData?.[`${keyPrefix}isWeeklyDeal`],
            'isBestSeller': bundle.inputData?.[`${keyPrefix}isBestSeller`],
            'isMonthlyDeal': bundle.inputData?.[`${keyPrefix}isMonthlyDeal`],
            'hasVariations': bundle.inputData?.[`${keyPrefix}hasVariations`],
            'isFixedDiscount': bundle.inputData?.[`${keyPrefix}isFixedDiscount`],
            'isDealersChoice': bundle.inputData?.[`${keyPrefix}isDealersChoice`],
            'manageInventory': bundle.inputData?.[`${keyPrefix}manageInventory`],
            'isOfficialChoice': bundle.inputData?.[`${keyPrefix}isOfficialChoice`],
            'validPrimaryImage': bundle.inputData?.[`${keyPrefix}validPrimaryImage`],
            'isDeadlineDiscount': bundle.inputData?.[`${keyPrefix}isDeadlineDiscount`],
            'displayShowcaseTab': bundle.inputData?.[`${keyPrefix}displayShowcaseTab`],
            'taxIncludedInPrice': bundle.inputData?.[`${keyPrefix}taxIncludedInPrice`],
            'isProductOfTheWeek': bundle.inputData?.[`${keyPrefix}isProductOfTheWeek`],
            'isProductOfTheMonth': bundle.inputData?.[`${keyPrefix}isProductOfTheMonth`],
            'isPercentageDiscount': bundle.inputData?.[`${keyPrefix}isPercentageDiscount`],
            'displayOnGlobalMozaic': bundle.inputData?.[`${keyPrefix}displayOnGlobalMozaic`],
            'displayOnBrandsMozaic': bundle.inputData?.[`${keyPrefix}displayOnBrandsMozaic`],
            'disableDefaultPolicies': bundle.inputData?.[`${keyPrefix}disableDefaultPolicies`],
            'displayOnCategoryMozaic': bundle.inputData?.[`${keyPrefix}displayOnCategoryMozaic`],
            'displayDescriptionEditor': bundle.inputData?.[`${keyPrefix}displayDescriptionEditor`],
            'displayShortDescriptionEditor': bundle.inputData?.[`${keyPrefix}displayShortDescriptionEditor`],
            'displayOnBannerMarketingRotation': bundle.inputData?.[`${keyPrefix}displayOnBannerMarketingRotation`],
            'auctionEnd': bundle.inputData?.[`${keyPrefix}auctionEnd`],
            'auctionStart': bundle.inputData?.[`${keyPrefix}auctionStart`],
            'publishedDate': bundle.inputData?.[`${keyPrefix}publishedDate`],
            'deadlineDiscountFromDate': bundle.inputData?.[`${keyPrefix}deadlineDiscountFromDate`],
            'deadlineDiscountDueDate': bundle.inputData?.[`${keyPrefix}deadlineDiscountDueDate`],
            'lastFixedPricesUpdateDateTime': bundle.inputData?.[`${keyPrefix}lastFixedPricesUpdateDateTime`],
            'images': bundle.inputData?.[`${keyPrefix}images`],
            'viewsCount': bundle.inputData?.[`${keyPrefix}viewsCount`],
            'reviewsCount': bundle.inputData?.[`${keyPrefix}reviewsCount`],
            'questionsCount': bundle.inputData?.[`${keyPrefix}questionsCount`],
            'packagedQuantity': bundle.inputData?.[`${keyPrefix}packagedQuantity`],
            'reviewsAvg': bundle.inputData?.[`${keyPrefix}reviewsAvg`],
            'recurrency': bundle.inputData?.[`${keyPrefix}recurrency`],
            'currentStock': bundle.inputData?.[`${keyPrefix}currentStock`],
            'width': bundle.inputData?.[`${keyPrefix}width`],
            'weight': bundle.inputData?.[`${keyPrefix}weight`],
            'length': bundle.inputData?.[`${keyPrefix}length`],
            'height': bundle.inputData?.[`${keyPrefix}height`],
            'regularPrice': bundle.inputData?.[`${keyPrefix}regularPrice`],
            'discountPrice': bundle.inputData?.[`${keyPrefix}discountPrice`],
            'customTaxValue': bundle.inputData?.[`${keyPrefix}customTaxValue`],
            'discountAmount': bundle.inputData?.[`${keyPrefix}discountAmount`],
            'inCartQuantity': bundle.inputData?.[`${keyPrefix}inCartQuantity`],
            'customTaxAmount': bundle.inputData?.[`${keyPrefix}customTaxAmount`],
            'discountPercentage': bundle.inputData?.[`${keyPrefix}discountPercentage`],
            'customTaxPercentage': bundle.inputData?.[`${keyPrefix}customTaxPercentage`],
            'estimatedTaxesInUsd': bundle.inputData?.[`${keyPrefix}estimatedTaxesInUsd`],
            'estimatedProfitInUsd': bundle.inputData?.[`${keyPrefix}estimatedProfitInUsd`],
            'estimatedBasePriceInUsd': bundle.inputData?.[`${keyPrefix}estimatedBasePriceInUsd`],
            'estimatedDiscountsInUsd': bundle.inputData?.[`${keyPrefix}estimatedDiscountsInUsd`],
            'estimatedSurchargesInUsd': bundle.inputData?.[`${keyPrefix}estimatedSurchargesInUsd`],
            'estimatedPaymentTaxInUsd': bundle.inputData?.[`${keyPrefix}estimatedPaymentTaxInUsd`],
            'estimatedTotalPriceInUsd': bundle.inputData?.[`${keyPrefix}estimatedTotalPriceInUsd`],
            'estimatedPaymentCostInUsd': bundle.inputData?.[`${keyPrefix}estimatedPaymentCostInUsd`],
            'estimatedDealSavingsInUsd': bundle.inputData?.[`${keyPrefix}estimatedDealSavingsInUsd`],
            'estimatedRegularPriceInUsd': bundle.inputData?.[`${keyPrefix}estimatedRegularPriceInUsd`],
            'estimatedTaxBasePriceInUsd': bundle.inputData?.[`${keyPrefix}estimatedTaxBasePriceInUsd`],
            'estimatedWithholdingTaxesInUsd': bundle.inputData?.[`${keyPrefix}estimatedWithholdingTaxesInUsd`],
            'estimatedDefaultShippingTaxInUsd': bundle.inputData?.[`${keyPrefix}estimatedDefaultShippingTaxInUsd`],
            'estimatedDefaultShippingCostInUsd': bundle.inputData?.[`${keyPrefix}estimatedDefaultShippingCostInUsd`],
            'selectedTags': bundle.inputData?.[`${keyPrefix}selectedTags`],
            'selectedTypes': bundle.inputData?.[`${keyPrefix}selectedTypes`],
            'selectedBrands': bundle.inputData?.[`${keyPrefix}selectedBrands`],
            'selectedCategories': bundle.inputData?.[`${keyPrefix}selectedCategories`],
            'selectedTaxPolicies': bundle.inputData?.[`${keyPrefix}selectedTaxPolicies`],
            'selectedPricingRules': bundle.inputData?.[`${keyPrefix}selectedPricingRules`],
            'selectedRefundPolicies': bundle.inputData?.[`${keyPrefix}selectedRefundPolicies`],
            'selectedReturnPolicies': bundle.inputData?.[`${keyPrefix}selectedReturnPolicies`],
            'selectedPricingPolicies': bundle.inputData?.[`${keyPrefix}selectedPricingPolicies`],
            'selectedGoogleCategories': bundle.inputData?.[`${keyPrefix}selectedGoogleCategories`],
            'selectedWarrantyPolicies': bundle.inputData?.[`${keyPrefix}selectedWarrantyPolicies`],
            'selectedShipmentPolicies': bundle.inputData?.[`${keyPrefix}selectedShipmentPolicies`],
            'selectedAttributesOptions': bundle.inputData?.[`${keyPrefix}selectedAttributesOptions`],
            'selectedSellingMarginPolicies': bundle.inputData?.[`${keyPrefix}selectedSellingMarginPolicies`],
            'serviceId': bundle.inputData?.[`${keyPrefix}serviceId`],
        }
    },
}
