const utils = require('../utils/utils');
const ContactDto = require('../models/ContactDto');
const TenantDto = require('../models/TenantDto');
const TenantEnrollmentDto = require('../models/TenantEnrollmentDto');
const UserDto = require('../models/UserDto');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}closed`,
                label: `[${labelPrefix}closed]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}type`,
                label: `[${labelPrefix}type]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}userId`,
                label: `[${labelPrefix}userId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tenantId`,
                label: `[${labelPrefix}tenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}priceListId`,
                label: `[${labelPrefix}priceListId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enrollmentId`,
                label: `[${labelPrefix}enrollmentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}individualId`,
                label: `[${labelPrefix}individualId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}organizationId`,
                label: `[${labelPrefix}organizationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}receiverTenantId`,
                label: `[${labelPrefix}receiverTenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}firstName`,
                label: `[${labelPrefix}firstName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lastName`,
                label: `[${labelPrefix}lastName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}companyName`,
                label: `[${labelPrefix}companyName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingEmail`,
                label: `[${labelPrefix}billingEmail]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine1`,
                label: `[${labelPrefix}addressLine1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine2`,
                label: `[${labelPrefix}addressLine2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}postalCode`,
                label: `[${labelPrefix}postalCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryId`,
                label: `[${labelPrefix}countryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}stateId`,
                label: `[${labelPrefix}stateId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cityId`,
                label: `[${labelPrefix}cityId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}customerNotes`,
                label: `[${labelPrefix}customerNotes]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}taxCalculationMethod`,
                label: `[${labelPrefix}taxCalculationMethod]`,
                type: 'string',
                choices: [
                    'Included',
                    'Excluded',
                ],
            },
            {
                key: `${keyPrefix}costCalculationMethod`,
                label: `[${labelPrefix}costCalculationMethod]`,
                type: 'string',
                choices: [
                    'Automatic',
                    'Custom',
                ],
            },
            {
                key: `${keyPrefix}forexRate`,
                label: `[${labelPrefix}forexRate]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}currencyId`,
                label: `[${labelPrefix}currencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDetail`,
                label: `[${labelPrefix}totalDetail]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDetailCurrencyId`,
                label: `[${labelPrefix}totalDetailCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalProfit`,
                label: `[${labelPrefix}totalProfit]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalProfitCurrencyId`,
                label: `[${labelPrefix}totalProfitCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDiscounts`,
                label: `[${labelPrefix}totalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalSurcharges`,
                label: `[${labelPrefix}totalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxBase`,
                label: `[${labelPrefix}totalTaxBase]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxBaseCurrencyId`,
                label: `[${labelPrefix}totalTaxBaseCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxes`,
                label: `[${labelPrefix}totalTaxes]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxesCurrencyId`,
                label: `[${labelPrefix}totalTaxesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingCost`,
                label: `[${labelPrefix}totalShippingCost]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingCostCurrencyId`,
                label: `[${labelPrefix}totalShippingCostCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingTax`,
                label: `[${labelPrefix}totalShippingTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingTaxCurrencyId`,
                label: `[${labelPrefix}totalShippingTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalWithheldTax`,
                label: `[${labelPrefix}totalWithheldTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalWithheldTaxCurrencyId`,
                label: `[${labelPrefix}totalWithheldTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalDiscounts`,
                label: `[${labelPrefix}totalGlobalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalGlobalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalSurcharges`,
                label: `[${labelPrefix}totalGlobalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalGlobalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}total`,
                label: `[${labelPrefix}total]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalCurrencyId`,
                label: `[${labelPrefix}totalCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDetailInUsd`,
                label: `[${labelPrefix}totalDetailInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalProfitInUsd`,
                label: `[${labelPrefix}totalProfitInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDiscountsInUsd`,
                label: `[${labelPrefix}totalDiscountsInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalSurchargesInUsd`,
                label: `[${labelPrefix}totalSurchargesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxBaseInUsd`,
                label: `[${labelPrefix}totalTaxBaseInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxesInUsd`,
                label: `[${labelPrefix}totalTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalWithheldTaxesInUsd`,
                label: `[${labelPrefix}totalWithheldTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingCostInUsd`,
                label: `[${labelPrefix}totalShippingCostInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingTaxesInUsd`,
                label: `[${labelPrefix}totalShippingTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalDiscountsInUsd`,
                label: `[${labelPrefix}totalGlobalDiscountsInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalSurchargesInUsd`,
                label: `[${labelPrefix}totalGlobalSurchargesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalInUsd`,
                label: `[${labelPrefix}totalInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}cartId`,
                label: `[${labelPrefix}cartId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dealUnitId`,
                label: `[${labelPrefix}dealUnitId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}effectiveTo`,
                label: `[${labelPrefix}effectiveTo]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}effectiveFrom`,
                label: `[${labelPrefix}effectiveFrom]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}quoteStatus`,
                label: `[${labelPrefix}quoteStatus]`,
                type: 'string',
                choices: [
                    'Draft',
                    'New',
                    'Accepted',
                    'Declined',
                    'Expired',
                ],
            },
            {
                key: `${keyPrefix}freightTerms`,
                label: `[${labelPrefix}freightTerms]`,
                type: 'string',
                choices: [
                    'FOB',
                    'NoCharge',
                ],
            },
            {
                key: `${keyPrefix}customDiscountsAmount`,
                label: `[${labelPrefix}customDiscountsAmount]`,
                type: 'number',
            },
            ...UserDto.fields(`${keyPrefix}user`, isInput),
            ...TenantDto.fields(`${keyPrefix}tenant`, isInput),
            ...ContactDto.fields(`${keyPrefix}individual`, isInput),
            ...ContactDto.fields(`${keyPrefix}organization`, isInput),
            ...TenantDto.fields(`${keyPrefix}receiverTenant`, isInput),
            ...TenantEnrollmentDto.fields(`${keyPrefix}enrollment`, isInput),
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'closed': bundle.inputData?.[`${keyPrefix}closed`],
            'type': bundle.inputData?.[`${keyPrefix}type`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'userId': bundle.inputData?.[`${keyPrefix}userId`],
            'tenantId': bundle.inputData?.[`${keyPrefix}tenantId`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'priceListId': bundle.inputData?.[`${keyPrefix}priceListId`],
            'enrollmentId': bundle.inputData?.[`${keyPrefix}enrollmentId`],
            'individualId': bundle.inputData?.[`${keyPrefix}individualId`],
            'organizationId': bundle.inputData?.[`${keyPrefix}organizationId`],
            'receiverTenantId': bundle.inputData?.[`${keyPrefix}receiverTenantId`],
            'firstName': bundle.inputData?.[`${keyPrefix}firstName`],
            'lastName': bundle.inputData?.[`${keyPrefix}lastName`],
            'companyName': bundle.inputData?.[`${keyPrefix}companyName`],
            'billingEmail': bundle.inputData?.[`${keyPrefix}billingEmail`],
            'addressLine1': bundle.inputData?.[`${keyPrefix}addressLine1`],
            'addressLine2': bundle.inputData?.[`${keyPrefix}addressLine2`],
            'postalCode': bundle.inputData?.[`${keyPrefix}postalCode`],
            'countryId': bundle.inputData?.[`${keyPrefix}countryId`],
            'stateId': bundle.inputData?.[`${keyPrefix}stateId`],
            'cityId': bundle.inputData?.[`${keyPrefix}cityId`],
            'customerNotes': bundle.inputData?.[`${keyPrefix}customerNotes`],
            'taxCalculationMethod': bundle.inputData?.[`${keyPrefix}taxCalculationMethod`],
            'costCalculationMethod': bundle.inputData?.[`${keyPrefix}costCalculationMethod`],
            'forexRate': bundle.inputData?.[`${keyPrefix}forexRate`],
            'currencyId': bundle.inputData?.[`${keyPrefix}currencyId`],
            'totalDetail': bundle.inputData?.[`${keyPrefix}totalDetail`],
            'totalDetailCurrencyId': bundle.inputData?.[`${keyPrefix}totalDetailCurrencyId`],
            'totalProfit': bundle.inputData?.[`${keyPrefix}totalProfit`],
            'totalProfitCurrencyId': bundle.inputData?.[`${keyPrefix}totalProfitCurrencyId`],
            'totalDiscounts': bundle.inputData?.[`${keyPrefix}totalDiscounts`],
            'totalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalDiscountsCurrencyId`],
            'totalSurcharges': bundle.inputData?.[`${keyPrefix}totalSurcharges`],
            'totalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalSurchargesCurrencyId`],
            'totalTaxBase': bundle.inputData?.[`${keyPrefix}totalTaxBase`],
            'totalTaxBaseCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxBaseCurrencyId`],
            'totalTaxes': bundle.inputData?.[`${keyPrefix}totalTaxes`],
            'totalTaxesCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxesCurrencyId`],
            'totalShippingCost': bundle.inputData?.[`${keyPrefix}totalShippingCost`],
            'totalShippingCostCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingCostCurrencyId`],
            'totalShippingTax': bundle.inputData?.[`${keyPrefix}totalShippingTax`],
            'totalShippingTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingTaxCurrencyId`],
            'totalWithheldTax': bundle.inputData?.[`${keyPrefix}totalWithheldTax`],
            'totalWithheldTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalWithheldTaxCurrencyId`],
            'totalGlobalDiscounts': bundle.inputData?.[`${keyPrefix}totalGlobalDiscounts`],
            'totalGlobalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalDiscountsCurrencyId`],
            'totalGlobalSurcharges': bundle.inputData?.[`${keyPrefix}totalGlobalSurcharges`],
            'totalGlobalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalSurchargesCurrencyId`],
            'total': bundle.inputData?.[`${keyPrefix}total`],
            'totalCurrencyId': bundle.inputData?.[`${keyPrefix}totalCurrencyId`],
            'totalDetailInUsd': bundle.inputData?.[`${keyPrefix}totalDetailInUsd`],
            'totalProfitInUsd': bundle.inputData?.[`${keyPrefix}totalProfitInUsd`],
            'totalDiscountsInUsd': bundle.inputData?.[`${keyPrefix}totalDiscountsInUsd`],
            'totalSurchargesInUsd': bundle.inputData?.[`${keyPrefix}totalSurchargesInUsd`],
            'totalTaxBaseInUsd': bundle.inputData?.[`${keyPrefix}totalTaxBaseInUsd`],
            'totalTaxesInUsd': bundle.inputData?.[`${keyPrefix}totalTaxesInUsd`],
            'totalWithheldTaxesInUsd': bundle.inputData?.[`${keyPrefix}totalWithheldTaxesInUsd`],
            'totalShippingCostInUsd': bundle.inputData?.[`${keyPrefix}totalShippingCostInUsd`],
            'totalShippingTaxesInUsd': bundle.inputData?.[`${keyPrefix}totalShippingTaxesInUsd`],
            'totalGlobalDiscountsInUsd': bundle.inputData?.[`${keyPrefix}totalGlobalDiscountsInUsd`],
            'totalGlobalSurchargesInUsd': bundle.inputData?.[`${keyPrefix}totalGlobalSurchargesInUsd`],
            'totalInUsd': bundle.inputData?.[`${keyPrefix}totalInUsd`],
            'cartId': bundle.inputData?.[`${keyPrefix}cartId`],
            'dealUnitId': bundle.inputData?.[`${keyPrefix}dealUnitId`],
            'effectiveTo': bundle.inputData?.[`${keyPrefix}effectiveTo`],
            'effectiveFrom': bundle.inputData?.[`${keyPrefix}effectiveFrom`],
            'quoteStatus': bundle.inputData?.[`${keyPrefix}quoteStatus`],
            'freightTerms': bundle.inputData?.[`${keyPrefix}freightTerms`],
            'customDiscountsAmount': bundle.inputData?.[`${keyPrefix}customDiscountsAmount`],
            'user': utils.removeIfEmpty(UserDto.mapping(bundle, `${keyPrefix}user`)),
            'tenant': utils.removeIfEmpty(TenantDto.mapping(bundle, `${keyPrefix}tenant`)),
            'individual': utils.removeIfEmpty(ContactDto.mapping(bundle, `${keyPrefix}individual`)),
            'organization': utils.removeIfEmpty(ContactDto.mapping(bundle, `${keyPrefix}organization`)),
            'receiverTenant': utils.removeIfEmpty(TenantDto.mapping(bundle, `${keyPrefix}receiverTenant`)),
            'enrollment': utils.removeIfEmpty(TenantEnrollmentDto.mapping(bundle, `${keyPrefix}enrollment`)),
        }
    },
}
