const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}closed`,
                label: `[${labelPrefix}closed]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}type`,
                label: `[${labelPrefix}type]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}title`,
                label: `[${labelPrefix}title]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}userId`,
                label: `[${labelPrefix}userId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}tenantId`,
                label: `[${labelPrefix}tenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}description`,
                label: `[${labelPrefix}description]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}priceListId`,
                label: `[${labelPrefix}priceListId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enrollmentId`,
                label: `[${labelPrefix}enrollmentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}individualId`,
                label: `[${labelPrefix}individualId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}organizationId`,
                label: `[${labelPrefix}organizationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}receiverTenantId`,
                label: `[${labelPrefix}receiverTenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}firstName`,
                label: `[${labelPrefix}firstName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}lastName`,
                label: `[${labelPrefix}lastName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}companyName`,
                label: `[${labelPrefix}companyName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}billingEmail`,
                label: `[${labelPrefix}billingEmail]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine1`,
                label: `[${labelPrefix}addressLine1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}addressLine2`,
                label: `[${labelPrefix}addressLine2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}postalCode`,
                label: `[${labelPrefix}postalCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}countryId`,
                label: `[${labelPrefix}countryId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}stateId`,
                label: `[${labelPrefix}stateId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}cityId`,
                label: `[${labelPrefix}cityId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}customerNotes`,
                label: `[${labelPrefix}customerNotes]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}taxCalculationMethod`,
                label: `[${labelPrefix}taxCalculationMethod]`,
                type: 'string',
                choices: [
                    'Included',
                    'Excluded',
                ],
            },
            {
                key: `${keyPrefix}costCalculationMethod`,
                label: `[${labelPrefix}costCalculationMethod]`,
                type: 'string',
                choices: [
                    'Automatic',
                    'Custom',
                ],
            },
            {
                key: `${keyPrefix}forexRate`,
                label: `[${labelPrefix}forexRate]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}forexRatesSnapshot`,
                label: `[${labelPrefix}forexRatesSnapshot]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}currencyId`,
                label: `[${labelPrefix}currencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDetail`,
                label: `[${labelPrefix}totalDetail]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDetailCurrencyId`,
                label: `[${labelPrefix}totalDetailCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalProfit`,
                label: `[${labelPrefix}totalProfit]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalProfitCurrencyId`,
                label: `[${labelPrefix}totalProfitCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDiscounts`,
                label: `[${labelPrefix}totalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalSurcharges`,
                label: `[${labelPrefix}totalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxBase`,
                label: `[${labelPrefix}totalTaxBase]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxBaseCurrencyId`,
                label: `[${labelPrefix}totalTaxBaseCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalTaxes`,
                label: `[${labelPrefix}totalTaxes]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxesCurrencyId`,
                label: `[${labelPrefix}totalTaxesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingCost`,
                label: `[${labelPrefix}totalShippingCost]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingCostCurrencyId`,
                label: `[${labelPrefix}totalShippingCostCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalShippingTax`,
                label: `[${labelPrefix}totalShippingTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingTaxCurrencyId`,
                label: `[${labelPrefix}totalShippingTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalWithheldTax`,
                label: `[${labelPrefix}totalWithheldTax]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalWithheldTaxCurrencyId`,
                label: `[${labelPrefix}totalWithheldTaxCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalDiscounts`,
                label: `[${labelPrefix}totalGlobalDiscounts]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalDiscountsCurrencyId`,
                label: `[${labelPrefix}totalGlobalDiscountsCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalGlobalSurcharges`,
                label: `[${labelPrefix}totalGlobalSurcharges]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalSurchargesCurrencyId`,
                label: `[${labelPrefix}totalGlobalSurchargesCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}total`,
                label: `[${labelPrefix}total]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalCurrencyId`,
                label: `[${labelPrefix}totalCurrencyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalDetailInUsd`,
                label: `[${labelPrefix}totalDetailInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalProfitInUsd`,
                label: `[${labelPrefix}totalProfitInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalDiscountsInUsd`,
                label: `[${labelPrefix}totalDiscountsInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalSurchargesInUsd`,
                label: `[${labelPrefix}totalSurchargesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxBaseInUsd`,
                label: `[${labelPrefix}totalTaxBaseInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalTaxesInUsd`,
                label: `[${labelPrefix}totalTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalWithheldTaxesInUsd`,
                label: `[${labelPrefix}totalWithheldTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingCostInUsd`,
                label: `[${labelPrefix}totalShippingCostInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalShippingTaxesInUsd`,
                label: `[${labelPrefix}totalShippingTaxesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalDiscountsInUsd`,
                label: `[${labelPrefix}totalGlobalDiscountsInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalGlobalSurchargesInUsd`,
                label: `[${labelPrefix}totalGlobalSurchargesInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalInUsd`,
                label: `[${labelPrefix}totalInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}itemId`,
                label: `[${labelPrefix}itemId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}itemTitle`,
                label: `[${labelPrefix}itemTitle]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}itemShortDescription`,
                label: `[${labelPrefix}itemShortDescription]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}itemPrimaryImageUrl`,
                label: `[${labelPrefix}itemPrimaryImageUrl]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingPolicyId`,
                label: `[${labelPrefix}shippingPolicyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}quantity`,
                label: `[${labelPrefix}quantity]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}free`,
                label: `[${labelPrefix}free]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}freeReason`,
                label: `[${labelPrefix}freeReason]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}freeReasonCode`,
                label: `[${labelPrefix}freeReasonCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data`,
                label: `[${labelPrefix}data]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}dataLabel`,
                label: `[${labelPrefix}dataLabel]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data1`,
                label: `[${labelPrefix}data1]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data1Label`,
                label: `[${labelPrefix}data1Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data2`,
                label: `[${labelPrefix}data2]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data2Label`,
                label: `[${labelPrefix}data2Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data3`,
                label: `[${labelPrefix}data3]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data3Label`,
                label: `[${labelPrefix}data3Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data4`,
                label: `[${labelPrefix}data4]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data4Label`,
                label: `[${labelPrefix}data4Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data5`,
                label: `[${labelPrefix}data5]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data5Label`,
                label: `[${labelPrefix}data5Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data6`,
                label: `[${labelPrefix}data6]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data6Label`,
                label: `[${labelPrefix}data6Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data7`,
                label: `[${labelPrefix}data7]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data7Label`,
                label: `[${labelPrefix}data7Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data8`,
                label: `[${labelPrefix}data8]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data8Label`,
                label: `[${labelPrefix}data8Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data9`,
                label: `[${labelPrefix}data9]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}data9Label`,
                label: `[${labelPrefix}data9Label]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}itemPriceId`,
                label: `[${labelPrefix}itemPriceId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}priceListItemId`,
                label: `[${labelPrefix}priceListItemId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}unitId`,
                label: `[${labelPrefix}unitId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}unitGroupId`,
                label: `[${labelPrefix}unitGroupId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}totalWarrantyCostInUsd`,
                label: `[${labelPrefix}totalWarrantyCostInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalReturnCostInUsd`,
                label: `[${labelPrefix}totalReturnCostInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}totalRefundCostInUsd`,
                label: `[${labelPrefix}totalRefundCostInUsd]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}customGlobalSurchargesAmount`,
                label: `[${labelPrefix}customGlobalSurchargesAmount]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}customGlobalDiscountsAmount`,
                label: `[${labelPrefix}customGlobalDiscountsAmount]`,
                type: 'number',
            },
            {
                key: `${keyPrefix}returnPolicyId`,
                label: `[${labelPrefix}returnPolicyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}refundPolicyId`,
                label: `[${labelPrefix}refundPolicyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}warrantyPolicyId`,
                label: `[${labelPrefix}warrantyPolicyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shipmentPolicyId`,
                label: `[${labelPrefix}shipmentPolicyId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}shippingLocationId`,
                label: `[${labelPrefix}shippingLocationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}locationId`,
                label: `[${labelPrefix}locationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}quoteItemRecordId`,
                label: `[${labelPrefix}quoteItemRecordId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}businessProfileRecordId`,
                label: `[${labelPrefix}businessProfileRecordId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}parentBillingItemRecordId`,
                label: `[${labelPrefix}parentBillingItemRecordId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}quoteId`,
                label: `[${labelPrefix}quoteId]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'closed': bundle.inputData?.[`${keyPrefix}closed`],
            'type': bundle.inputData?.[`${keyPrefix}type`],
            'title': bundle.inputData?.[`${keyPrefix}title`],
            'userId': bundle.inputData?.[`${keyPrefix}userId`],
            'tenantId': bundle.inputData?.[`${keyPrefix}tenantId`],
            'description': bundle.inputData?.[`${keyPrefix}description`],
            'priceListId': bundle.inputData?.[`${keyPrefix}priceListId`],
            'enrollmentId': bundle.inputData?.[`${keyPrefix}enrollmentId`],
            'individualId': bundle.inputData?.[`${keyPrefix}individualId`],
            'organizationId': bundle.inputData?.[`${keyPrefix}organizationId`],
            'receiverTenantId': bundle.inputData?.[`${keyPrefix}receiverTenantId`],
            'firstName': bundle.inputData?.[`${keyPrefix}firstName`],
            'lastName': bundle.inputData?.[`${keyPrefix}lastName`],
            'companyName': bundle.inputData?.[`${keyPrefix}companyName`],
            'billingEmail': bundle.inputData?.[`${keyPrefix}billingEmail`],
            'addressLine1': bundle.inputData?.[`${keyPrefix}addressLine1`],
            'addressLine2': bundle.inputData?.[`${keyPrefix}addressLine2`],
            'postalCode': bundle.inputData?.[`${keyPrefix}postalCode`],
            'countryId': bundle.inputData?.[`${keyPrefix}countryId`],
            'stateId': bundle.inputData?.[`${keyPrefix}stateId`],
            'cityId': bundle.inputData?.[`${keyPrefix}cityId`],
            'customerNotes': bundle.inputData?.[`${keyPrefix}customerNotes`],
            'taxCalculationMethod': bundle.inputData?.[`${keyPrefix}taxCalculationMethod`],
            'costCalculationMethod': bundle.inputData?.[`${keyPrefix}costCalculationMethod`],
            'forexRate': bundle.inputData?.[`${keyPrefix}forexRate`],
            'forexRatesSnapshot': bundle.inputData?.[`${keyPrefix}forexRatesSnapshot`],
            'currencyId': bundle.inputData?.[`${keyPrefix}currencyId`],
            'totalDetail': bundle.inputData?.[`${keyPrefix}totalDetail`],
            'totalDetailCurrencyId': bundle.inputData?.[`${keyPrefix}totalDetailCurrencyId`],
            'totalProfit': bundle.inputData?.[`${keyPrefix}totalProfit`],
            'totalProfitCurrencyId': bundle.inputData?.[`${keyPrefix}totalProfitCurrencyId`],
            'totalDiscounts': bundle.inputData?.[`${keyPrefix}totalDiscounts`],
            'totalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalDiscountsCurrencyId`],
            'totalSurcharges': bundle.inputData?.[`${keyPrefix}totalSurcharges`],
            'totalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalSurchargesCurrencyId`],
            'totalTaxBase': bundle.inputData?.[`${keyPrefix}totalTaxBase`],
            'totalTaxBaseCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxBaseCurrencyId`],
            'totalTaxes': bundle.inputData?.[`${keyPrefix}totalTaxes`],
            'totalTaxesCurrencyId': bundle.inputData?.[`${keyPrefix}totalTaxesCurrencyId`],
            'totalShippingCost': bundle.inputData?.[`${keyPrefix}totalShippingCost`],
            'totalShippingCostCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingCostCurrencyId`],
            'totalShippingTax': bundle.inputData?.[`${keyPrefix}totalShippingTax`],
            'totalShippingTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalShippingTaxCurrencyId`],
            'totalWithheldTax': bundle.inputData?.[`${keyPrefix}totalWithheldTax`],
            'totalWithheldTaxCurrencyId': bundle.inputData?.[`${keyPrefix}totalWithheldTaxCurrencyId`],
            'totalGlobalDiscounts': bundle.inputData?.[`${keyPrefix}totalGlobalDiscounts`],
            'totalGlobalDiscountsCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalDiscountsCurrencyId`],
            'totalGlobalSurcharges': bundle.inputData?.[`${keyPrefix}totalGlobalSurcharges`],
            'totalGlobalSurchargesCurrencyId': bundle.inputData?.[`${keyPrefix}totalGlobalSurchargesCurrencyId`],
            'total': bundle.inputData?.[`${keyPrefix}total`],
            'totalCurrencyId': bundle.inputData?.[`${keyPrefix}totalCurrencyId`],
            'totalDetailInUsd': bundle.inputData?.[`${keyPrefix}totalDetailInUsd`],
            'totalProfitInUsd': bundle.inputData?.[`${keyPrefix}totalProfitInUsd`],
            'totalDiscountsInUsd': bundle.inputData?.[`${keyPrefix}totalDiscountsInUsd`],
            'totalSurchargesInUsd': bundle.inputData?.[`${keyPrefix}totalSurchargesInUsd`],
            'totalTaxBaseInUsd': bundle.inputData?.[`${keyPrefix}totalTaxBaseInUsd`],
            'totalTaxesInUsd': bundle.inputData?.[`${keyPrefix}totalTaxesInUsd`],
            'totalWithheldTaxesInUsd': bundle.inputData?.[`${keyPrefix}totalWithheldTaxesInUsd`],
            'totalShippingCostInUsd': bundle.inputData?.[`${keyPrefix}totalShippingCostInUsd`],
            'totalShippingTaxesInUsd': bundle.inputData?.[`${keyPrefix}totalShippingTaxesInUsd`],
            'totalGlobalDiscountsInUsd': bundle.inputData?.[`${keyPrefix}totalGlobalDiscountsInUsd`],
            'totalGlobalSurchargesInUsd': bundle.inputData?.[`${keyPrefix}totalGlobalSurchargesInUsd`],
            'totalInUsd': bundle.inputData?.[`${keyPrefix}totalInUsd`],
            'itemId': bundle.inputData?.[`${keyPrefix}itemId`],
            'itemTitle': bundle.inputData?.[`${keyPrefix}itemTitle`],
            'itemShortDescription': bundle.inputData?.[`${keyPrefix}itemShortDescription`],
            'itemPrimaryImageUrl': bundle.inputData?.[`${keyPrefix}itemPrimaryImageUrl`],
            'shippingPolicyId': bundle.inputData?.[`${keyPrefix}shippingPolicyId`],
            'quantity': bundle.inputData?.[`${keyPrefix}quantity`],
            'free': bundle.inputData?.[`${keyPrefix}free`],
            'freeReason': bundle.inputData?.[`${keyPrefix}freeReason`],
            'freeReasonCode': bundle.inputData?.[`${keyPrefix}freeReasonCode`],
            'data': bundle.inputData?.[`${keyPrefix}data`],
            'dataLabel': bundle.inputData?.[`${keyPrefix}dataLabel`],
            'data1': bundle.inputData?.[`${keyPrefix}data1`],
            'data1Label': bundle.inputData?.[`${keyPrefix}data1Label`],
            'data2': bundle.inputData?.[`${keyPrefix}data2`],
            'data2Label': bundle.inputData?.[`${keyPrefix}data2Label`],
            'data3': bundle.inputData?.[`${keyPrefix}data3`],
            'data3Label': bundle.inputData?.[`${keyPrefix}data3Label`],
            'data4': bundle.inputData?.[`${keyPrefix}data4`],
            'data4Label': bundle.inputData?.[`${keyPrefix}data4Label`],
            'data5': bundle.inputData?.[`${keyPrefix}data5`],
            'data5Label': bundle.inputData?.[`${keyPrefix}data5Label`],
            'data6': bundle.inputData?.[`${keyPrefix}data6`],
            'data6Label': bundle.inputData?.[`${keyPrefix}data6Label`],
            'data7': bundle.inputData?.[`${keyPrefix}data7`],
            'data7Label': bundle.inputData?.[`${keyPrefix}data7Label`],
            'data8': bundle.inputData?.[`${keyPrefix}data8`],
            'data8Label': bundle.inputData?.[`${keyPrefix}data8Label`],
            'data9': bundle.inputData?.[`${keyPrefix}data9`],
            'data9Label': bundle.inputData?.[`${keyPrefix}data9Label`],
            'itemPriceId': bundle.inputData?.[`${keyPrefix}itemPriceId`],
            'priceListItemId': bundle.inputData?.[`${keyPrefix}priceListItemId`],
            'unitId': bundle.inputData?.[`${keyPrefix}unitId`],
            'unitGroupId': bundle.inputData?.[`${keyPrefix}unitGroupId`],
            'totalWarrantyCostInUsd': bundle.inputData?.[`${keyPrefix}totalWarrantyCostInUsd`],
            'totalReturnCostInUsd': bundle.inputData?.[`${keyPrefix}totalReturnCostInUsd`],
            'totalRefundCostInUsd': bundle.inputData?.[`${keyPrefix}totalRefundCostInUsd`],
            'customGlobalSurchargesAmount': bundle.inputData?.[`${keyPrefix}customGlobalSurchargesAmount`],
            'customGlobalDiscountsAmount': bundle.inputData?.[`${keyPrefix}customGlobalDiscountsAmount`],
            'returnPolicyId': bundle.inputData?.[`${keyPrefix}returnPolicyId`],
            'refundPolicyId': bundle.inputData?.[`${keyPrefix}refundPolicyId`],
            'warrantyPolicyId': bundle.inputData?.[`${keyPrefix}warrantyPolicyId`],
            'shipmentPolicyId': bundle.inputData?.[`${keyPrefix}shipmentPolicyId`],
            'shippingLocationId': bundle.inputData?.[`${keyPrefix}shippingLocationId`],
            'locationId': bundle.inputData?.[`${keyPrefix}locationId`],
            'quoteItemRecordId': bundle.inputData?.[`${keyPrefix}quoteItemRecordId`],
            'businessProfileRecordId': bundle.inputData?.[`${keyPrefix}businessProfileRecordId`],
            'parentBillingItemRecordId': bundle.inputData?.[`${keyPrefix}parentBillingItemRecordId`],
            'quoteId': bundle.inputData?.[`${keyPrefix}quoteId`],
        }
    },
}
