const utils = require('../utils/utils');

module.exports = {
    fields: (prefix = '', isInput = true, isArrayChild = false) => {
        const {keyPrefix, labelPrefix} = utils.buildKeyAndLabel(prefix, isInput, isArrayChild)
        return [
            {
                key: `${keyPrefix}id`,
                label: `[${labelPrefix}id]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}timestamp`,
                label: `[${labelPrefix}timestamp]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}type`,
                label: `[${labelPrefix}type]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}message`,
                label: `[${labelPrefix}message]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}logType`,
                label: `[${labelPrefix}logType]`,
                type: 'string',
                choices: [
                    'Continue',
                    'SwitchingProtocols',
                    'Processing',
                    'EarlyHints',
                    'OK',
                    'Created',
                    'Accepted',
                    'NonAuthoritativeInformation',
                    'NoContent',
                    'ResetContent',
                    'PartialContent',
                    'MultiStatus',
                    'AlreadyReported',
                    'IMUsed',
                    'MultipleChoices',
                    'MovedPermanently',
                    'Found',
                    'SeeOther',
                    'NotModified',
                    'UseProxy',
                    'Unused',
                    'TemporaryRedirect',
                    'PermanentRedirect',
                    'BadRequest',
                    'Unauthorized',
                    'PaymentRequired',
                    'Forbidden',
                    'NotFound',
                    'MethodNotAllowed',
                    'NotAcceptable',
                    'ProxyAuthenticationRequired',
                    'RequestTimeout',
                    'Conflict',
                    'Gone',
                    'LengthRequired',
                    'PreconditionFailed',
                    'RequestEntityTooLarge',
                    'RequestUriTooLong',
                    'UnsupportedMediaType',
                    'RequestedRangeNotSatisfiable',
                    'ExpectationFailed',
                    'MisdirectedRequest',
                    'UnprocessableEntity',
                    'Locked',
                    'FailedDependency',
                    'UpgradeRequired',
                    'PreconditionRequired',
                    'TooManyRequests',
                    'RequestHeaderFieldsTooLarge',
                    'UnavailableForLegalReasons',
                    'InternalServerError',
                    'NotImplemented',
                    'BadGateway',
                    'ServiceUnavailable',
                    'GatewayTimeout',
                    'HttpVersionNotSupported',
                    'VariantAlsoNegotiates',
                    'InsufficientStorage',
                    'LoopDetected',
                    'NotExtended',
                    'NetworkAuthenticationRequired',
                ],
            },
            {
                key: `${keyPrefix}securityEvent`,
                label: `[${labelPrefix}securityEvent]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}requiresAttention`,
                label: `[${labelPrefix}requiresAttention]`,
                type: 'boolean',
            },
            {
                key: `${keyPrefix}tenantId`,
                label: `[${labelPrefix}tenantId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}userId`,
                label: `[${labelPrefix}userId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}enrollmentId`,
                label: `[${labelPrefix}enrollmentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}contactId`,
                label: `[${labelPrefix}contactId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}signingProfileId`,
                label: `[${labelPrefix}signingProfileId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}signingCertificateId`,
                label: `[${labelPrefix}signingCertificateId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}signedDocumentId`,
                label: `[${labelPrefix}signedDocumentId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}operationType`,
                label: `[${labelPrefix}operationType]`,
                type: 'string',
                choices: [
                    'Unknown',
                    'Sign',
                    'Verify',
                    'Seal',
                    'RotateCredential',
                    'ResolveCredential',
                    'SubmitToAuthority',
                    'ReceiveAuthorityResponse',
                    'Freeze',
                ],
            },
            {
                key: `${keyPrefix}correlationId`,
                label: `[${labelPrefix}correlationId]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}inputHash`,
                label: `[${labelPrefix}inputHash]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}outputHash`,
                label: `[${labelPrefix}outputHash]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}providerName`,
                label: `[${labelPrefix}providerName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}resultCode`,
                label: `[${labelPrefix}resultCode]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}signingProfileDisplayName`,
                label: `[${labelPrefix}signingProfileDisplayName]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}signingCertificateTitle`,
                label: `[${labelPrefix}signingCertificateTitle]`,
                type: 'string',
            },
            {
                key: `${keyPrefix}signedDocumentTitle`,
                label: `[${labelPrefix}signedDocumentTitle]`,
                type: 'string',
            },
        ]
    },
    mapping: (bundle, prefix = '') => {
        const {keyPrefix} = utils.buildKeyAndLabel(prefix)
        return {
            'id': bundle.inputData?.[`${keyPrefix}id`],
            'timestamp': bundle.inputData?.[`${keyPrefix}timestamp`],
            'type': bundle.inputData?.[`${keyPrefix}type`],
            'message': bundle.inputData?.[`${keyPrefix}message`],
            'logType': bundle.inputData?.[`${keyPrefix}logType`],
            'securityEvent': bundle.inputData?.[`${keyPrefix}securityEvent`],
            'requiresAttention': bundle.inputData?.[`${keyPrefix}requiresAttention`],
            'tenantId': bundle.inputData?.[`${keyPrefix}tenantId`],
            'userId': bundle.inputData?.[`${keyPrefix}userId`],
            'enrollmentId': bundle.inputData?.[`${keyPrefix}enrollmentId`],
            'contactId': bundle.inputData?.[`${keyPrefix}contactId`],
            'signingProfileId': bundle.inputData?.[`${keyPrefix}signingProfileId`],
            'signingCertificateId': bundle.inputData?.[`${keyPrefix}signingCertificateId`],
            'signedDocumentId': bundle.inputData?.[`${keyPrefix}signedDocumentId`],
            'operationType': bundle.inputData?.[`${keyPrefix}operationType`],
            'correlationId': bundle.inputData?.[`${keyPrefix}correlationId`],
            'inputHash': bundle.inputData?.[`${keyPrefix}inputHash`],
            'outputHash': bundle.inputData?.[`${keyPrefix}outputHash`],
            'providerName': bundle.inputData?.[`${keyPrefix}providerName`],
            'resultCode': bundle.inputData?.[`${keyPrefix}resultCode`],
            'signingProfileDisplayName': bundle.inputData?.[`${keyPrefix}signingProfileDisplayName`],
            'signingCertificateTitle': bundle.inputData?.[`${keyPrefix}signingCertificateTitle`],
            'signedDocumentTitle': bundle.inputData?.[`${keyPrefix}signedDocumentTitle`],
        }
    },
}
